import { DestinationConfig, TiqetsNiche, EntryInfo, ClimateMonth } from "@/types";

// heroImage: lokaler Pfad → Bilder in /public/images/destinations/ ablegen
// heroImageFallback: Unsplash-Platzhalter bis eigene Bilder da sind
export const destinations: DestinationConfig[] = [
  {
    slug: "antalya",
    name: "Antalya",
    regionIds: [126, 133, 129],
    country: "Türkei",
    heroImage: "/images/destinations/antalya-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1600&q=80",
    cardImage: "/images/destinations/antalya-card.jpg",
    description: "Antalya – die Perle der türkischen Riviera. Türkisblaues Meer, antike Ruinen und erstklassige Hotels erwarten euch.",
    metaTitle: "Antalya Urlaub 2026 – All Inclusive günstig buchen",
    metaDescription: "Antalya Urlaub günstig buchen: Pauschalreisen ✓ All Inclusive ✓ Last Minute Türkei ✓ Jetzt Angebote vergleichen & Traumurlaub an der türkischen Riviera buchen!",
    guideSlug: "reisefuehrer-antalya",
    iataCode: "AYT",
    ibeBpRegion: "turkey",
    ibeRegionId: "149",
    ibeCityId: "930",
    tiqetsCityId: "78987",
    tiqetsNiches: [
      {
        slug: "outdoor-abenteuer",
        label: "Outdoor & Abenteuer",
        keywords: "canyon|zipline|rafting|klettern|paragliding|quad|jeep|abenteuer|bootstour|bootsfahrt|safari|tauchen",
        metaTitle: "Outdoor & Abenteuer in Antalya – Tickets günstig buchen",
        metaDescription: "Jeep-Safari, Canyoning, Paragliding & mehr – die besten Outdoor-Aktivitäten in Antalya günstig buchen. ✓ Sofortbuchung ✓ Gratis Storno ✓ Top-Bewertungen.",
        h1: "Outdoor & Abenteuer in Antalya",
        intro: "Antalya ist nicht nur für seine Strände bekannt – die Region bietet auch atemberaubende Outdoor-Erlebnisse. Ob Jeep-Safari durch die Berge, Paragliding über dem Mittelmeer oder Canyoning in wilden Schluchten: Hier kommt jeder Abenteurer auf seine Kosten.",
      },
      {
        slug: "ausfluege-touren",
        label: "Ausflüge & Touren",
        keywords: "tagesausflug|ausflug|tour|rundfahrt|jeep|safari|bootsfahrt|bootstour|kurs|erlebnis",
        metaTitle: "Ausflüge & Touren ab Antalya – Tagestouren buchen",
        metaDescription: "Tagesausflüge & geführte Touren ab Antalya günstig buchen. ✓ Bootstouren ✓ Jeep-Safaris ✓ Stadtführungen ✓ Sofortbuchung & Gratis Storno.",
        h1: "Ausflüge & Touren ab Antalya",
        intro: "Entdecke die Umgebung von Antalya mit geführten Tagestouren und spannenden Ausflügen. Von Bootsfahrten entlang der Küste bis zu Jeep-Safaris durch den Taurus – hier ist für jeden Geschmack etwas dabei.",
      },
      {
        slug: "wassersport-strand",
        label: "Wassersport & Strand",
        keywords: "aquapark|wasserpark|jet ski|jetski|wakeboard|schnorchel|tauchen|surfen|kayak|kajak|strand|beach|swim",
        metaTitle: "Wassersport & Strandaktivitäten in Antalya buchen",
        metaDescription: "Wassersport in Antalya: Aquaparks, Jet-Ski, Schnorcheln, Paragliding & mehr günstig buchen. ✓ Spaß für die ganze Familie ✓ Sofortbuchung.",
        h1: "Wassersport & Strandaktivitäten in Antalya",
        intro: "Das kristallklare Mittelmeer vor Antalyas Küste lädt zu allem ein: Schnorcheln, Tauchen, Jet-Ski-Fahren oder einfach einen aufregenden Tag im Aquapark verbringen – Wasserspaß ist in Antalya garantiert.",
      },
      {
        slug: "kulturerlebnisse",
        label: "Kultur & Sehenswürdigkeiten",
        keywords: "museum|aspendos|perge|thermessos|antik|historisch|altstadt|roman|ruinen|kulturell|konyaaltı|besichtig",
        metaTitle: "Kulturerlebnisse & Sehenswürdigkeiten in Antalya buchen",
        metaDescription: "Kulturelle Highlights in Antalya: Antike Ruinen, Museen & Altstadt-Touren günstig buchen. ✓ Geführte Besichtigungen ✓ Geschichte erleben ✓ Sofortbuchung.",
        h1: "Kultur & Sehenswürdigkeiten in Antalya",
        intro: "Antalya blickt auf eine über 2.000-jährige Geschichte zurück. Besuche das gut erhaltene Amphitheater von Aspendos, die antike Stadt Perge oder flaniere durch die charmante Altstadt Kaleiçi – Geschichte zum Anfassen.",
      },
    ] as TiqetsNiche[],
    faqs: [
      {
        question: "Wann ist die beste Reisezeit für Antalya?",
        answer: "Die beste Reisezeit für Antalya ist von Mai bis Oktober. Juli und August sind mit bis zu 35 °C am heißesten. Für angenehmere Temperaturen empfehlen sich Mai, Juni oder September – mit viel Sonne und weniger Trubel.",
      },
      {
        question: "Brauche ich ein Visum für einen Antalya Urlaub?",
        answer: "Deutsche Staatsbürger benötigen für die Türkei ein e-Visum, das online über das offizielle Portal beantragt werden kann. Es kostet ca. 35 USD und ist für 90 Tage gültig. Ein gültiger Reisepass (mindestens 6 Monate über das Reisedatum hinaus) ist erforderlich.",
      },
      {
        question: "Was kostet eine Pauschalreise nach Antalya?",
        answer: "Pauschalreisen nach Antalya sind schon ab ca. 350 € pro Person (inkl. Flug & Hotel, 7 Nächte) erhältlich. All-Inclusive-Angebote starten ab ca. 500 € p.P. Die Preise variieren je nach Reisezeitraum, Hotel-Kategorie und Abflughafen.",
      },
      {
        question: "Welcher Flughafen liegt nah an Antalya?",
        answer: "Der internationale Flughafen Antalya (IATA: AYT) liegt nur etwa 13 km vom Stadtzentrum entfernt. Von Deutschland aus gibt es Direktflüge u.a. ab Frankfurt, München, Düsseldorf, Berlin und Hamburg – Flugzeit ca. 3,5 Stunden.",
      },
      {
        question: "Lohnt sich All-Inclusive in Antalya?",
        answer: "Ja – Antalya ist weltweit für seine hervorragenden All-Inclusive-Resorts bekannt. Gerade an der Türkischen Riviera (Belek, Side, Alanya) bieten 4- und 5-Sterne-Hotels ausgezeichnetes AI-Angebot zu fairen Preisen. Ideal für Familien und Paare.",
      },
    ],
    entryInfo: {
      visa: "E-Visum erforderlich (ca. 35 USD, online unter evisa.gov.tr beantragen). Reisepass mind. 6 Monate gültig.",
      currency: "Türkische Lira (TRY). Kreditkarten werden in Hotels und Restaurants weitgehend akzeptiert. Wechselgeld in TRY empfohlen.",
      language: "Türkisch. In Touristengebieten wird häufig Englisch und Deutsch gesprochen.",
      timezone: "UTC+3 (keine Sommerzeit). Türkei ist 2 Stunden vor Deutschland (Winter) bzw. 1 Stunde vor (Sommer).",
      voltage: "220 V, 50 Hz. Steckdosen Typ F (Schuko) – deutsche Stecker passen direkt.",
      health: "Krankenversicherung mit Auslandsschutz empfohlen. Keine Pflichtimpfungen für EU-Bürger. Sonnenschutz und Wasservorsicht beachten.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 14, tempLow: 6, rain: 240 },
      { month: "Feb", tempHigh: 15, tempLow: 7, rain: 170 },
      { month: "Mär", tempHigh: 18, tempLow: 9, rain: 105 },
      { month: "Apr", tempHigh: 22, tempLow: 13, rain: 50 },
      { month: "Mai", tempHigh: 27, tempLow: 17, rain: 25 },
      { month: "Jun", tempHigh: 32, tempLow: 22, rain: 5 },
      { month: "Jul", tempHigh: 35, tempLow: 25, rain: 2 },
      { month: "Aug", tempHigh: 35, tempLow: 25, rain: 2 },
      { month: "Sep", tempHigh: 31, tempLow: 21, rain: 18 },
      { month: "Okt", tempHigh: 25, tempLow: 16, rain: 70 },
      { month: "Nov", tempHigh: 19, tempLow: 11, rain: 150 },
      { month: "Dez", tempHigh: 15, tempLow: 8, rain: 230 },
    ] as ClimateMonth[],
    carLocationKey: "AS.TR.07.AYT.AYT",
    coordinates: { lat: 36.8969, lng: 30.7133 },
  },
  {
    slug: "mallorca",
    name: "Mallorca",
    regionIds: [1, 2, 3],
    country: "Spanien",
    heroImage: "/images/destinations/mallorca-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=1600&q=80",
    cardImage: "/images/destinations/mallorca-card.jpg",
    description: "Mallorca – die größte Baleareninsel mit traumhaften Stränden, malerischen Dörfern und leckerem Essen.",
    metaTitle: "Mallorca Urlaub 2026 – günstig buchen",
    metaDescription: "Günstige Mallorca Pauschalreisen ✓ All-Inclusive ✓ Last-Minute ✓ Jetzt Angebote vergleichen und Traumurlaub auf den Balearen buchen.",
    iataCode: "PMI",
    ibeBpRegion: "eu",
    ibeRegionId: "133",
    tiqetsCityId: "65915",
    tiqetsNiches: [
      {
        slug: "museen-kultur",
        label: "Museen & Kultur",
        keywords: "museum|kathedrale|palast|almudaina|miró|miro|nadal|galerie|kunst|kultur|denkmal|fundació",
        metaTitle: "Museen & Kultur auf Mallorca – Eintrittskarten günstig buchen",
        metaDescription: "Die schönsten Museen & Kulturhighlights auf Mallorca entdecken: Kathedrale La Seu, Fundació Miró, Königspalast & mehr. ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Museen & Kultur auf Mallorca",
        intro: "Mallorca hat weit mehr zu bieten als Strand und Sonne. Die gotische Kathedrale La Seu, das Fundació Miró Mallorca und der beeindruckende Königspalast La Almudaina laden zu unvergesslichen Kulturerlebnissen ein.",
      },
      {
        slug: "ausfluege-natur",
        label: "Ausflüge & Natur",
        keywords: "segeln|boot|segeltörn|höhle|garten|ausflug|tour|hop-on|quad|sóller|natur|wandern|alfabia|campanet",
        metaTitle: "Ausflüge & Natur auf Mallorca – Touren günstig buchen",
        metaDescription: "Mallorca Ausflüge & Naturerlebnisse: Segeltörns, Höhlen, Hop-on Hop-off & Quad-Touren günstig buchen. ✓ Kleine Gruppen ✓ Sofortbuchung ✓ Top-Bewertungen.",
        h1: "Ausflüge & Natur auf Mallorca",
        intro: "Von romantischen Segeltörns entlang der Küste bis zu mystischen Tropfsteinhöhlen und üppigen Gärten – Mallorca bietet atemberaubende Naturerlebnisse und spannende Ausflüge für die ganze Familie.",
      },
      {
        slug: "familien-freizeitparks",
        label: "Familie & Freizeitparks",
        keywords: "aquarium|marineland|waterpark|wasserpark|dinosaur|dino|western|palma aquarium|tierpark|freizeitpark|abenteuerpark|katmandu",
        metaTitle: "Familienaktivitäten & Freizeitparks auf Mallorca buchen",
        metaDescription: "Freizeitparks, Aquarien & Familienattraktionen auf Mallorca günstig buchen: Palma Aquarium, Marineland, Western Water Park & mehr. ✓ Spaß für Kinder & Erwachsene.",
        h1: "Familienaktivitäten & Freizeitparks auf Mallorca",
        intro: "Mallorca ist perfekt für Familien! Das Palma Aquarium mit Europas tiefster Haifischbecken, Marineland mit Delfinen und Pinguinen sowie abenteuerliche Freizeitparks sorgen für unvergessliche Urlaubserinnerungen.",
      },
    ] as TiqetsNiche[],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten überall akzeptiert. Spanien hat kein Trinkgeldpflicht, aber 10 % ist üblich.",
      language: "Katalanisch & Spanisch. In Touristengebieten weit verbreitet: Englisch, Deutsch.",
      timezone: "UTC+1 / UTC+2 (Sommerzeit). Gleiche Zeitzone wie Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC/EHIC) wird akzeptiert. Sunscreen empfohlen. Leitungswasser trinkbar.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 15, tempLow: 8, rain: 40 },
      { month: "Feb", tempHigh: 16, tempLow: 8, rain: 35 },
      { month: "Mär", tempHigh: 18, tempLow: 10, rain: 40 },
      { month: "Apr", tempHigh: 20, tempLow: 12, rain: 45 },
      { month: "Mai", tempHigh: 24, tempLow: 16, rain: 30 },
      { month: "Jun", tempHigh: 28, tempLow: 20, rain: 15 },
      { month: "Jul", tempHigh: 31, tempLow: 23, rain: 5 },
      { month: "Aug", tempHigh: 31, tempLow: 23, rain: 10 },
      { month: "Sep", tempHigh: 28, tempLow: 20, rain: 40 },
      { month: "Okt", tempHigh: 23, tempLow: 16, rain: 70 },
      { month: "Nov", tempHigh: 18, tempLow: 12, rain: 60 },
      { month: "Dez", tempHigh: 15, tempLow: 9, rain: 50 },
    ] as ClimateMonth[],
    carLocationKey: "AS.ES.07.PMI.PMI",
    coordinates: { lat: 39.6953, lng: 3.0176 },
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    regionIds: [200, 201],
    country: "Spanien",
    heroImage: "/images/destinations/barcelona-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1600&q=80",
    cardImage: "/images/destinations/barcelona-card.jpg",
    description: "Barcelona – Gaudí, Tapas und Strand. Die katalanische Metropole begeistert mit Architektur, Kultur und Mittelmeer-Flair.",
    metaTitle: "Barcelona Urlaub 2026 – Städtereise günstig buchen",
    metaDescription: "Günstige Barcelona Städtereisen ✓ Kurzurlaub ✓ Jetzt Angebote vergleichen und die katalanische Metropole entdecken.",
    iataCode: "BCN",
    ibeBpRegion: "eu",
    ibeRegionId: "100027",
    ibeCityId: "587",
    tiqetsCityId: "66342",
    tiqetsNiches: [
      {
        slug: "gaudi-architektur",
        label: "Gaudí & Architektur",
        keywords: "gaudí|gaudi|sagrada|güell|guell|batlló|batllo|pedrera|milà|mila|casa|palau",
        metaTitle: "Gaudí Sehenswürdigkeiten in Barcelona – Tickets günstig buchen",
        metaDescription: "Sagrada Família, Park Güell, Casa Batlló & mehr – Eintrittskarten für Gaudís Meisterwerke in Barcelona günstig buchen. ✓ Skip-the-Line ✓ Sofortbuchung.",
        h1: "Gaudí & Architektur in Barcelona",
        intro: "Kein Besuch Barcelonas ist vollständig ohne Antoni Gaudís architektonische Meisterwerke. Von der unvollendeten Sagrada Família über den bunten Park Güell bis zum atemberaubenden Casa Batlló – entdecke die Ikonen des katalanischen Modernismus.",
        tiqetsCategoryPath: "/sehenswuerdigkeiten-t435/",
      },
      {
        slug: "museen-kunst",
        label: "Museen & Kunst",
        keywords: "museum|moco|aquarium|zoo|kunst|galerie|fc barcelona|camp nou|picasso|historisches",
        metaTitle: "Museen & Kunst in Barcelona – Eintrittskarten günstig buchen",
        metaDescription: "Die besten Museen in Barcelona: Moco Museum, FC Barcelona Museum, Barcelona Aquarium & mehr günstig buchen. ✓ Gratis Storno ✓ Skip-the-Line Tickets.",
        h1: "Museen & Kunst in Barcelona",
        intro: "Barcelona ist eine Welthauptstadt der Kunst und Kultur. Das innovative Moco Museum, das legendäre Camp Nou, das faszinierende Barcelona Aquarium und unzählige weitere Museen machen die Stadt zu einem Paradies für Kulturliebhaber.",
      },
      {
        slug: "stadttouren",
        label: "Stadttouren",
        keywords: "hop-on|hop off|city tour|stadtführung|audioguide|audio guide|bus|sightseeing|guided|führung|rundfahrt",
        metaTitle: "Stadttouren Barcelona – Hop-on Hop-off & Geführte Touren buchen",
        metaDescription: "Barcelona Stadttouren günstig buchen: Hop-on Hop-off Bus, geführte Touren, Audioguides & mehr. ✓ Sofortbuchung ✓ Top-Bewertungen ✓ Gratis Storno.",
        h1: "Stadttouren in Barcelona",
        intro: "Entdecke Barcelona auf deine Art: Mit dem klassischen Hop-on Hop-off Bus hältst du an den schönsten Sehenswürdigkeiten, geführte Touren bringen dir die Geschichte der Stadt näher, und mit Audioguide-Apps erkundest du die Metropole in deinem eigenen Tempo.",
      },
      {
        slug: "sport-fc-barcelona",
        label: "Sport & FC Barcelona",
        keywords: "fc barcelona|camp nou|fútbol|fußball|sport|montjuïc|seilbahn|stadion|museum fc|barcelon",
        metaTitle: "FC Barcelona & Sport-Aktivitäten in Barcelona – Tickets buchen",
        metaDescription: "FC Barcelona Tickets, Camp Nou Tour, Montjuïc Seilbahn & Sportaktivitäten in Barcelona günstig buchen. ✓ Sofortbuchung ✓ Offizielle Tickets ✓ Top-Bewertungen.",
        h1: "Sport & FC Barcelona in Barcelona",
        intro: "Für Fußballfans ist eine Besichtigung des Camp Nou und des FC Barcelona Museums ein absolutes Muss. Darüber hinaus bietet Barcelona mit der Montjuïc-Seilbahn, Strand-Sports und vielen weiteren Aktivitäten Erlebnisse für jeden Sportbegeisterten.",
      },
      {
        slug: "barcelona-pass-citycard",
        label: "City Pässe & Kombi-Tickets",
        keywords: "pass|card|karte|kombi|bundle|essentials|hola|paket|kombiniert|transport|öpnv",
        metaTitle: "Barcelona City Pass & Kombi-Tickets – Günstig & Flexibel buchen",
        metaDescription: "Barcelona Pass, Hola Barcelona Card & Kombi-Tickets günstig buchen. Mit einem Pass Öffis + Attraktionen sparen. ✓ Sofortbuchung ✓ Gratis Storno ✓ Top-Angebote.",
        h1: "City Pässe & Kombi-Tickets für Barcelona",
        intro: "Mit einem Barcelona City Pass oder der Hola Barcelona Card sparst du doppelt: Du erhältst freien Eintritt oder Rabatte bei den beliebtesten Attraktionen und nutzt dabei bequem und kostenlos den öffentlichen Nahverkehr. Ideal für Kurzentschlossene und Vielseher.",
      },
    ] as TiqetsNiche[],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten überall akzeptiert. Restaurants: 10 % Trinkgeld ist üblich.",
      language: "Katalanisch & Spanisch. Englisch in der Tourismusbranche weit verbreitet.",
      timezone: "UTC+1 / UTC+2 (Sommerzeit). Gleiche Zeitzone wie Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Leitungswasser ist trinkbar.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 13, tempLow: 6, rain: 45 },
      { month: "Feb", tempHigh: 14, tempLow: 7, rain: 40 },
      { month: "Mär", tempHigh: 16, tempLow: 9, rain: 50 },
      { month: "Apr", tempHigh: 18, tempLow: 11, rain: 55 },
      { month: "Mai", tempHigh: 22, tempLow: 15, rain: 55 },
      { month: "Jun", tempHigh: 26, tempLow: 19, rain: 35 },
      { month: "Jul", tempHigh: 28, tempLow: 22, rain: 25 },
      { month: "Aug", tempHigh: 28, tempLow: 22, rain: 45 },
      { month: "Sep", tempHigh: 25, tempLow: 19, rain: 70 },
      { month: "Okt", tempHigh: 21, tempLow: 15, rain: 90 },
      { month: "Nov", tempHigh: 16, tempLow: 10, rain: 65 },
      { month: "Dez", tempHigh: 13, tempLow: 7, rain: 55 },
    ] as ClimateMonth[],
    carLocationKey: "AS.ES.06.BCN.BCN",
    coordinates: { lat: 41.3851, lng: 2.1734 },
  },
  {
    slug: "kreta",
    name: "Kreta",
    regionIds: [50, 51, 52],
    country: "Griechenland",
    heroImage: "/images/destinations/kreta-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1600&q=80",
    cardImage: "/images/destinations/kreta-card.jpg",
    description: "Kreta – die größte griechische Insel mit wilden Schluchten, goldenen Stränden und jahrtausendealter Geschichte.",
    metaTitle: "Kreta Urlaub 2026 – Pauschalreisen günstig buchen",
    metaDescription: "Günstige Kreta Pauschalreisen ✓ All-Inclusive ✓ Last-Minute ✓ Jetzt Angebote vergleichen und Griechenlands größte Insel erleben.",
    iataCode: "HER",
    ibeBpRegion: "eu",
    ibeRegionId: "46",
    tiqetsCityId: "38",
    tiqetsNiches: [
      {
        slug: "geschichte-archaeologie",
        label: "Geschichte & Archäologie",
        keywords: "knossos|minoisch|minoer|museum|archäolog|antik|byzantin|palast|festung|ruinen|minoan",
        metaTitle: "Geschichte & Archäologie auf Kreta – Tickets günstig buchen",
        metaDescription: "Kreta entdecken: Knossos, minoische Paläste, archäologische Museen & mehr günstig buchen. ✓ Sofortbuchung ✓ Gratis Storno ✓ Führungen auf Deutsch.",
        h1: "Geschichte & Archäologie auf Kreta",
        intro: "Kreta ist die Wiege der minoischen Zivilisation, einer der ältesten Hochkulturen Europas. Der Palast von Knossos, eindrucksvolle archäologische Museen und byzantinische Festungen machen die Insel zu einem Paradies für Geschichtsbegeisterte.",
      },
      {
        slug: "outdoor-natur",
        label: "Outdoor & Natur",
        keywords: "wandern|schlucht|gorge|strand|boot|segeln|kajak|natur|weinverkostung|wein|outdoor|tauchen|schnorcheln",
        metaTitle: "Outdoor & Natur auf Kreta – Aktivitäten günstig buchen",
        metaDescription: "Outdoor-Aktivitäten auf Kreta: Schluchten-Wanderungen, Segeln, Weinverkostungen & mehr günstig buchen. ✓ Unvergessliche Erlebnisse ✓ Sofortbuchung.",
        h1: "Outdoor & Natur auf Kreta",
        intro: "Kreta begeistert mit wilder Natur und vielfältigen Outdoor-Erlebnissen. Wandere durch die beeindruckende Samaria-Schlucht, erkunde die Küste per Boot oder genieße eine authentische kretische Weinverkostung inmitten atemberaubender Landschaft.",
      },
    ] as TiqetsNiche[],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten werden in Hotels und größeren Restaurants akzeptiert. Bargeld für kleine Tavernen empfohlen.",
      language: "Griechisch. In Touristengebieten wird Englisch und Deutsch häufig gesprochen.",
      timezone: "UTC+2 / UTC+3 (Sommerzeit). Kreta ist im Sommer 1 Stunde vor Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Sonnenschutz wichtig. Leitungswasser trinkbar in Städten.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 15, tempLow: 9, rain: 105 },
      { month: "Feb", tempHigh: 16, tempLow: 9, rain: 88 },
      { month: "Mär", tempHigh: 18, tempLow: 11, rain: 52 },
      { month: "Apr", tempHigh: 21, tempLow: 14, rain: 22 },
      { month: "Mai", tempHigh: 25, tempLow: 18, rain: 10 },
      { month: "Jun", tempHigh: 29, tempLow: 22, rain: 5 },
      { month: "Jul", tempHigh: 31, tempLow: 24, rain: 1 },
      { month: "Aug", tempHigh: 31, tempLow: 24, rain: 2 },
      { month: "Sep", tempHigh: 28, tempLow: 21, rain: 20 },
      { month: "Okt", tempHigh: 24, tempLow: 17, rain: 52 },
      { month: "Nov", tempHigh: 20, tempLow: 13, rain: 82 },
      { month: "Dez", tempHigh: 16, tempLow: 10, rain: 100 },
    ] as ClimateMonth[],
    carLocationKey: "AS.GR.07.HER.HER",
    coordinates: { lat: 35.3387, lng: 25.1442 },
  },
];

export function getDestinationBySlug(slug: string): DestinationConfig | undefined {
  return destinations.find((d) => d.slug === slug);
}

// Bild-Fallback: Unsplash bis eigene Bilder in /public/images/ vorhanden
export function destImg(dest: DestinationConfig, type: "hero" | "card" = "hero"): string {
  if (type === "card") return dest.heroImageFallback || dest.heroImage;
  return dest.heroImageFallback || dest.heroImage;
}
