-- ── Reiseziele (Top 20 für deutsche Urlauber) ────────────────────
INSERT INTO destinations (slug, name, country, country_code, continent, lat, lng, description, climate, best_season, tags) VALUES
  ('mallorca', 'Mallorca', 'Spanien', 'ES', 'Europa', 39.6953, 3.0176, 'Die beliebteste Urlaubsinsel der Deutschen bietet traumhafte Strände, malerische Buchten und das pulsierende Palma de Mallorca.', 'mediterran', ARRAY['Mai','Jun','Jul','Aug','Sep','Okt'], ARRAY['strand','familie','kultur','nachtleben']),
  ('antalya', 'Antalya', 'Türkei', 'TR', 'Europa', 36.8969, 30.7133, 'Die türkische Riviera begeistert mit All-Inclusive-Resorts, antiken Ruinen und der spektakulären Küstenlandschaft.', 'mediterran', ARRAY['Mai','Jun','Jul','Aug','Sep','Okt'], ARRAY['strand','all-inclusive','kultur','familie']),
  ('kreta', 'Kreta', 'Griechenland', 'GR', 'Europa', 35.2401, 24.8093, 'Griechenlands größte Insel vereint mythische Geschichte, wilde Schluchten und kristallklares Wasser.', 'mediterran', ARRAY['Mai','Jun','Jul','Aug','Sep','Okt'], ARRAY['strand','kultur','wandern','natur']),
  ('hurghada', 'Hurghada', 'Ägypten', 'EG', 'Afrika', 27.2579, 33.8116, 'Am Roten Meer gelegen, ist Hurghada ein Paradies für Taucher und Schnorchler mit ganzjährig warmem Wetter.', 'wüste', ARRAY['Jan','Feb','Mär','Apr','Okt','Nov','Dez'], ARRAY['strand','tauchen','all-inclusive','schnorcheln']),
  ('barcelona', 'Barcelona', 'Spanien', 'ES', 'Europa', 41.3874, 2.1686, 'Gaudís Meisterwerke, lebendige Ramblas und mediterranes Flair machen Barcelona zu einem perfekten Städtetrip.', 'mediterran', ARRAY['Apr','Mai','Jun','Sep','Okt'], ARRAY['kultur','stadt','strand','architektur']),
  ('fuerteventura', 'Fuerteventura', 'Spanien', 'ES', 'Europa', 28.3587, -14.0537, 'Die Kanareninsel beeindruckt mit endlosen Sandstränden, türkisem Wasser und idealen Windsurfbedingungen.', 'subtropisch', ARRAY['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'], ARRAY['strand','surfen','natur','ganzjährig']),
  ('gran-canaria', 'Gran Canaria', 'Spanien', 'ES', 'Europa', 27.9202, -15.5474, 'Der Miniaturkontinent bietet von Dünen über Bergdörfer bis zu lebendigen Städten alles für jeden Geschmack.', 'subtropisch', ARRAY['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'], ARRAY['strand','natur','wandern','ganzjährig']),
  ('teneriffa', 'Teneriffa', 'Spanien', 'ES', 'Europa', 28.2916, -16.6291, 'Vom Teide-Vulkan über schwarze Lavastrände bis zum grünen Norden – Teneriffa überrascht mit Kontrasten.', 'subtropisch', ARRAY['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'], ARRAY['strand','natur','wandern','vulkan','ganzjährig']),
  ('rhodos', 'Rhodos', 'Griechenland', 'GR', 'Europa', 36.4341, 28.2176, 'Die Sonneninsel der Ägäis lockt mit der mittelalterlichen Altstadt, antiken Stätten und wunderschönen Stränden.', 'mediterran', ARRAY['Mai','Jun','Jul','Aug','Sep','Okt'], ARRAY['strand','kultur','geschichte','familie']),
  ('rom', 'Rom', 'Italien', 'IT', 'Europa', 41.9028, 12.4964, 'Die Ewige Stadt fasziniert mit dem Kolosseum, dem Vatikan und der besten Küche der Welt.', 'mediterran', ARRAY['Mär','Apr','Mai','Sep','Okt','Nov'], ARRAY['kultur','stadt','geschichte','essen']),
  ('side', 'Side', 'Türkei', 'TR', 'Europa', 36.7673, 31.3886, 'Antike Ruinen direkt am Strand – Side verbindet Geschichte mit modernem Badeurlaub an der türkischen Riviera.', 'mediterran', ARRAY['Mai','Jun','Jul','Aug','Sep','Okt'], ARRAY['strand','all-inclusive','kultur','familie']),
  ('bodrum', 'Bodrum', 'Türkei', 'TR', 'Europa', 37.0344, 27.4305, 'Das Saint-Tropez der Türkei mit weißen Häusern, lebendiger Marina und kristallklaren Buchten.', 'mediterran', ARRAY['Mai','Jun','Jul','Aug','Sep'], ARRAY['strand','nachtleben','segeln','kultur']),
  ('malediven', 'Malediven', 'Malediven', 'MV', 'Asien', 3.2028, 73.2207, 'Traumhafte Overwater-Bungalows, türkisfarbene Lagunen und unberührte Korallenriffe im Indischen Ozean.', 'tropisch', ARRAY['Jan','Feb','Mär','Apr','Nov','Dez'], ARRAY['strand','luxus','tauchen','honeymoon']),
  ('dubai', 'Dubai', 'Vereinigte Arabische Emirate', 'AE', 'Asien', 25.2048, 55.2708, 'Wolkenkratzer, Wüstensafaris und Luxus-Shopping – Dubai ist die Stadt der Superlative.', 'wüste', ARRAY['Nov','Dez','Jan','Feb','Mär'], ARRAY['stadt','luxus','shopping','strand']),
  ('phuket', 'Phuket', 'Thailand', 'TH', 'Asien', 7.8804, 98.3923, 'Thailands größte Insel begeistert mit tropischen Stränden, buddhistischen Tempeln und weltberühmter Küche.', 'tropisch', ARRAY['Nov','Dez','Jan','Feb','Mär','Apr'], ARRAY['strand','kultur','essen','tauchen']),
  ('bali', 'Bali', 'Indonesien', 'ID', 'Asien', -8.3405, 115.0920, 'Die Insel der Götter fasziniert mit Reisterrassen, Hindu-Tempeln, Yoga-Retreats und Surfspots.', 'tropisch', ARRAY['Apr','Mai','Jun','Jul','Aug','Sep','Okt'], ARRAY['kultur','natur','surfen','yoga']),
  ('kapstadt', 'Kapstadt', 'Südafrika', 'ZA', 'Afrika', -33.9249, 18.4241, 'Am Fuße des Tafelbergs gelegen, bietet Kapstadt Weinberge, Pinguinkolonien und spektakuläre Küsten.', 'mediterran', ARRAY['Nov','Dez','Jan','Feb','Mär'], ARRAY['natur','stadt','wein','abenteuer']),
  ('new-york', 'New York', 'USA', 'US', 'Nordamerika', 40.7128, -74.0060, 'Die Stadt, die niemals schläft – von der Freiheitsstatue über den Times Square bis zum Central Park.', 'kontinental', ARRAY['Apr','Mai','Jun','Sep','Okt'], ARRAY['stadt','kultur','shopping','sightseeing']),
  ('cancun', 'Cancún', 'Mexiko', 'MX', 'Nordamerika', 21.1619, -86.8515, 'Karibische Traumstrände, Maya-Ruinen und ein legendäres Nachtleben an der mexikanischen Riviera Maya.', 'tropisch', ARRAY['Dez','Jan','Feb','Mär','Apr'], ARRAY['strand','kultur','all-inclusive','tauchen']),
  ('sansibar', 'Sansibar', 'Tansania', 'TZ', 'Afrika', -6.1659, 39.1989, 'Die Gewürzinsel im Indischen Ozean bezaubert mit weißen Stränden, Stone Town und exotischen Aromen.', 'tropisch', ARRAY['Jun','Jul','Aug','Sep','Jan','Feb'], ARRAY['strand','kultur','natur','exotisch']);

-- ── Achievements ─────────────────────────────────────────────────
INSERT INTO achievements (slug, name, description, icon, xp_reward, condition, category) VALUES
  ('first_favorite', 'Erster Favorit', 'Speichere dein erstes Reiseziel als Favorit', '⭐', 10, '{"type": "favorites_count", "value": 1}', 'collector'),
  ('first_report', 'Reisereporter', 'Schreibe deinen ersten Reisebericht', '📝', 25, '{"type": "reports_count", "value": 1}', 'community'),
  ('five_reports', 'Vielschreiber', 'Schreibe 5 Reiseberichte', '✍️', 100, '{"type": "reports_count", "value": 5}', 'community'),
  ('three_countries', 'Weltenbummler', 'Besuche 3 verschiedene Länder', '🌍', 50, '{"type": "countries_count", "value": 3}', 'explorer'),
  ('ten_countries', 'Globetrotter', 'Besuche 10 verschiedene Länder', '✈️', 200, '{"type": "countries_count", "value": 10}', 'explorer'),
  ('five_favorites', 'Sammler', 'Speichere 5 Reiseziele als Favoriten', '💎', 30, '{"type": "favorites_count", "value": 5}', 'collector'),
  ('first_alert', 'Schnäppchenjäger', 'Erstelle deinen ersten Preisalarm', '🔔', 15, '{"type": "alerts_count", "value": 1}', 'collector'),
  ('top_rated', 'Bestnote', 'Gib einem Reiseziel 5 Sterne', '🏆', 20, '{"type": "five_star_review", "value": 1}', 'community');
