import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🌿", text: "Milde 12–15 °C, kaum Touristen. Alanya gehört den Einheimischen. Ideale Zeit für Stadtbesichtigungen, Wanderungen und authentische Restaurants." },
    { label: "Februar",   emoji: "🌸", text: "Zitrus- und Mandelbäume blühen. Angenehme 16 °C. Kein Badewetter, aber perfekt für kulturelle Entdeckungen." },
    { label: "März",      emoji: "🌼", text: "Frühling beginnt mit 19 °C. Erste Sonnentage, Restaurants öffnen wieder. Günstige Vorsaison-Preise." },
    { label: "April",     emoji: "📸", text: "Angenehme 22 °C, Touristensaison beginnt. Burg von Alanya und Roten Turm ohne Gedränge besichtigen." },
    { label: "Mai",       emoji: "🏖️", text: "Badesaison offiziell eröffnet. 23 °C Wassertemperatur. Cleopatra Beach füllt sich langsam – ideale Zeit." },
    { label: "Juni",      emoji: "☀️", text: "Hochsaison beginnt. 27 °C, angenehm heißes Wetter. Abende zum Bummeln und Essen am Hafen perfekt." },
    { label: "Juli",      emoji: "🔆", text: "Heißester Monat mit 35 °C. Früh morgens Sehenswürdigkeiten, mittags Strand und Pool. Sehr belebt." },
    { label: "August",    emoji: "🌊", text: "Hochsaison: Alles ausgebucht, Preise auf Maximum. Cleopatra Beach täglich voll. Wassertemperatur 28 °C." },
    { label: "September", emoji: "🌅", text: "Noch heiß (30 °C), aber deutlich ruhiger. Günstigere Preise, warmes Meer. Perfekter Herbsturlaub." },
    { label: "Oktober",   emoji: "🍊", text: "Angenehme 26 °C, letztes echtes Badewetter. Cleopatra Beach fast leer. Orangenernte beginnt." },
    { label: "November",  emoji: "🌧️", text: "Erste Regentage, Temperaturen sinken auf 19 °C. Betriebe schließen. Authentisches Alanya für Individualreisende." },
    { label: "Dezember",  emoji: "☕", text: "Ruhige Winterzeit mit 14 °C. Lokale Märkte, frische Zitrusfrüchte und Tee in Çay-Häusern." },
  ],
  sights: [
    {
      title: "Kızılkule – Roter Turm",
      desc: "Das Wahrzeichen Alanyas: Der 1226 von Sultan Alaeddin Keykubat erbaute achteckige Turm aus rotem Backstein bewacht den Hafen. Die 33 m hohe Wehranlage gilt als perfektestes Beispiel seldschukischer Militärarchitektur.",
      mapHref: "https://maps.google.com/?q=Kizilkule+Alanya",
      address: "İskele Caddesi, Alanya",
      duration: "1 Std.",
      cost: "5 € (ca. 100 TL)",
      tip: "Von der Turm-Galerie der schönste Blick auf den Hafen und die Burg bei Sonnenuntergang.",
    },
    {
      title: "Alanya Burg (Alanya Kalesi)",
      desc: "Die imposante Kreuzfahrerburg hoch über der Stadt mit 6,5 km Mauern und fantastischem Panorama. Im Inneren: die İç Kale-Festung, die byzantinische Kirche und der historische Palast der Seldschuken.",
      mapHref: "https://maps.google.com/?q=Alanya+Kalesi",
      address: "Hisarönü Mah., Alanya",
      duration: "2–3 Std.",
      cost: "8 € (ca. 150 TL)",
      tip: "Shuttle-Bus von unten für 3 € – oder abenteuerliche Wanderung durch die Altstadt hinauf.",
    },
    {
      title: "Damlataş-Höhle & Cleopatra Beach",
      desc: "Die 1948 entdeckte Tropfsteinhöhle ist für ihr heilsames Mikroklima (feuchte Luft bei 23 °C) bekannt. Direkt daneben: der weltberühmte Cleopatra Beach mit feinem Quarzsand.",
      mapHref: "https://maps.google.com/?q=Damlatas+Cave+Alanya",
      address: "Cleopatra Plajı, Alanya",
      duration: "30 Min. (Höhle) + Strand",
      cost: "Höhle: 3 €",
      tip: "Der Sand von Cleopatra Beach enthält einen hohen Quarzanteil – er klebt nicht an der Haut.",
    },
    {
      title: "Alanya Meereshöhlen (Piratenhöhle & Phosphoreszenz)",
      desc: "Bootstouren entlang der Halbinsel führen zu spektakulären Meereshöhlen: Die Piratenhöhle (Korsanlar Mağarası) und die Phosphoreszenz-Höhle (Fosforlu Mağara) leuchten durch Algen magisch.",
      mapHref: "https://maps.google.com/?q=Alanya+Cave+Boat+Tour",
      address: "Hafen Alanya (Bootsanleger)",
      duration: "2–3 Std.",
      cost: "15–25 € (Bootstour)",
      tip: "Günstigste Touren direkt am Hafen buchen – Preise verhandelbar.",
    },
    {
      title: "Aspendos – Antikes Theater",
      desc: "Das besterhaltene römische Theater der Welt (ca. 155 n. Chr.) liegt 60 km westlich von Alanya. Das 15.000-Plätze-Theater wird noch heute für Konzerte und Opernaufführungen genutzt.",
      mapHref: "https://maps.google.com/?q=Aspendos+Theatre+Turkey",
      address: "Aspendos, Serik/Antalya",
      duration: "2–3 Std.",
      cost: "10 € (ca. 200 TL)",
      tip: "Kombination mit dem antiken Side auf einer Tagesausflug-Route.",
    },
  ],
  history: [
    {
      year: "4. Jh. v. Chr.",
      title: "Coracesium – Griechische Gründung",
      text: "Die Griechen gründeten auf dem Burgfelsen eine Befestigung namens Coracesium. Die strategische Position über dem Mittelmeer machte sie zur wichtigen Handelsstation und Seefestung.",
    },
    {
      year: "67 v. Chr.",
      title: "Pompejus besiegt die Piraten",
      text: "Der Fels von Alanya war Hauptstützpunkt der gefürchteten kilikischen Piraten. Der römische General Pompejus beendete ihre Herrschaft in der Seeschlacht vor Coracesium und befriedete das Mittelmeer.",
    },
    {
      year: "1221",
      title: "Seldschukische Eroberung",
      text: "Sultan Alaeddin Keykubat von Rum-Seldschuken nahm die Burg nach kurzer Belagerung ein und ließ die Stadt zu 'Alaiye' umbenennen. Er baute den Roten Turm, die Schiffswerft und die Burgmauern – die prägendsten Bauwerke Alanyas.",
    },
    {
      year: "1471",
      title: "Osmanische Herrschaft",
      text: "Die Osmanen unter Mehmed II. übernahmen Alanya kampflos. Die Stadt verlor an strategischer Bedeutung und verarmte. Erst im 20. Jahrhundert erlangte sie durch den Tourismus neue Dynamik.",
    },
    {
      year: "1935",
      title: "Umbenennung in Alanya",
      text: "Atatürk besuchte die Stadt und gab ihr auf Anregung türkischer Historiker den neuen Namen 'Alanya'. Die moderne Stadtentwicklung begann.",
    },
    {
      year: "1970er–heute",
      title: "Tourismus-Boom",
      text: "Deutsche, russische und skandinavische Touristen entdeckten Alanya als bezahlbares Sonnenziel. Cleopatra Beach wurde weltberühmt. Heute ist Alanya eines der meistbesuchten Tourismuszentren der Türkischen Riviera.",
    },
  ],
  food: [
    {
      emoji: "🥙",
      name: "Döner Kebap",
      original: "Döner Kebap",
      desc: "Der klassische türkische Döner aus dünnen Fleischscheiben (Lamm oder Huhn) im frischen Fladenbrot mit Tomaten, Paprika, Zwiebeln und Joghurt-Sauce – das Streetfood-Erlebnis Nummer 1.",
      price: "60–100 TL (~2–3 €)",
      tip: "Authentische Dönercis abseits der Touristenzone sind günstiger und besser.",
    },
    {
      emoji: "🍆",
      name: "İmam Bayıldı",
      original: "İmam Bayıldı",
      desc: "Im Ofen geschmorte Auberginen gefüllt mit Tomaten, Zwiebeln und Knoblauch – eines der bekanntesten vegetarischen Gerichte der türkischen Küche. Kalt oder warm als Vorspeise.",
      price: "150–200 TL (~5–7 €)",
    },
    {
      emoji: "🐟",
      name: "Balik Ekmek",
      original: "Balık Ekmek",
      desc: "Gegrillter Fisch im rustikalen Weißbrot mit Salat, Zwiebeln und Zitrone. Das einfachste und köstlichste Strandessen der türkischen Küste – frisch am Hafen zubereitet.",
      price: "80–120 TL (~2,5–4 €)",
      tip: "Direkt am Alanya-Hafen bei den kleinen Fischerständen.",
    },
    {
      emoji: "🍮",
      name: "Baklava",
      original: "Baklava",
      desc: "Hauchdünne Teigschichten mit gehackten Pistazien oder Walnüssen, getränkt in Zuckersirup oder Honig. Das süßeste Symbol der türkischen Küche – jede Region hat ihr Rezept.",
      price: "100–150 TL (~3–5 €) pro 100g",
      tip: "Gaziantep-Baklava gilt als Original – auf das Qualitätsmerkmal achten.",
    },
    {
      emoji: "🥤",
      name: "Ayran & Türkischer Çay",
      original: "Ayran / Türk Çayı",
      desc: "Ayran (gesalzenes Joghurtgetränk) ist das ideale Begleitgetränk zu scharfem Essen. Türkischer Çay (schwarzer Tee aus dem Doppelteekessel) ist das soziale Getränk des Landes – immer in kleinen Tulpengläsern.",
      price: "20–40 TL (~0,60–1,30 €)",
    },
  ],
  phrases: [
    { original: "Merhaba!", pronunciation: "mer-ha-ba", translation: "Hallo!" },
    { original: "Günaydın!", pronunciation: "gü-nai-dın", translation: "Guten Morgen!" },
    { original: "Teşekkür ederim", pronunciation: "te-schek-kür e-de-rim", translation: "Danke" },
    { original: "Lütfen", pronunciation: "lüt-fen", translation: "Bitte" },
    { original: "Bu ne kadar?", pronunciation: "bu ne ka-dar", translation: "Was kostet das?" },
    { original: "Hesabı alabilir miyim?", pronunciation: "he-sa-bı a-la-bi-lir mi-jim", translation: "Kann ich die Rechnung haben?" },
    { original: "Plaj nerede?", pronunciation: "plaj ne-re-de", translation: "Wo ist der Strand?" },
    { original: "Bir bira lütfen", pronunciation: "bir bi-ra lüt-fen", translation: "Ein Bier, bitte" },
    { original: "Doktora ihtiyacım var", pronunciation: "dok-to-ra ich-ti-ja-dschım var", translation: "Ich brauche einen Arzt" },
    { original: "Güle güle!", pronunciation: "gü-le gü-le", translation: "Auf Wiedersehen!" },
  ],
  insider: [
    {
      icon: "🚌",
      title: "Dolmuş statt Taxi",
      text: "Die Dolmuş-Minibusse fahren entlang der Hauptstraße und kosten ca. 15–25 TL (0,50–0,80 €) statt 150–300 TL Taxi. Einfach am Straßenrand winken und einsteigen.",
    },
    {
      icon: "🏪",
      title: "Bazaar-Preise verhandeln",
      text: "Im Alanya-Bazaar sind alle Preise Verhandlungssache. Faustregel: Mit 50 % des Erstpreises beginnen, freundlich bleiben, auf Weggehen vorbereiten. Für echte Lederwaren und Gewürze gilt: 30–40 % Rabatt realistisch.",
    },
    {
      icon: "🌅",
      title: "Sonnenuntergang von der Burg",
      text: "Der Sonnenuntergang vom İç Kale (Innenburg) bietet ein 360°-Panorama über Stadt, Meer und Halbinsel. Eintritt 8 € – der günstigste Aussichtspunkt der türkischen Riviera.",
    },
    {
      icon: "🐠",
      title: "Frühe Bootstouren für Meereshöhlen",
      text: "Bootstouren zu den Meereshöhlen starten zwischen 10 und 11 Uhr. Wer am Hafen wartet und mit mehreren Anbietern spricht, bekommt die 3-stündige Tour für 10–15 € statt 25 €.",
    },
    {
      icon: "🌿",
      title: "Bananen aus dem Alanya-Land",
      text: "Alanya ist Zentrum des türkischen Bananenanbaus – das milde Klima ermöglicht es als einziger Region der Türkei. Die kleinen lokalen Bananen sind süßer und aromatischer als Importbananen. An jedem Marktstand für wenige Lira.",
    },
  ],
  beaches: [
    {
      name: "Cleopatra Beach",
      emoji: "👑",
      desc: "Der berühmteste Strand Alanyas mit feinem Quarzsand, der angeblich nicht an der Haut klebt. Laut Legende badete die ägyptische Königin hier.",
      type: "Feiner Quarzsandstrand",
      tip: "Früh morgens oder nach 17 Uhr kommen – tagsüber extrem voll.",
    },
    {
      name: "Keykubat Beach",
      emoji: "🏖️",
      desc: "Ruhigerer Strand östlich des Zentrums, länger und weniger belebt als Cleopatra. Direkt an der Promenade mit Cafés und Restaurants.",
      type: "Sandstrand / Promenade",
    },
    {
      name: "Sapadere Schlucht",
      emoji: "🏞️",
      desc: "Kein Strand, aber ein spektakuläres Naturerlebnis: die Sapadere-Schlucht mit kristallklarem Bergbach und natürlichen Schwimmbecken in der Schlucht.",
      type: "Bergbach / Naturpool",
      tip: "Tagesausflug ab Alanya – kühle Alternative an Hitzetagen.",
    },
    {
      name: "Tosmur Beach",
      emoji: "🌊",
      desc: "Ruhiger Kiesstrand am östlichen Stadtrand, beliebter bei Einheimischen als bei Touristen. Günstige Strandrestaurants.",
      type: "Kiesstrand",
    },
    {
      name: "Mahmutlar Beach",
      emoji: "⛱️",
      desc: "Langer, ruhiger Sandstrand 10 km östlich von Alanya. Sehr beliebt bei deutschen und russischen Langzeiturlaubern – authentische Atmosphäre.",
      type: "Sandstrand / Wohnviertel",
    },
  ],
  regions: [
    {
      name: "Alanya Altstadt & Burg",
      emoji: "🏰",
      desc: "Das historische Herz auf dem Burgfelsen mit der Seldschuken-Burg, Rotem Turm und Schiffswerft.",
      highlights: ["Kızılkule (Roter Turm)", "Alanya Kalesi", "Seldschukische Schiffswerft"],
    },
    {
      name: "Cleopatra Beach & Zentrum",
      emoji: "👑",
      desc: "Das touristische Zentrum mit dem weltberühmten Strand, Einkaufsstraßen und Nachtleben.",
      highlights: ["Cleopatra Beach", "Damlataş Höhle", "Alanya Bazaar"],
    },
    {
      name: "Mahmutlar & Ostküste",
      emoji: "🌴",
      desc: "Ruhigere Urlaubsviertel östlich von Alanya mit langen Stränden und günstigeren Apartments.",
      highlights: ["Mahmutlar Beach", "Avsallar", "Türkische Restaurants"],
    },
    {
      name: "Umgebung & Tagesausflüge",
      emoji: "🏞️",
      desc: "Wunderschöne Natur und antike Stätten in der Umgebung – von der Sapadere-Schlucht bis Aspendos.",
      highlights: ["Sapadere Schlucht", "Aspendos Theater", "Dim Çay Fluss"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "20–50 €", mid: "60–130 €", luxury: "150–400 €+" },
    { label: "Essen (pro Tag)", budget: "8–15 €", mid: "20–45 €", luxury: "60–120 €+" },
    { label: "Transport (pro Tag)", budget: "2–5 € (Dolmuş)", mid: "15–30 € (Taxi)", luxury: "50–100 € (Privat)" },
    { label: "Aktivitäten (pro Tag)", budget: "5–15 €", mid: "20–50 €", luxury: "80–200 €+" },
    { label: "Tagesbudget gesamt", budget: "35–85 €", mid: "115–255 €", luxury: "340–820 €+" },
  ],
  emergency: {
    police: "155",
    ambulance: "112",
    fire: "110",
    embassy: "+90 312 455 5100 (Deutsche Botschaft Ankara) / Konsulat Antalya: +90 242 248 0454",
    hospital: "Alanya Eğitim ve Araştırma Hastanesi: +90 242 512 2400",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Burg & Sonnenuntergang am Hafen",
      icon: "🏰",
      color: "bg-rose-100",
      dayCost: "~60 €",
      transport: "Shuttle-Bus zur Burg",
      meals: "Harborfront Restaurant",
      stops: [
        { time: "09:30", activity: "Roter Turm & Hafen erkunden", icon: "🔴", tip: "Frühmorgens kaum Besucher – beste Lichtbedingungen für Fotos." },
        { time: "11:00", activity: "Shuttle-Bus zur Alanya Burg", icon: "🚌" },
        { time: "12:00", activity: "İç Kale – Innenburg und byzantinische Kirche", icon: "🏰" },
        { time: "14:00", activity: "Mittagessen in der Altstadt", icon: "🍽️" },
        { time: "17:00", activity: "Cleopatra Beach – Romantisches Strandspazieren", icon: "🏖️" },
        { time: "20:00", activity: "Abendessen am Hafen mit Hafenblick", icon: "🌃" },
      ],
    },
    {
      day: "Tag 2",
      title: "Meereshöhlen & Bootsromantik",
      icon: "⛵",
      color: "bg-sky-100",
      dayCost: "~70 €",
      transport: "Bootsausflug",
      meals: "Strandtaverne",
      stops: [
        { time: "10:00", activity: "Bootsausflug zu den Meereshöhlen", icon: "🚢", tip: "Private Tour für Paare am Hafen buchen – romantischer als Gruppenboot." },
        { time: "12:00", activity: "Schwimmen in der Phosphoreszenz-Höhle", icon: "✨" },
        { time: "14:00", activity: "Mittagessen an Bord oder am Strand", icon: "🐟" },
        { time: "16:00", activity: "Damlataş-Höhle besichtigen", icon: "🪨" },
        { time: "19:00", activity: "Sundowner auf der Hafenpromenade", icon: "🌅" },
      ],
    },
    {
      day: "Tag 3",
      title: "Sapadere Schlucht & Naturabenteuer",
      icon: "🏞️",
      color: "bg-emerald-100",
      dayCost: "~55 €",
      transport: "Taxi oder Ausflugstour",
      meals: "Restaurant an der Schlucht",
      stops: [
        { time: "09:30", activity: "Fahrt zur Sapadere-Schlucht (30 km)", icon: "🚗" },
        { time: "10:30", activity: "Wanderung durch die Schlucht", icon: "🥾" },
        { time: "12:30", activity: "Baden im natürlichen Bergbach-Pool", icon: "🏊" },
        { time: "14:00", activity: "Mittagessen mit Dim Çay-Forelle", icon: "🐟", tip: "Die Bergforelle aus dem Dim Çay ist ein regionales Delikatessen." },
        { time: "16:30", activity: "Rückfahrt mit Stop am Dim Stausee", icon: "💧" },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Cleopatra Beach & Wasserpark",
      icon: "🌊",
      color: "bg-cyan-100",
      dayCost: "~100 € (Fam. 4)",
      transport: "Dolmuş / Taxi",
      meals: "Strandrestaurant",
      stops: [
        { time: "09:30", activity: "Cleopatra Beach – Schwimmen & Sandspielen", icon: "🏖️", tip: "Früh kommen für gute Liegenplätze." },
        { time: "13:00", activity: "Mittagessen an der Strandpromenade", icon: "🍽️" },
        { time: "15:00", activity: "Water World Alanya Aquapark", icon: "🎢", tip: "Tagesticket für Kinder günstiger – online kaufen." },
        { time: "19:00", activity: "Eis und Bummel am Abend", icon: "🍦" },
      ],
    },
    {
      day: "Tag 2",
      title: "Bootsabenteuer & Meereshöhlen",
      icon: "⛵",
      color: "bg-yellow-100",
      dayCost: "~80 € (Fam. 4)",
      transport: "Bootsausflug",
      meals: "Hafen-Restaurant",
      stops: [
        { time: "10:00", activity: "Bootsausflug für Familien (3 Std.)", icon: "🚢", tip: "Kinder lieben die Sprünge ins Meer von Bord." },
        { time: "11:00", activity: "Piratenhöhle – magisches Lichtspiel", icon: "🏴‍☠️" },
        { time: "12:30", activity: "Schwimmstopp in der Bucht", icon: "🤿" },
        { time: "14:00", activity: "Rückfahrt und Mittagessen am Hafen", icon: "🍽️" },
        { time: "16:00", activity: "Roter Turm besichtigen", icon: "🔴" },
      ],
    },
    {
      day: "Tag 3",
      title: "Sapadere & Krokodilpark",
      icon: "🐊",
      color: "bg-pink-100",
      dayCost: "~90 € (Fam. 4)",
      transport: "Taxi",
      meals: "Schlucht-Restaurant",
      stops: [
        { time: "09:30", activity: "Alligator & Reptilienpark Alanya", icon: "🐊", tip: "Kinder können Krokodile und Schlangen anfassen – unter Aufsicht." },
        { time: "12:00", activity: "Sapadere Schlucht – Bergbach-Abenteuer", icon: "🏞️" },
        { time: "14:00", activity: "Mittagessen mit Forelle", icon: "🐟" },
        { time: "16:00", activity: "Strand zum Auskühlen", icon: "🏖️" },
        { time: "18:30", activity: "Abendessen mit Baklava-Dessert", icon: "🍬" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Burg & Altstadt erkunden",
      icon: "🏰",
      color: "bg-indigo-100",
      dayCost: "~30 €",
      transport: "Zu Fuß / Dolmuş",
      meals: "Lokales Kebap-Restaurant",
      stops: [
        { time: "08:30", activity: "Altstadt-Spaziergang am Morgen", icon: "🚶" },
        { time: "10:00", activity: "Roter Turm und Seldschukische Schiffswerft", icon: "🔴" },
        { time: "12:00", activity: "Alanya Burg zu Fuß hinaufsteigen", icon: "🥾", tip: "Die Fußroute durch die Altstadt zeigt das echte Alanya." },
        { time: "14:00", activity: "Mittagessen in der Altstadt", icon: "🍽️" },
        { time: "16:00", activity: "Damlataş-Höhle & Cleopatra Beach", icon: "🪨" },
        { time: "20:00", activity: "Abendessen im lokalen Balık-Lokal", icon: "🐟" },
      ],
    },
    {
      day: "Tag 2",
      title: "Dim Çay & Sapadere Natur",
      icon: "🌿",
      color: "bg-teal-100",
      dayCost: "~40 €",
      transport: "Dolmuş",
      meals: "Dim Çay Restaurant",
      stops: [
        { time: "09:30", activity: "Dim Çay Fluss – Morgenwanderung", icon: "🌊" },
        { time: "11:30", activity: "Sapadere-Schlucht Solo-Wanderung", icon: "🥾" },
        { time: "14:00", activity: "Frische Bergforelle am Fluss", icon: "🐟", tip: "Restaurants direkt am Wasser – Tische auf Holzplattformen über dem Bach." },
        { time: "16:30", activity: "Zurück an den Strand – abendliches Schwimmen", icon: "🏊" },
        { time: "20:00", activity: "Streetfood-Tour: Bazaar und Çay", icon: "☕" },
      ],
    },
    {
      day: "Tag 3",
      title: "Aspendos Tagesausflug",
      icon: "🏛️",
      color: "bg-orange-100",
      dayCost: "~50 €",
      transport: "Bus oder Taxi nach Aspendos",
      meals: "Lokale Taverne in Serik",
      stops: [
        { time: "08:30", activity: "Bus/Taxi nach Aspendos (60 km, 1 Std.)", icon: "🚌" },
        { time: "10:00", activity: "Aspendos Theater – bestes römisches Theater der Welt", icon: "🏛️", tip: "Früh kommen – Reisegruppen ab 10 Uhr." },
        { time: "12:00", activity: "Antike Stadt Side – Apollon-Tempel", icon: "🏺" },
        { time: "14:00", activity: "Mittagessen in Side", icon: "🍽️" },
        { time: "16:00", activity: "Side Beach – Schwimmen im Archäologie-Flair", icon: "🏖️" },
        { time: "19:00", activity: "Rückfahrt nach Alanya", icon: "🚌" },
      ],
    },
  ],
};

export default content;
