import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "☀️", text: "Perfekte Reisezeit mit 24 °C und blauem Himmel. Hochsaison – Hotels rechtzeitig buchen. Ideal für alle Outdoor-Aktivitäten." },
    { label: "Februar",   emoji: "🌸", text: "Dubai Shopping Festival läuft. Angenehme 26 °C, kaum Regen. Perfekt für Strandtage und Sightseeing." },
    { label: "März",      emoji: "🏖️", text: "Letzte Chance vor der Hitze. 28–30 °C – ideale Temperaturen für Wüstentouren und den Strand." },
    { label: "April",     emoji: "🌡️", text: "Temperaturen klettern auf 35 °C. Immer noch angenehm am Morgen. Reisepreise sinken leicht." },
    { label: "Mai",       emoji: "🔆", text: "38–42 °C machen Outdoor-Aktivitäten zur Herausforderung. Günstige Hotelpreise, Malls als Zuflucht." },
    { label: "Juni",      emoji: "🥵", text: "Extremhitze bis 44 °C. Nur für hartgesottene Städtereisende. Sehr günstige Preise, alles klimatisiert." },
    { label: "Juli",      emoji: "🌊", text: "Heißester Monat bis 46 °C. Poolurlaub und Indoor-Erlebnisse im Vordergrund. Touristisch sehr ruhig." },
    { label: "August",    emoji: "💦", text: "Schwül und heiß. Underwater-Zoo, Aquapark und Malls sind die Rettung. Günstigstes Reisemonat." },
    { label: "September", emoji: "🏙️", text: "Temperaturen sinken langsam auf 38 °C. Noch heiß, aber erstes Lebenszeichen im Freien." },
    { label: "Oktober",   emoji: "🌤️", text: "Angenehme 32 °C, Preise steigen wieder. Dubai-Saison beginnt offiziell. Ideale Zeit." },
    { label: "November",  emoji: "🎉", text: "Dubai Airshow und zahlreiche Events. 26 °C, ideale Temperaturen. Buchungen gut im Voraus." },
    { label: "Dezember",  emoji: "🎄", text: "Weihnachten und Silvester in Dubai sind atemberaubend. Höchste Preise, spektakuläres Feuerwerk am Burj Khalifa." },
  ],
  sights: [
    {
      title: "Burj Khalifa",
      desc: "Das höchste Gebäude der Welt (828 m) mit Aussichtsplattformen auf Ebene 124 und 148. Die Plattform At the Top SKY bietet einen 360°-Blick über Dubai, Wüste und Persischen Golf.",
      mapHref: "https://maps.google.com/?q=Burj+Khalifa+Dubai",
      address: "1 Sheikh Mohammed bin Rashid Blvd, Downtown Dubai",
      duration: "2–3 Std.",
      cost: "From 149 AED (~37 €) Ebene 124",
      tip: "Tickets online buchen – bis zu 50 % günstiger als vor Ort. Sonnenuntergang-Slot ist der populärste.",
    },
    {
      title: "Dubai Mall & Dubai Fountain",
      desc: "Die weltgrößte Einkaufsmall mit über 1.200 Geschäften, Aquarium, Eislaufbahn und dem Dubai Fountain davor – dem größten tanzenden Springbrunnen der Welt (274 m lang).",
      mapHref: "https://maps.google.com/?q=Dubai+Mall",
      address: "Financial Centre Road, Downtown Dubai",
      duration: "Halbtag",
      cost: "Kostenlos (Eintritt), Aquarium 130 AED",
      tip: "Dubai Fountain Show: kostenlos täglich 18 und 18:30 Uhr, dann stündlich bis 23 Uhr.",
    },
    {
      title: "Dubai Creek & Al-Fahidi-Viertel",
      desc: "Das historische Herz Dubais mit dem Goldsouk, dem Gewürzsouk und dem restaurierten Al-Fahidi-Viertel (Bastakiya) mit traditioneller Wind-Tower-Architektur. Abra-Boote überqueren den Creek für 1 AED.",
      mapHref: "https://maps.google.com/?q=Al+Fahidi+Dubai",
      address: "Al Fahidi, Bur Dubai",
      duration: "3–4 Std.",
      cost: "Kostenlos",
      tip: "Abra-Bootsfahrt für 1 AED – günstigste Touristenattraktion Dubais.",
    },
    {
      title: "Palm Jumeirah & Atlantis",
      desc: "Die künstliche Palminsel ist Dubais ikonischstes Symbol. Das Atlantis-Resort mit Aquapark und Unterwasser-Zoo, die Monorail und die Aussicht von der Palme sind Must-Sees.",
      mapHref: "https://maps.google.com/?q=Palm+Jumeirah+Dubai",
      address: "Palm Jumeirah",
      duration: "Halbtag",
      cost: "Monorail ca. 25 AED, Atlantis Aquaventure ab 350 AED",
      tip: "Der öffentliche Strand am Ende der Palm (Aquaventure-Außenbereich) ist kostenlos zugänglich.",
    },
    {
      title: "Desert Safari & Al Lahbab",
      desc: "Dünenfahrten (Dune Bashing) im 4×4 über die roten Sanddünen bei Al Lahbab (Red Dunes), gefolgt von Kamelreiten, Sandboarden und einem Barbecue-Dinner unter Sternenhimmel im Beduinencamp.",
      mapHref: "https://maps.google.com/?q=Al+Lahbab+Dubai",
      address: "Al Lahbab Road, Dubai",
      duration: "6–7 Std. (Nachmittag/Abend)",
      cost: "60–120 € pro Person inkl. Transfer",
      tip: "Halbprivate Touren buchen – weniger Leute im Jeep, besseres Erlebnis.",
    },
  ],
  history: [
    {
      year: "1833",
      title: "Gründung des Emirats Dubai",
      text: "Der Bani-Yas-Stamm unter Ubaid bin Said und Maktoum bin Butti Al Maktoum siedelte am Dubai Creek. Die Maktoum-Dynastie regiert Dubai bis heute und ist entscheidend für den modernen Aufstieg verantwortlich.",
    },
    {
      year: "1894",
      title: "Dubai als Handelsmetropole",
      text: "Herrscher Maktoum bin Hasher bot ausländischen Händlern Steuerfreiheit an. Persische und indische Kaufleute strömten in die Stadt. Der Dubai Creek entwickelte sich zum wichtigsten Handelsknotenpunkt am Golf.",
    },
    {
      year: "1966",
      title: "Entdeckung von Erdöl",
      text: "Offshore-Erdöl wurde im Fateh-Feld gefunden. Die Öleinnahmen ermöglichten den radikalen Umbau Dubais von einem Fischerdorf zur modernen Stadt. Herrscher Rashid investierte massiv in Infrastruktur.",
    },
    {
      year: "1971",
      title: "Gründung der VAE",
      text: "Dubai wurde neben Abu Dhabi und fünf weiteren Emiraten Teil der Vereinigten Arabischen Emirate. Die Föderalstruktur erlaubte Dubai weitgehende wirtschaftliche Autonomie.",
    },
    {
      year: "2004–2010",
      title: "Der Bauboom",
      text: "Innerhalb weniger Jahre entstanden Burj Al Arab, Palm Jumeirah, Burj Khalifa und die Dubai Marina. Dubai wurde zur Baustelle der Welt und zum Symbol schrankenloser Modernität.",
    },
    {
      year: "2020",
      title: "Expo 2020 & Zukunftsvision",
      text: "Dubai richtete die Weltausstellung Expo 2020 aus (verzögert auf 2021 durch COVID). Das Gelände wurde zu Dubai Südstadt. Vision 2040 setzt auf Technologie, Bildung und Nachhaltigkeit als Fundament.",
    },
  ],
  food: [
    {
      emoji: "🥙",
      name: "Shawarma",
      original: "شاورما",
      desc: "Das Streetfood Dubais schlechthin – dünne Fleischscheiben (Hähnchen oder Lamm) in dünnem Fladenbrot mit Tahini, Garlic-Sauce und Gurken. In jeder Seitenstraße für 5–10 AED.",
      price: "5–10 AED (~1,5–2,5 €)",
      tip: "Al Mallah in Satwa ist legendär – seit 40 Jahren das beste Shawarma der Stadt.",
    },
    {
      emoji: "🍚",
      name: "Machboos",
      original: "مجبوس",
      desc: "Das Nationalgericht der VAE: gewürzter Basmati-Reis mit Lamm, Huhn oder Meeresfrüchten, langsam gedämpft mit Safran, Limette und arabischen Gewürzen. Comfort Food der Emiratis.",
      price: "45–80 AED (~12–22 €)",
    },
    {
      emoji: "🥛",
      name: "Camel Milk & Camel Burger",
        desc: "Frische Kamelmilch (mild-süßlich) und Burgern aus Kamelsfleisch sind Dubai-typische Erfahrungen. Im Camel Museum in Nad Al Sheba oder in spezialisierten Restaurants.",
      price: "25–60 AED (~7–16 €)",
    },
    {
      emoji: "🍢",
      name: "Luqaimat",
      original: "لقيمات",
      desc: "Kleine knusprige Teigbällchen aus Mehl, Hefe und Safran, frittiert und mit Dattelsirup oder Honig übergossen. Das traditionelle Ramadan-Dessert, das ganzjährig beliebt ist.",
      price: "15–25 AED (~4–7 €)",
      tip: "Im Ramadan kostenlos von den Emiraten an Passanten verschenkt.",
    },
    {
      emoji: "☕",
      name: "Gahwa & Datteln",
      original: "قهوة عربية",
      desc: "Arabischer Kaffee mit Kardamom (Gahwa) und frischen Medjool-Datteln – die traditionelle emiratische Gastfreundschaft. Wird in jedem Souk und Hotel gratis angeboten.",
      price: "Kostenlos (als Gast)",
      tip: "Schale leicht schütteln, wenn man genug hat – das signalisiert dem Gastgeber, nicht nachzuschenken.",
    },
  ],
  phrases: [
    { original: "مرحبا (Marhaba)", pronunciation: "mar-ha-ba", translation: "Hallo / Willkommen" },
    { original: "السلام عليكم (As-salamu alaykum)", pronunciation: "as-sa-la-mu a-lai-kum", translation: "Friede sei mit euch (traditionelle Begrüßung)" },
    { original: "شكراً (Shukran)", pronunciation: "schu-kran", translation: "Danke" },
    { original: "من فضلك (Min fadlak)", pronunciation: "min fad-lak", translation: "Bitte (an Mann) / Min fadlik (an Frau)" },
    { original: "كم السعر؟ (Kam as-si'r?)", pronunciation: "kam as-sirr", translation: "Was kostet das?" },
    { original: "الحساب من فضلك (Al-hisab min fadlak)", pronunciation: "al-hi-sab min fad-lak", translation: "Die Rechnung, bitte" },
    { original: "يمين / يسار (Yamin / Yasar)", pronunciation: "ja-min / ja-sar", translation: "Rechts / Links" },
    { original: "أحتاج طبيباً (Ahtaj tabiban)", pronunciation: "ah-tadsch ta-bi-ban", translation: "Ich brauche einen Arzt" },
    { original: "في صحتك! (Fi sahetak!)", pronunciation: "fi sa-he-tak", translation: "Auf deine Gesundheit!" },
    { original: "مع السلامة (Ma'a as-salama)", pronunciation: "maa as-sa-la-ma", translation: "Auf Wiedersehen / Geh in Frieden" },
  ],
  insider: [
    {
      icon: "🕌",
      title: "Jumeirah Moschee – kostenlose Führung",
      text: "Die Jumeirah-Moschee bietet täglich Führungen für Nicht-Muslime an (25 AED inkl. Tee und Datteln). Die schönste Moschee Dubais und ein einzigartiger kultureller Einblick.",
    },
    {
      icon: "🚇",
      title: "Dubai Metro – günstigster Weg",
      text: "Die Dubai Metro fährt zum Burj Khalifa (Station Dubai Mall), zur Mall of the Emirates und zur Dubai Marina. Tagesticket 22 AED (~6 €) – sehr zu empfehlen statt Taxi.",
    },
    {
      icon: "🛍️",
      title: "Goldsouk – Preise verhandeln",
      text: "Im Goldsouk sind alle Preise verhandelbar. Faustregel: erst mal 40 % weniger bieten. Der angezeigte Preis ist nie der Endpreis – Geduld und freundliches Feilschen zahlen sich aus.",
    },
    {
      icon: "🏙️",
      title: "Alte Dubai Creek Seite – al-Fahidi",
      text: "Das Al-Fahidi-Viertel auf der Bur Dubai-Seite ist das authentischste Stück Dubai mit echten Wind-Tower-Häusern, dem Dubai Museum und günstigen indischen Restaurants.",
    },
    {
      icon: "🌙",
      title: "Dresscode & Verhaltensregeln",
      text: "In Malls und öffentlichen Bereichen gilt: schulterbedeckt und kniebedeckt. Am Strand ist Badebekleidung erlaubt. Alkohol nur in lizenzierten Hotels und Restaurants. Öffentliche Zuneigung vermeiden.",
    },
  ],
  beaches: [
    {
      name: "Jumeirah Beach (JBR)",
      emoji: "🏖️",
      desc: "Der lebhafteste öffentliche Strand Dubais mit der The Walk Promenade, zahlreichen Restaurants und Aktivitäten.",
      type: "Stadtnaher Sandstrand",
      tip: "La Mer Beach als Alternative – etwas ruhiger mit schicken Restaurants.",
    },
    {
      name: "Kite Beach",
      emoji: "🪁",
      desc: "Beliebter öffentlicher Strand beim Kitesurfen und Stand-up-Paddeln mit Blick auf den Burj Al Arab.",
      type: "Aktivstrand",
    },
    {
      name: "Palm Jumeirah Beach",
      emoji: "🌴",
      desc: "Exklusive Hotelstrände auf der Palminsel mit kristallklarem Wasser und Skyline-Blick auf Dubai.",
      type: "Privatstrand",
      tip: "Tagestickets für Atlantis-Aquaventure inkl. Strandnutzung ab 350 AED.",
    },
    {
      name: "Umm Suqeim Beach",
      emoji: "📸",
      desc: "Ruhiger öffentlicher Strand mit dem ikonischsten Blick auf den Burj Al Arab – ideal für Fotos.",
      type: "Ruhiger Öffentlicher Strand",
    },
    {
      name: "Sunset Beach",
      emoji: "🌅",
      desc: "Beliebtester Strand für Sonnenuntergänge mit atemberaubendem Blick auf den Burj Al Arab am Abendhimmel.",
      type: "Panoramastrand",
    },
  ],
  regions: [
    {
      name: "Downtown Dubai & Business Bay",
      emoji: "🏙️",
      desc: "Das moderne Herz der Stadt mit Burj Khalifa, Dubai Mall und dem Dubai Fountain.",
      highlights: ["Burj Khalifa", "Dubai Mall", "Dubai Fountain", "Business Bay Kanal"],
    },
    {
      name: "Dubai Marina & JBR",
      emoji: "⛵",
      desc: "Künstlicher Wasserkanal mit Luxusjachten, Hochhäusern und dem beliebten JBR-Strand.",
      highlights: ["JBR Strand", "Dubai Marina Walk", "Palm Jumeirah"],
    },
    {
      name: "Bur Dubai & Deira (Old Dubai)",
      emoji: "🕌",
      desc: "Das historische Dubai mit den Souks, dem Dubai Creek und dem Al-Fahidi-Kulturviertel.",
      highlights: ["Gold Souk", "Gewürzsouk", "Dubai Museum", "Abra-Bootsfahrten"],
    },
    {
      name: "Al Quoz & Jumeirah",
      emoji: "🎨",
      desc: "Modernes Galerieviertel, Jumeirah-Moschee und exklusive Strandhotels.",
      highlights: ["Alserkal Avenue Galerien", "Jumeirah Moschee", "Kite Beach"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "60–120 €", mid: "150–350 €", luxury: "400–2000 €+" },
    { label: "Essen (pro Tag)", budget: "15–30 € (Shawarma & Souk)", mid: "50–100 €", luxury: "150–500 €+" },
    { label: "Transport (pro Tag)", budget: "8–15 € (Metro)", mid: "30–60 € (Taxi)", luxury: "100–300 € (Privatchauffeur)" },
    { label: "Aktivitäten (pro Tag)", budget: "10–30 €", mid: "60–150 €", luxury: "300–1000 €+" },
    { label: "Tagesbudget gesamt", budget: "100–200 €", mid: "280–660 €", luxury: "1000–3000 €+" },
  ],
  emergency: {
    police: "999",
    ambulance: "998",
    fire: "997",
    embassy: "+971 4 349 8888 (Deutsche Botschaft Abu Dhabi) / Konsulat Dubai: +971 4 349 8888",
    hospital: "Rashid Hospital Dubai: +971 4 219 2000",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Burj Khalifa & Dubai Fountain bei Nacht",
      icon: "🌃",
      color: "bg-rose-100",
      dayCost: "~200 €",
      transport: "Metro bis Dubai Mall",
      meals: "Zuma Restaurant Dubai Mall",
      stops: [
        { time: "10:00", activity: "Dubai Mall – Aquarium und Unterwasserzoo", icon: "🐠", tip: "Gemeinsamer Tunnel-Spaziergang durch den Shark Tank." },
        { time: "13:00", activity: "Mittagessen in der Dubai Mall", icon: "🍽️" },
        { time: "15:00", activity: "Bummel durch die Indoor-Souk-Bereiche", icon: "🛍️" },
        { time: "17:30", activity: "Burj Khalifa At the Top – Sunset Slot", icon: "🌇", tip: "Sunset-Tickets online kaufen – das Erlebnis bei Dämmerung ist unvergesslich." },
        { time: "20:00", activity: "Dubai Fountain Show & romantisches Abendessen", icon: "💦" },
      ],
    },
    {
      day: "Tag 2",
      title: "Wüsten-Romantik & Sterne-BBQ",
      icon: "🌙",
      color: "bg-amber-100",
      dayCost: "~180 €",
      transport: "Privater Transfer (inklusive in Tour)",
      meals: "Beduinen-Camp Dinner",
      stops: [
        { time: "10:00", activity: "Jumeirah Moschee Führung", icon: "🕌" },
        { time: "12:30", activity: "Mittagessen im historischen Al-Fahidi-Viertel", icon: "🍛" },
        { time: "15:30", activity: "Wüstentour Abholung – Dune Bashing", icon: "🚙", tip: "Privattour für Paare buchen – kleinere Gruppe, romantischer." },
        { time: "18:00", activity: "Sonnenuntergang auf der Düne", icon: "🌅" },
        { time: "20:00", activity: "Sterne-BBQ im Beduinencamp", icon: "🌟" },
      ],
    },
    {
      day: "Tag 3",
      title: "Palm Jumeirah & Dhow-Bootstour",
      icon: "⛵",
      color: "bg-sky-100",
      dayCost: "~160 €",
      transport: "Monorail Palm + Taxi",
      meals: "Nobu at Atlantis",
      stops: [
        { time: "10:00", activity: "Palm Monorail – Blick auf die Palminsel", icon: "🚝" },
        { time: "11:00", activity: "Atlantis The Palm – Aquaventure", icon: "🌊" },
        { time: "14:00", activity: "Mittagessen am Palmenstrand", icon: "🍹" },
        { time: "17:30", activity: "Romantische Dhow-Kreuzfahrt auf dem Dubai Creek", icon: "⛵", tip: "Abendlicher Dinner-Dhow mit Blick auf die Skyline – ab 80 AED/Person." },
        { time: "21:00", activity: "Cocktails mit Skyline-Blick im 40 Kong", icon: "🍸" },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Dubai Mall & Aquarium",
      icon: "🐠",
      color: "bg-cyan-100",
      dayCost: "~250 € (Fam. 4)",
      transport: "Metro",
      meals: "Dubai Mall Food Court",
      stops: [
        { time: "10:00", activity: "Dubai Aquarium & Unterwasserzoo", icon: "🦈", tip: "Tunnel-Spaziergang mitten durch das Aquarium – Kinder sind begeistert." },
        { time: "13:00", activity: "Mittagessen im riesigen Food Court", icon: "🍔" },
        { time: "14:30", activity: "Dubai Ice Rink – Schlittschuhlaufen", icon: "⛸️" },
        { time: "17:00", activity: "Dubai Fountain Show kostenlos anschauen", icon: "💦" },
        { time: "18:30", activity: "Kidzania Dubai – Rollenspielpark für Kinder", icon: "👮", tip: "Kidzania am Abend ist ruhiger – Tageskarten online kaufen." },
      ],
    },
    {
      day: "Tag 2",
      title: "Atlantis Aquaventure Wasserpark",
      icon: "🎢",
      color: "bg-teal-100",
      dayCost: "~350 € (Fam. 4)",
      transport: "Taxi / Transfer",
      meals: "Aquaventure Restaurant",
      stops: [
        { time: "09:30", activity: "Atlantis Aquaventure – Ganztagesticket", icon: "🎢", tip: "Poseidon's Revenge Rutsche für ältere Kinder ist der Favorit." },
        { time: "13:00", activity: "Mittagessen im Park", icon: "🍟" },
        { time: "15:00", activity: "Private Beach & Wellenbad", icon: "🏖️" },
        { time: "17:00", activity: "Atlantis Aquarium & Meerestiere", icon: "🐬" },
        { time: "19:00", activity: "Rückfahrt mit Panoramablick auf die Skyline", icon: "🌆" },
      ],
    },
    {
      day: "Tag 3",
      title: "Wüstensafari mit Kamelen",
      icon: "🐪",
      color: "bg-yellow-100",
      dayCost: "~280 € (Fam. 4)",
      transport: "Privater 4x4-Transfer",
      meals: "Wüstencamp BBQ",
      stops: [
        { time: "15:00", activity: "Abholung vom Hotel – 4×4 Dune Bashing", icon: "🚙", tip: "Kinder ab 4 Jahren. Kleinere Kinder in ruhigerem Auto möglich." },
        { time: "17:00", activity: "Kamelreiten und Sandboarden", icon: "🐫" },
        { time: "18:30", activity: "Beduinencamp – Henna und Falknerei", icon: "🦅" },
        { time: "19:30", activity: "BBQ-Dinner unter Sternenhimmel", icon: "🌟" },
        { time: "21:30", activity: "Rückfahrt nach Dubai", icon: "🌃" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Old Dubai & Souk-Erkundung",
      icon: "🕌",
      color: "bg-indigo-100",
      dayCost: "~50 €",
      transport: "Metro + Abra",
      meals: "Al Ustad Special Kabab, Deira",
      stops: [
        { time: "09:00", activity: "Al-Fahidi-Historisches-Viertel erkunden", icon: "🏛️", tip: "XVA Art Hotel mit kostenlosem Galerie-Eintritt." },
        { time: "10:30", activity: "Dubai Museum – Geschichte des Emirats", icon: "🏺" },
        { time: "12:00", activity: "Abra-Bootsfahrt über den Creek (1 AED)", icon: "⛵" },
        { time: "13:00", activity: "Gewürzsouk & Goldsouk durchstöbern", icon: "✨", tip: "Preise immer verhandeln – 30–40 % Rabatt möglich." },
        { time: "19:00", activity: "Abendessen im authentischen Deira-Restaurant", icon: "🍛" },
      ],
    },
    {
      day: "Tag 2",
      title: "Skyline-Tag & Burj Khalifa",
      icon: "🏙️",
      color: "bg-blue-100",
      dayCost: "~80 €",
      transport: "Metro",
      meals: "Streetfood Dubai Mall",
      stops: [
        { time: "10:00", activity: "Dubai Frame – Skyline von alt und neu", icon: "🖼️", tip: "Günstigste Aussichtsplattform (50 AED) mit einzigartigem Perspektivvergleich." },
        { time: "12:30", activity: "Downtown Dubai – Flanieren", icon: "🚶" },
        { time: "14:00", activity: "Dubai Mall – Mittagessen im Food Court", icon: "🍜" },
        { time: "17:30", activity: "Burj Khalifa At the Top Sunset", icon: "🌇" },
        { time: "20:00", activity: "Dubai Fountain Show", icon: "💦" },
      ],
    },
    {
      day: "Tag 3",
      title: "Wüsten-Solo-Abenteuer",
      icon: "🏜️",
      color: "bg-orange-100",
      dayCost: "~80 €",
      transport: "Shared Desert Tour",
      meals: "Wüstencamp",
      stops: [
        { time: "08:00", activity: "Selbstfahrer: Hatta Mountain Drive", icon: "🚗", tip: "Hatta Wadi Hub mit Kayaking, Mountainbiking und Zipline (40–80 AED je Activity)." },
        { time: "11:00", activity: "Hatta Dam & Wadi Pool schwimmen", icon: "🏊" },
        { time: "14:30", activity: "Heritage Village Hatta", icon: "🏡" },
        { time: "16:00", activity: "Gruppendesert-Safari (shared tour)", icon: "🌅" },
        { time: "20:00", activity: "Camp-BBQ und Rückfahrt", icon: "🔥" },
      ],
    },
  ],
};

export default content;
