import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "☀️", text: "Gran Canaria im Januar: 20–22 °C, kein Regen, Frühlingsgefühl mitten im Winter. Europäer flüchten hierher vor der Kälte – idealer Wintersonnenurlaub." },
    { label: "Februar",   emoji: "🎉", text: "Las Palmas feiert den zweitgrößten Karneval der Welt nach Rio. 20 °C, Badezeit in Maspalomas gut möglich. Frühzeitig buchen." },
    { label: "März",      emoji: "🌸", text: "Frühling auf der Insel mit blühendem Innenland. Beste Wanderbedingungen im Roque-Nublo-Massiv bei 23 °C." },
    { label: "April",     emoji: "🌿", text: "Vor-Hochsaison: angenehme 23 °C, erste Strandurlauber. Wanderungen in der Caldera de Tejeda bei optimalen Temperaturen." },
    { label: "Mai",       emoji: "🏖️", text: "Badesaison in Maspalomas beginnt. 22 °C Wassertemperatur. Preisgünstige Hochsaisonvorstufe." },
    { label: "Juni",      emoji: "🌬️", text: "Passatwinde sorgen für angenehme Temperaturen um 26 °C. Wassersportler lieben die Winde – beste Kitesurfbedingungen." },
    { label: "Juli",      emoji: "🔆", text: "Hochsaison: Bis 28 °C, Maspalomas-Dünen glühen gold. Alle Resorts ausgebucht – Monate im Voraus reservieren." },
    { label: "August",    emoji: "🌡️", text: "Wärmster Monat mit 29 °C. Gelegentlich Sahara-Calima (Wüstenstaub). Strände voll, Innenland herrlich." },
    { label: "September", emoji: "🌊", text: "Noch warm bei 27 °C, Touristenansturm ebbt ab. Wasser wärmer als im Sommer (24 °C). Ideal." },
    { label: "Oktober",   emoji: "🍂", text: "Angenehme 24 °C, erste Herbststimmung im Bergland. Wanderungen im Landesinneren besonders schön." },
    { label: "November",  emoji: "🌤️", text: "Gleichmäßige 22 °C, weniger Betrieb. Weihnachtstourismus beginnt Ende des Monats." },
    { label: "Dezember",  emoji: "🎄", text: "Weihnachten unter Palmen! Maspalomas ist europäisches Winterziel Nummer 1. Über 23 °C garantiert." },
  ],
  sights: [
    {
      title: "Maspalomas Dünen & Naturschutzgebiet",
      desc: "Einzigartiges Wüstenparadies auf Kanarenniveau: 4 km² Sanddünen direkt am Atlantik. Ein UNESCO-Biosphärenreservat, das Sahara-Feeling in der Nähe Europas bietet. Dahinter die berühmte Oase mit Lagune.",
      mapHref: "https://maps.google.com/?q=Maspalomas+Dunas",
      address: "Playa de Maspalomas, Gran Canaria",
      duration: "Halbtag",
      cost: "Kostenlos",
      tip: "Früh morgens oder abends: Dünen in rosafarbenem Licht mit weniger Menschen. Kamelreiten am Rande möglich.",
    },
    {
      title: "Roque Nublo",
      desc: "Der 80 m hohe Basaltfelsen auf 1813 m Höhe ist das Wahrzeichen des Inselinneren. Von weitem sichtbar, gilt er als heiliger Ort der Ureinwohner (Guanchen). Der Wanderweg hinauf bietet einen 360°-Blick über die gesamte Insel.",
      mapHref: "https://maps.google.com/?q=Roque+Nublo+Gran+Canaria",
      address: "Tejeda, Gran Canaria",
      duration: "2–3 Std. (inkl. Wanderung)",
      cost: "Kostenlos",
      tip: "Parkplatz La Goleta als Ausgangspunkt. Klarer Tag für den Blick auf den Teide auf Teneriffa.",
    },
    {
      title: "Vegueta – Historisches Kolonialviertel",
      desc: "Das älteste Viertel von Las Palmas mit dem Geburtshaus von Christoph Kolumbus (Casa de Colón), der Kathedrale Santa Ana und dem Marktplatz. Spanisches Kolonialflair vom Feinsten.",
      mapHref: "https://maps.google.com/?q=Vegueta+Las+Palmas",
      address: "Vegueta, Las Palmas de Gran Canaria",
      duration: "2–3 Std.",
      cost: "Kostenlos (Museen ab 4 €)",
      tip: "Sonntagsmorgens wird ein Antiquitäten- und Kunstmarkt vor der Kathedrale abgehalten.",
    },
    {
      title: "Caldera de Tejeda",
      desc: "Ein gigantischer erloschener Vulkankrater im Herzen der Insel mit dramatischen Felsformationen, kleinen Dörfern (Tejeda, Artenara) und weißen Mandelblüten im Februar. Die Landschaft erinnert an den Mond.",
      mapHref: "https://maps.google.com/?q=Caldera+de+Tejeda+Gran+Canaria",
      address: "Tejeda, Gran Canaria",
      duration: "Halbtag",
      cost: "Kostenlos",
      tip: "Mietwagen empfohlen. Das Dorf Tejeda mit Mandelgebäck (Mazapán) ist das Beste der Insel.",
    },
    {
      title: "Palmitos Park",
      desc: "Botanischer Zoo- und Vogelpark inmitten einer Palmenschlucht mit 230 Vogelarten, Schmetterlingshaus, Delfinarium und tropischen Pflanzen. Einer der besten Tierparks der Kanarischen Inseln.",
      mapHref: "https://maps.google.com/?q=Palmitos+Park+Gran+Canaria",
      address: "Barranco de los Palmitos, Maspalomas",
      duration: "Halbtag",
      cost: "Ab 28 €",
      tip: "Online-Ticket günstiger. Nachmittagsshows besonders sehenswert.",
    },
  ],
  history: [
    {
      year: "bis 1478",
      title: "Die Guanchen – Ureinwohner Gran Canarias",
      text: "Die Guanchen, Nachfahren der berberischen Cro-Magnon-Bevölkerung Nordafrikas, besiedelten Gran Canaria seit mindestens 2000 Jahren. Sie lebten in Höhlen und Steinhäusern, verehrten Roque Nublo als heiligen Ort und hinterließen eindrucksvolle Höhlenmalereien.",
    },
    {
      year: "1478–1483",
      title: "Spanische Conquista",
      text: "Juan Rejón begann die Eroberung im Auftrag der Könige Isabella und Ferdinand. Die Guanchen leisteten erbitterten Widerstand unter Führung von Doramas und Tenesor Semidan. Erst 1483 kapitulierte der letzte Widerstand.",
    },
    {
      year: "1492",
      title: "Kolumbus stoppt auf Gran Canaria",
      text: "Christoph Kolumbus legte auf seiner ersten Amerika-Reise in Las Palmas an, um Schäden zu reparieren. Das Casa de Colón erinnert heute daran. Die Kanarischen Inseln wurden zum wichtigsten Umschlagplatz zwischen Europa und der Neuen Welt.",
    },
    {
      year: "17.–18. Jh.",
      title: "Piratengefahr & Kanonentürme",
      text: "Englische und niederländische Piraten attackierten die Insel regelmäßig. Schutzforts wurden gebaut, darunter das Castillo de la Luz in Las Palmas. Sir Francis Drake versuchte 1595, Las Palmas zu plündern, wurde aber zurückgeschlagen.",
    },
    {
      year: "1936",
      title: "Franco erhebt sich auf Gran Canaria",
      text: "General Francisco Franco koordinierte von Las Palmas aus den Militärputsch gegen die Spanische Republik. Die Kanarischen Inseln blieben während des Bürgerkriegs franquistische Hochburg.",
    },
    {
      year: "1960er",
      title: "Beginn des Massentourismus",
      text: "Mit dem Bau der ersten großen Hotels in Maspalomas und Playa del Inglés begann der Tourismusboom. Die Insel wandelte sich von einer Landwirtschaftsgesellschaft zur dienstleistungsorientierten Tourismuswirtschaft.",
    },
  ],
  food: [
    {
      emoji: "🥣",
      name: "Papas Arrugadas con Mojo",
      original: "Papas Arrugadas con Mojo",
      desc: "Das kanarische Nationalgericht: kleine Kartoffeln in stark gesalzenem Wasser gekocht, bis die Schale runzelig wird. Serviert mit rotem (scharf) oder grünem (Koriander/Knoblauch) Mojo-Dip. Einfach, unverzichtbar.",
      price: "5–9 €",
      tip: "Überall erhältlich – aber in rustikalen Mesones im Inselinneren am authentischsten.",
    },
    {
      emoji: "🐟",
      name: "Vieja a la Canaria",
      original: "Vieja a la Canaria",
      desc: "Gebratener Papageienfisch – ein Atlantikfisch mit festem weißen Fleisch – mit Mojo, Papas und einem Glas Vino de Mesa. Das typischste Fischgericht der Insel.",
      price: "12–20 €",
    },
    {
      emoji: "🌽",
      name: "Gofio",
      original: "Gofio Canario",
      desc: "Geröstetes Mehl aus Weizen, Mais oder Gerste – das Grundnahrungsmittel der Guanchen seit Jahrtausenden. Heute in Eiscreme, Brot, Suppen und Desserts verwendet.",
      price: "3–8 €",
    },
    {
      emoji: "🫒",
      name: "Queso de Flor",
      original: "Queso de Flor de Guía",
      desc: "Einzigartiger Käse aus Santa María de Guía – hergestellt mit Blüten der Artischockendistel als Lab. Geschützte Ursprungsbezeichnung, cremig mit blumigem Aroma.",
      price: "6–12 €",
      tip: "Markt von Santa María de Guía am Sonntag für frischen Käse direkt vom Produzenten.",
    },
    {
      emoji: "🍬",
      name: "Bienmesabe",
      original: "Bienmesabe",
      desc: "Süße Mandelcreme aus gemahlenen Mandeln, Honig, Eigelb und Zimt. Das typischste kanarische Dessert – wird pur gelöffelt oder über Eis serviert.",
      price: "4–7 €",
    },
  ],
  phrases: [
    { original: "¡Hola! / Buenos días", pronunciation: "o-la / bwe-nos di-as", translation: "Hallo! / Guten Morgen!" },
    { original: "Por favor", pronunciation: "por fa-bor", translation: "Bitte" },
    { original: "Gracias", pronunciation: "gra-θjas", translation: "Danke" },
    { original: "¿Cuánto cuesta?", pronunciation: "kwan-to kwes-ta", translation: "Was kostet das?" },
    { original: "La cuenta, por favor", pronunciation: "la kwen-ta por fa-bor", translation: "Die Rechnung, bitte" },
    { original: "¿Dónde está la playa?", pronunciation: "don-de es-ta la pla-ja", translation: "Wo ist der Strand?" },
    { original: "Una cerveza, por favor", pronunciation: "u-na θer-be-θa por fa-bor", translation: "Ein Bier, bitte" },
    { original: "¡Salud!", pronunciation: "sa-lu", translation: "Prost!" },
    { original: "Necesito ayuda", pronunciation: "ne-θe-si-to a-ju-da", translation: "Ich brauche Hilfe" },
    { original: "¡Hasta luego!", pronunciation: "as-ta lwe-go", translation: "Auf Wiedersehen!" },
  ],
  insider: [
    {
      icon: "🌅",
      title: "Dünen bei Sonnenaufgang",
      text: "Die Maspalomas-Dünen sind um 7 Uhr morgens nahezu menschenleer und leuchten in warmem Rosa. Der schönste Moment, um die Stille des Wüstengefühls zu erleben – kostenlos und unvergesslich.",
    },
    {
      icon: "🚌",
      title: "Global Bus statt Taxi",
      text: "Die Buslinie 30 verbindet Maspalomas, Playa del Inglés und das Stadtzentrum für 1,85 € statt 20–30 € Taxi. Für Tagesausflüge: Bus 18 bis Tejeda oder Las Palmas.",
    },
    {
      icon: "🧀",
      title: "Queso-Markt in Guía",
      text: "Santa María de Guía ist die Käsehauptstadt der Insel. Der Sonntags-Markt bietet frischen Queso de Flor direkt vom Produzenten für ein Drittel des Touristenpreises.",
    },
    {
      icon: "🌊",
      title: "Pozo Izquierdo – Weltklasse-Windsurfen",
      text: "Pozo Izquierdo ist als Austragungsort der Windsurf-Weltmeisterschaft bekannt. Auch Nicht-Surfer können zuschauen – spektakuläres kostenloses Schauspiel bei starkem Wind im Sommer.",
    },
    {
      icon: "🥘",
      title: "Guachinches im Innenland",
      text: "Guachinches sind einfache Bauernrestaurants im Innenland, die kanarische Hausmannskost für 8–12 € servieren. Keine Touristenspeisekarte – echte Papas, Mojo und lokalen Wein.",
    },
  ],
  beaches: [
    {
      name: "Playa de Maspalomas",
      emoji: "🏜️",
      desc: "Wildester und ursprünglichster Strand der Insel, direkt neben den Dünen und der Lagune. FKK-Bereich am Ende des Strandes.",
      type: "Naturstrand / FKK",
      tip: "Hier keine Liegenverleih – eigene Matte mitbringen.",
    },
    {
      name: "Playa del Inglés",
      emoji: "🏖️",
      desc: "Kilometerbreiter Sandstrand, der nahtlos in die Dünen übergeht. Beliebtester und belebtester Strand der Insel mit allem Komfort.",
      type: "Touristischer Sandstrand",
    },
    {
      name: "Playa de Amadores",
      emoji: "🌊",
      desc: "Künstlicher Sandstrand (importierter Sand aus der Sahara) in einer geschützten Bucht – ruhiges Wasser, ideal für Familien.",
      type: "Geschützte Familienbucht",
    },
    {
      name: "Playa de Las Canteras (Las Palmas)",
      emoji: "🏙️",
      desc: "Einer der besten Stadtstrände Europas: 3,5 km weißer Sand mitten in der Hauptstadt mit natürlichem Riff als Wellenbrecher.",
      type: "Stadtstrand",
      tip: "Zum Surfen an der offenen Seite des Riffs – zum Schwimmen in der geschützten Lagune.",
    },
    {
      name: "Playa de Mogán",
      emoji: "⛵",
      desc: "Pittoresker kleiner Strand im 'kleinen Venedig Gran Canarias' – Puerto de Mogán mit Blumenbrücken und bunten Booten.",
      type: "Malerischer Hafen-Strand",
    },
  ],
  regions: [
    {
      name: "Maspalomas & Playa del Inglés",
      emoji: "🏖️",
      desc: "Das touristische Herz der Insel im Süden mit Dünen, langen Stränden, Resorts und Nachtleben.",
      highlights: ["Maspalomas Dünen", "Oase & Lagune", "Waterworld Maspalomas"],
    },
    {
      name: "Las Palmas de Gran Canaria",
      emoji: "🏙️",
      desc: "Die lebendige Hauptstadt mit historischem Kolonialviertel, bestem Stadtstrand Europas und pulsierendem Stadtleben.",
      highlights: ["Vegueta Altstadt", "Las Canteras Strand", "Casa de Colón"],
    },
    {
      name: "Innenland – Tejeda & Roque Nublo",
      emoji: "⛰️",
      desc: "Das grüne Herz der Insel mit dramatischen Vulkanlandschaften, Dörfern und dem heiligen Felsen der Guanchen.",
      highlights: ["Roque Nublo", "Caldera de Tejeda", "Dorf Artenara"],
    },
    {
      name: "Westküste – Mogán & Arguineguín",
      emoji: "⛵",
      desc: "Ruhige Fischerorte und malerische Häfen abseits des Massentourismus mit echtem kanarischen Flair.",
      highlights: ["Puerto de Mogán", "Arguineguín Fischmarkt", "Playa de Tasarte"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "30–60 €", mid: "70–150 €", luxury: "180–400 €+" },
    { label: "Essen (pro Tag)", budget: "12–20 €", mid: "25–50 €", luxury: "70–150 €+" },
    { label: "Transport (pro Tag)", budget: "4–8 € (Bus)", mid: "25–45 € (Mietauto)", luxury: "60–120 € (Taxi)" },
    { label: "Aktivitäten (pro Tag)", budget: "5–15 €", mid: "20–50 €", luxury: "80–200 €+" },
    { label: "Tagesbudget gesamt", budget: "55–105 €", mid: "140–295 €", luxury: "390–870 €+" },
  ],
  emergency: {
    police: "112",
    ambulance: "112",
    fire: "112",
    embassy: "+34 928 491 461 (Deutsches Konsulat Las Palmas)",
    hospital: "Hospital Universitario de Gran Canaria Doctor Negrín: +34 928 450 000",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Dünen & Romantischer Sonnenuntergang",
      icon: "🏜️",
      color: "bg-rose-100",
      dayCost: "~70 €",
      transport: "Zu Fuß / Taxi",
      meals: "Restaurante El Capricho, Maspalomas",
      stops: [
        { time: "08:00", activity: "Maspalomas Dünen bei Sonnenaufgang", icon: "🌅", tip: "Zu Fuß von Maspalomas Leuchtturm – romantisch und menschenleer." },
        { time: "10:00", activity: "Oase & Lagune erkunden", icon: "🦩" },
        { time: "13:00", activity: "Mittagessen in Maspalomas", icon: "🍽️" },
        { time: "15:00", activity: "Playa de Maspalomas – Schwimmen & Strandlesen", icon: "🏖️" },
        { time: "19:30", activity: "Sundowner & romantisches Abendessen", icon: "🌅" },
      ],
    },
    {
      day: "Tag 2",
      title: "Inselinneres & Roque Nublo",
      icon: "⛰️",
      color: "bg-amber-100",
      dayCost: "~60 €",
      transport: "Mietauto",
      meals: "Mesón la Silla, Tejeda",
      stops: [
        { time: "09:00", activity: "Fahrt durchs Gebirge nach Tejeda", icon: "🚗", tip: "Kurvenreiche Panoramastraße GC-60 – atemberaubende Aussichten." },
        { time: "10:30", activity: "Wanderung zum Roque Nublo (2 Std. Hin/Rück)", icon: "🥾" },
        { time: "13:30", activity: "Mittagessen in Tejeda – Bienmesabe & Mazapán", icon: "🍯" },
        { time: "15:30", activity: "Artenara – höchstes Dorf der Insel", icon: "🏘️" },
        { time: "17:30", activity: "Sonnenuntergang über der Caldera", icon: "🌄" },
      ],
    },
    {
      day: "Tag 3",
      title: "Puerto de Mogán – Klein-Venedig",
      icon: "⛵",
      color: "bg-sky-100",
      dayCost: "~65 €",
      transport: "Bus 32 oder Mietauto",
      meals: "Taverne Puerto de Mogán",
      stops: [
        { time: "10:00", activity: "Puerto de Mogán Bummel & Blumenbrücken", icon: "🌺" },
        { time: "11:30", activity: "Bootsausflug entlang der Westküste", icon: "⛵", tip: "Delphinbeobachtung auf dem offenen Atlantik – fast garantiert." },
        { time: "14:00", activity: "Mittagessen mit frischem Fisch im Hafen", icon: "🐟" },
        { time: "16:00", activity: "Playa de Mogán – Schwimmen", icon: "🏖️" },
        { time: "19:00", activity: "Sonnenuntergang mit Wein im Hafencafé", icon: "🍷" },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Waterworld & Dünen",
      icon: "🎢",
      color: "bg-cyan-100",
      dayCost: "~150 € (Fam. 4)",
      transport: "Bus / Taxi",
      meals: "Wasserpark + Strandtaverne",
      stops: [
        { time: "10:00", activity: "Aqualand Maspalomas Wasserpark", icon: "🎢", tip: "Online-Tickets günstiger kaufen." },
        { time: "13:00", activity: "Mittagessen im Wasserpark", icon: "🍔" },
        { time: "15:00", activity: "Maspalomas Dünen – Sandschlittenfahren", icon: "🏜️", tip: "Sandschlitten mieten – Kinder lieben die Dünenabfahrten." },
        { time: "18:00", activity: "Abendessen an der Strandpromenade", icon: "🍝" },
      ],
    },
    {
      day: "Tag 2",
      title: "Palmitos Park & Strand",
      icon: "🦜",
      color: "bg-yellow-100",
      dayCost: "~120 € (Fam. 4)",
      transport: "Taxi / Bus",
      meals: "Palmitos Park + Strandrestaurant",
      stops: [
        { time: "10:00", activity: "Palmitos Park – Delfine, Vögel, Schmetterlinge", icon: "🦜", tip: "Delfinshow um 12 Uhr und 16 Uhr – vorher im Programm nachschauen." },
        { time: "13:30", activity: "Picknick oder Restaurant im Park", icon: "🥪" },
        { time: "15:30", activity: "Playa de Amadores – ruhige Familienbucht", icon: "🌊" },
        { time: "18:30", activity: "Eis-Stopp und Bummel", icon: "🍦" },
      ],
    },
    {
      day: "Tag 3",
      title: "Kamelreiten & Strandparadies",
      icon: "🐪",
      color: "bg-pink-100",
      dayCost: "~90 € (Fam. 4)",
      transport: "Bus",
      meals: "Strandtaverne Playa del Inglés",
      stops: [
        { time: "09:30", activity: "Kamelreiten an den Dünen (Camello Safari)", icon: "🐪", tip: "15-minütige Kamelrunde durch die Dünen – Kinder-Favorit." },
        { time: "11:00", activity: "Playa del Inglés – Sandburgen & Schwimmen", icon: "🏖️" },
        { time: "13:30", activity: "Mittagessen an der Strandpromenade", icon: "🍽️" },
        { time: "15:30", activity: "Aqua Sur Wasserrutschen", icon: "🌊" },
        { time: "18:00", activity: "Mini-Golf an der Promenade", icon: "⛳" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Las Palmas City & Stadtstrand",
      icon: "🏙️",
      color: "bg-indigo-100",
      dayCost: "~40 €",
      transport: "Bus 30 nach Las Palmas",
      meals: "Mercado del Puerto, Las Palmas",
      stops: [
        { time: "09:00", activity: "Vegueta Altstadt – Kathedrale & Kolumbus-Haus", icon: "⛪" },
        { time: "11:00", activity: "Mercado del Puerto – günstigste Tapas der Stadt", icon: "🥘", tip: "Frische Meeresfrüchte-Tapas ab 2,50 €." },
        { time: "13:30", activity: "Las Canteras Strand – Schwimmen und Sonnenbaden", icon: "🏖️" },
        { time: "16:00", activity: "Paseo de Las Canteras – Strandpromenade", icon: "🚶" },
        { time: "20:00", activity: "Tapas-Abend in der Altstadt", icon: "🍻" },
      ],
    },
    {
      day: "Tag 2",
      title: "Roque Nublo Solo-Wanderung",
      icon: "⛰️",
      color: "bg-green-100",
      dayCost: "~35 €",
      transport: "Bus 18 nach Tejeda (2 Std.)",
      meals: "Rucksackverpflegung",
      stops: [
        { time: "07:30", activity: "Bus ab Las Palmas / Maspalomas nach Tejeda", icon: "🚌" },
        { time: "10:00", activity: "Wanderung Roque Nublo (ab Parkplatz La Goleta)", icon: "🥾", tip: "Früh genug – Mittags kann es windig und kalt werden." },
        { time: "13:00", activity: "Tejeda – Mandelgebäck & Mittagessen", icon: "🍯" },
        { time: "15:00", activity: "Artenara – Höhlenwohnungen besichtigen", icon: "🪨" },
        { time: "17:00", activity: "Bus zurück", icon: "🚌" },
      ],
    },
    {
      day: "Tag 3",
      title: "Westkuste & Kitesurfen",
      icon: "🏄",
      color: "bg-teal-100",
      dayCost: "~55 €",
      transport: "Mietauto oder Bus",
      meals: "Lokale Taverne",
      stops: [
        { time: "09:30", activity: "Playa de Güi-Güi (nur zu Fuß erreichbar)", icon: "🏖️", tip: "2 Std. Wanderung – einer der abgelegensten Strände der Insel." },
        { time: "13:00", activity: "Mittagessen in Arguineguín – Fischmarkt", icon: "🐟" },
        { time: "15:30", activity: "Pozo Izquierdo – Windsurf-WM-Strand zuschauen", icon: "🏄" },
        { time: "18:00", activity: "Playa de Maspalomas – letzter Sonnenuntergang", icon: "🌅" },
      ],
    },
  ],
};

export default content;
