import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🌿", text: "Ruhige Insel mit milden 12–15 °C. Ideal für Wanderungen im Inselinneren und authentische Dorfbesuche ohne Touristen." },
    { label: "Februar",   emoji: "🌸", text: "Mandelblüte im Landesinneren. Günstigste Preise des Jahres, fast alle Clubs geschlossen – perfekt für Naturfreunde." },
    { label: "März",      emoji: "🌞", text: "Frühling erwacht. Erste Radtouren und Wanderungen entlang der Küstenpfade bei 16–18 °C." },
    { label: "April",     emoji: "🚴", text: "Vorsaison: Hippie-Märkte öffnen wieder, wenig Betrieb, angenehme Temperaturen, günstige Hotels." },
    { label: "Mai",       emoji: "🏄", text: "Badesaison beginnt mit 21 °C Wassertemperatur. Erste Yachten im Hafen, entspannte Atmosphäre." },
    { label: "Juni",      emoji: "🎉", text: "Partysaison startet. Clubs wie Pacha und Amnesia eröffnen. Preise steigen stark – frühzeitig buchen." },
    { label: "Juli",      emoji: "🔥", text: "Hochsaison: Heiß, laut, teuer. Für Strandurlaub und Nachtleben perfekt. Unterkunft lange im Voraus buchen." },
    { label: "August",    emoji: "🎶", text: "Peak-Saison mit Weltklasse-DJs. Eivissa ist ausgebucht. Preise auf Höchstniveau – aber das Erlebnis ist einzigartig." },
    { label: "September", emoji: "🌅", text: "Noch warm (27 °C Wasser), deutlich ruhiger. Perfekte Balance zwischen Strand und Party." },
    { label: "Oktober",   emoji: "🍂", text: "Clubs schließen, Preise fallen stark. Letzte Badesaison. Wunderschöne Sonnenuntergänge am Cap d'es Falcó." },
    { label: "November",  emoji: "☕", text: "Insel kehrt zur Ruhe zurück. Wintersaison der Einheimischen beginnt. Authentische Restaurants öffnen wieder." },
    { label: "Dezember",  emoji: "🌟", text: "Weihnachten in Eivissa mit spanischem Flair. Wenig Touristen, günstige Preise, gemütliche Atmosphäre." },
  ],
  sights: [
    {
      title: "Dalt Vila – Burg und UNESCO-Altstadt",
      desc: "Die ummauerte Oberstadt Eivissas zählt seit 1999 zum UNESCO-Welterbe. Gepflasterte Gassen führen zur imposanten Kathedrale und zur Burg mit Panoramablick über den Hafen.",
      mapHref: "https://maps.google.com/?q=Dalt+Vila+Ibiza",
      address: "Dalt Vila, Eivissa",
      duration: "2–3 Std.",
      cost: "Kostenlos",
      tip: "Sonnenuntergang von der Stadtmauer aus ist unübertroffen – komm 30 Min. vorher.",
    },
    {
      title: "Es Vedrà – Mystische Felsinsel",
      desc: "Der 382 m hohe Felskoloss vor der Westküste gilt als einer der magnetischsten Orte der Erde. Zahlreiche Legenden ranken sich um den Monolithen, der bei Sonnenuntergang leuchtend orange erstrahlt.",
      mapHref: "https://maps.google.com/?q=Es+Vedra+Ibiza",
      address: "Cap Llentrisca, Südwestibiza",
      duration: "Halbtag",
      cost: "Kostenlos",
      tip: "Aussichtspunkt Torre d'en Rovira für das beste Foto ohne Wanderung.",
    },
    {
      title: "Hippie-Markt Las Dalias",
      desc: "Seit 1985 der berühmteste Hippie-Markt der Insel in San Carlos. Handgemachter Schmuck, Kleidung, Kunsthandwerk und Weltküche in einzigartiger Atmosphäre.",
      mapHref: "https://maps.google.com/?q=Las+Dalias+Ibiza",
      address: "Carretera Sant Carles, Km 12, San Carlos",
      duration: "2–3 Std.",
      cost: "Kostenlos",
      tip: "Samstags 10–21 Uhr. Montagsmarkt im Sommer bis Mitternacht (Nachtmarkt).",
    },
    {
      title: "Cala d'Hort – Traumbucht mit Blick auf Es Vedrà",
      desc: "Eine der schönsten Buchten Ibizas mit türkisfarbenem Wasser und direktem Blick auf die Insel Es Vedrà. Kleines Fischerdorf mit exzellenten Strandrestaurants.",
      mapHref: "https://maps.google.com/?q=Cala+d%27Hort+Ibiza",
      address: "Cala d'Hort, Sant Josep de sa Talaia",
      duration: "Halbtag",
      cost: "Kostenlos",
      tip: "Früh kommen, da nur begrenzt Parkplätze vorhanden.",
    },
    {
      title: "Sa Caleta – Phönizische Siedlung",
      desc: "Älteste Siedlung Ibizas, gegründet von den Phöniziern um 650 v. Chr. Die Ruinen liegen direkt am Meer. UNESCO-Welterbe zusammen mit Dalt Vila.",
      mapHref: "https://maps.google.com/?q=Sa+Caleta+Ibiza",
      address: "Sa Caleta, Sant Josep",
      duration: "1 Std.",
      cost: "Kostenlos",
      tip: "Kombination mit Cala d'Hort für einen perfekten Halbtag.",
    },
  ],
  history: [
    {
      year: "654 v. Chr.",
      title: "Phönizische Gründung von Ibosim",
      text: "Phönizier aus Karthago gründeten die Siedlung Ibosim (heute Eivissa) als Handelsposten. Die strategische Lage im westlichen Mittelmeer machte die Insel zum wichtigen Umschlagplatz für Salz, Blei und Farbstoffe.",
    },
    {
      year: "218 v. Chr.",
      title: "Römische Eroberung",
      text: "Im Zweiten Punischen Krieg fiel Ibiza an Rom. Die Römer nannten die Insel Ebusus. Trotz der Romanisierung behielten viele Bewohner ihre punische Kultur und Götterverehrung bei.",
    },
    {
      year: "902",
      title: "Arabische Herrschaft beginnt",
      text: "Mauren aus al-Andalus eroberten Ibiza. Für 300 Jahre prägte arabische Kultur die Insel. Viele Ortsnamen enden noch heute auf die arabische Vorsilbe 'al-'.",
    },
    {
      year: "1235",
      title: "Reconquista – Iberische Rückeroberung",
      text: "König Jakob I. von Aragon eroberte Ibiza von den Mauren zurück. Die Insel wurde auf die katalanischen Adligen aufgeteilt. Katalanisch als Sprache prägt die Insel bis heute.",
    },
    {
      year: "1960er",
      title: "Entdeckung durch Hippies & Künstler",
      text: "Ibiza wurde von der internationalen Hippie-Bewegung entdeckt. Schriftsteller, Maler und Aussteiger siedelten sich an. Die Insel entwickelte sich zum Zentrum von Gegenkultur und freiem Geist.",
    },
    {
      year: "1987",
      title: "Geburt der modernen Clubkultur",
      text: "Das legendäre DJ-Set von Alfredo im Club Amnesia gilt als Geburtsstunde des Ibiza-Sounds. House und Electronic Music verbreiteten sich von hier aus in die ganze Welt. Ibiza wurde zur Welthauptstadt des Club-Tourismus.",
    },
  ],
  food: [
    {
      emoji: "🥘",
      name: "Bullit de Peix",
      original: "Bullit de Peix",
      desc: "Das traditionelle ibizenkische Fischgericht: Kartoffeln und frischer Fisch werden zuerst gekocht, dann der Fond zu goldgelbem Arroz a banda (Reis) verarbeitet. Zwei Gänge aus einem Topf.",
      price: "18–28 €",
      tip: "Nur in authentischen Can-Restaurants, nicht in Touristenrestaurants erhältlich.",
    },
    {
      emoji: "🫓",
      name: "Flaó",
      original: "Flaó",
      desc: "Traditioneller ibizenkischer Käsekuchen aus frischem Ziegenkäse, Minze und Anis. Das Originalrezept stammt aus der maurischen Zeit und ist einzigartig auf der Insel.",
      price: "4–7 €",
    },
    {
      emoji: "🌿",
      name: "Sofrit Pagès",
      original: "Sofrit Pagès",
      desc: "Rustikaler Bauerneintopf mit Lammfleisch, Wurst, Kartoffeln und Gewürzen. Das Herzstück der ibizenkischen Hausmannskost – wird bei Festen und Familientreffen serviert.",
      price: "14–22 €",
    },
    {
      emoji: "🍬",
      name: "Greixonera",
      original: "Greixonera",
      desc: "Süßer Brotpudding aus altem Ensaimada-Gebäck, Ei und Zimt. Das beliebteste Dessert der Insel, einfach und unwiderstehlich.",
      price: "4–6 €",
    },
    {
      emoji: "🥤",
      name: "Hierbas Ibicencas",
      original: "Hierbas Ibicencas",
      desc: "Traditioneller Kräuterlikör aus über 20 Wildkräutern – Rosmarin, Thymian, Majoran und mehr. Das typische Mitbringsel von Ibiza, trocken oder süß erhältlich.",
      price: "3–5 € (Glas)",
      tip: "Destillerie Can Rich bietet Führungen und Verkostung an.",
    },
  ],
  phrases: [
    { original: "¡Hola! / ¡Bon dia! (Kat.)", pronunciation: "o-la / bon di-a", translation: "Hallo! / Guten Morgen! (Katalanisch)" },
    { original: "Por favor / Si us plau", pronunciation: "por fa-bor / si us plau", translation: "Bitte (Spanisch / Katalanisch)" },
    { original: "Gracias / Gràcies", pronunciation: "gra-θjas / gra-si-əs", translation: "Danke (Spanisch / Katalanisch)" },
    { original: "¿Cuánto cuesta?", pronunciation: "kwan-to kwes-ta", translation: "Was kostet das?" },
    { original: "La cuenta, por favor", pronunciation: "la kwen-ta por fa-bor", translation: "Die Rechnung, bitte" },
    { original: "¿Dónde está la playa?", pronunciation: "don-de es-ta la pla-ja", translation: "Wo ist der Strand?" },
    { original: "Una cerveza, por favor", pronunciation: "u-na θer-be-θa por fa-bor", translation: "Ein Bier, bitte" },
    { original: "¡Salud!", pronunciation: "sa-lu", translation: "Prost! / Zum Wohl!" },
    { original: "Necesito un médico", pronunciation: "ne-θe-si-to un me-di-ko", translation: "Ich brauche einen Arzt" },
    { original: "¡Hasta luego!", pronunciation: "as-ta lwe-go", translation: "Auf Wiedersehen!" },
  ],
  insider: [
    {
      icon: "🌅",
      title: "Sonnenuntergang bei Café del Mar",
      text: "Das Café del Mar in San Antonio ist der Kultplatz für Sonnenuntergänge. Komm 30 Minuten vorher und sichere dir einen Platz direkt am Wasser. Der Eintritt ist kostenlos – du zahlst nur für Getränke.",
    },
    {
      icon: "🛵",
      title: "Scooter für Buchten-Hopping",
      text: "Mit einem Moped (ab 20 €/Tag) erreichst du die abgelegenen Traumstrände, die Busse nicht anfahren. Cala Conta, Cala Bassa und Cala Tarida sind per Scooter in 20 Minuten erreichbar.",
    },
    {
      icon: "🎶",
      title: "Früh in Clubs – halber Eintrittspreis",
      text: "Clubs wie Privilege oder Amnesia haben Eintrittspreise von 30–60 €. Wer vor 1 Uhr eingeht, zahlt oft nur die Hälfte. Die Party startet ohnehin erst nach Mitternacht richtig.",
    },
    {
      icon: "🏊",
      title: "Geheimstrand Cala Saladeta",
      text: "Nur wenige Minuten von der überfüllten Cala Salada entfernt liegt die kleine Cala Saladeta – kristallklares Wasser, Felsen und kaum Touristen. Nur zu Fuß erreichbar.",
    },
    {
      icon: "🛒",
      title: "Nachtmarkt in San Juan",
      text: "Jeden Donnerstagabend von Juli bis September verwandelt sich San Juan in einen bunten Nachtmarkt. Einheimische Musiker, lokale Händler und die beste Atmosphäre der Insel – kostenlos.",
    },
  ],
  beaches: [
    {
      name: "Playa d'en Bossa",
      emoji: "🎉",
      desc: "Längster Strand Ibizas mit direktem Zugang zu den berühmtesten Clubs und Beach Bars der Insel.",
      type: "Sandstrand",
      tip: "Ushuaïa Beach Club für Tagespartys – Karten im Voraus kaufen.",
    },
    {
      name: "Cala Conta (Cala Comte)",
      emoji: "🌊",
      desc: "Mehrere türkisblaue Buchten mit flachem, glasklarem Wasser und spektakulärem Blick auf die Ilhetes-Inselchen.",
      type: "Felsenbucht",
      tip: "Einer der schönsten Sonnenuntergänge Ibizas – Platz früh sichern.",
    },
    {
      name: "Ses Salines",
      emoji: "🌿",
      desc: "Naturschutzgebiet mit weißem Feinsand und türkisem Wasser. Beliebt bei der Fashionista-Szene und Naturliebhabern gleichermaßen.",
      type: "Naturstrand",
    },
    {
      name: "Cala Bassa",
      emoji: "⛵",
      desc: "Halbmondförmige Bucht mit tiefblauem Wasser, Pinienwald und einer der besten Beach Bars der Insel.",
      type: "Sandstrand",
      tip: "Per Wassertaxi von San Antonio anfahren – entspannter als Autofahrt.",
    },
    {
      name: "Aguas Blancas",
      emoji: "🤸",
      desc: "Naturstrand im Nordosten der Insel, bekannt als FKK-Strand. Weiße Klippen, klares Wasser und entspannte Atmosphäre abseits des Mainstream.",
      type: "Naturstrand / FKK",
    },
  ],
  regions: [
    {
      name: "Eivissa (Ibiza-Stadt)",
      emoji: "🏰",
      desc: "Die Hauptstadt mit UNESCO-Altstadt Dalt Vila, lebhaftem Hafen und dem Ausgehviertel La Marina.",
      highlights: ["Dalt Vila & Stadtmauer", "Hafenpromenade", "Nachtleben La Marina"],
    },
    {
      name: "San Antonio & Westküste",
      emoji: "🌅",
      desc: "Touristisches Zentrum mit Sonnenuntergangsstrände, Café del Mar und der beliebtesten Party-Bucht.",
      highlights: ["Café del Mar", "Cala Conta", "Cala Bassa"],
    },
    {
      name: "San Carlos & Nordosten",
      emoji: "🌿",
      desc: "Hippie-Herz der Insel mit dem berühmten Las-Dalias-Markt, einsamen Buchten und authentischen Dörfern.",
      highlights: ["Las Dalias Markt", "Aguas Blancas", "Pou des Lleó"],
    },
    {
      name: "Sant Josep & Südwesten",
      emoji: "🧘",
      desc: "Ruhigste Ecke Ibizas mit den schönsten Naturstränden, Es Vedrà und der phönizischen Siedlung Sa Caleta.",
      highlights: ["Es Vedrà", "Cala d'Hort", "Ses Salines"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "40–80 €", mid: "100–200 €", luxury: "250–600 €+" },
    { label: "Essen (pro Tag)", budget: "15–25 €", mid: "35–65 €", luxury: "80–200 €+" },
    { label: "Transport (pro Tag)", budget: "8–15 € (Bus)", mid: "20–35 € (Scooter)", luxury: "50–100 € (Mietwagen)" },
    { label: "Clubs & Aktivitäten", budget: "0–20 €", mid: "30–80 €", luxury: "100–300 €+" },
    { label: "Tagesbudget gesamt", budget: "65–130 €", mid: "180–350 €", luxury: "500–1200 €+" },
  ],
  emergency: {
    police: "112",
    ambulance: "112",
    fire: "112",
    embassy: "+34 971 303 113 (Deutsches Konsulat Palma de Mallorca)",
    hospital: "Can Misses Hospital Ibiza: +34 971 397 000",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Dalt Vila & romantischer Hafenabend",
      icon: "🏰",
      color: "bg-rose-100",
      dayCost: "~80 €",
      transport: "Zu Fuß / Taxi",
      meals: "Restaurante La Brasa",
      stops: [
        { time: "10:00", activity: "Dalt Vila – Stadtmauer und Kathedrale", icon: "🏰", tip: "Früh kommen – die Gassen sind noch kühl und leer." },
        { time: "12:00", activity: "Archäologisches Museum Ibiza", icon: "🏛️" },
        { time: "14:00", activity: "Mittagessen in der Altstadt", icon: "🍽️" },
        { time: "17:00", activity: "Bummel durch La Marina & Hafen", icon: "⚓" },
        { time: "20:00", activity: "Romantisches Dinner am alten Hafen", icon: "🌃", tip: "Restaurant La Brasa in der Altstadt – Reservierung empfohlen." },
      ],
    },
    {
      day: "Tag 2",
      title: "Cala Conta & Sonnenuntergang",
      icon: "🌅",
      color: "bg-amber-100",
      dayCost: "~70 €",
      transport: "Mietauto / Taxi",
      meals: "Strandrestaurant Cala Conta",
      stops: [
        { time: "10:30", activity: "Cala Bassa – Schwimmen und Relaxen", icon: "🏊" },
        { time: "13:00", activity: "Mittagessen an der Beach Bar", icon: "🍹" },
        { time: "15:00", activity: "Weiterfahrt zur Cala Conta", icon: "🚗" },
        { time: "17:00", activity: "Schnorcheln in der Bucht", icon: "🤿" },
        { time: "19:30", activity: "Sonnenuntergang von den Felsen", icon: "🌅", tip: "Einer der schönsten Sonnenuntergänge der Insel." },
      ],
    },
    {
      day: "Tag 3",
      title: "Es Vedrà & Abendessen in Sant Josep",
      icon: "🗿",
      color: "bg-emerald-100",
      dayCost: "~65 €",
      transport: "Mietauto",
      meals: "Can Berri Vell, Sant Josep",
      stops: [
        { time: "09:00", activity: "Cala d'Hort – Schwimmen mit Es-Vedrà-Blick", icon: "🌊" },
        { time: "11:30", activity: "Wanderung zum Aussichtspunkt Torre d'en Rovira", icon: "🥾" },
        { time: "14:00", activity: "Mittagessen im Fischrestaurant", icon: "🐟" },
        { time: "16:30", activity: "Sa Caleta – Phönizische Ruinen", icon: "🏛️" },
        { time: "20:00", activity: "Abendessen im rustikalen Landrestaurant", icon: "🍷", tip: "Can Berri Vell – traditionelle Ibiza-Küche in einem 300 Jahre alten Finca." },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Playa d'en Bossa & Wasserpark",
      icon: "🎢",
      color: "bg-cyan-100",
      dayCost: "~150 € (Fam. 4)",
      transport: "Bus / Taxi",
      meals: "Strandrestaurant",
      stops: [
        { time: "10:00", activity: "Aguamar Water Park in Playa d'en Bossa", icon: "🎢", tip: "Günstigere Karten online im Voraus kaufen." },
        { time: "13:00", activity: "Mittagessen im Wasserpark", icon: "🌮" },
        { time: "15:30", activity: "Strand Playa d'en Bossa – Sandburgen & Schwimmen", icon: "🏖️" },
        { time: "18:30", activity: "Eisessen an der Promenade", icon: "🍦" },
      ],
    },
    {
      day: "Tag 2",
      title: "Piratenburg & Dalt Vila",
      icon: "🏴‍☠️",
      color: "bg-yellow-100",
      dayCost: "~60 €",
      transport: "Bus nach Eivissa",
      meals: "Altstadt-Restaurant",
      stops: [
        { time: "10:00", activity: "Dalt Vila – Burg und Stadtmauer erkunden", icon: "🏰", tip: "Kinder lieben die Mauern und Türme – wie eine echte Piratenburg." },
        { time: "12:00", activity: "Archäologisches Museum (Kinder frei bis 12)", icon: "🏛️" },
        { time: "14:00", activity: "Mittagessen mit Blick auf den Hafen", icon: "🍽️" },
        { time: "16:00", activity: "Strand Figueretes – ruhig und flach", icon: "🏖️" },
        { time: "18:30", activity: "Einkehr in der Hafenpromenade", icon: "🍹" },
      ],
    },
    {
      day: "Tag 3",
      title: "Ses Salines Naturpark & Flamingos",
      icon: "🦩",
      color: "bg-pink-100",
      dayCost: "~55 €",
      transport: "Mietauto",
      meals: "Strandbar Ses Salines",
      stops: [
        { time: "09:30", activity: "Ses Salines Naturpark – Flamingos beobachten", icon: "🦩", tip: "Von Oktober bis März sind Flamingos fast garantiert zu sehen." },
        { time: "11:00", activity: "Strand Ses Salines – flaches Wasser für Kinder", icon: "🏖️" },
        { time: "13:30", activity: "Picknick am Strand oder Strandbar", icon: "🥪" },
        { time: "15:30", activity: "Bootsausflug zu den Salinen-Lagunen", icon: "⛵" },
        { time: "17:30", activity: "Rückfahrt mit Eisstop in Sant Francesc", icon: "🍦" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Altstadt & Hippie-Markt",
      icon: "🎒",
      color: "bg-indigo-100",
      dayCost: "~40 €",
      transport: "Bus / Zu Fuß",
      meals: "Streetfood Hafenpromenade",
      stops: [
        { time: "09:00", activity: "Dalt Vila bei Sonnenaufgang erkunden", icon: "🌅" },
        { time: "11:00", activity: "Las Dalias Hippie-Markt (samstags)", icon: "🌸", tip: "Günstigste und authentischste Souvenirs der Insel." },
        { time: "14:00", activity: "Streetfood am Hafen", icon: "🌮" },
        { time: "16:00", activity: "Ses Feixes – Wanderweg durch die Salinen", icon: "🚶" },
        { time: "20:00", activity: "Sundowner an der Hafenbar", icon: "🍻" },
      ],
    },
    {
      day: "Tag 2",
      title: "Buchten-Hopping per Scooter",
      icon: "🛵",
      color: "bg-orange-100",
      dayCost: "~50 €",
      transport: "Scooter (ab 20 €/Tag)",
      meals: "Unterwegs",
      stops: [
        { time: "09:00", activity: "Scooter mieten in Eivissa", icon: "🛵" },
        { time: "10:00", activity: "Cala Saladeta – Geheimstrand", icon: "🏊" },
        { time: "12:30", activity: "Cala Conta – Schnorcheln und Mittagessen", icon: "🤿" },
        { time: "15:30", activity: "Cala d'Hort mit Blick auf Es Vedrà", icon: "🗿" },
        { time: "19:00", activity: "Café del Mar – Sonnenuntergang", icon: "🌅", tip: "Kult-Sonnenuntergang mit Chillout-Musik – kostenlos." },
      ],
    },
    {
      day: "Tag 3",
      title: "Nachtleben & Club-Erlebnis",
      icon: "🎶",
      color: "bg-purple-100",
      dayCost: "~80 €",
      transport: "Taxi / Disco-Bus",
      meals: "Abendessen in Playa d'en Bossa",
      stops: [
        { time: "12:00", activity: "Entspannter Morgen am Strand", icon: "🏖️" },
        { time: "15:00", activity: "Siesta und Vorbereitung", icon: "😴" },
        { time: "19:00", activity: "Abendessen in Playa d'en Bossa", icon: "🍝" },
        { time: "22:00", activity: "Vorglühen im Hi Ibiza Beach Club", icon: "🍹" },
        { time: "01:00", activity: "Amnesia oder Pacha – Weltklasse-DJs", icon: "🎧", tip: "Karten online vorbestellen – spart 20–30 % Eintritt." },
      ],
    },
  ],
};

export default content;
