import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🌿", text: "Korfu im Winter: Grün, ruhig und mild (12 °C). Olivenernte läuft. Ideale Zeit für Wanderungen im Inselinneren ohne jeglichen Touristenstress." },
    { label: "Februar",   emoji: "🌸", text: "Karnevalssaison in Korfu-Stadt mit Umzügen. Mandelblüte. Günstigste Preise des Jahres. Authentische Inselatmosphäre." },
    { label: "März",      emoji: "☘️", text: "Frühling kommt früh auf Korfu – erste grüne Wiesen und Wildblumen. Wanderungen im Hinterland besonders schön." },
    { label: "April",     emoji: "⛪", text: "Griechisch-Orthodoxes Ostern (Lampedusa Prozession in Korfu-Stadt) – einzigartiges kulturelles Ereignis. Vorsaison mit angenehmen 20 °C." },
    { label: "Mai",       emoji: "🏖️", text: "Badesaison beginnt! 21 °C Wassertemperatur. Herrliche Temperaturen, wenig Massen. Bestes Frühjahrs-Reiseziel." },
    { label: "Juni",      emoji: "⛵", text: "Hochsaison beginnt. Erste Kreuzfahrtschiffe in Korfu-Stadt. Paleokastritsa tadellos im Juni." },
    { label: "Juli",      emoji: "☀️", text: "Heiß und lebhaft (32 °C). Alle Strände voll. Frühzeitig aufstehen für die schönsten Plätze." },
    { label: "August",    emoji: "🔆", text: "Peak-Saison: Heißes, überfülltes Korfu. Paleokastritsa nahezu unzugänglich. Wer trotzdem kommt, fährt früh morgens." },
    { label: "September", emoji: "🌊", text: "Noch warm (27 °C), deutlich ruhiger. Günstigere Preise. Beste Reisezeit für Korfu schlechthin." },
    { label: "Oktober",   emoji: "🍇", text: "Weinlese. Angenehme 24 °C, letztes Badewetter. Herrliche Herbstlandschaft im grünen Inselinneren." },
    { label: "November",  emoji: "🌧️", text: "Erste Regentage. Olivenernte beginnt. Insel kehrt zum Alltagsleben zurück. Günstig und authentisch." },
    { label: "Dezember",  emoji: "🌲", text: "Korfu im Advent: Weihnachtsbräuche mit griechisch-venezianischem Flair. Milde 14 °C, ruhige Atmosphäre." },
  ],
  sights: [
    {
      title: "Korfu-Altstadt – UNESCO-Welterbe",
      desc: "Die Altstadt von Korfu ist ein einzigartiges Zeugnis venezianischer, französischer und britischer Herrschaft. Das Liston (venezianische Arkaden-Promenade), die Spianada (größter Platz Griechenlands), die Alten und Neuen Festungen machen die Stadt zur elegantesten Altstadt der griechischen Inseln.",
      mapHref: "https://maps.google.com/?q=Korfu+Altstadt+UNESCO",
      address: "Korfu-Stadt (Kerkyra)",
      duration: "3–4 Std.",
      cost: "Kostenlos (Alte Festung 6 €)",
      tip: "Abends in der Alten Festung: Licht- und Tonshow im Sommer. Liston-Café für den Aperitivo.",
    },
    {
      title: "Paleokastritsa – Schönste Bucht Korfu",
      desc: "Das Juwel Korfu's: mehrere türkisfarbene Buchten umgeben von grünen Hügeln, einem venezianischen Kloster auf der Klippe und dem klarsten Wasser der Insel. Angelehnt an Homers Phäaken-Insel aus der Odyssee.",
      mapHref: "https://maps.google.com/?q=Paleokastritsa+Korfu",
      address: "Paleokastritsa, Westkorfu",
      duration: "Halbtag",
      cost: "Kostenlos",
      tip: "Vor 9 Uhr kommen oder nach 17 Uhr. Ein Boot mieten (15 €/Std.) für Zugang zu geheimen Buchten.",
    },
    {
      title: "Achilleion-Palast",
      desc: "Das märchenhafte Schloss der Kaiserin Sisi (Elisabeth von Österreich) auf einem Hügel mit Blick aufs Meer. Der neoklassizistische Palast mit Gärten voller antiker Statuen ist eines der meistbesuchten Denkmäler Griechenlands.",
      mapHref: "https://maps.google.com/?q=Achilleion+Korfu",
      address: "Gastouri, Korfu",
      duration: "1,5–2 Std.",
      cost: "10 €",
      tip: "Sisi war eine leidenschaftliche Griechenland-Liebhaberin – die Statuen und Gärten erzählen ihre Geschichte.",
    },
    {
      title: "Angelokastro – Byzantinische Festung",
      desc: "Auf einem 163 m hohen Felsen über dem Meer thronende byzantinische Festung aus dem 13. Jahrhundert. Während aller türkischen Angriffe hielt sie stand – ihre uneinnehmbare Position bietet spektakulären Blick auf die albanische Küste.",
      mapHref: "https://maps.google.com/?q=Angelokastro+Korfu",
      address: "Krini, Nordwestkorfu",
      duration: "1,5 Std.",
      cost: "4 €",
      tip: "Kurze Kletterpartie auf Fels – festes Schuhwerk empfohlen. Kombinierbar mit Paleokastritsa.",
    },
    {
      title: "Agios Stefanos & Nordkorfu",
      desc: "Das ruhige Fischereidorf Agios Stefanos im Norden der Insel mit klarem Wasser, weißem Sand und einem der besten Fischrestaurants Korfu's. Nicht zu verwechseln mit dem gleichnamigen Ort im Osten.",
      mapHref: "https://maps.google.com/?q=Agios+Stefanos+Avliotis+Korfu",
      address: "Agios Stefanos Avliotis, Nordkorfu",
      duration: "Halbtag",
      cost: "Kostenlos",
      tip: "Taverna Eucalyptus direkt am Wasser – frischer Fang täglich.",
    },
  ],
  history: [
    {
      year: "730 v. Chr.",
      title: "Korkyra – Korinthische Kolonie",
      text: "Korinth gründete auf der Insel die Kolonie Korkyra. Die strategische Lage zwischen Adria und Mittelmeer machte sie schnell zur reichen und selbstbewussten Stadt – und zum Auslöser des Peloponnesischen Krieges.",
    },
    {
      year: "433 v. Chr.",
      title: "Auslöser des Peloponnesischen Krieges",
      text: "Ein Bündnisstreit zwischen Korkyra und Korinth zwang Athen zur Parteinahme für Korkyra. Dies gilt als unmittelbarer Anlass des Peloponnesischen Krieges (431–404 v. Chr.), der die griechische Welt veränderte.",
    },
    {
      year: "1386",
      title: "Venezianische Herrschaft beginnt",
      text: "Korfu unterwarf sich freiwillig der Serenissima Venezia. Für 411 Jahre prägten die Venezianer die Architektur, die Sprache und die Kultur. Die Altstadt mit Liston, Festungen und Gassen ist ein venezianisches Meisterwerk.",
    },
    {
      year: "1797",
      title: "Französische Herrschaft & Ionische Inseln",
      text: "Nach dem Frieden von Campo Formio fiel Korfu an Frankreich. Napoleon ließ die venezianischen Privilegien abschaffen. Später übernahmen die Briten die Verwaltung der Vereinigten Ionischen Inseln bis 1864.",
    },
    {
      year: "1864",
      title: "Vereinigung mit Griechenland",
      text: "Die Ionischen Inseln wurden dem Königreich Griechenland übergeben – als Hochzeitsgeschenk für den neuen griechischen König Georg I. aus Dänemark. Korfu war die letzte griechische Insel, die unter britischem Protektorat stand.",
    },
    {
      year: "2007",
      title: "UNESCO-Welterbe",
      text: "Die Korfu-Altstadt wurde in die UNESCO-Welterbeliste aufgenommen, als Zeugnis für die außergewöhnliche Überlagerung venezianischer, französischer und britischer Architektur an einem einzigen Ort.",
    },
  ],
  food: [
    {
      emoji: "🥩",
      name: "Sofrito",
      original: "Σοφρίτο",
      desc: "Das Korfiotische Nationalgericht: zartes Kalbfleisch in weißem Knoblauch-Weißwein-Essig-Fond geschmort, mit Petersilie. Venezianischen Ursprungs, einzigartig auf Korfu.",
      price: "14–22 €",
      tip: "Nur in authentischen Korfiotischen Restaurants erhältlich – nicht auf anderen griechischen Inseln.",
    },
    {
      emoji: "🧅",
      name: "Pastitsada",
      original: "Παστιτσάδα",
      desc: "Korfiotischer Schmorbraten aus Rindfleisch oder Hahn in Tomaten-Zimt-Gewürzsauce mit handgemachten Nudeln (Pastitsio). Ein weiteres venezianisches Erbstück der Inselküche.",
      price: "12–20 €",
    },
    {
      emoji: "🐟",
      name: "Bourdeto",
      original: "Μπουρδέτο",
      desc: "Scharfer Fisch-Eintopf mit rotem Paprika, Zwiebeln und reichlich Cayennepfeffer. Das rustikalste und würzigste Gericht Korfu's – Korfudialekt für 'würzig'.",
      price: "14–24 €",
    },
    {
      emoji: "🍊",
      name: "Kumquat-Likör",
      original: "Κουμ Κουάτ Λικέρ",
      desc: "Korfu ist das einzige Gebiet Europas, wo Kumquats (kleine Zitrusfrüchte) angebaut werden. Der Likör aus diesen winzigen Früchten ist das typischste Mitbringsel der Insel.",
      price: "3–6 € (Glas)",
      tip: "Destillerie Mavromatis für eine Fabrikführung und Verkostung.",
    },
    {
      emoji: "🍪",
      name: "Mandolato",
      original: "Μαντολάτο",
      desc: "Korfiotisches Nougat aus Mandeln, Honig und Eiweiß. Das traditionelle Weihnachtsgebäck, das ganzjährig in den Zuckerbäckereien der Altstadt verkauft wird.",
      price: "4–8 €",
    },
  ],
  phrases: [
    { original: "Γεια σας! (Yeia sas!)", pronunciation: "jɑ sas", translation: "Guten Tag! (formell / an mehrere)" },
    { original: "Καλημέρα (Kaliméra)", pronunciation: "kali-me-ra", translation: "Guten Morgen" },
    { original: "Ευχαριστώ (Efcharistó)", pronunciation: "ef-cha-ri-sto", translation: "Danke" },
    { original: "Παρακαλώ (Parakaló)", pronunciation: "pa-ra-ka-lo", translation: "Bitte / Gern geschehen" },
    { original: "Πόσο κάνει; (Póso káni?)", pronunciation: "po-so ka-ni", translation: "Was kostet das?" },
    { original: "Τον λογαριασμό (Ton logariasmó)", pronunciation: "ton lo-ga-ria-smo", translation: "Die Rechnung" },
    { original: "Πού είναι το λιμάνι; (Pu ine to limani?)", pronunciation: "pu i-ne to li-ma-ni", translation: "Wo ist der Hafen?" },
    { original: "Μία μπύρα παρακαλώ (Mia bira parakaló)", pronunciation: "mi-a bi-ra pa-ra-ka-lo", translation: "Ein Bier, bitte" },
    { original: "Χρειάζομαι γιατρό (Chriázomai jatró)", pronunciation: "chri-a-zo-me ja-tro", translation: "Ich brauche einen Arzt" },
    { original: "Αντίο! (Andío!)", pronunciation: "an-di-o", translation: "Auf Wiedersehen!" },
  ],
  insider: [
    {
      icon: "🛥️",
      title: "Mietboot für geheime Buchten",
      text: "In Paleokastritsa kann man für 15–20 €/Stunde ein kleines Motorboot mieten (kein Führerschein nötig bis 10 PS). Damit erreicht man Buchten, zu denen sonst niemand kommt – das beste Erlebnis der Insel.",
    },
    {
      icon: "🌳",
      title: "Olivenhain-Wanderungen im Norden",
      text: "Die Nordküste Korfu's hat Europas dichteste Olivenwälder – 4 Millionen Olivenbäume bedecken die Insel. Wanderungen durch alte Olivenwälder nach Agios Stefanos kosten nichts und bieten unvergessliche Natur.",
    },
    {
      icon: "🎶",
      title: "Philharmoniker am Sonntag",
      text: "Korfu-Stadt ist Griechenlands Musikhauptstadt mit 18 Philharmonikern. Sonntags spielen Kapellen auf der Spianada – griechische Marschmusik mit venezianischem Flair. Kostenlos und einmalig.",
    },
    {
      icon: "⛪",
      title: "Griechisch-Orthodoxes Ostern",
      text: "Korfu feiert Ostern spektakulärer als alle anderen griechischen Inseln. Am Karsamstag werden Keramiktöpfe aus den Fenstern geworfen (Symbol der Erneuerung) – ein Volksfest ohne gleichen. Reisetermin entsprechend planen.",
    },
    {
      icon: "🚌",
      title: "Günstige Busse statt Taxi",
      text: "Das blaue Busnetz (KTEL) fährt von Korfu-Stadt nach Paleokastritsa (2,40 €), Kassiopi (3,00 €) und Agios Gordios (1,80 €). Taxis kosten das 5-fache.",
    },
  ],
  beaches: [
    {
      name: "Paleokastritsa",
      emoji: "🏖️",
      desc: "Mehrere türkisblaue Buchten unter grünen Hügeln – der fotogenste Strand Griechenlands und gleichzeitig ideal zum Schnorcheln.",
      type: "Buchten-Paradies",
      tip: "Mit gemieteten Motorboot weitere geheime Buchten erkunden.",
    },
    {
      name: "Glyfada",
      emoji: "🌊",
      desc: "Langer, feiner Sandstrand an der Westküste mit türkisblauem Wasser – einer der schönsten Sandbuchten der Insel.",
      type: "Feiner Sandstrand",
    },
    {
      name: "Sidari & Canal d'Amour",
      emoji: "💕",
      desc: "Legendärer Felskanal im Norden: Wer durch den Canal d'Amour schwimmt, findet angeblich die ewige Liebe. Warmes, flaches Wasser.",
      type: "Romantische Felsbucht",
    },
    {
      name: "Agios Gordios",
      emoji: "🌅",
      desc: "Langer Sandstrand an der Südwestküste mit spektakulärem Blick auf eine riesige Felsnadel im Meer. Entspannte Atmosphäre.",
      type: "Weitläufiger Sandstrand",
      tip: "Pink Palace Hostel – weltberühmte Partyatmosphäre für junge Reisende.",
    },
    {
      name: "Nissaki & Nordostküste",
      emoji: "🐠",
      desc: "Kleine, ruhige Buchten an der Nordostküste mit glasklarem Wasser und direktem Blick auf Albanien.",
      type: "Ruhige Buchten / Schnorcheln",
    },
  ],
  regions: [
    {
      name: "Korfu-Stadt (Kerkyra)",
      emoji: "🏰",
      desc: "UNESCO-Altstadt mit venezianischen Arkaden, Altem und Neuem Fort sowie der elegantesten Strandpromenade Griechenlands.",
      highlights: ["Liston & Spianada", "Alte Festung", "Achilleion-Ausflug"],
    },
    {
      name: "Nordwestküste & Paleokastritsa",
      emoji: "🌊",
      desc: "Die wildeste und schönste Ecke der Insel mit dramatischen Buchten, Klippen und byzantinischen Festungen.",
      highlights: ["Paleokastritsa", "Angelokastro", "Bella Vista Aussichtspunkt"],
    },
    {
      name: "Nordküste & Kassiopi",
      emoji: "🌿",
      desc: "Grüne Olivenwälder, ruhige Fischerorte und die schönsten Buchten des nördlichen Korfu.",
      highlights: ["Kassiopi Hafen", "Agios Stefanos", "Canal d'Amour Sidari"],
    },
    {
      name: "Südkorfu & Benitses",
      emoji: "⛵",
      desc: "Ruhigerer Süden mit Olivenhainen, dem Achilleion-Palast und weniger touristisch geprägten Stränden.",
      highlights: ["Achilleion Palast", "Boukari Fischerdorf", "Kavos Party-Strand"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "25–55 €", mid: "60–140 €", luxury: "160–500 €+" },
    { label: "Essen (pro Tag)", budget: "12–22 €", mid: "28–55 €", luxury: "70–150 €+" },
    { label: "Transport (pro Tag)", budget: "4–8 € (Bus)", mid: "20–40 € (Scooter/Taxi)", luxury: "60–120 € (Mietwagen)" },
    { label: "Aktivitäten (pro Tag)", budget: "5–15 €", mid: "20–50 €", luxury: "80–200 €+" },
    { label: "Tagesbudget gesamt", budget: "50–100 €", mid: "130–285 €", luxury: "370–970 €+" },
  ],
  emergency: {
    police: "100",
    ambulance: "166",
    fire: "199",
    embassy: "+30 210 728 5111 (Deutsche Botschaft Athen)",
    hospital: "Allgemeines Krankenhaus Korfu: +30 26610 45811",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Korfu-Altstadt & venezianischer Abend",
      icon: "🏰",
      color: "bg-rose-100",
      dayCost: "~70 €",
      transport: "Zu Fuß",
      meals: "Taverna Ninos, Altstadt",
      stops: [
        { time: "09:30", activity: "Alte Festung – Panoramablick über die Stadt", icon: "🏰", tip: "Früh kommen – vor 10 Uhr fast allein." },
        { time: "11:30", activity: "Liston Promenade – Kaffee unter Arkaden", icon: "☕" },
        { time: "13:00", activity: "Mittagessen in der Altstadt", icon: "🍽️" },
        { time: "15:00", activity: "Museum für Asiatische Kunst (im Palast)", icon: "🎨" },
        { time: "20:00", activity: "Romantisches Abendessen in der Altstadt", icon: "🌃", tip: "Gasse Guilford Street – die schönsten Restaurants." },
      ],
    },
    {
      day: "Tag 2",
      title: "Paleokastritsa & geheime Buchten",
      icon: "🌊",
      color: "bg-sky-100",
      dayCost: "~80 €",
      transport: "Bus KTEL (2,40 €) oder Mietwagen",
      meals: "Taverna Paleokastritsa",
      stops: [
        { time: "09:00", activity: "Bus nach Paleokastritsa", icon: "🚌", tip: "Früh fahren – nachmittags sehr voll." },
        { time: "10:00", activity: "Motorboot mieten – geheime Buchten entdecken", icon: "🛥️" },
        { time: "12:30", activity: "Kloster Paleokastritsa", icon: "⛪" },
        { time: "14:00", activity: "Mittagessen mit Meeresfrüchten", icon: "🦐" },
        { time: "16:00", activity: "Angelokastro – byzantinische Festung", icon: "🏰" },
        { time: "19:30", activity: "Bella Vista – Sonnenuntergang über Buchten", icon: "🌅" },
      ],
    },
    {
      day: "Tag 3",
      title: "Achilleion & Südküste",
      icon: "👸",
      color: "bg-amber-100",
      dayCost: "~65 €",
      transport: "Mietwagen",
      meals: "Lokales Meeresfrüchterestaurant Benitses",
      stops: [
        { time: "10:00", activity: "Achilleion-Palast – Kaiserin Sisi's Schloss", icon: "🏛️" },
        { time: "12:30", activity: "Fahrt nach Benitses – kleines Fischerdorf", icon: "🚗" },
        { time: "13:30", activity: "Mittagessen mit frischem Fisch", icon: "🐟" },
        { time: "15:30", activity: "Boukari Strand – ruhig und kristallklar", icon: "🏖️" },
        { time: "19:00", activity: "Rückfahrt über die Westküste – Glyfada", icon: "🌅" },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Altstadt & Neue Festung",
      icon: "🏰",
      color: "bg-cyan-100",
      dayCost: "~70 € (Fam. 4)",
      transport: "Zu Fuß",
      meals: "Altstadt-Taverne",
      stops: [
        { time: "10:00", activity: "Alte Festung – Kinder als Ritter", icon: "🏰", tip: "Die Burgmauern und Kanonen begeistern alle Kinder." },
        { time: "12:30", activity: "Mittagessen am Liston", icon: "🍽️" },
        { time: "14:00", activity: "Neue Festung – Labyrinthische Gänge", icon: "🏰" },
        { time: "16:00", activity: "Arillas Beach – ruhiger Nordstrand", icon: "🏖️" },
        { time: "18:30", activity: "Gelato an der Spianada", icon: "🍦" },
      ],
    },
    {
      day: "Tag 2",
      title: "Wasserpark & Nordstrand",
      icon: "🎢",
      color: "bg-yellow-100",
      dayCost: "~130 € (Fam. 4)",
      transport: "Taxi / Bus",
      meals: "Wasserpark + Strandtaverne",
      stops: [
        { time: "10:00", activity: "Aqualand Korfu Wasserpark", icon: "🎢", tip: "Früh kommen – Schlangen wachsen ab 11 Uhr stark." },
        { time: "14:00", activity: "Mittagessen im Park", icon: "🍟" },
        { time: "16:00", activity: "Sidari Beach – Canal d'Amour", icon: "💕", tip: "Sehr flaches, warmes Wasser – ideal für Kinder." },
        { time: "18:30", activity: "Abendessen in Sidari", icon: "🍽️" },
      ],
    },
    {
      day: "Tag 3",
      title: "Paleokastritsa Bootsabenteuer",
      icon: "⛵",
      color: "bg-pink-100",
      dayCost: "~90 € (Fam. 4)",
      transport: "Bus + Motorboot",
      meals: "Strandtaverne Paleokastritsa",
      stops: [
        { time: "09:00", activity: "Bus nach Paleokastritsa", icon: "🚌" },
        { time: "10:00", activity: "Kleines Motorboot für die Familie mieten", icon: "🛥️", tip: "Kinder als Kapitäne – sie dürfen das Steuer halten." },
        { time: "12:30", activity: "Mittagessen am Strand", icon: "🍝" },
        { time: "14:30", activity: "Kloster Paleokastritsa – Schildkröten im Garten", icon: "🐢" },
        { time: "16:30", activity: "Schnorcheln in der Bucht", icon: "🤿" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Altstadt-Erkundung & Nachtleben",
      icon: "🚶",
      color: "bg-indigo-100",
      dayCost: "~35 €",
      transport: "Zu Fuß",
      meals: "Günstige Taverne in der Altstadt",
      stops: [
        { time: "08:30", activity: "Altstadt am frühen Morgen – venezianische Gassen", icon: "🌅" },
        { time: "10:00", activity: "Alte Festung", icon: "🏰" },
        { time: "12:30", activity: "Mittagessen: Sofrito in einem Souvlaki-Laden", icon: "🥩" },
        { time: "14:30", activity: "Museum für Asiatische Kunst", icon: "🎨" },
        { time: "17:00", activity: "Spaziergang entlang der Stadtmauern", icon: "🚶" },
        { time: "21:00", activity: "Diskothek oder Abendessen in Gardenbar", icon: "🎶" },
      ],
    },
    {
      day: "Tag 2",
      title: "Scooter-Tour durch Nordkorfu",
      icon: "🛵",
      color: "bg-orange-100",
      dayCost: "~50 €",
      transport: "Scooter (ab 18 €/Tag)",
      meals: "Agios Stefanos Taverne",
      stops: [
        { time: "09:00", activity: "Scooter mieten in Korfu-Stadt", icon: "🛵" },
        { time: "10:00", activity: "Kassiopi – venezianische Burgmauern", icon: "🏰" },
        { time: "12:00", activity: "Agios Stefanos – Mittagessen mit frischem Fang", icon: "🐟" },
        { time: "14:00", activity: "Sidari Canal d'Amour – kurzes Bad", icon: "💕" },
        { time: "16:00", activity: "Rodoula Beach – geheimer Nordstrand", icon: "🏖️" },
        { time: "19:00", activity: "Rückfahrt durch Olivenwälder", icon: "🌿" },
      ],
    },
    {
      day: "Tag 3",
      title: "Paleokastritsa solo & Wandern",
      icon: "🥾",
      color: "bg-teal-100",
      dayCost: "~40 €",
      transport: "Bus + Zu Fuß",
      meals: "Taverne in Makrades",
      stops: [
        { time: "08:30", activity: "Frühbus nach Paleokastritsa", icon: "🚌", tip: "Allein um 9 Uhr im Wasser – ein unvergessliches Erlebnis." },
        { time: "09:30", activity: "Schwimmen in der leeren Hauptbucht", icon: "🏊" },
        { time: "11:30", activity: "Wanderung zum Angelokastro (45 Min.)", icon: "🥾" },
        { time: "13:30", activity: "Mittagessen im Dorf Makrades", icon: "🍽️" },
        { time: "15:00", activity: "Bella Vista – Aussicht über die Buchten", icon: "🌅" },
        { time: "17:00", activity: "Bus zurück nach Korfu-Stadt", icon: "🚌" },
      ],
    },
  ],
};

export default content;
