import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🌧️", text: "Ruhige Nebensaison mit 15 °C und gelegentlichem Regen. Museen ohne Warteschlangen, günstige Hotels und authentisches Lissabon-Feeling." },
    { label: "Februar",   emoji: "🌸", text: "Karneval in der Stadt! Mandelbäume blühen im Alentejo. Kühle 16 °C, kaum Touristen." },
    { label: "März",      emoji: "🌿", text: "Frühling erwacht, erste sonnige Tage. Ideale Zeit für Miradouro-Besuche und lange Tram-28-Fahrten." },
    { label: "April",     emoji: "🌼", text: "Freiheitstag am 25. April (Nelkenrevolution 1974) wird gefeiert. Vorsaison mit angenehmen 20 °C." },
    { label: "Mai",       emoji: "☀️", text: "Traumhaftes Klima um 23 °C. Terrassenrestaurants öffnen, Touristenzahlen steigen mäßig." },
    { label: "Juni",      emoji: "🎉", text: "Santos Populares – Lissabons größtes Straßenfest zu Ehren des Heiligen Antonius (12.–13. Juni). Sardinengrill und Fado bis in die Nacht." },
    { label: "Juli",      emoji: "🔆", text: "Hochsaison: Heiß bis 30 °C, aber selten schwül. Große Menschenmassen in Alfama. Früh aufstehen lohnt sich." },
    { label: "August",    emoji: "🏖️", text: "Viele Einheimische reisen nach Cascais oder Setúbal. Touristisch voll, aber Strände der Riviera sind in 30 Min. erreichbar." },
    { label: "September", emoji: "🍷", text: "Weinlese in der Region. Angenehme 25 °C, weniger Massen. Ideale Zeit für Ausflüge nach Sintra und Óbidos." },
    { label: "Oktober",   emoji: "🌤️", text: "Goldener Oktober – oft noch Badewetter, günstigere Preise und sanfte Beleuchtung für Fotos." },
    { label: "November",  emoji: "🎶", text: "Fado-Saison: Kleinere Casa de Fado öffnen wieder. Nebel und Melancholie passen perfekt zur Saudade." },
    { label: "Dezember",  emoji: "🎄", text: "Weihnachtsbeleuchtung in der Baixa. Traditionelle Adventskonzerte in den Kirchen. Mild um 14 °C." },
  ],
  sights: [
    {
      title: "Alfama & Miradouro da Graça",
      desc: "Das älteste Viertel Lissabons, maurischen Ursprungs, mit engen Gassen, bunten Kachelhäusern und dem schönsten Aussichtspunkt der Stadt. Vom Miradouro da Graça überblickt man ganz Lissabon und den Tejo.",
      mapHref: "https://maps.google.com/?q=Miradouro+da+Graca+Lissabon",
      address: "Largo da Graça, Alfama, Lissabon",
      duration: "3–4 Std.",
      cost: "Kostenlos",
      tip: "Donnerstagvormittag: Alfama-Flohmarkt Feira da Ladra – perfekt für Azulejo-Funde.",
    },
    {
      title: "Kloster Jerónimos",
      desc: "Das beeindruckendste Baudenkmal Portugals und UNESCO-Welterbe. Das manuelinische Kloster wurde 1502 unter König Manuel I. erbaut und ist das Meisterwerk des sogenannten Manuelino-Stils – portugiesische Spätgotik mit Seefahrer-Motiven.",
      mapHref: "https://maps.google.com/?q=Mosteiro+dos+Jeronimos+Lissabon",
      address: "Praça do Império, Belém, Lissabon",
      duration: "1,5–2 Std.",
      cost: "10 € (Kirche kostenlos)",
      tip: "Direkt daneben liegt die Original-Pastelaria de Belém – Schlange anstellen lohnt sich.",
    },
    {
      title: "Tram 28 – Historische Straßenbahn",
      desc: "Die gelbe Straßenbahn Nr. 28 verbindet Martim Moniz mit Prazeres und durchquert dabei Alfama, Graça und Estrela. Nicht nur Transport – eine Reise durch die Geschichte der Stadt.",
      mapHref: "https://maps.google.com/?q=Tram+28+Lissabon",
      address: "Rua Martim Moniz bis Campo de Ourique",
      duration: "45 Min. (eine Fahrt)",
      cost: "3 € (Einzelticket)",
      tip: "Früh morgens ab 8 Uhr einsteigen – zu touristischen Zeiten ist die Tram überfüllt und Taschendiebstahl ein Problem.",
    },
    {
      title: "Belém-Turm & Denkmal der Entdeckungen",
      desc: "Der manuelinische Belém-Turm (UNESCO) wachte einst über den Eingang zum Tejo. Gegenüber das 52 m hohe Denkmal der Entdeckungen zeigt Vasco da Gama, Magellan und andere Seefahrer-Helden Portugals.",
      mapHref: "https://maps.google.com/?q=Torre+de+Belem",
      address: "Avenida Brasília, Belém, Lissabon",
      duration: "1,5 Std. (beide Monumente)",
      cost: "Turm 6 €, Denkmal 6 €",
      tip: "Frühmorgens kommen – ab 10 Uhr lange Schlangen. Kombiniertes Ticket spart Geld.",
    },
    {
      title: "Sintra – Palast und Märchenwald",
      desc: "UNESCO-Kulturlandschaft 30 km von Lissabon entfernt. Der Palácio da Pena auf einem bewaldeten Fels und der geheimnisvolle Nationalpalast von Sintra sind Portugals bekannteste Sehenswürdigkeiten.",
      mapHref: "https://maps.google.com/?q=Pena+Palace+Sintra",
      address: "Estrada da Pena, Sintra",
      duration: "Ganztag",
      cost: "Palácio da Pena 14 €",
      tip: "Per Zug ab Rossio (40 Min., 2,25 €). Früh losfahren – Burg wird sehr voll.",
    },
  ],
  history: [
    {
      year: "205 v. Chr.",
      title: "Römische Gründung von Olisipo",
      text: "Die Römer befestigten die phönizische Handelssiedlung auf dem Tejo-Hügel und nannten sie Olisipo. Die Stadt wurde zur wichtigsten römischen Kolonie auf der Iberischen Halbinsel westlich des Flusses Tagus.",
    },
    {
      year: "714",
      title: "Arabische Herrschaft – al-Ushbuna",
      text: "Mauren aus Nordafrika eroberten die Stadt und nannten sie al-Ushbuna. Für über 400 Jahre prägten arabische Kultur, Architektur und Ortsnamen die Stadt. Das Viertel Alfama ist moorischen Ursprungs.",
    },
    {
      year: "1147",
      title: "Reconquista – König Afonso I.",
      text: "Der erste König Portugals, Afonso Henriques, belagerte Lissabon mit Hilfe der Kreuzritter und befreite die Stadt von den Mauren. 1255 wurde Lissabon zur Hauptstadt Portugals ernannt.",
    },
    {
      year: "1498",
      title: "Zeitalter der Entdeckungen",
      text: "Vasco da Gama segelte von Belém aus nach Indien und fand den Seeweg. Portugal wurde zur führenden Seemacht der Welt. Lissabon wurde zum Zentrum des Welthandels mit Gewürzen, Gold und Sklaven.",
    },
    {
      year: "1755",
      title: "Großes Erdbeben von Lissabon",
      text: "Am Allerheiligentag 1755 zerstörte ein Erdbeben der Stärke 8,5–9 gefolgt von Tsunami und Feuer 80 % der Stadt und tötete 30.000–100.000 Menschen. Marquis de Pombal baute die Baixa systematisch wieder auf.",
    },
    {
      year: "1974",
      title: "Nelkenrevolution",
      text: "Am 25. April 1974 beendete eine gewaltlose Militärrevolution die 48-jährige Salazar-Diktatur. Soldaten steckten rote Nelken in ihre Gewehrläufe – seither Symbol der Freiheit und des Nationalfeiertags.",
    },
  ],
  food: [
    {
      emoji: "🥐",
      name: "Pastel de Nata",
      original: "Pastel de Nata",
      desc: "Das ikonischste Gebäck Portugals: knuspriger Blätterteig mit cremiger Puddingtarte, oben leicht karamellisiert. Warm mit Zimt und Puderzucker bestäubt – ein Muss in Lissabon.",
      price: "1,20–1,80 €",
      tip: "Pastelaria de Belém (Original seit 1837) vs. Manteigaria in der Chiado – beide sind legendär.",
    },
    {
      emoji: "🐟",
      name: "Bacalhau à Brás",
      original: "Bacalhau à Brás",
      desc: "Gesalzener Kabeljau mit feinen Strohkartoffeln, Eiern und Oliven. Bacalhau (Kabeljau) ist das Nationalgericht Portugals – angeblich 365 verschiedene Rezepte, eines für jeden Tag.",
      price: "12–20 €",
    },
    {
      emoji: "🐙",
      name: "Polvo à Lagareiro",
      original: "Polvo à Lagareiro",
      desc: "Oktopus im Ofen mit Olivenöl, Knoblauch und Kartoffeln überbacken. Das beste Oktopusgericht Portugals – zartes Fleisch, krosse Außenhaut.",
      price: "16–24 €",
      tip: "Im Viertel Alfama die besten Oktopusrestaurants: Zé da Mouraria oder O Velho Eurico.",
    },
    {
      emoji: "🥩",
      name: "Francesinha",
      original: "Francesinha",
      desc: "Das portugiesische Nationaltoast aus Porto – aber auch in Lissabon erhältlich: gegrilltes Schweinefleisch, Wurst und Schinken zwischen Toast, mit Käse überbacken und in scharf-würziger Tomatenbiersoße schwimmend.",
      price: "10–16 €",
    },
    {
      emoji: "🍷",
      name: "Ginjinha",
      original: "Ginjinha",
      desc: "Süßer Sauerkirschlikör – das Wahrzeichen Lissabons. In kleinen Bars an der Praça de São Domingos steht man am Tresen und trinkt einen oder zwei aus einem Schokoladenbecher.",
      price: "1,50–2 €",
      tip: "A Ginjinha oder Sem Rival nahe Rossio – seit dem 19. Jahrhundert das Original.",
    },
  ],
  phrases: [
    { original: "Olá!", pronunciation: "o-la", translation: "Hallo!" },
    { original: "Bom dia / Boa tarde", pronunciation: "bom di-a / bo-a tar-dʒ", translation: "Guten Morgen / Guten Tag" },
    { original: "Por favor", pronunciation: "pur fa-vor", translation: "Bitte" },
    { original: "Obrigado / Obrigada", pronunciation: "o-bri-ga-du / o-bri-ga-da", translation: "Danke (Mann / Frau)" },
    { original: "Quanto custa?", pronunciation: "kwan-tu kush-ta", translation: "Was kostet das?" },
    { original: "A conta, por favor", pronunciation: "a kon-ta pur fa-vor", translation: "Die Rechnung, bitte" },
    { original: "Onde é a estação?", pronunciation: "on-dʒ e a ish-ta-saun", translation: "Wo ist der Bahnhof?" },
    { original: "Uma imperial, por favor", pronunciation: "u-ma im-pe-ri-al pur fa-vor", translation: "Ein Bier vom Fass, bitte" },
    { original: "Preciso de um médico", pronunciation: "pre-si-zu dʒ um me-di-ku", translation: "Ich brauche einen Arzt" },
    { original: "Até logo!", pronunciation: "a-te lo-gu", translation: "Auf Wiedersehen!" },
  ],
  insider: [
    {
      icon: "🚡",
      title: "Electrico 28 vs. Ascensor de Bica",
      text: "Statt der überfüllten Tram 28 die Ascensor da Bica oder Elevador da Glória nehmen – steilste Seilbahnen der Stadt für nur 3,90 €. Authentischer und weniger Taschendiebstahl-Risiko.",
    },
    {
      icon: "🌅",
      title: "Miradouro da Graça statt Portas do Sol",
      text: "Der Miradouro da Graça ist unter Touristen weniger bekannt, hat aber den besseren Blick auf Alfama und den Tejo. Abends kommen Lissabonner mit Bier und Gitarre – gratis und herzlich.",
    },
    {
      icon: "🎶",
      title: "Echter Fado in kleinen Casas",
      text: "Fado-Shows in Touristen-Restaurants kosten 30–50 € inkl. Essen. Echten Fado in kleinen Casas wie Tasca do Chico oder Mesa de Frades erlebt man für 10–15 € Mindestkonsum – das Authentischste.",
    },
    {
      icon: "🍊",
      title: "LX Factory am Sonntag",
      text: "Die LX Factory in Alcântara verwandelt sich sonntags in einen Kreativmarkt mit Designer-Ständen, Vintage-Mode und dem weltbekannten Ler Devagar Buchladen – keine Eintrittsgebühr.",
    },
    {
      icon: "🚌",
      title: "Carris-Netz statt Tuk-Tuk",
      text: "Ein 24-Stunden-Ticket für Bus, Metro und Tram kostet 6,60 €. Tuk-Tuks sind überbewertet und teuer (15–30 € für 20 Min.). Mit dem Carris-Netz kommt man überall hin.",
    },
  ],
  beaches: [
    {
      name: "Praia de Cascais",
      emoji: "🏖️",
      desc: "Eleganter Badeort 30 km von Lissabon entfernt, per Zug in 40 Minuten erreichbar. Sandstrand, historische Altstadt und der beste Fisch an der Küste.",
      type: "Sandstrand / Badeort",
      tip: "Zug ab Cais do Sodré – direkte Verbindung alle 30 Minuten.",
    },
    {
      name: "Praia de Setúbal",
      emoji: "🌊",
      desc: "Naturschutzgebiet der Arrábida-Küste mit türkisblauem Wasser und weißen Kalkfelsen – einer der schönsten Strände Europas.",
      type: "Naturstrand / Felsenküste",
      tip: "Auto nötig oder organisierte Touren ab Lissabon.",
    },
    {
      name: "Praia de Sesimbra",
      emoji: "🐟",
      desc: "Malerisches Fischerdorf mit mondförmiger Bucht und ruhigem Wasser. Ideal für Familien und Schnorchler.",
      type: "Fischereibucht",
    },
    {
      name: "Praia de Costa da Caparica",
      emoji: "🏄",
      desc: "30 km Sandstrand südlich des Tejo. Beliebtester Surf- und Badestrand der Lissabonner – per Fähre und Bus erreichbar.",
      type: "Surfstrand",
      tip: "Fähre ab Cais do Sodré nach Cacilhas, dann Bus – günstigste Route.",
    },
    {
      name: "Praia Grande (Sintra)",
      emoji: "🌿",
      desc: "Wilder atlantischer Strand bei Sintra mit Wellen und unberührter Natur. Bekannt für Fossilien in den Klippen.",
      type: "Wilder Atlantikstrand",
    },
  ],
  regions: [
    {
      name: "Alfama & Mouraria",
      emoji: "🎶",
      desc: "Das älteste und authentischste Viertel – Fado, Kachelfassaden, enge Gassen und das maurische Erbe der Stadt.",
      highlights: ["Miradouro da Graça", "Castelo de São Jorge", "Feira da Ladra"],
    },
    {
      name: "Chiado & Bairro Alto",
      emoji: "📚",
      desc: "Das kulturelle Herz Lissabons mit eleganten Cafés, Theatern, Buchläden und dem besten Nachtleben.",
      highlights: ["Livraria Bertrand", "Café A Brasileira", "Bairro Alto Nachtleben"],
    },
    {
      name: "Belém",
      emoji: "⛵",
      desc: "Das historische Viertel der Entdecker mit UNESCO-Monumenten, Museen und dem Original-Pastel-de-Nata.",
      highlights: ["Kloster Jerónimos", "Belém-Turm", "Pastelaria de Belém"],
    },
    {
      name: "LX Factory & Alcântara",
      emoji: "🎨",
      desc: "Lissabons kreatives Viertel mit Street Art, Designerläden, Restaurants und dem legendären Sonntagsmarkt.",
      highlights: ["LX Factory", "Ler Devagar Buchladen", "Ponte 25 de Abril"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "30–60 €", mid: "70–150 €", luxury: "180–450 €+" },
    { label: "Essen (pro Tag)", budget: "12–20 €", mid: "25–50 €", luxury: "70–150 €+" },
    { label: "Transport (pro Tag)", budget: "3–7 € (Metro/Tram)", mid: "15–30 € (Taxi/Uber)", luxury: "50–100 €" },
    { label: "Aktivitäten (pro Tag)", budget: "5–15 €", mid: "20–50 €", luxury: "80–180 €+" },
    { label: "Tagesbudget gesamt", budget: "55–105 €", mid: "130–280 €", luxury: "380–900 €+" },
  ],
  emergency: {
    police: "112",
    ambulance: "112",
    fire: "112",
    embassy: "+351 21 810 1000 (Deutsche Botschaft Lissabon)",
    hospital: "Hospital de Santa Maria: +351 21 780 5000",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Alfama, Fado & Ginjinha",
      icon: "🎶",
      color: "bg-rose-100",
      dayCost: "~70 €",
      transport: "Tram 28 / Zu Fuß",
      meals: "Tasca do Chico (Fado-Restaurant)",
      stops: [
        { time: "09:30", activity: "Alfama zu Fuß erkunden – früh & leer", icon: "🚶", tip: "Die Gassen Rua das Escolas Gerais und Beco dos Armazéns." },
        { time: "11:00", activity: "Miradouro da Graça – Panorama-Blick", icon: "🌅" },
        { time: "13:00", activity: "Mittagessen: Bacalhau à Brás in der Alfama", icon: "🐟" },
        { time: "15:30", activity: "Tram 28 bis Belém", icon: "🚃" },
        { time: "17:00", activity: "Abendessen & Fado in Tasca do Chico", icon: "🎶", tip: "Reservierung Wochen im Voraus – nur 20 Plätze." },
      ],
    },
    {
      day: "Tag 2",
      title: "Belém & Tejo-Spaziergang",
      icon: "⛵",
      color: "bg-sky-100",
      dayCost: "~60 €",
      transport: "Bus 727 ab Cais do Sodré",
      meals: "Restaurante Vela Latina, Belém",
      stops: [
        { time: "09:30", activity: "Pastelaria de Belém – frische Pastéis", icon: "🥐", tip: "Früh kommen, um Warteschlange zu vermeiden." },
        { time: "10:30", activity: "Kloster Jerónimos", icon: "🏛️" },
        { time: "12:30", activity: "Tejo-Uferpromenade spazieren", icon: "🌊" },
        { time: "14:00", activity: "Mittagessen mit Tejoblick", icon: "🍽️" },
        { time: "16:00", activity: "Belém-Turm & Denkmal der Entdeckungen", icon: "🗺️" },
        { time: "19:00", activity: "Sundowner mit Blick auf Ponte 25 de Abril", icon: "🌅" },
      ],
    },
    {
      day: "Tag 3",
      title: "Sintra – Märchenpärchen-Tag",
      icon: "🏰",
      color: "bg-emerald-100",
      dayCost: "~80 €",
      transport: "Zug ab Rossio (40 Min.)",
      meals: "Saudade Restaurant, Sintra",
      stops: [
        { time: "08:30", activity: "Frühzug nach Sintra ab Rossio", icon: "🚂" },
        { time: "09:30", activity: "Palácio da Pena – buntes Märchenschloss", icon: "🏰", tip: "Früh kommen – bei Öffnung um 9:30 Uhr fast menschenleer." },
        { time: "12:00", activity: "Nationalpalast Sintra – gotisch-maurisch", icon: "🕌" },
        { time: "14:00", activity: "Mittagessen in der Sintra-Altstadt", icon: "🍷" },
        { time: "16:00", activity: "Praia Grande – romantischer Atlantikstrand", icon: "🌊" },
        { time: "19:30", activity: "Rückzug nach Lissabon", icon: "🚂" },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Ozean-Museum & Belém",
      icon: "🦈",
      color: "bg-cyan-100",
      dayCost: "~100 € (Fam. 4)",
      transport: "Bus 727",
      meals: "Pastéis de Belém + Tejo-Restaurant",
      stops: [
        { time: "09:30", activity: "Pastéis de Belém – Morgensnack", icon: "🥐" },
        { time: "10:30", activity: "Oceanarium Lissabon (Parque das Nações)", icon: "🦈", tip: "Eines der besten Aquarien Europas – Kinder lieben die Haifisch-Tanks." },
        { time: "13:30", activity: "Mittagessen im Parque das Nações", icon: "🍽️" },
        { time: "15:00", activity: "Kloster Jerónimos – Kinder können Kreuzgang erkunden", icon: "🏛️" },
        { time: "17:00", activity: "Belém-Turm – Ritterburg für Kinder", icon: "🏰" },
      ],
    },
    {
      day: "Tag 2",
      title: "Sintra Märchenschloss",
      icon: "🏰",
      color: "bg-yellow-100",
      dayCost: "~90 € (Fam. 4)",
      transport: "Zug ab Rossio",
      meals: "Sintra Altstadt",
      stops: [
        { time: "08:30", activity: "Zug nach Sintra", icon: "🚂" },
        { time: "09:30", activity: "Palácio da Pena – Fantasieschloss", icon: "🏰", tip: "Kinder lieben die bunten Türme und das Labyrinth des Waldes." },
        { time: "12:30", activity: "Mittagessen + Gelados (Eis) in Sintra", icon: "🍦" },
        { time: "14:30", activity: "Castelo dos Mouros – Mauerkletterei", icon: "🏔️", tip: "Ältere Kinder lieben die Zinnenmauern hoch über den Wäldern." },
        { time: "17:30", activity: "Rückzug nach Lissabon", icon: "🚂" },
      ],
    },
    {
      day: "Tag 3",
      title: "Strand & Cascais",
      icon: "🏖️",
      color: "bg-pink-100",
      dayCost: "~60 € (Fam. 4)",
      transport: "Zug ab Cais do Sodré",
      meals: "Cascais Hafenrestaurant",
      stops: [
        { time: "09:30", activity: "Zug nach Cascais (40 Min.)", icon: "🚂" },
        { time: "10:30", activity: "Praia de Cascais – Sandschlösser & Schwimmen", icon: "🏖️" },
        { time: "13:00", activity: "Mittagessen mit frischem Fisch am Hafen", icon: "🐟" },
        { time: "15:00", activity: "Stadtbummel Cascais – Marktplatz & Eis", icon: "🍦" },
        { time: "17:00", activity: "Boca do Inferno – dramatische Felsküste", icon: "🌊", tip: "Ungefährliche Aussicht auf Klippen und tosende Wellen." },
        { time: "19:00", activity: "Rückzug nach Lissabon", icon: "🚂" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Alfama solo erkunden",
      icon: "🚶",
      color: "bg-indigo-100",
      dayCost: "~35 €",
      transport: "Zu Fuß / Tram",
      meals: "Mercado da Ribeira (Time Out Market)",
      stops: [
        { time: "08:00", activity: "Alfama bei Sonnenaufgang – fast allein", icon: "🌅", tip: "Die besten Fotos entstehen um 8 Uhr – keine Touristenmassen." },
        { time: "10:00", activity: "Castelo de São Jorge", icon: "🏰" },
        { time: "12:30", activity: "Time Out Market – günstigstes Gourmet-Erlebnis", icon: "🍽️" },
        { time: "14:30", activity: "Chiado & Bairro Alto – Buchladen Bertrand", icon: "📚" },
        { time: "17:00", activity: "Ginjinha an der Praça de São Domingos", icon: "🍒" },
        { time: "21:00", activity: "Bairro Alto – kleines Fado-Café", icon: "🎶" },
      ],
    },
    {
      day: "Tag 2",
      title: "Museen & Kreativviertel",
      icon: "🎨",
      color: "bg-teal-100",
      dayCost: "~45 €",
      transport: "Metro + Bus",
      meals: "LX Factory",
      stops: [
        { time: "10:00", activity: "Museu Nacional do Azulejo – Kachelmuseum", icon: "🔷", tip: "Pflichtbesuch – die Azulejo-Kunst ist Lissabons DNA." },
        { time: "12:30", activity: "LX Factory – Sonntagsmarkt & Essen", icon: "🛍️" },
        { time: "14:30", activity: "Ler Devagar Buchladen – berühmtester Buchladen", icon: "📖" },
        { time: "16:00", activity: "Museu de Arte Antiga", icon: "🖼️" },
        { time: "19:00", activity: "Sundowner am Tejo im PARK Bar (Bairro Alto)", icon: "🌅" },
      ],
    },
    {
      day: "Tag 3",
      title: "Tagestour Sintra & Küste",
      icon: "🌊",
      color: "bg-orange-100",
      dayCost: "~50 €",
      transport: "Zug",
      meals: "Unterwegs",
      stops: [
        { time: "07:30", activity: "Frühzug nach Sintra", icon: "🚂" },
        { time: "09:00", activity: "Palácio da Pena & Park erkunden", icon: "🏰" },
        { time: "12:00", activity: "Mittagessen in Sintra-Altstadt", icon: "🍽️" },
        { time: "14:00", activity: "Praia Grande – atlantische Wellen", icon: "🌊" },
        { time: "17:00", activity: "Cabo da Roca – Westlichster Punkt Europas", icon: "🌍", tip: "Das Kap markiert das Ende Europas – beeindruckende Klippen." },
        { time: "19:30", activity: "Rückzug nach Lissabon", icon: "🚂" },
      ],
    },
  ],
};

export default content;
