import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🏛️", text: "Kühl und ruhig – ideal für Kulturbesuche in der Altstadt ohne Touristenandrang." },
    { label: "Februar",   emoji: "🌿", text: "Erste Frühlingsblüher. Wanderungen im Inneren der Insel bei angenehmen Temperaturen." },
    { label: "März",      emoji: "🌸", text: "Mandelblüte und aufblühende Landschaft. Perfekt für Sightseeing und Aktivurlaub." },
    { label: "April",     emoji: "📸", text: "Vorsaison: Altstadt ohne Menschenmassen, angenehme 20 °C, günstige Preise." },
    { label: "Mai",       emoji: "🏖️", text: "Badesaison beginnt, 24 °C Wassertemperatur. Ideal für Schnorcheln und Wandern." },
    { label: "Juni",      emoji: "⛵", text: "Hochsaison beginnt. Bootstouren zur Lindos-Bucht besonders schön." },
    { label: "Juli",      emoji: "☀️", text: "Heißester Monat, 35+ °C. Früh aufstehen, mittags in den Schatten." },
    { label: "August",    emoji: "🌊", text: "Hochsommer mit Meltemi-Wind – zum Surfen ideal, aber für Landausflüge heiß." },
    { label: "September", emoji: "🌅", text: "Noch warm (29 °C), deutlich ruhiger. Die beste Zeit auf Rhodos." },
    { label: "Oktober",   emoji: "🏞️", text: "Herbstfarben im Inselinneren, angenehme 25 °C, letztes Badewetter." },
    { label: "November",  emoji: "🌧️", text: "Erste Regentage, Insel erholt sich. Kulturbegeisterte kommen jetzt auf ihre Kosten." },
    { label: "Dezember",  emoji: "☕", text: "Ruhige Winterzeit. Weihnachtsstimmung in Rhodos-Stadt mit Lichtern und Märkten." },
  ],
  sights: [
    { title: "Mittelalterliche Altstadt von Rhodos", desc: "Eine der am besten erhaltenen mittelalterlichen Städte der Welt, seit 1988 UNESCO-Welterbe. Die Ritter-Stadtmauer, die Ritterstraße und der Palace of the Grand Master sind die Highlights.", mapHref: "https://maps.google.com/?q=Altstadt+Rhodos", address: "Rhodos-Stadt", duration: "3–4 Std.", cost: "Kostenlos (Palast 6 €)", tip: "Abends beleuchtet besonders magisch. Die Gassen um die Mitternacht genießen." },
    { title: "Akropolis von Lindos", desc: "Hoch auf einem Felsen über dem türkisfarbenen Meer thronende antike Festung mit Tempel der Athena Lindia. Der Blick auf die Lindos-Bucht ist einer der schönsten Griechenlands.", mapHref: "https://maps.google.com/?q=Akropolis+Lindos+Rhodos", address: "Lindos, Rhodos", duration: "2–3 Std.", cost: "12 €", tip: "Sehr früh morgens oder abends gehen – tagsüber extreme Hitze auf den Treppen." },
    { title: "Antike Stadt Kamiros", desc: "Wenig bekannte antike Ruinenstadt im Westen der Insel, bedeutend weniger überlaufen als Lindos. Die gut erhaltenen Strukturen zeigen das Leben der Röderzeit.", mapHref: "https://maps.google.com/?q=Kamiros+Rhodos", address: "Kamiros, Westrhodos", duration: "1–2 Std.", cost: "6 €", tip: "Authentischer Geheimtipp mit kaum Touristen." },
    { title: "Anthony Quinn Bay", desc: "Berühmte Bucht, benannt nach dem Schauspieler, der hier für 'Alexis Sorbas' drehte und so von dem Ort begeistert war, dass er ihn kaufen wollte. Kristallklares Wasser und Schnorchelparadies.", mapHref: "https://maps.google.com/?q=Anthony+Quinn+Bay+Rhodos", address: "Ladiko, Rhodos", duration: "Halbtag", cost: "Kostenlos", tip: "Sehr klein – früh morgens kommen für einen guten Platz." },
    { title: "Schmetterlingstal (Valle delle Farfalle)", desc: "Natürliches Naturschutzgebiet, in dem sich von Juni bis September Tausende Jersey-Tiger-Schmetterlinge sammeln. Ein einzigartiges Naturschauspiel mitten im Wald.", mapHref: "https://maps.google.com/?q=Schmetterlingstal+Rhodos", address: "Petaloudes, Rhodos", duration: "1–2 Std.", cost: "5 €", tip: "Von Mitte Juli bis Mitte September am beeindruckendsten." },
  ],
  history: [
    { year: "408 v. Chr.", title: "Gründung von Rhodos-Stadt", text: "Die drei Stadtstaaten Ialysos, Kamiros und Lindos vereinten sich zur neuen Hauptstadt Rhodos. Der Stadtplan mit Rasterstruktur stammte vom Stadtplaner Hippodamos von Milet." },
    { year: "292 v. Chr.", title: "Der Koloss von Rhodos", text: "Der Bronze-Koloss des Helios – eines der Sieben Weltwunder der Antike – wurde errichtet. Er soll 33 m hoch gewesen sein. Schon 226 v. Chr. wurde er durch ein Erdbeben zerstört." },
    { year: "1309", title: "Johanniterritter übernehmen Rhodos", text: "Der Johanniterorden, aus dem Heiligen Land vertrieben, machte Rhodos zu seiner Festung. Sie bauten die noch heute sichtbare Stadtmauer und regierten 213 Jahre." },
    { year: "1522", title: "Osmanische Eroberung", text: "Suleiman der Prächtige belagerte Rhodos mit 200.000 Mann. Nach sechs Monaten kapitulierten die 7.000 Ritter ehrenvoll und verließen die Insel. Für 390 Jahre blieb Rhodos osmanisch." },
    { year: "1912–1947", title: "Italienische Herrschaft & Befreiung", text: "Im Italo-Türkischen Krieg wurde Rhodos von Italien besetzt. Viele Jugendstil-Bauten stammen aus dieser Zeit. 1947 vereinte sich Rhodos mit Griechenland." },
    { year: "1988", title: "UNESCO-Weltkulturerbe", text: "Die mittelalterliche Altstadt von Rhodos wurde wegen ihrer außergewöhnlich gut erhaltenen Ritter-Architektur in die UNESCO-Welterbeliste aufgenommen." },
  ],
  food: [
    { emoji: "🥗", name: "Pitaroudia", original: "Πιταρούδια", desc: "Knusprige Kichererbsen-Fritter mit Kräutern – das typische Streetfood von Rhodos. Als Vorspeise oder Snack überall erhältlich.", price: "3–6 €" },
    { emoji: "🍤", name: "Loukoumades", original: "Λουκουμάδες", desc: "Griechische Honig-Donut-Bällchen, frisch frittiert mit Honig, Zimt und Walnüssen. Das beliebteste Dessert auf Rhodos.", price: "4–6 €", tip: "Im alten Markt gibt es die besten." },
    { emoji: "🐙", name: "Oktopus vom Grill", original: "Χταπόδι σχαρας", desc: "Frisch gegrillter Oktopus, auf Holzkohle zubereitet. An jedem Hafen ein Anblick – und ein Geschmackserlebnis.", price: "10–18 €" },
    { emoji: "🧀", name: "Graviera-Käse", original: "Γραβιέρα", desc: "Harter, leicht süßlicher Schafskäse aus der Region. Als Saganaki frittiert oder pur mit Honig und Walnüssen.", price: "6–10 €" },
    { emoji: "🍷", name: "Rhoditiko-Wein", original: "Ροδίτικο κρασί", desc: "Lokaler Wein aus der Muscat Alexandria-Traube. Der süße Weiß- und Roséwein passt perfekt zu Meeresfrüchten.", price: "3–5 € (Glas)" },
  ],
  phrases: [
    { original: "Γεια σου! (Yeia sou!)", pronunciation: "jɑ su", translation: "Hallo! (informell)" },
    { original: "Καλημέρα (Kaliméra)", pronunciation: "kali-mera", translation: "Guten Morgen!" },
    { original: "Ευχαριστώ (Efcharistó)", pronunciation: "ef-charis-to", translation: "Danke" },
    { original: "Παρακαλώ (Parakaló)", pronunciation: "para-kalo", translation: "Bitte / Gern geschehen" },
    { original: "Πόσο κάνει; (Póso káni?)", pronunciation: "poso kani", translation: "Was kostet das?" },
    { original: "Τον λογαριασμό (Ton logariasmó)", pronunciation: "ton log-arjasmo", translation: "Die Rechnung" },
    { original: "Ναι / Όχι (Nai / Óchi)", pronunciation: "ne / ohi", translation: "Ja / Nein" },
    { original: "Χρειάζομαι γιατρό (Chriázomai jatró)", pronunciation: "chrjazome jatro", translation: "Ich brauche einen Arzt" },
    { original: "Στην υγειά σου! (Stin igiá sou!)", pronunciation: "stin igia su", translation: "Auf deine Gesundheit! (Prost!)" },
    { original: "Αντίο! (Andío!)", pronunciation: "an-dio", translation: "Tschüss!" },
  ],
  insider: [
    { icon: "🌙", title: "Altstadt nach Mitternacht", text: "Die Ritter-Altstadt leert sich gegen 22 Uhr. Spaziere danach allein durch die beleuchteten Gassen – ein magisches Erlebnis, völlig kostenlos und unvergesslich." },
    { icon: "⛵", title: "Kaik-Boote nach Symi statt Linienferries", text: "Kleine traditionelle Holzboote (Kaiken) fahren günstiger und gemütlicher als Linienferries zur Insel Symi. Einheimische bevorzugen sie." },
    { icon: "🏖️", title: "Tsambika Strand früh morgens", text: "Einer der schönsten Strände Griechenlands – aber bis 9 Uhr fast menschenleer. Parkplatz kostenlos, Liegen noch frei." },
    { icon: "🍽️", title: "Keine Touristenfallen – in die Nebenstraßen", text: "Restaurants direkt am Hauptplatz der Altstadt sind bis zu 40 % teurer. Zwei Straßen weiter isst man das gleiche Essen zum halben Preis." },
    { icon: "🛵", title: "Scooter statt Auto", text: "Auf Rhodos ist ein Moped die beste Art sich fortzubewegen – günstiger als Mietauto (ab 15 €/Tag), flexibler und man findet überall Parkplätze." },
  ],
  beaches: [
    { name: "Tsambika Beach", emoji: "🏖️", desc: "Goldener Sandstrand im Nordosten, kristallklares Wasser, ideal für Familien.", type: "Sandstrand", tip: "Früh kommen – einer der bekanntesten Strände." },
    { name: "Anthony Quinn Bay", emoji: "🤿", desc: "Kleine Felsbucht mit glasklarem Wasser, ideal zum Schnorcheln.", type: "Felsenbucht" },
    { name: "Faliraki Beach", emoji: "🎉", desc: "Langer Sandstrand mit vielen Wassersportmöglichkeiten und Nachtleben.", type: "Sandstrand" },
    { name: "Lindos Beach", emoji: "🌊", desc: "Geschützter Strand direkt unter der Akropolis – unvergesslicher Anblick.", type: "Sandstrand", tip: "Vom Dorf Lindos mit dem Esel hinauf zur Akropolis – oder zu Fuß." },
    { name: "Prasonisi", emoji: "🏄", desc: "Halbinsel an der Südspitze der Insel – Treffpunkt von Mittelmeer und Ägäis. Kitesurfer-Paradies.", type: "Windstrand" },
  ],
  regions: [
    { name: "Rhodos-Stadt & Altstadt", emoji: "🏰", desc: "Hauptstadt mit UNESCO-Altstadt, Nachtleben und Kulturangeboten.", highlights: ["Ritter-Stadtmauer", "Palast des Großmeisters", "Mandra-Gasse"] },
    { name: "Lindos & Ostküste", emoji: "🏛️", desc: "Malerisches Fischerdorf mit weißen Häusern und der berühmten Akropolis.", highlights: ["Akropolis Lindos", "Lindos Beach", "Historisches Dorf"] },
    { name: "Faliraki & Nordosten", emoji: "🎉", desc: "Touristisches Zentrum mit Sandstränden, Wasserpark und Nachtleben.", highlights: ["Faliraki Beach", "Faliraki Wasserpark", "Tsambika Beach"] },
    { name: "Inselinneres", emoji: "🌿", desc: "Grüne Hügel, Weinberge und authentische Dörfer abseits des Tourismus.", highlights: ["Schmetterlingstal", "Embonas-Wein", "Kloster Tharri"] },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "25–55 €", mid: "60–140 €", luxury: "150–500 €+" },
    { label: "Essen (pro Tag)", budget: "12–20 €", mid: "25–45 €", luxury: "60–120 €+" },
    { label: "Transport (pro Tag)", budget: "5–10 € (Bus)", mid: "15–25 € (Scooter)", luxury: "40–70 € (Mietwagen)" },
    { label: "Aktivitäten (pro Tag)", budget: "5–15 €", mid: "20–45 €", luxury: "80–150 €+" },
    { label: "Tagesbudget gesamt", budget: "50–100 €", mid: "120–220 €", luxury: "300–800 €+" },
  ],
  emergency: { police: "100", ambulance: "166", fire: "199", embassy: "+30 210 728 5111 (Deutsche Botschaft Athen)", hospital: "Allgemeines Krankenhaus Rhodos: +30 22410 80000" },
  couplesDays: [
    { day: "Tag 1", title: "Altstadt & romantisches Abendessen", icon: "🏰", color: "bg-rose-100", dayCost: "~50 €", transport: "Zu Fuß", meals: "Altstadt-Restaurant", stops: [
      { time: "10:00", activity: "Ritter-Stadtmauer spazieren", icon: "🏰", tip: "Eintritt 2,50 €, 4 km Rundweg mit Blick auf die See" },
      { time: "12:00", activity: "Palast des Großmeisters besichtigen", icon: "🏛️" },
      { time: "14:00", activity: "Mittagessen in der Altstadt", icon: "🍽️" },
      { time: "16:00", activity: "Anthony Quinn Bay – Schnorcheln", icon: "🤿" },
      { time: "20:00", activity: "Romantisches Dinner am alten Hafen", icon: "🌃" },
    ]},
    { day: "Tag 2", title: "Lindos – Akropolis & weißes Dorf", icon: "🏛️", color: "bg-white", dayCost: "~45 €", transport: "Bus oder Mietauto", meals: "Lindos Taverne", stops: [
      { time: "08:30", activity: "Früh nach Lindos fahren (45 km)", icon: "🚗", tip: "Früh kommen, um Hitze zu vermeiden" },
      { time: "10:00", activity: "Akropolis von Lindos", icon: "🏛️" },
      { time: "12:00", activity: "Bummel durch das weiße Dorf", icon: "🚶" },
      { time: "14:00", activity: "Mittagessen mit Blick aufs Meer", icon: "🍽️" },
      { time: "16:00", activity: "Lindos Beach schwimmen", icon: "🏊" },
    ]},
    { day: "Tag 3", title: "Sonnenuntergang am Akantia-Kap", icon: "🌅", color: "bg-amber-100", dayCost: "~35 €", transport: "Scooter", meals: "Fischerdorf Kameiros Skala", stops: [
      { time: "10:00", activity: "Antike Stadt Kamiros", icon: "🏛️" },
      { time: "13:00", activity: "Fischerdorf Kameiros Skala – Meeresfrüchte", icon: "🦐" },
      { time: "16:00", activity: "Monolithos-Burg mit Panoramablick", icon: "🏰" },
      { time: "19:30", activity: "Sonnenuntergang am Akantia-Kap", icon: "🌅", tip: "Einer der spektakulärsten Sonnenuntergänge auf Rhodos" },
    ]},
  ],
  familiesDays: [
    { day: "Tag 1", title: "Faliraki Wasserpark & Strand", icon: "🌊", color: "bg-cyan-100", dayCost: "~130 € (Fam. 4)", transport: "Bus/Taxi", meals: "Im Park + Taverne", stops: [
      { time: "10:00", activity: "Faliraki Water Park", icon: "🎢", tip: "Riesenrutsche 'Kamikaze' für ältere Kinder, Kinderbad für Kleinere" },
      { time: "14:00", activity: "Mittagessen im Park", icon: "🍔" },
      { time: "16:00", activity: "Faliraki Beach", icon: "🏖️" },
      { time: "19:00", activity: "Pizza-Abend in Faliraki", icon: "🍕" },
    ]},
    { day: "Tag 2", title: "Altstadt erkunden & Eis essen", icon: "🏰", color: "bg-yellow-100", dayCost: "~50 €", transport: "Bus nach Rhodos-Stadt", meals: "Altstadt-Restaurant", stops: [
      { time: "10:00", activity: "Kinder-Führung durch die Altstadt", icon: "🗺️", tip: "Die Gassen sind wie ein Labyrinth – Kinderaugen leuchten" },
      { time: "12:00", activity: "Ritter-Palast besichtigen", icon: "🏰" },
      { time: "14:00", activity: "Mittagessen mit Gyros & Tiropita", icon: "🍽️" },
      { time: "16:00", activity: "Strand Monte Smith", icon: "🏖️" },
      { time: "18:00", activity: "Eis am alten Hafen", icon: "🍦" },
    ]},
    { day: "Tag 3", title: "Schmetterlingstal & Tsambika-Strand", icon: "🦋", color: "bg-pink-100", dayCost: "~40 €", transport: "Mietauto", meals: "Strandtaverne", stops: [
      { time: "09:00", activity: "Schmetterlingstal Petaloudes", icon: "🦋", tip: "Kinder lieben es – Tausende Schmetterlinge im Wald" },
      { time: "12:00", activity: "Fahrt nach Tsambika Beach", icon: "🚗" },
      { time: "13:00", activity: "Mittagessen an der Strandtaverne", icon: "🍽️" },
      { time: "14:00", activity: "Schwimmen und Sandburgen bauen", icon: "🏖️" },
    ]},
  ],
  soloDays: [
    { day: "Tag 1", title: "Altstadt-Erkundung & Nachtleben", icon: "🏰", color: "bg-indigo-100", dayCost: "~35 €", transport: "Zu Fuß", meals: "Altstadt-Gassen", stops: [
      { time: "09:00", activity: "Altstadt am frühen Morgen (fast leer)", icon: "🚶" },
      { time: "11:00", activity: "Archäologisches Museum", icon: "🏛️" },
      { time: "14:00", activity: "Straßenfood: Souvlaki und Loukoumades", icon: "🍢" },
      { time: "17:00", activity: "Stadtmauer-Rundgang", icon: "🏰" },
      { time: "21:00", activity: "Nachtleben in der Altstadt (Odos Miltiádou)", icon: "🎵" },
    ]},
    { day: "Tag 2", title: "Scooter-Tour rund um die Insel", icon: "🛵", color: "bg-orange-100", dayCost: "~45 €", transport: "Scooter (ab 15 €)", meals: "Unterwegs", stops: [
      { time: "09:00", activity: "Scooter mieten in Rhodos-Stadt", icon: "🛵" },
      { time: "10:00", activity: "Antike Stadt Kamiros", icon: "🏛️" },
      { time: "13:00", activity: "Mittagessen in Kameiros Skala", icon: "🍽️" },
      { time: "15:00", activity: "Monolithos-Burg", icon: "🏰" },
      { time: "17:00", activity: "Prasonisi – Südspitze der Insel", icon: "🌊" },
      { time: "20:00", activity: "Rückfahrt entlang der Ostküste", icon: "🌅" },
    ]},
    { day: "Tag 3", title: "Tagesausflug nach Symi", icon: "⛵", color: "bg-sky-100", dayCost: "~40 €", transport: "Fähre ab Rhodos-Hafen (ca. 18 € Hin/Rück)", meals: "Symi-Taverne", stops: [
      { time: "08:00", activity: "Fähre nach Symi", icon: "⛴️", tip: "1 Stunde Fahrt, wunderschöne farbige Häuser am Hafen" },
      { time: "09:30", activity: "Spaziergang zum Kloster Panormitis", icon: "⛪" },
      { time: "12:00", activity: "Mittagessen mit Garnelen in Symi", icon: "🦐", tip: "Symi-Garnelen sind berühmt in ganz Griechenland" },
      { time: "15:00", activity: "Schwimmen in einer Bucht", icon: "🏊" },
      { time: "17:00", activity: "Fähre zurück nach Rhodos", icon: "⛴️" },
    ]},
  ],
};

export default content;
