import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🌨️", text: "Ruhige Winterzeit mit 12 °C. Die meisten Betriebe geschlossen, aber Oia und Fira sind bewohnbar. Günstigste Preise des Jahres." },
    { label: "Februar",   emoji: "🌿", text: "Erste Frühlingszeichen. Insel gehört den Einheimischen. Perfekt für authentische Entdeckungen ohne Touristen." },
    { label: "März",      emoji: "🌸", text: "Vorfrühling mit wildblühenden Wiesen. Hotels öffnen wieder, Temperaturen steigen auf 17 °C." },
    { label: "April",     emoji: "📸", text: "Vorsaison: Traumhafte Lichtverhältnisse, kaum Massen, erstes Schiff im Hafen. Ideal für Fotografen." },
    { label: "Mai",       emoji: "🌊", text: "Badesaison beginnt mit 20 °C Wassertemperatur. Perfekte Temperaturen um 25 °C, Insel erwacht." },
    { label: "Juni",      emoji: "⛵", text: "Hochsaison beginnt. Kreutzfahrtschiffe im Hafen, Oia täglich überfüllt. Früh aufstehen für Fotos." },
    { label: "Juli",      emoji: "☀️", text: "Heißeste Monate mit 32–35 °C und starkem Meltemi-Wind. Perfekt für Wassersport, heiß für Wanderungen." },
    { label: "August",    emoji: "🔆", text: "Peak-Saison: Teuerste Preise, Oia-Sonnenuntergang extrem überlaufen. Mindestens 6 Monate im Voraus buchen." },
    { label: "September", emoji: "🌅", text: "Noch warm (27 °C), deutlich ruhiger, niedrigere Preise. Beste Zeit für Santorini – das goldene Licht ist einzigartig." },
    { label: "Oktober",   emoji: "🍇", text: "Weinlese-Saison. Letztes Badewetter, kühlere Abende, Weinfestival. Insel übergibt sich an Einheimische." },
    { label: "November",  emoji: "🌧️", text: "Betriebe schließen ab Mitte November. Letzter Monat für einen ruhigen Besuch mit echtem Dorfgefühl." },
    { label: "Dezember",  emoji: "⛪", text: "Griechenland-Weihnachten: Orthodox und still. Nur wenige Hotels geöffnet, dafür unvergessliche Ruhe." },
  ],
  sights: [
    {
      title: "Oia – Windmühlen & Sonnenuntergang",
      desc: "Das malerischste Dorf der Welt: weiß getünchte Höhlenhäuser, blaue Kuppelkirchen und der berühmteste Sonnenuntergang Griechenlands. Die Windmühlen am Dorfrand sind das ikonischste Symbol Santorinis.",
      mapHref: "https://maps.google.com/?q=Oia+Santorini",
      address: "Oia, Santorini",
      duration: "3–4 Std.",
      cost: "Kostenlos",
      tip: "Für den Sonnenuntergang 2 Stunden vorher kommen und einen Platz auf der Burgmauer sichern.",
    },
    {
      title: "Akrotiri – Minoische Ausgrabungsstätte",
      desc: "Das 'pompeianische Griechenlands': Eine minoische Siedlung aus dem 17. Jahrhundert v. Chr. wurde 1967 unter Vulkanasche freigelegt. Mehrere Häuser sind vollständig erhalten – einzigartiges archäologisches Fenster in die Bronzezeit.",
      mapHref: "https://maps.google.com/?q=Akrotiri+Santorini",
      address: "Akrotiri, Santorini",
      duration: "1,5–2 Std.",
      cost: "12 €",
      tip: "Im Sommer schattig und angenehm – ideal als Mittagsprogramm bei Hitze.",
    },
    {
      title: "Caldera-Wanderweg Fira–Oia",
      desc: "Der 10 km lange Wanderpfad entlang der Caldera-Kante verbindet Fira mit Oia und bietet ununterbrochene Blicke auf den Vulkankrater, das Ägäische Meer und die umliegenden Inseln – eines der schönsten Wandererlebnisse Griechenlands.",
      mapHref: "https://maps.google.com/?q=Fira+to+Oia+hike+Santorini",
      address: "Start: Fira, Ziel: Oia",
      duration: "4–5 Std.",
      cost: "Kostenlos",
      tip: "Früh morgens starten (7–8 Uhr) – nachmittags sehr heiß und kein Schatten.",
    },
    {
      title: "Vulkaninsel Nea Kameni",
      desc: "Bootsausflug zum aktiven Vulkan der Caldera. Wanderung auf den noch warmen Krater, der zuletzt 1950 ausbrach. Danach heiße Schwefelquellen (Hot Springs) mit mineralreinigendem Badeerlebnis.",
      mapHref: "https://maps.google.com/?q=Nea+Kameni+Santorini",
      address: "Nea Kameni (Caldera-Vulkaninsel)",
      duration: "4–5 Std. (inkl. Bootsfahrt)",
      cost: "15–25 € (Bootstour)",
      tip: "Dunkle Badekleidung mitbringen – die Schwefelquellen färben weißen Stoff gelb.",
    },
    {
      title: "Roter Strand (Red Beach) & Weißer Strand",
      desc: "Spektakulärer Strand mit tiefroten Vulkanklippen und schwarzem Kiesboden bei Akrotiri. Direkte Nachbarschaft zum Weißen Strand (White Beach) der nur per Boot erreichbar ist – märchenhaft.",
      mapHref: "https://maps.google.com/?q=Red+Beach+Santorini",
      address: "Akrotiri, Santorini",
      duration: "Halbtag",
      cost: "Kostenlos (Weißer Strand: Bootsfahrt ca. 10 €)",
      tip: "Vorsicht: regelmäßig Steinschlag von den roten Klippen – gesperrte Bereiche beachten.",
    },
  ],
  history: [
    {
      year: "3000 v. Chr.",
      title: "Erste Besiedlung – Akrotiri",
      text: "Die minoische Zivilisation besiedelte Santorini (damals Strongylē – 'die Runde'). Die blühende Handelsstadt Akrotiri entwickelte sich zu einer der fortschrittlichsten Städte der Bronzezeit mit mehrstöckigen Häusern und Fresken.",
    },
    {
      year: "ca. 1620 v. Chr.",
      title: "Der Minoische Ausbruch",
      text: "Eine der größten vulkanischen Eruptionen der Menschheitsgeschichte zerstörte die Insel. Der Ausbruch soll die minoische Zivilisation auf Kreta geschwächt und den Mythos von Atlantis inspiriert haben. Die Insel blieb 200 Jahre unbewohnt.",
    },
    {
      year: "1204",
      title: "Venezianische Herrschaft",
      text: "Nach dem Vierten Kreuzzug gelangte Santorini (jetzt Santorin) an venezianische Adlige. Die Genuesen und Venezianer prägten die Architektur der Insel. Der Name 'Santorini' leitet sich von der venezianischen Bezeichnung 'Santa Irene' ab.",
    },
    {
      year: "1566",
      title: "Osmanische Herrschaft",
      text: "Das Osmanische Reich übernahm die Kontrolle über Santorini, ließ aber weitgehend autonome Selbstverwaltung zu. Die orthodoxe Kirche blieb das Zentrum des Gemeinschaftslebens.",
    },
    {
      year: "1956",
      title: "Verheerendes Erdbeben",
      text: "Ein schweres Erdbeben (7,8) zerstörte 2.000 Häuser und zwang viele Einwohner zur Emigration. Die charakteristischen Höhlenhäuser (Yposkafa) entstanden als Reaktion – in den Fels gehauen, erdbebensicher und temperaturstabil.",
    },
    {
      year: "1967",
      title: "Entdeckung von Akrotiri",
      text: "Archäologe Spyridon Marinatos begann die Ausgrabungen in Akrotiri. Die vollständig erhaltene minoische Stadt unter der Asche machte Santorini weltberühmt und löste einen Tourismus-Boom aus.",
    },
  ],
  food: [
    {
      emoji: "🍅",
      name: "Tomatokeftedes",
      original: "Τοματοκεφτέδες",
      desc: "Knusprige Fritter aus kleinen Santorini-Kirschtomaten (eine einzigartige, süße Lokalsorte), gemischt mit Minze, Zwiebeln und Feta. Das unverwechselbare Streetfood der Insel.",
      price: "8–12 €",
      tip: "Am besten in Fira nahe dem Archäologischen Museum – die kleinen lokalen Kirschtomaten sind einmalig.",
    },
    {
      emoji: "🫘",
      name: "Fava",
      original: "Φάβα Σαντορίνης",
      desc: "Gelbe Spalterbsencrème aus dem weltberühmten Santorini-Fava – eine geschützte Ursprungsbezeichnung. Mit Olivenöl, Kapern und roten Zwiebeln serviert – cremig und nussig.",
      price: "10–15 €",
    },
    {
      emoji: "🦐",
      name: "Gegrillte Garnelen mit Feta",
      original: "Γαρίδες σαγανάκι",
      desc: "Große Gambas in Tomaten-Feta-Sauce im Tontopf überbacken – typisch griechisches Meeresfrüchtegericht mit Santorini-Twist.",
      price: "18–28 €",
    },
    {
      emoji: "🍷",
      name: "Assyrtiko-Wein",
      original: "Ασσύρτικο",
      desc: "Der weltberühmte Weißwein aus der Assyrtiko-Traube – trocken, mineralisch mit Zitrusaromen. Gedeiht auf dem Vulkanboden Santorinis in einzigartiger Korbform (Kouloura). Qualitätssiegel: Santorini PDO.",
      price: "5–12 € (Glas)",
      tip: "Weingut Santo Wines oder Domaine Sigalas für Weinproben mit Caldera-Blick.",
    },
    {
      emoji: "🍯",
      name: "Melitinia",
      original: "Μελιτίνια",
      desc: "Traditionelle Santorini-Käsekuchen aus frischem Ziegenkäse (Chloro) und Honig in knusprigem Teig. Werden traditionell zu Ostern gebacken, aber ganzjährig erhältlich.",
      price: "3–5 €",
    },
  ],
  phrases: [
    { original: "Γεια σας! (Yeia sas!)", pronunciation: "jɑ sas", translation: "Guten Tag! (formell)" },
    { original: "Καλημέρα (Kaliméra)", pronunciation: "kali-me-ra", translation: "Guten Morgen" },
    { original: "Ευχαριστώ (Efcharistó)", pronunciation: "ef-cha-ri-sto", translation: "Danke" },
    { original: "Παρακαλώ (Parakaló)", pronunciation: "pa-ra-ka-lo", translation: "Bitte" },
    { original: "Πόσο κάνει; (Póso káni?)", pronunciation: "po-so ka-ni", translation: "Was kostet das?" },
    { original: "Τον λογαριασμό (Ton logariasmó)", pronunciation: "ton lo-ga-ria-smo", translation: "Die Rechnung, bitte" },
    { original: "Πού είναι η παραλία; (Pu ine i paralia?)", pronunciation: "pu i-ne i pa-ra-li-a", translation: "Wo ist der Strand?" },
    { original: "Στην υγειά σας! (Stin igiá sas!)", pronunciation: "stin i-gi-a sas", translation: "Auf Ihr Wohl! (Prost)" },
    { original: "Χρειάζομαι γιατρό (Chriázomai jatró)", pronunciation: "chri-a-zo-me ja-tro", translation: "Ich brauche einen Arzt" },
    { original: "Αντίο! (Andío!)", pronunciation: "an-di-o", translation: "Auf Wiedersehen!" },
  ],
  insider: [
    {
      icon: "🚌",
      title: "KTEL-Bus statt teures Taxi",
      text: "Das öffentliche Busnetz (KTEL) verbindet Fira mit Oia (2,70 €), Akrotiri (2,10 €) und Perissa (2,10 €). Taxis sind 5–10× teurer. Die Busse fahren von 06:00–23:00 Uhr.",
    },
    {
      icon: "🌅",
      title: "Sonnenuntergang von der Burg Skaros",
      text: "Wenige Touristen kennen die venezianische Burg Skaros bei Imerovigli – besserer Blick als Oia, ohne die Menschenmassen. 20 Minuten Wanderung von Imerovigli.",
    },
    {
      icon: "🍷",
      title: "Weingut-Verkostung mit Caldera-Blick",
      text: "Das Weingut Santo Wines bei Pyrgos bietet Weinproben von Assyrtiko ab 15 € mit dem besten Caldera-Panorama der Insel – und kostet das Gleiche wie ein mittelmäßiger Cocktail in Oia.",
    },
    {
      icon: "⛱️",
      title: "Perissa statt Red Beach",
      text: "Der schwarze Vulkansand von Perissa Beach ist genauso spektakulär wie der Red Beach, aber 10× länger und weniger überlaufen. Liegen und Tavermen direkt am Strand.",
    },
    {
      icon: "🌊",
      title: "Abendliches Caldera-Schwimmen",
      text: "Nach 18 Uhr ist die Ammoudi Bay unter Oia fast leer. Das Schwimmen in der Caldera bei abendlichem Licht, dann frischen Hummer in der Bucht essen – Santorini von seiner ruhigsten Seite.",
    },
  ],
  beaches: [
    {
      name: "Perissa & Perivolos",
      emoji: "⬛",
      desc: "Kilometerlanger schwarzer Vulkansandstrand im Südosten – lebhaft, mit Tavernen, Bars und Wassersport.",
      type: "Schwarzer Vulkansand",
      tip: "Günstigster Strand der Insel – Liegen ab 5 € statt 20 € in Kamari.",
    },
    {
      name: "Red Beach",
      emoji: "🔴",
      desc: "Spektakulärer Strand mit dunkelroten Klippen und schwarzem Kies bei Akrotiri – eines der fotogensten Naturwunder Griechenlands.",
      type: "Vulkanischer Kiesstrand",
      tip: "Kein Zugang unter den roten Klippen (Steinschlag) – nur rechte Seite des Strandes.",
    },
    {
      name: "Kamari",
      emoji: "🌊",
      desc: "Beliebtester Strand Santorinis mit schwarzem Kiesboden, klarem Wasser und langer Uferpromenade mit Restaurants.",
      type: "Schwarzer Kiesstrand",
    },
    {
      name: "Vlychada",
      emoji: "🏜️",
      desc: "Geheimnisvoller Strand mit weißen, vom Wind erodierten Klippen – sieht aus wie eine Mondlandschaft und ist fast unbekannt.",
      type: "Wüstenartige Klippen",
    },
    {
      name: "Ammoudi Bay",
      emoji: "⛵",
      desc: "Winzige Bucht direkt unter Oia mit Fischrestaurants und Felsen zum Springen – per Treppen von Oia erreichbar.",
      type: "Felsen- und Hafenbucht",
      tip: "Taverna Dimitris: frischgefangener Hummer direkt aus dem Wasser.",
    },
  ],
  regions: [
    {
      name: "Oia & Nördliche Caldera",
      emoji: "🌅",
      desc: "Das bekannteste Dorf der Insel mit dem Weltklasse-Sonnenuntergang, teuersten Hotels und malerischsten Gassen.",
      highlights: ["Sonnenuntergang Oia", "Windmühlen", "Ammoudi Bay"],
    },
    {
      name: "Fira & Imerovigli",
      emoji: "🏙️",
      desc: "Die lebhafte Hauptstadt mit Nachtleben, Museen und dem besten Ausgangspunkt für Caldera-Wanderungen.",
      highlights: ["Archäologisches Museum", "Caldera-Wanderweg", "Burg Skaros"],
    },
    {
      name: "Akrotiri & Südwesten",
      emoji: "🏛️",
      desc: "Die geschichtsträchtige Ecke mit Ausgrabungsstätte, Red Beach und spektakulären Vulkanklippen.",
      highlights: ["Akrotiri Ausgrabungen", "Red Beach", "White Beach"],
    },
    {
      name: "Perissa & Kamari",
      emoji: "⬛",
      desc: "Die entspannteste Seite der Insel mit langen schwarzen Stränden, Tavernen und günstigeren Unterkünften.",
      highlights: ["Perissa Beach", "Kamari Beach", "Mesa Vouno"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "40–90 €", mid: "120–350 €", luxury: "400–2000 €+" },
    { label: "Essen (pro Tag)", budget: "15–25 €", mid: "35–70 €", luxury: "100–300 €+" },
    { label: "Transport (pro Tag)", budget: "5–10 € (Bus)", mid: "30–60 € (Taxi/Quad)", luxury: "100–200 € (Privatfahrer)" },
    { label: "Aktivitäten (pro Tag)", budget: "10–20 €", mid: "30–80 €", luxury: "150–500 €+" },
    { label: "Tagesbudget gesamt", budget: "70–145 €", mid: "215–560 €", luxury: "750–3000 €+" },
  ],
  emergency: {
    police: "100",
    ambulance: "166",
    fire: "199",
    embassy: "+30 210 728 5111 (Deutsche Botschaft Athen)",
    hospital: "Krankenhaus Santorini (Fira): +30 22860 22237",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Oia & Weltberühmter Sonnenuntergang",
      icon: "🌅",
      color: "bg-rose-100",
      dayCost: "~120 €",
      transport: "Bus Fira–Oia (2,70 €)",
      meals: "Restaurant Ammoudi Fish Taverna",
      stops: [
        { time: "09:00", activity: "Oia am Morgen – leere Gassen erkunden", icon: "🚶", tip: "Morgens gehören die weißen Gassen euch allein." },
        { time: "11:00", activity: "Ammoudi Bay – Schwimmen von den Felsen", icon: "🏊" },
        { time: "13:30", activity: "Frischer Hummer in Ammoudi Bay Taverne", icon: "🦞", tip: "Taverna Katina – Hummer direkt aus dem Becken ausgewählt." },
        { time: "17:00", activity: "Platz auf der Oia-Burg sichern", icon: "🏰" },
        { time: "20:00", activity: "Sonnenuntergang & Champagner", icon: "🥂" },
      ],
    },
    {
      day: "Tag 2",
      title: "Vulkan & Weindegustation",
      icon: "🌋",
      color: "bg-amber-100",
      dayCost: "~100 €",
      transport: "Bootsausflug + Bus",
      meals: "Santo Wines Restaurant",
      stops: [
        { time: "09:30", activity: "Bootsausflug zur Vulkaninsel Nea Kameni", icon: "🚢" },
        { time: "10:30", activity: "Wanderung auf den Vulkankrater", icon: "🌋" },
        { time: "12:00", activity: "Heiße Schwefelquellen – natürliches Thermalbad", icon: "♨️" },
        { time: "15:00", activity: "Santo Wines – Assyrtiko-Degustation mit Caldera-Blick", icon: "🍷", tip: "Das Weingut bietet Meze + Weinpairing für 25 € an." },
        { time: "20:00", activity: "Romantisches Dinner in Imerovigli", icon: "🌃" },
      ],
    },
    {
      day: "Tag 3",
      title: "Akrotiri & Schwarzer Strand",
      icon: "🏛️",
      color: "bg-emerald-100",
      dayCost: "~80 €",
      transport: "Bus oder Quad",
      meals: "Taverna Perissa",
      stops: [
        { time: "09:30", activity: "Akrotiri – minoische Ausgrabungsstätte", icon: "🏛️" },
        { time: "12:00", activity: "Red Beach bewundern", icon: "🔴" },
        { time: "13:30", activity: "Mittagessen in Akrotiri-Dorf", icon: "🍽️" },
        { time: "15:00", activity: "Perissa Beach – schwarzer Sand & Schwimmen", icon: "⬛", tip: "Sonnenliegen bis 19 Uhr – bis dahin ist das Wasser am wärmsten." },
        { time: "19:30", activity: "Sonnenuntergang von der Burg Skaros (Wanderung)", icon: "🏰" },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Kamari Strand & Schwarzer Sand",
      icon: "⬛",
      color: "bg-cyan-100",
      dayCost: "~80 € (Fam. 4)",
      transport: "Bus",
      meals: "Kamari Strandtaverne",
      stops: [
        { time: "10:00", activity: "Kamari Beach – schwarzer Kies, flaches Wasser", icon: "🏖️", tip: "Sehr kinderfreundlich – flach und sicher." },
        { time: "13:00", activity: "Mittagessen an der Strandpromenade", icon: "🍽️" },
        { time: "15:00", activity: "Bootsausflug zu Kamari-Buchten", icon: "⛵" },
        { time: "17:30", activity: "Eis und Bummel an der Kamari-Promenade", icon: "🍦" },
      ],
    },
    {
      day: "Tag 2",
      title: "Vulkan-Bootsabenteuer",
      icon: "🌋",
      color: "bg-yellow-100",
      dayCost: "~120 € (Fam. 4)",
      transport: "Bootsausflug",
      meals: "Picknick & Taverne",
      stops: [
        { time: "09:30", activity: "Bootsausflug: Vulkaninsel Nea Kameni", icon: "🚢", tip: "Kinder ab 5 Jahren für die Vulkanwanderung geeignet." },
        { time: "11:00", activity: "Wanderung auf den Vulkankrater", icon: "🌋" },
        { time: "12:30", activity: "Thermalbad in den Heißen Quellen", icon: "♨️" },
        { time: "15:00", activity: "Bootstopp an Perissa Beach", icon: "⬛" },
        { time: "18:00", activity: "Taverne am Hafen – frische Meeresfrüchte", icon: "🦐" },
      ],
    },
    {
      day: "Tag 3",
      title: "Akrotiri Archäologie & Roter Strand",
      icon: "🏛️",
      color: "bg-pink-100",
      dayCost: "~70 € (Fam. 4)",
      transport: "Bus",
      meals: "Lokale Taverne Akrotiri",
      stops: [
        { time: "09:30", activity: "Akrotiri – 'Griechenlands Pompeji'", icon: "🏛️", tip: "Kinder über 8 sind fasziniert – wie eine Zeitreise in die Steinzeit." },
        { time: "12:00", activity: "Red Beach anschauen & Fotos machen", icon: "🔴" },
        { time: "13:30", activity: "Mittagessen in Akrotiri-Dorf", icon: "🍽️" },
        { time: "15:00", activity: "Perissa Beach – Schwimmen & Sandspiele", icon: "⬛" },
        { time: "18:00", activity: "Abendessen mit Sonnenblick", icon: "🌅" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Caldera-Wanderung Fira–Oia",
      icon: "🥾",
      color: "bg-indigo-100",
      dayCost: "~40 €",
      transport: "Zu Fuß + Bus zurück",
      meals: "Unterwegs (Snacks mitnehmen)",
      stops: [
        { time: "07:00", activity: "Start der Caldera-Wanderung in Fira", icon: "🌅", tip: "Frühzeitig starten – nachmittags zu heiß und keine Schattenbereiche." },
        { time: "09:00", activity: "Imerovigli – Burg Skaros-Abstecher", icon: "🏰" },
        { time: "11:30", activity: "Firostefani – Caldera-Pause mit Blick", icon: "☕" },
        { time: "13:00", activity: "Ankunft Oia – Belohnung mit Mittagessen", icon: "🍽️" },
        { time: "15:00", activity: "Oia erkunden & Kunstgalerien", icon: "🎨" },
        { time: "20:00", activity: "Sonnenuntergang & Bus zurück nach Fira", icon: "🌅" },
      ],
    },
    {
      day: "Tag 2",
      title: "Wein, Geschichte & Geheimstrand",
      icon: "🍷",
      color: "bg-teal-100",
      dayCost: "~55 €",
      transport: "Bus",
      meals: "Weingut + Taverne",
      stops: [
        { time: "09:30", activity: "Akrotiri Ausgrabungen", icon: "🏛️" },
        { time: "11:30", activity: "Red Beach – Fotos & kurzes Schwimmen", icon: "🔴" },
        { time: "13:00", activity: "Mittagessen in Akrotiri", icon: "🍽️" },
        { time: "15:00", activity: "Domaine Sigalas – Weinführung & Degustation", icon: "🍷", tip: "Einer der besten Winzer Griechenlands auf Santorini." },
        { time: "18:30", activity: "Vlychada Strand – einsamer Mondlandschaftsstrand", icon: "🏜️" },
      ],
    },
    {
      day: "Tag 3",
      title: "Vulkantour & Sonnenuntergang solo",
      icon: "🌋",
      color: "bg-orange-100",
      dayCost: "~60 €",
      transport: "Bootsausflug + Bus",
      meals: "Taverne Perissa",
      stops: [
        { time: "09:30", activity: "Vulkan Nea Kameni Bootsausflug", icon: "🚢" },
        { time: "11:30", activity: "Heiße Quellen – schwefeliges Thermalbad", icon: "♨️" },
        { time: "14:00", activity: "Perissa Beach – Entspannung solo", icon: "⬛" },
        { time: "17:00", activity: "Bus nach Oia", icon: "🚌" },
        { time: "20:00", activity: "Sonnenuntergang in Oia allein genießen", icon: "🌅", tip: "Burgmauer hoch und einen Platz an der Kante suchen – unvergesslich." },
      ],
    },
  ],
};

export default content;
