import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🏛️", text: "Side im Winter: Ideale Zeit für Archäologie-Begeisterte ohne Touristen. 13 °C, Ruinen fast menschenleer. Günstigste Unterkunftspreise." },
    { label: "Februar",   emoji: "🌸", text: "Erste Frühlingsblüten um die antiken Ruinen. 16 °C, keine Massen. Einheimische Side in seiner ruhigsten Form." },
    { label: "März",      emoji: "🌿", text: "Frühling: Wildblumen zwischen Säulenresten. Wanderungen im Taurusgebirge bei 19 °C. Vorsaison-Preise." },
    { label: "April",     emoji: "📸", text: "Perfekte Lichtbedingungen für Fotos der Ruinen. 23 °C, erste Badefreudige. Ideale Zeit für Geschichte-Fans." },
    { label: "Mai",       emoji: "🏖️", text: "Badesaison beginnt. 23 °C Wassertemperatur. Sidestrand beginnt sich zu füllen – noch angenehme Bedingungen." },
    { label: "Juni",      emoji: "☀️", text: "Hochsaison beginnt. 27 °C und sonnig. Strände füllen sich, aber Side ist weniger überlaufen als Antalya oder Alanya." },
    { label: "Juli",      emoji: "🔆", text: "Heiß und voll mit 35 °C. Apollon-Tempel täglich bei Sonnenuntergang besetzt. Früh morgens Ruinen erkunden." },
    { label: "August",    emoji: "🌊", text: "Peak-Saison: Hotspots voll, Preise auf Maximum. Wassertemperatur 28 °C. Restaurants ausgebucht." },
    { label: "September", emoji: "🌅", text: "Noch warm (30 °C), viel ruhiger als August. Perfekter Monat für Side – Ruinen bei milderem Licht besonders fotogen." },
    { label: "Oktober",   emoji: "🍂", text: "Angenehme 26 °C, letztes Badewetter. Herbstlicht über dem Apollon-Tempel ist einmalig. Günstige Preise." },
    { label: "November",  emoji: "🌧️", text: "Touristensaison endet. Erste Regentage. Side gehört den Einheimischen. Authentische Tavernen öffnen wieder." },
    { label: "Dezember",  emoji: "☕", text: "Ruhige Winterzeit. 14 °C, keine Touristen. Ideale Zeit für intensive Archäologie-Touren ohne Ablenkung." },
  ],
  sights: [
    {
      title: "Apollon- & Athena-Tempel",
      desc: "Die fünf stehenden Säulen des Apollon-Tempels (2. Jh. n. Chr.) direkt am Meer sind das ikonischste Symbol Sides und einer der photogensten antiken Orte der Türkei. Daneben die Ruinen des Athena-Tempels aus dem 2. Jahrhundert v. Chr.",
      mapHref: "https://maps.google.com/?q=Apollo+Temple+Side+Turkey",
      address: "Antike Stadt Side, Manavgat",
      duration: "1 Std.",
      cost: "Inklusive im Side-Museumsticket (8 €)",
      tip: "Bei Sonnenuntergang: Die Säulen leuchten gold-orange über dem Mittelmeer – eines der schönsten Naturschauspiele Anatoliens.",
    },
    {
      title: "Antike Stadt Side – Ruinenfeld",
      desc: "Side war eine der wichtigsten Handelsstädte der Antike. Die Überreste umfassen: das riesige Theater (15.000 Plätze), Thermenanlage, Agora, Triumphbogen und hellenistische Stadtmauern – alles auf einer Halbinsel ins Mittelmeer gebettet.",
      mapHref: "https://maps.google.com/?q=Ancient+Side+Turkey",
      address: "Side, Manavgat/Antalya",
      duration: "2–3 Std.",
      cost: "8 € (Kombination Stadtticket)",
      tip: "Früh morgens um 8 Uhr starten – bei Hitze unangenehm, und Licht ist morgens am besten.",
    },
    {
      title: "Side Antikes Theater",
      desc: "Das besterhaltene Theater Kleinasiens mit Kapazität für 15.000 Zuschauer. Zweistöckige Bühnenarchitektur, Gladiatorenring und das antike Gewölbesystem sind beeindruckend erhalten. Wird noch heute für Konzerte genutzt.",
      mapHref: "https://maps.google.com/?q=Side+Theatre+Turkey",
      address: "Antike Stadt Side",
      duration: "45 Min.",
      cost: "Inklusive Stadtticket",
      tip: "Konzerte im Sommer im alten Theater – Tickets über Antalya-Kulturamt.",
    },
    {
      title: "Side Museum (Antike Thermen)",
      desc: "Das Side-Museum ist einzigartig: Es ist in den perfekt erhaltenen antiken Bädern (Thermen) untergebracht. Herausragende Skulpturen, Sarkophage und Mosaiken aus dem 2.–4. Jh. n. Chr., darunter die berühmte Dreier-Grazie.",
      mapHref: "https://maps.google.com/?q=Side+Museum+Turkey",
      address: "Liman Caddesi, Side",
      duration: "1–1,5 Std.",
      cost: "5 €",
      tip: "Eines der besten Archäologiemuseen der Türkei – unterschätzt und fast immer leer.",
    },
    {
      title: "Köprülü Kanyon – Rafting & Natur",
      desc: "Der Köprülü-Flusskanyon 60 km nördlich von Side bietet die schönsten Raftingtouren der türkischen Mittelmeerküste. Kristallklares Bergwasser, antike Brücken und umgebende Zedern-Nationalpark.",
      mapHref: "https://maps.google.com/?q=Koprulu+Canyon+Turkey",
      address: "Köprülü Kanyon Nationalpark, Antalya",
      duration: "Ganztag (inkl. Transfer)",
      cost: "30–50 € (inkl. Transfer und Ausrüstung)",
      tip: "Beste Raftingzeit: April–Oktober. Frühbucher-Rabatte bei lokalen Veranstaltern.",
    },
  ],
  history: [
    {
      year: "7. Jh. v. Chr.",
      title: "Gründung von Side",
      text: "Griechische Kolonisten aus Kyme (Aeolis) gründeten Side. Die Einwohner bewahrten lange ihre eigene Sprache (Sidisch), die sich von griechisch unterschied – eine der letzten Inschriften in dieser rätselhaften Sprache stammt aus Side.",
    },
    {
      year: "333 v. Chr.",
      title: "Alexander der Große",
      text: "Alexander der Große nahm Side kampflos ein. Nach seinem Tod fiel die Stadt an die Ptolemäer Ägyptens, dann an die Seleukiden. Berühmterweise war Side in dieser Zeit auch ein Zentrum des Sklavenhandels.",
    },
    {
      year: "190 v. Chr.",
      title: "Römer schlagen Antiochos bei Side",
      text: "In der Seeschlacht bei Side besiegte die römisch-rhodische Flotte die syrisch-seleukidische Flotte unter Antiochos III. – eine Entscheidungsschlacht für die Vorherrschaft im Mittelmeer.",
    },
    {
      year: "1.–3. Jh. n. Chr.",
      title: "Blütezeit unter Rom",
      text: "Side erreichte unter der Pax Romana seine größte Blüte. Theater, Nymphäum, Thermenanlage und die Tempel für Apollo und Athena entstanden. Die Stadt hatte über 60.000 Einwohner.",
    },
    {
      year: "7. Jh. n. Chr.",
      title: "Arabische Überfälle & Niedergang",
      text: "Arabische Überfälle zwangen die Bevölkerung, hinter den Mauern zu leben. Die Stadt verlor ihre Bedeutung als Handelshafen. Im 10. Jahrhundert wurde Side verlassen und versandete.",
    },
    {
      year: "1895",
      title: "Wiederbesiedlung durch kretische Flüchtlinge",
      text: "Muslimische Flüchtlinge aus Kreta siedelten sich in der verlassenen antiken Stadt an und nannten den Ort 'Selimiye'. Erst ab den 1970er Jahren entwickelte sich Side zum Touristenziel – die antiken Ruinen blieben überraschend gut erhalten.",
    },
  ],
  food: [
    {
      emoji: "🐟",
      name: "Levrek (Wolfsbarsch)",
      original: "Levrek Izgara",
      desc: "Frisch gegrillter Wolfsbarsch vom Holzkohlegrill – das beste Fischgericht der südtürkischen Küste. Wird ganz serviert mit Salat, Brot und Rakı.",
      price: "150–250 TL (~5–8 €)",
      tip: "Restaurants direkt am Apollon-Tempel – Abendessen mit Säulenblick.",
    },
    {
      emoji: "🥗",
      name: "Çoban Salatası",
      original: "Çoban Salatası",
      desc: "Türkischer Hirtensalat aus frischen Tomaten, Gurken, grünem Paprika, Zwiebeln und Petersilie mit Olivenöl und Zitrone. Die beste Begleitung zu jedem Gericht.",
      price: "60–100 TL (~2–3 €)",
    },
    {
      emoji: "🥙",
      name: "Şiş Kebap",
      original: "Şiş Kebap",
      desc: "Zartes Lammfleisch auf dem Metallspieß gegrillt, serviert mit Fladenbrot, frischen Tomaten und Ayran. In Side die ehrlichste Küche ohne Touristenzuschlag in lokalen Kebapçıs.",
      price: "100–150 TL (~3–5 €)",
    },
    {
      emoji: "🧆",
      name: "Meze-Platte",
      original: "Meze Tabağı",
      desc: "Auswahl an kalten und warmen Vorspeisen: Hummus, Haydari (Joghurt-Kräuter), Sigara Böreği (frittierte Käseröllchen), gefüllte Weinblätter und Babaganuş. Das sociale Essen Anatoliens.",
      price: "150–250 TL (~5–8 €) für zwei",
    },
    {
      emoji: "🍡",
      name: "Lokum & Fıstıklı Baklava",
      original: "Lokum / Fıstıklı Baklava",
      desc: "Türkisches Lokum (Gelée-Würfel) und Pistazienbaklava sind das süßeste Mitbringsel aus Side. In der Altstadt zahlreiche Süßwarenläden mit Frischware.",
      price: "50–100 TL (~1,5–3 €) pro 100g",
      tip: "Gaziantep-Baklava hat Ursprungsbezeichnung – auf Qualitätssticker achten.",
    },
  ],
  phrases: [
    { original: "Merhaba!", pronunciation: "mer-ha-ba", translation: "Hallo!" },
    { original: "Günaydın! / İyi günler!", pronunciation: "gü-nai-dın / i-ji gün-ler", translation: "Guten Morgen! / Guten Tag!" },
    { original: "Teşekkür ederim", pronunciation: "te-schek-kür e-de-rim", translation: "Danke schön" },
    { original: "Lütfen", pronunciation: "lüt-fen", translation: "Bitte" },
    { original: "Bu ne kadar?", pronunciation: "bu ne ka-dar", translation: "Was kostet das?" },
    { original: "Hesap alabilir miyim?", pronunciation: "he-sap a-la-bi-lir mi-jim", translation: "Kann ich die Rechnung haben?" },
    { original: "Müze nerede?", pronunciation: "mü-ze ne-re-de", translation: "Wo ist das Museum?" },
    { original: "Bir çay lütfen", pronunciation: "bir tschai lüt-fen", translation: "Einen Tee bitte" },
    { original: "Ambulans çağırın!", pronunciation: "am-bu-lans tscha-ı-rın", translation: "Rufen Sie einen Krankenwagen!" },
    { original: "İyi yolculuklar!", pronunciation: "i-ji jol-dschu-luk-lar", translation: "Gute Reise!" },
  ],
  insider: [
    {
      icon: "🌅",
      title: "Apollon-Tempel bei Sonnenuntergang",
      text: "Der Apollon-Tempel ist um Mitternacht unbewacht zugänglich (Außenbereich). Aber bereits der Abendblick vom freien Aussichtspunkt daneben, wenn die 5 Säulen im Sonnenuntergang leuchten, ist kostenlos und unvergesslich.",
    },
    {
      icon: "🏛️",
      title: "Ruinen am frühen Morgen",
      text: "Das gesamte Ruinengelände öffnet um 8 Uhr. In den ersten zwei Stunden teilst du die antike Stadt oft mit nur wenigen anderen Menschen – eine seltene Möglichkeit, eine 2000 Jahre alte Metropole in fast völliger Stille zu erleben.",
    },
    {
      icon: "🚌",
      title: "Dolmuş nach Manavgat",
      text: "Der Dolmuş nach Manavgat (6 km) kostet 10–15 TL und fährt alle 15 Minuten. Von Manavgat gibt es günstige Busse nach Antalya (1,5 Std.) und Alanya (1 Std.). Taxi ist das 10-fache.",
    },
    {
      icon: "🛒",
      title: "Manavgat-Markt donnerstags",
      text: "Der Freiluftmarkt in Manavgat jeden Donnerstag ist einer der größten der Region – frische Gewürze, Trockenfrüchte, Textilien und Lederwaren zu Einheimischen-Preisen. 10 Min. mit dem Dolmuş.",
    },
    {
      icon: "🐢",
      title: "Caretta-Schildkröten am Strand",
      text: "Side-Ost-Strand ist ausgewiesener Brutplatz für Caretta-Caretta-Meeresschildkröten. In der Dämmerung kann man Weibchen beim Nestnachsehen beobachten – nur in ausgewiesenen Bereichen, nicht stören.",
    },
  ],
  beaches: [
    {
      name: "Side West-Strand",
      emoji: "🏛️",
      desc: "Feiner Sandstrand westlich der Halbinsel, direkt unterhalb des Apollon-Tempels. Das Schwimmen mit Blick auf die antiken Säulen ist ein einzigartiges Erlebnis.",
      type: "Sandstrand / Kulturpanorama",
      tip: "Abends schwimmen – Sonnenuntergang hinter dem Apollon-Tempel.",
    },
    {
      name: "Side Ost-Strand",
      emoji: "🐢",
      desc: "Langer Sandstrand östlich der Altstadt, gesäumt von Resorts. Ausgewiesener Schutzbereich für Caretta-Schildkröten.",
      type: "Breiter Sandstrand",
    },
    {
      name: "Kumköy Beach",
      emoji: "🌊",
      desc: "Ruhigerer Strand 5 km westlich von Side mit weniger Touristen und günstigeren Strandrestaurants.",
      type: "Sandstrand / Ruhiger",
      tip: "Beliebt bei Familien und Langzeiturlaubern.",
    },
    {
      name: "Evrenseki Beach",
      emoji: "🏖️",
      desc: "Touristisch erschlossener Sandstrand 10 km östlich von Side mit All-Inclusive-Hotels und Wasserpark.",
      type: "Touristischer Ferienhotel-Strand",
    },
    {
      name: "Titreyengöl Lagune",
      emoji: "🦩",
      desc: "Natürliche Süßwasserlagune hinter dem Ost-Strand – Flamingos, Reiher und Wasservögel in natürlichem Biotop. Kostenloses Naturspektakel.",
      type: "Naturschutz-Lagune",
      tip: "Morgens oder abends besuchen – Vögel sind dann aktiver.",
    },
  ],
  regions: [
    {
      name: "Antike Stadt Side (Halbinsel)",
      emoji: "🏛️",
      desc: "Das historische Herz auf der Halbinsel mit Apollon-Tempel, Theater, Museum und den meisten Ruinen.",
      highlights: ["Apollon-Tempel", "Antikes Theater", "Side Museum"],
    },
    {
      name: "Side West & Hafen",
      emoji: "⛵",
      desc: "Der Fischerhafen mit Boutiquen, Restaurants und dem Blick auf den Tempel bei Sonnenuntergang.",
      highlights: ["Fischerhafen", "Altstadtgassen", "Abendessen mit Tempelblick"],
    },
    {
      name: "Manavgat & Umgebung",
      emoji: "🌊",
      desc: "Die 6 km entfernte Kreisstadt mit Wasserfall, Markt und Ausgangspunkt für Ausflüge in die Region.",
      highlights: ["Manavgat-Wasserfall", "Donnerstagmarkt", "Köprülü Kanyon"],
    },
    {
      name: "Taurusgebirge & Natur",
      emoji: "⛰️",
      desc: "Spektakuläres Hinterland mit Köprülü Kanyon, Rafting und antiken Bergstraßen.",
      highlights: ["Köprülü Kanyon Rafting", "Seleukeia Ruinen", "Traditionelle Bergdörfer"],
    },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "20–50 €", mid: "60–130 €", luxury: "150–350 €+" },
    { label: "Essen (pro Tag)", budget: "8–15 €", mid: "20–45 €", luxury: "60–120 €+" },
    { label: "Transport (pro Tag)", budget: "2–5 € (Dolmuş)", mid: "15–30 € (Taxi)", luxury: "50–100 € (Privat)" },
    { label: "Aktivitäten (pro Tag)", budget: "5–15 €", mid: "20–50 €", luxury: "80–200 €+" },
    { label: "Tagesbudget gesamt", budget: "35–85 €", mid: "115–255 €", luxury: "340–770 €+" },
  ],
  emergency: {
    police: "155",
    ambulance: "112",
    fire: "110",
    embassy: "+90 312 455 5100 (Deutsche Botschaft Ankara) / Konsulat Antalya: +90 242 248 0454",
    hospital: "Manavgat Devlet Hastanesi: +90 242 742 1014",
  },
  couplesDays: [
    {
      day: "Tag 1",
      title: "Ruinen & Sonnenuntergang am Apollon-Tempel",
      icon: "🏛️",
      color: "bg-rose-100",
      dayCost: "~60 €",
      transport: "Zu Fuß",
      meals: "Restaurant am Apollon-Tempel",
      stops: [
        { time: "08:00", activity: "Antike Stadt früh morgens – fast allein", icon: "🌅", tip: "Bestes Licht für Fotos und keine Touristengruppen." },
        { time: "09:30", activity: "Antikes Theater besteigen", icon: "🎭" },
        { time: "11:30", activity: "Side Museum in den antiken Thermen", icon: "🏛️" },
        { time: "14:00", activity: "Mittagessen in der Altstadtgasse", icon: "🍽️" },
        { time: "16:00", activity: "Westlicher Strand – Schwimmen mit Tempelblick", icon: "🏖️" },
        { time: "19:30", activity: "Apollon-Tempel Sonnenuntergang & Abendessen", icon: "🌅", tip: "Romantischster Sonnenuntergang der Türkischen Riviera." },
      ],
    },
    {
      day: "Tag 2",
      title: "Köprülü Kanyon Rafting",
      icon: "🌊",
      color: "bg-sky-100",
      dayCost: "~80 €",
      transport: "Gebuchter Transfer (inklusive)",
      meals: "Kanyon-Restaurant",
      stops: [
        { time: "08:30", activity: "Abholung vom Hotel – Transfer zum Kanyon", icon: "🚌" },
        { time: "10:30", activity: "Rafting im Köprülü Kanyon (2 Std.)", icon: "🚣", tip: "Level 1–2 – auch für Anfänger geeignet. Sehr erfrischend." },
        { time: "13:00", activity: "Mittagessen am Flussufer", icon: "🐟" },
        { time: "15:00", activity: "Römische Brücke Oluk Köprüsü besichtigen", icon: "🏛️" },
        { time: "17:00", activity: "Rückfahrt nach Side", icon: "🚌" },
        { time: "20:00", activity: "Romantisches Abendessen an der Hafenpromenade", icon: "🌃" },
      ],
    },
    {
      day: "Tag 3",
      title: "Aspendos & Entspannung",
      icon: "🎭",
      color: "bg-amber-100",
      dayCost: "~70 €",
      transport: "Taxi oder Mietwagen",
      meals: "Lokale Taverne Antalya",
      stops: [
        { time: "09:00", activity: "Aspendos Theater (30 km) – Weltbestes römisches Theater", icon: "🎭", tip: "Das besterhaltene römische Theater der Welt – 15.000 Plätze." },
        { time: "11:30", activity: "Perge Ruinen (weitere 17 km)", icon: "🏛️" },
        { time: "14:00", activity: "Mittagessen in Antalya Altstadt (Kaleiçi)", icon: "🍽️" },
        { time: "16:00", activity: "Rückfahrt – Stopp am Side-Strand", icon: "🏖️" },
        { time: "19:30", activity: "Abschluss-Abendessen am Apollon-Tempel", icon: "🌅" },
      ],
    },
  ],
  familiesDays: [
    {
      day: "Tag 1",
      title: "Antike Stadtdetektive",
      icon: "🏛️",
      color: "bg-cyan-100",
      dayCost: "~70 € (Fam. 4)",
      transport: "Zu Fuß",
      meals: "Strandrestaurant",
      stops: [
        { time: "09:00", activity: "Antike Stadt – Schatzsuche zwischen Ruinen", icon: "🗺️", tip: "Kinder als Archäologen: Welches Gebäude ist was? Quiz durch die Ruinen." },
        { time: "11:30", activity: "Side Museum – Skulpturen und Sarkophage", icon: "🏛️" },
        { time: "13:00", activity: "Mittagessen am Westlichen Strand", icon: "🍽️" },
        { time: "15:00", activity: "Schwimmen mit Blick auf Apollon-Tempel", icon: "🏊" },
        { time: "18:00", activity: "Abendessen & Lokum für Kinder", icon: "🍡" },
      ],
    },
    {
      day: "Tag 2",
      title: "Rafting & Naturerlebnis",
      icon: "🚣",
      color: "bg-teal-100",
      dayCost: "~160 € (Fam. 4)",
      transport: "Gebuchter Transfer",
      meals: "Kanyon-BBQ",
      stops: [
        { time: "08:30", activity: "Transfer zum Köprülü Kanyon", icon: "🚌" },
        { time: "10:30", activity: "Familienrafting – sanfte Stromschnellen", icon: "🚣", tip: "Kinder ab 6 Jahren. Rettungswesten inklusive – sehr sicher." },
        { time: "13:00", activity: "BBQ-Mittagessen am Flussufer", icon: "🔥" },
        { time: "15:00", activity: "Baden im kristallklaren Bergwasser", icon: "🏊" },
        { time: "17:30", activity: "Rückfahrt nach Side", icon: "🚌" },
      ],
    },
    {
      day: "Tag 3",
      title: "Strand & Schildkröten",
      icon: "🐢",
      color: "bg-yellow-100",
      dayCost: "~60 € (Fam. 4)",
      transport: "Zu Fuß / Dolmuş",
      meals: "Strandtaverne",
      stops: [
        { time: "08:30", activity: "Titreyengöl Lagune – Flamingos beobachten", icon: "🦩", tip: "Kinder sind von Flamingos und Reihern begeistert." },
        { time: "10:30", activity: "Ost-Strand Schildkröten-Schutzzone Spaziergang", icon: "🐢" },
        { time: "13:00", activity: "Mittagessen am Strandrestaurant", icon: "🍽️" },
        { time: "15:00", activity: "Strand & Schwimmen", icon: "🏖️" },
        { time: "17:30", activity: "Apollon-Tempel Besuch bei Abendlicht", icon: "🏛️" },
        { time: "19:30", activity: "Eis und Baklava in der Altstadtgasse", icon: "🍦" },
      ],
    },
  ],
  soloDays: [
    {
      day: "Tag 1",
      title: "Ruinen & Archäologie intensiv",
      icon: "🏛️",
      color: "bg-indigo-100",
      dayCost: "~30 €",
      transport: "Zu Fuß",
      meals: "Lokales Kebapçı",
      stops: [
        { time: "07:30", activity: "Antike Stadt bei Öffnung – Sonnenaufgang", icon: "🌅", tip: "Allein im antiken Theater bei Sonnenaufgang – eines der beeindruckendsten Erlebnisse der Türkei." },
        { time: "09:00", activity: "Alle Ruinen systematisch erkunden", icon: "🗺️" },
        { time: "11:30", activity: "Side Museum", icon: "🏛️" },
        { time: "14:00", activity: "Günstiges Mittagessen: Kebap im Lokal", icon: "🥙" },
        { time: "16:00", activity: "Strand schwimmen", icon: "🏊" },
        { time: "19:30", activity: "Apollon-Tempel Sonnenuntergang", icon: "🌅" },
      ],
    },
    {
      day: "Tag 2",
      title: "Manavgat & Wasserfall",
      icon: "💧",
      color: "bg-green-100",
      dayCost: "~35 €",
      transport: "Dolmuş nach Manavgat",
      meals: "Manavgat Markt + Flussgaststätte",
      stops: [
        { time: "09:00", activity: "Dolmuş nach Manavgat (15 Min.)", icon: "🚌" },
        { time: "09:30", activity: "Manavgat-Wasserfall – natürliches Wunder", icon: "💧", tip: "Trotz geringer Höhe (3m) ist die Breite und Wassermasse imposant." },
        { time: "11:00", activity: "Donnerstagmarkt (donnerstags) oder Stadtbummel", icon: "🛒" },
        { time: "13:00", activity: "Mittagessen am Flussufer mit frischem Fisch", icon: "🐟" },
        { time: "15:00", activity: "Rückfahrt + Strand in Side", icon: "🏖️" },
        { time: "19:00", activity: "Streetfood-Tour durch Side-Altstadt", icon: "🍡" },
      ],
    },
    {
      day: "Tag 3",
      title: "Aspendos Solo-Tagesausflug",
      icon: "🎭",
      color: "bg-stone-100",
      dayCost: "~45 €",
      transport: "Bus oder Sammeltaxi",
      meals: "Lokale Taverne Aspendos",
      stops: [
        { time: "08:00", activity: "Früher Bus/Sammeltaxi nach Aspendos", icon: "🚌" },
        { time: "09:30", activity: "Aspendos Theater bei Öffnung – allein im Theater", icon: "🎭", tip: "Um 9:30 Uhr ist man fast allein – ein unvergessliches Erlebnis." },
        { time: "11:30", activity: "Aquädukt von Aspendos erkunden", icon: "🌉" },
        { time: "13:30", activity: "Mittagessen in Serik (nahe Aspendos)", icon: "🍽️" },
        { time: "15:30", activity: "Rückfahrt nach Side", icon: "🚌" },
        { time: "18:00", activity: "Letztes Schwimmen am Westlichen Strand", icon: "🏊" },
        { time: "20:00", activity: "Abschluss-Abendessen am Apollon-Tempel", icon: "🌅" },
      ],
    },
  ],
};

export default content;
