import type { GuideContent } from "./_types";

const content: GuideContent = {
  monthlyNotes: [
    { label: "Januar",    emoji: "🌤️", text: "Mild und ruhig – perfekt für Wanderungen am Teide und Kulturbesuche in La Laguna." },
    { label: "Februar",   emoji: "🎭", text: "Karneval von Santa Cruz – einer der größten der Welt. Stimmung pur in der Hauptstadt." },
    { label: "März",      emoji: "🌸", text: "Frühling auf der Insel, Mandelbäume blühen. Ideal für Wanderungen im Anaga-Gebirge." },
    { label: "April",     emoji: "🏖️", text: "Vorsaison: angenehme 22 °C, wenig Trubel und günstige Preise." },
    { label: "Mai",       emoji: "🌊", text: "Wassersport-Saison beginnt. Wellen für Surfer in El Médano, ruhige Buchten im Süden." },
    { label: "Juni",      emoji: "🌞", text: "Hochsaison beginnt. Süden ist sonnig und warm, Norden gelegentlich mit Wolken." },
    { label: "Juli",      emoji: "☀️", text: "Heißester Monat. Siam Park und Playa de las Américas sind voll – früh losfahren." },
    { label: "August",    emoji: "🏄", text: "Hochsaison: Spitzenpreise, aber längste Tage und perfektes Badewetter." },
    { label: "September", emoji: "🍇", text: "Noch warm, deutlich ruhiger als im Sommer. Beste Zeit für Aktivurlaub." },
    { label: "Oktober",   emoji: "🌅", text: "Herbst-Highlights: La Laguna leuchtet golden, Wanderungen im Wald von La Esperanza." },
    { label: "November",  emoji: "🔭", text: "Teide-Sternenhimmel in bester Qualität. Stern-Touren buchen lohnt sich." },
    { label: "Dezember",  emoji: "🎄", text: "Mild mit 20 °C – idealer Winterurlaub. Weihnachtsfeierlichkeiten mit kanarischem Flair." },
  ],
  sights: [
    { title: "Teide Nationalpark & Pico del Teide", desc: "Der Teide ist mit 3.715 m der höchste Berg Spaniens und ein UNESCO-Weltnaturerbe. Die bizarre Mondlandschaft rund um den Vulkankegel gehört zu den eindrucksvollsten Naturschauplätzen Europas.", mapHref: "https://maps.google.com/?q=Teide+Nationalpark+Teneriffa", address: "Parque Nacional del Teide, Teneriffa", duration: "Ganztag", cost: "Seilbahn ab 27 €", tip: "Gipfelbesuch benötigt kostenlosen Permit – 3 Monate im Voraus online buchen!" },
    { title: "Loro Parque, Puerto de la Cruz", desc: "Einer der besten Zoos Europas mit spektakulären Orca-, Delfin- und Pinguinshows. Weltweite Naturschutzprojekte machen ihn zu mehr als einem gewöhnlichen Tierpark.", mapHref: "https://maps.google.com/?q=Loro+Parque+Puerto+de+la+Cruz", address: "Av. Loro Parque, Puerto de la Cruz", duration: "4–6 Std.", cost: "ab 39 €", tip: "Combo-Ticket mit Siam Park spart rund 15 €." },
    { title: "Siam Park, Adeje", desc: "Mehrfach ausgezeichnet als bester Wasserpark der Welt. Riesige Wellen, Lazy River und spektakuläre Rutschen für alle Altersgruppen.", mapHref: "https://maps.google.com/?q=Siam+Park+Teneriffa", address: "Av. Siam, Costa Adeje", duration: "Ganztag", cost: "ab 38 €", tip: "Dienstags und mittwochs ist es am ruhigsten." },
    { title: "Masca-Schlucht", desc: "Das pittoreske Bergdorf Masca liegt auf 650 m Höhe im Teno-Gebirge. Der Abstieg durch die wilde Schlucht bis zum Meer ist eine der schönsten Wanderungen Teneriffas.", mapHref: "https://maps.google.com/?q=Masca+Teneriffa", address: "Masca, Buenavista del Norte", duration: "5–6 Std.", cost: "Fähre zurück ca. 15 €", tip: "Permit ab April 2024 erforderlich – vorab online reservieren." },
    { title: "La Laguna (UNESCO-Weltkulturerbe)", desc: "Die ehemalige Hauptstadt Teneriffas ist seit 1999 UNESCO-Weltkulturerbe. Farbenfrohe Kolonialhäuser, lebendige Studenten-Atmosphäre und exzellente Restaurants machen sie zum kulturellen Herzstück der Insel.", mapHref: "https://maps.google.com/?q=La+Laguna+Teneriffa", address: "San Cristóbal de La Laguna", duration: "3–4 Std.", cost: "Kostenlos", tip: "Sonntagsmarkt und die Kathedrale sind Highlights." },
  ],
  history: [
    { year: "vor 50.000 J.", title: "Guanchen – die Ureinwohner", text: "Die Guanchen, Nachfahren nordafrikanischer Berber, besiedelten Teneriffa vor Zehntausenden Jahren. Sie lebten in Höhlen und einfachen Hütten, jagten Ziegen und kultivierten Gerste." },
    { year: "1494–1496", title: "Spanische Eroberung", text: "Nach zwei gescheiterten Versuchen (1494 scheiterte das Heer an der Schlucht von Acentejo) eroberte Alonso Fernández de Lugo 1496 die Insel für die Spanische Krone. Die Guanchen-Zivilisation wurde nahezu ausgelöscht." },
    { year: "1706", title: "Ausbruch des Teide", text: "Der letzte große Vulkanausbruch des Teide vernichtete mehrere Dörfer. Teneriffa liegt bis heute auf einem der aktivsten Vulkansysteme Europas." },
    { year: "1797", title: "Nelson scheitert in Santa Cruz", text: "Admiral Horatio Nelson griff Santa Cruz de Tenerife an – und verlor dabei seinen rechten Arm. Die Kanonenkugel, die ihn traf, wird in der Kirche Nuestra Señora de la Concepción aufbewahrt." },
    { year: "1970er", title: "Tourismus-Boom", text: "Mit dem Bau der großen Hotelanlagen im Süden begann Teneriffas Aufstieg zum Massentouristenziel. Costa Adeje und Los Cristianos wurden zur touristischen Hauptachse der Insel." },
    { year: "1997", title: "UNESCO-Welterbe", text: "Die Stadt La Laguna wurde als erstes koloniales Stadtensemble in Spanien zum UNESCO-Weltkulturerbe ernannt. Der Nationalpark Teide folgte 2007 als Weltnaturerbe." },
  ],
  food: [
    { emoji: "🥔", name: "Papas arrugadas con mojo", original: "Papas arrugadas", desc: "Das kanarische Nationalgericht: kleine, in Salzwasser gekochte Runzelkartoffeln mit Mojo rojo (scharf, Chili) oder Mojo verde (mild, Koriander).", price: "4–7 €", tip: "In jedem Restaurant, immer bestellen!" },
    { emoji: "🍞", name: "Gofio", original: "Gofio canario", desc: "Geröstetes Getreide- oder Maismehl – das Grundnahrungsmittel der Guanchen. Heute als Brot, Suppe oder Dessert serviert.", price: "3–5 €" },
    { emoji: "🍮", name: "Bienmesabe", original: "Bienmesabe", desc: "Süßes Mandelcreme-Dessert mit Honig und Zitronen. Typisch für die kanarische Küche und in vielen Cafés zu finden.", price: "3–5 €", tip: "Mit Helado (Eis) kombiniert ein Traum." },
    { emoji: "🐟", name: "Cherne & Vieja", original: "Pescado fresco", desc: "Frisch gegrillter Grouper (Cherne) oder Papageienfisch (Vieja) – die beliebtesten Fische auf Teneriffa. Am besten in den Fischerorten am Nordkap.", price: "12–20 €" },
    { emoji: "🍷", name: "Kanarischer Wein", original: "Vino de Tenerife", desc: "Teneriffa besitzt fünf geschützte Weinanbaugebiete. Besonders der Weißwein aus dem Orotava-Tal und der Rotwein aus Abona genießen internationales Ansehen.", price: "3–6 € (Glas)" },
  ],
  phrases: [
    { original: "¡Buenos días!", pronunciation: "bwenos días", translation: "Guten Morgen!" },
    { original: "¡Hola! / ¡Buenas!", pronunciation: "ola / bwenas", translation: "Hallo! / Hi!" },
    { original: "Gracias", pronunciation: "gratzias", translation: "Danke" },
    { original: "Por favor", pronunciation: "por fabor", translation: "Bitte" },
    { original: "¿Cuánto cuesta?", pronunciation: "kwanto kwesta", translation: "Was kostet das?" },
    { original: "La cuenta, por favor", pronunciation: "la kwenta por fabor", translation: "Die Rechnung, bitte" },
    { original: "¿Habla alemán?", pronunciation: "abla alemann", translation: "Sprechen Sie Deutsch?" },
    { original: "Necesito un médico", pronunciation: "netschesito un mediko", translation: "Ich brauche einen Arzt" },
    { original: "¡Salud!", pronunciation: "salud", translation: "Prost! / Gesundheit!" },
    { original: "¡Hasta luego!", pronunciation: "asta lwego", translation: "Tschüss! / Auf Wiedersehen!" },
  ],
  insider: [
    { icon: "🌋", title: "Teide um Sonnenaufgang", text: "Übernachte im Parador de las Cañadas del Teide und stehe um 6 Uhr früh auf. Der Sternenhimmel und der Sonnenaufgang über dem Wolkenmeer sind unvergesslich – und fast niemand ist da." },
    { icon: "🚌", title: "Günstig mit dem Bus reisen", text: "Das TITSA-Busnetz ist günstig und gut ausgebaut. Mit der 'Bono Bus'-Karte fährt man deutlich günstiger als mit Einzel-Tickets. Wer mobil ist, braucht kein Mietauto." },
    { icon: "🏖️", title: "Las Teresitas – der wahre Geheimtipp", text: "Der einzige natürliche Sandstrand im Norden (Sand aus der Sahara importiert) liegt direkt bei Santa Cruz und ist kaum touristisch erschlossen. Entspannt und authentisch." },
    { icon: "🍽️", title: "Mercado de Nuestra Señora de África", text: "Der Markt in Santa Cruz de Tenerife ist das kulinarische Herz der Insel. Frischer Fisch, lokaler Käse, Papas, Mojo und Tapas – authentisch, günstig, wunderschön." },
    { icon: "🌿", title: "Anaga-Gebirge – Urwald auf Teneriffa", text: "Der Nordosten der Insel ist mit dem Anaga Rural Park eine der botanisch vielfältigsten Regionen Europas. Schmale Pfade führen durch Nebelwälder – fast menschenleer." },
  ],
  beaches: [
    { name: "Las Teresitas", emoji: "🌴", desc: "Goldener Sandstrand nahe Santa Cruz mit ruhigem Wasser – ideal für Familien.", type: "Sandstrand", tip: "Sahara-Sand, kostenlos, kein Touristen-Rummel." },
    { name: "Playa del Duque", emoji: "🏖️", desc: "Exklusiver Sandstrand in Costa Adeje, ruhig und gut gepflegt.", type: "Sandstrand", tip: "Liegestühle teuer – früh kommen und guten Platz sichern." },
    { name: "Los Gigantes", emoji: "🌊", desc: "Dramatischer schwarzer Vulkanstrand unter 600 m hohen Steilklippen. Einer der beeindruckendsten Anblicke Teneriffas.", type: "Vulkanstrand", tip: "Bootstouren zu Delfinen und Walen direkt ab hier." },
    { name: "El Médano", emoji: "🏄", desc: "Der Surf- und Kitesurfer-Hotspot Teneriffas im Südosten mit konstantem Wind.", type: "Windstrand", tip: "Besonders im Winter tolle Wellen, Surfen für alle Level." },
    { name: "Playa de las Américas", emoji: "🎉", desc: "Touristischer Hauptstrand im Süden, belebt, mit Infrastruktur und Strandrestaurants.", type: "Sandstrand" },
  ],
  regions: [
    { name: "Costa Adeje & Los Cristianos", emoji: "🏨", desc: "Das touristische Herz Teneriffas im Süden. Große Hotelanlagen, Siam Park, Shoppingmeilen und lebendige Bars.", highlights: ["Siam Park", "Playa del Duque", "Whale watching"] },
    { name: "Puerto de la Cruz", emoji: "🌺", desc: "Die traditionelle Urlaubshauptstadt im Norden. Charmanter, grüner und authentischer als der Süden – mit Loro Parque.", highlights: ["Loro Parque", "Jardín Botánico", "Lago Martiánez"] },
    { name: "Teide-Nationalpark", emoji: "🌋", desc: "Das UNESCO-Welterbe und Herzstück der Insel. Vulkankegel, rote Lavafelder und das Meer aus Wolken.", highlights: ["Pico del Teide", "Roques de García", "Sternenhimmel"] },
    { name: "La Laguna & Anaga", emoji: "🏛️", desc: "Die kulturelle Seele Teneriffas. UNESCO-Altstadt und der üppig grüne Anaga-Urwald.", highlights: ["Koloniale Altstadt", "Anaga Rural Park", "Märkte"] },
  ],
  budget: [
    { label: "Unterkunft (pro Nacht)", budget: "30–60 €", mid: "60–150 €", luxury: "150–400 €+" },
    { label: "Essen (pro Tag)", budget: "15–25 €", mid: "30–50 €", luxury: "60–120 €+" },
    { label: "Transport (pro Tag)", budget: "3–8 € (Bus)", mid: "15–30 € (Taxi)", luxury: "50–80 € (Mietwagen)" },
    { label: "Aktivitäten (pro Tag)", budget: "0–10 €", mid: "20–50 €", luxury: "80–200 €+" },
    { label: "Tagesbudget gesamt", budget: "50–100 €", mid: "120–230 €", luxury: "300–800 €+" },
  ],
  emergency: { police: "091", ambulance: "112", fire: "080", embassy: "+34 928 256 500 (Konsulat Las Palmas)", hospital: "Hospital Universitario de Canarias: +34 922 678 000" },
  couplesDays: [
    { day: "Tag 1", title: "Teide & Sonnenuntergang über den Wolken", icon: "🌋", color: "bg-orange-100", dayCost: "~55 €", transport: "Mietwagen empfohlen", meals: "Parador-Restaurant", stops: [
      { time: "08:00", activity: "Fahrt in den Teide-Nationalpark", icon: "🚗", tip: "Früh losstarten, um die besten Parkplätze zu bekommen" },
      { time: "10:00", activity: "Seilbahn auf den Teide", icon: "🚠", tip: "Mit Permit weiter zum Gipfel (3.715 m) – Ausblick überragend" },
      { time: "13:00", activity: "Mittagessen im Parador de las Cañadas", icon: "🍽️" },
      { time: "15:00", activity: "Wanderung zu den Roques de García", icon: "🥾", tip: "1,5 km Rundweg, kostenlos, spektakuläre Felsformationen" },
      { time: "18:00", activity: "Sonnenuntergang über dem Wolkenmeer", icon: "🌅", tip: "Einer der schönsten Sonnenuntergänge Europas" },
    ]},
    { day: "Tag 2", title: "Masca-Schlucht & Nordkap", icon: "🏔️", color: "bg-emerald-100", dayCost: "~45 €", transport: "Mietwagen (Serpentinen!)", meals: "Fischrestaurant Buenavista", stops: [
      { time: "09:00", activity: "Fahrt nach Masca (Teno-Gebirge)", icon: "🚗", tip: "Serpentinen – gemächlich fahren und Ausblicke genießen" },
      { time: "10:30", activity: "Dorf Masca erkunden", icon: "🏘️" },
      { time: "11:30", activity: "Abstieg durch die Masca-Schlucht", icon: "🥾", tip: "Gutes Schuhwerk und Wasser mitnehmen – 3 h Abstieg" },
      { time: "15:00", activity: "Fähre ab Masca-Strand (zurück nach Masca-Dorf)", icon: "⛴️" },
      { time: "18:00", activity: "Romantisches Fisch-Dinner in Buenavista", icon: "🐟" },
    ]},
    { day: "Tag 3", title: "La Laguna & Anaga-Urwald", icon: "🌿", color: "bg-teal-100", dayCost: "~30 €", transport: "Bus oder Taxi", meals: "La Laguna Marktrestaurant", stops: [
      { time: "10:00", activity: "Bummel durch La Laguna Altstadt", icon: "🏛️", tip: "UNESCO-Weltkulturerbe – farbenfrohe Kolonialarchitektur" },
      { time: "12:30", activity: "Mittagessen auf dem Mercado de La Laguna", icon: "🍽️" },
      { time: "14:00", activity: "Fahrt in den Anaga Rural Park", icon: "🚗" },
      { time: "15:00", activity: "Wanderung im Nebelwald (Cruz del Carmen)", icon: "🌿", tip: "Einer der letzten Lorbeer-Urwälder Europas" },
      { time: "18:00", activity: "Tapas und Wein in Santa Cruz", icon: "🍷" },
    ]},
  ],
  familiesDays: [
    { day: "Tag 1", title: "Siam Park – bester Wasserpark der Welt", icon: "🌊", color: "bg-blue-100", dayCost: "~160 € (Familie 4 P.)", transport: "Bus oder Taxi ab Hotel", meals: "Im Park + Abendessen", stops: [
      { time: "10:00", activity: "Siam Park öffnet – sofort rein!", icon: "🎢", tip: "Dienstags/mittwochs ruhiger – weniger Wartezeiten" },
      { time: "13:00", activity: "Mittagessen im Park", icon: "🍔" },
      { time: "16:00", activity: "Lazy River & Kinderbad", icon: "🏊", tip: "Für kleinere Kinder gibt es flache Spielbereiche" },
      { time: "18:00", activity: "Abendessen in Los Cristianos", icon: "🍽️" },
    ]},
    { day: "Tag 2", title: "Loro Parque & Puerto de la Cruz", icon: "🦜", color: "bg-yellow-100", dayCost: "~130 €", transport: "Bus TF-325 ab Sur", meals: "In Puerto de la Cruz", stops: [
      { time: "10:00", activity: "Loro Parque – Orca- und Delfin-Shows", icon: "🐬", tip: "Shows pünktlich sein – besonders die Orcarshow ist beliebt" },
      { time: "13:00", activity: "Mittagessen im Park", icon: "🍽️" },
      { time: "15:30", activity: "Lago Martiánez – Naturschwimmbäder", icon: "🌊", tip: "César-Manrique-Design, Meerwasser, bezahlbarer Eintritt" },
      { time: "18:00", activity: "Eisessen in Puerto de la Cruz", icon: "🍦" },
    ]},
    { day: "Tag 3", title: "Teide Nationalpark mit Kindern", icon: "🌋", color: "bg-red-100", dayCost: "~70 €", transport: "Mietwagen", meals: "Picknick + Parador", stops: [
      { time: "09:00", activity: "Fahrt in den Nationalpark", icon: "🚗" },
      { time: "10:30", activity: "Seilbahn (Kinder unter 12 kostenlos!)", icon: "🚠" },
      { time: "12:00", activity: "Picknick an den Roques de García", icon: "🧺" },
      { time: "14:00", activity: "Besucherzentrum El Portillo", icon: "🏛️", tip: "Kostenlos, interaktive Ausstellung über Vulkane" },
      { time: "16:00", activity: "Lavafeld-Spaziergang", icon: "🥾" },
    ]},
  ],
  soloDays: [
    { day: "Tag 1", title: "Surfen in El Médano & Küstenroute", icon: "🏄", color: "bg-sky-100", dayCost: "~40 €", transport: "Bus oder Mietwagen", meals: "Strandcafé", stops: [
      { time: "09:00", activity: "Surfstunde buchen in El Médano", icon: "🏄", tip: "Anfängerkurse ab 30 € p.P., ideale Wellen für Einsteiger" },
      { time: "13:00", activity: "Mittagessen am Strand", icon: "🍽️" },
      { time: "15:00", activity: "Küstenspaziergang nach Los Abrigos", icon: "🚶" },
      { time: "17:00", activity: "Fischerhafen Los Abrigos", icon: "⛵", tip: "Bestes Fischrestaurant der Region: El Cardon" },
    ]},
    { day: "Tag 2", title: "Alleinwanderer: Teide Umrundung", icon: "🥾", color: "bg-stone-100", dayCost: "~25 €", transport: "Bus 342 ab Santa Cruz", meals: "Selbstversorgung", stops: [
      { time: "07:00", activity: "Bus nach Las Cañadas del Teide", icon: "🚌", tip: "Wasser, Snacks und Sonnencreme einpacken" },
      { time: "09:00", activity: "Wanderweg Nº7 – Boca Tauce", icon: "🥾" },
      { time: "12:00", activity: "Lavafelder von Llano de Ucanca", icon: "🌋" },
      { time: "15:00", activity: "Roques de García Aussichtspunkt", icon: "📸" },
      { time: "17:00", activity: "Bus zurück nach Santa Cruz", icon: "🚌" },
    ]},
    { day: "Tag 3", title: "Santa Cruz entdecken & Nachtleben", icon: "🎭", color: "bg-purple-100", dayCost: "~50 €", transport: "Zu Fuß & Bus", meals: "Mercado + Tapas-Bar", stops: [
      { time: "10:00", activity: "Mercado de Nuestra Señora de África", icon: "🛒", tip: "Frühstücken mit lokalem Käse, Mojo und frischen Säften" },
      { time: "12:00", activity: "Museum für Natur und Mensch", icon: "🏛️" },
      { time: "14:00", activity: "Tapas in La Noria Barrio", icon: "🍷" },
      { time: "17:00", activity: "Spaziergang am Rambla de Santa Cruz", icon: "🌳" },
      { time: "21:00", activity: "Barhopping im Barrio del Principe", icon: "🎶" },
    ]},
  ],
};

export default content;
