import { DestinationConfig, TiqetsNiche, EntryInfo, ClimateMonth } from "@/types";

// heroImage: lokaler Pfad → Bilder in /public/images/destinations/ ablegen
// heroImageFallback: Unsplash-Platzhalter bis eigene Bilder da sind
export const destinations: DestinationConfig[] = [
  {
    slug: "antalya",
    name: "Antalya",
    regionIds: [126, 133, 129],
    country: "Türkei",
    heroImage: "/images/destinations/antalya-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1600&q=80",
    cardImage: "/images/destinations/antalya-card.jpg",
    description: "Antalya – die Perle der türkischen Riviera. Türkisblaues Meer, antike Ruinen und erstklassige Hotels erwarten euch.",
    metaTitle: "Antalya Urlaub – All Inclusive buchen",
    metaDescription: "Antalya Urlaub günstig buchen: Pauschalreisen ✓ All Inclusive ✓ Last Minute Türkei ✓ Jetzt Angebote vergleichen & Traumurlaub an der türkischen Riviera buchen!",
    guideSlug: "reisefuehrer-antalya",
    iataCode: "AYT",
    ibeBpRegion: "turkey",
    ibeRegionId: "149",
    ibeCityId: "930",
    tiqetsCityId: "78987",
    tiqetsNiches: [
      {
        slug: "outdoor-abenteuer",
        label: "Outdoor & Abenteuer",
        keywords: "canyon|zipline|rafting|klettern|paragliding|quad|jeep|abenteuer|bootstour|bootsfahrt|safari|tauchen",
        metaTitle: "Outdoor & Abenteuer in Antalya – Tickets günstig buchen",
        metaDescription: "Jeep-Safari, Canyoning, Paragliding & mehr – die besten Outdoor-Aktivitäten in Antalya günstig buchen. ✓ Sofortbuchung ✓ Gratis Storno ✓ Top-Bewertungen.",
        h1: "Outdoor & Abenteuer in Antalya",
        intro: "Antalya ist nicht nur für seine Strände bekannt – die Region bietet auch atemberaubende Outdoor-Erlebnisse. Ob Jeep-Safari durch die Berge, Paragliding über dem Mittelmeer oder Canyoning in wilden Schluchten: Hier kommt jeder Abenteurer auf seine Kosten.",
      },
      {
        slug: "ausfluege-touren",
        label: "Ausflüge & Touren",
        keywords: "tagesausflug|ausflug|tour|rundfahrt|jeep|safari|bootsfahrt|bootstour|kurs|erlebnis",
        metaTitle: "Ausflüge & Touren ab Antalya – Tagestouren buchen",
        metaDescription: "Tagesausflüge & geführte Touren ab Antalya günstig buchen. ✓ Bootstouren ✓ Jeep-Safaris ✓ Stadtführungen ✓ Sofortbuchung & Gratis Storno.",
        h1: "Ausflüge & Touren ab Antalya",
        intro: "Entdecke die Umgebung von Antalya mit geführten Tagestouren und spannenden Ausflügen. Von Bootsfahrten entlang der Küste bis zu Jeep-Safaris durch den Taurus – hier ist für jeden Geschmack etwas dabei.",
      },
      {
        slug: "wassersport-strand",
        label: "Wassersport & Strand",
        keywords: "aquapark|wasserpark|jet ski|jetski|wakeboard|schnorchel|tauchen|surfen|kayak|kajak|strand|beach|swim",
        metaTitle: "Wassersport & Strandaktivitäten in Antalya buchen",
        metaDescription: "Wassersport in Antalya: Aquaparks, Jet-Ski, Schnorcheln, Paragliding & mehr günstig buchen. ✓ Spaß für die ganze Familie ✓ Sofortbuchung.",
        h1: "Wassersport & Strandaktivitäten in Antalya",
        intro: "Das kristallklare Mittelmeer vor Antalyas Küste lädt zu allem ein: Schnorcheln, Tauchen, Jet-Ski-Fahren oder einfach einen aufregenden Tag im Aquapark verbringen – Wasserspaß ist in Antalya garantiert.",
      },
      {
        slug: "kulturerlebnisse",
        label: "Kultur & Sehenswürdigkeiten",
        keywords: "museum|aspendos|perge|thermessos|antik|historisch|altstadt|roman|ruinen|kulturell|konyaaltı|besichtig",
        metaTitle: "Kulturerlebnisse & Sehenswürdigkeiten in Antalya buchen",
        metaDescription: "Kulturelle Highlights in Antalya: Antike Ruinen, Museen & Altstadt-Touren günstig buchen. ✓ Geführte Besichtigungen ✓ Geschichte erleben ✓ Sofortbuchung.",
        h1: "Kultur & Sehenswürdigkeiten in Antalya",
        intro: "Antalya blickt auf eine über 2.000-jährige Geschichte zurück. Besuche das gut erhaltene Amphitheater von Aspendos, die antike Stadt Perge oder flaniere durch die charmante Altstadt Kaleiçi – Geschichte zum Anfassen.",
      },
    ] as TiqetsNiche[],
    faqs: [
      {
        question: "Wann ist die beste Reisezeit für Antalya?",
        answer: "Die beste Reisezeit für Antalya ist von Mai bis Oktober. Juli und August sind mit bis zu 35 °C am heißesten. Für angenehmere Temperaturen empfehlen sich Mai, Juni oder September – mit viel Sonne und weniger Trubel.",
      },
      {
        question: "Brauche ich ein Visum für einen Antalya Urlaub?",
        answer: "Deutsche Staatsbürger benötigen für die Türkei ein e-Visum, das online über das offizielle Portal beantragt werden kann. Es kostet ca. 35 USD und ist für 90 Tage gültig. Ein gültiger Reisepass (mindestens 6 Monate über das Reisedatum hinaus) ist erforderlich.",
      },
      {
        question: "Was kostet eine Pauschalreise nach Antalya?",
        answer: "Pauschalreisen nach Antalya sind schon ab ca. 350 € pro Person (inkl. Flug & Hotel, 7 Nächte) erhältlich. All-Inclusive-Angebote starten ab ca. 500 € p.P. Die Preise variieren je nach Reisezeitraum, Hotel-Kategorie und Abflughafen.",
      },
      {
        question: "Welcher Flughafen liegt nah an Antalya?",
        answer: "Der internationale Flughafen Antalya (IATA: AYT) liegt nur etwa 13 km vom Stadtzentrum entfernt. Von Deutschland aus gibt es Direktflüge u.a. ab Frankfurt, München, Düsseldorf, Berlin und Hamburg – Flugzeit ca. 3,5 Stunden.",
      },
      {
        question: "Lohnt sich All-Inclusive in Antalya?",
        answer: "Ja – Antalya ist weltweit für seine hervorragenden All-Inclusive-Resorts bekannt. Gerade an der Türkischen Riviera (Belek, Side, Alanya) bieten 4- und 5-Sterne-Hotels ausgezeichnetes AI-Angebot zu fairen Preisen. Ideal für Familien und Paare.",
      },
    ],
    entryInfo: {
      visa: "E-Visum erforderlich (ca. 35 USD, online unter evisa.gov.tr beantragen). Reisepass mind. 6 Monate gültig.",
      currency: "Türkische Lira (TRY). Kreditkarten werden in Hotels und Restaurants weitgehend akzeptiert. Wechselgeld in TRY empfohlen.",
      language: "Türkisch. In Touristengebieten wird häufig Englisch und Deutsch gesprochen.",
      timezone: "UTC+3 (keine Sommerzeit). Türkei ist 2 Stunden vor Deutschland (Winter) bzw. 1 Stunde vor (Sommer).",
      voltage: "220 V, 50 Hz. Steckdosen Typ F (Schuko) – deutsche Stecker passen direkt.",
      health: "Krankenversicherung mit Auslandsschutz empfohlen. Keine Pflichtimpfungen für EU-Bürger. Sonnenschutz und Wasservorsicht beachten.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 14, tempLow: 6, rain: 240 },
      { month: "Feb", tempHigh: 15, tempLow: 7, rain: 170 },
      { month: "Mär", tempHigh: 18, tempLow: 9, rain: 105 },
      { month: "Apr", tempHigh: 22, tempLow: 13, rain: 50 },
      { month: "Mai", tempHigh: 27, tempLow: 17, rain: 25 },
      { month: "Jun", tempHigh: 32, tempLow: 22, rain: 5 },
      { month: "Jul", tempHigh: 35, tempLow: 25, rain: 2 },
      { month: "Aug", tempHigh: 35, tempLow: 25, rain: 2 },
      { month: "Sep", tempHigh: 31, tempLow: 21, rain: 18 },
      { month: "Okt", tempHigh: 25, tempLow: 16, rain: 70 },
      { month: "Nov", tempHigh: 19, tempLow: 11, rain: 150 },
      { month: "Dez", tempHigh: 15, tempLow: 8, rain: 230 },
    ] as ClimateMonth[],
    carLocationKey: "AS.TR.07.AYT.AYT",
    coordinates: { lat: 36.8969, lng: 30.7133 },
  },
  {
    slug: "mallorca",
    name: "Mallorca",
    regionIds: [1, 2, 3],
    country: "Spanien",
    heroImage: "/images/destinations/mallorca-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=1600&q=80",
    cardImage: "/images/destinations/mallorca-card.jpg",
    description: "Mallorca – die größte Baleareninsel mit traumhaften Stränden, malerischen Dörfern und leckerem Essen.",
    metaTitle: "Mallorca Urlaub 2026 – günstig buchen",
    metaDescription: "Günstige Mallorca Pauschalreisen ✓ All-Inclusive ✓ Last-Minute ✓ Jetzt Angebote vergleichen und Traumurlaub auf den Balearen buchen.",
    iataCode: "PMI",
    ibeBpRegion: "eu",
    ibeRegionId: "133",
    tiqetsCityId: "65915",
    tiqetsNiches: [
      {
        slug: "museen-kultur",
        label: "Museen & Kultur",
        keywords: "museum|kathedrale|palast|almudaina|miró|miro|nadal|galerie|kunst|kultur|denkmal|fundació",
        metaTitle: "Museen & Kultur auf Mallorca – Eintrittskarten günstig buchen",
        metaDescription: "Die schönsten Museen & Kulturhighlights auf Mallorca entdecken: Kathedrale La Seu, Fundació Miró, Königspalast & mehr. ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Museen & Kultur auf Mallorca",
        intro: "Mallorca hat weit mehr zu bieten als Strand und Sonne. Die gotische Kathedrale La Seu, das Fundació Miró Mallorca und der beeindruckende Königspalast La Almudaina laden zu unvergesslichen Kulturerlebnissen ein.",
      },
      {
        slug: "ausfluege-natur",
        label: "Ausflüge & Natur",
        keywords: "segeln|boot|segeltörn|höhle|garten|ausflug|tour|hop-on|quad|sóller|natur|wandern|alfabia|campanet",
        metaTitle: "Ausflüge & Natur auf Mallorca – Touren günstig buchen",
        metaDescription: "Mallorca Ausflüge & Naturerlebnisse: Segeltörns, Höhlen, Hop-on Hop-off & Quad-Touren günstig buchen. ✓ Kleine Gruppen ✓ Sofortbuchung ✓ Top-Bewertungen.",
        h1: "Ausflüge & Natur auf Mallorca",
        intro: "Von romantischen Segeltörns entlang der Küste bis zu mystischen Tropfsteinhöhlen und üppigen Gärten – Mallorca bietet atemberaubende Naturerlebnisse und spannende Ausflüge für die ganze Familie.",
      },
      {
        slug: "familien-freizeitparks",
        label: "Familie & Freizeitparks",
        keywords: "aquarium|marineland|waterpark|wasserpark|dinosaur|dino|western|palma aquarium|tierpark|freizeitpark|abenteuerpark|katmandu",
        metaTitle: "Familienaktivitäten & Freizeitparks auf Mallorca buchen",
        metaDescription: "Freizeitparks, Aquarien & Familienattraktionen auf Mallorca günstig buchen: Palma Aquarium, Marineland, Western Water Park & mehr. ✓ Spaß für Kinder & Erwachsene.",
        h1: "Familienaktivitäten & Freizeitparks auf Mallorca",
        intro: "Mallorca ist perfekt für Familien! Das Palma Aquarium mit Europas tiefster Haifischbecken, Marineland mit Delfinen und Pinguinen sowie abenteuerliche Freizeitparks sorgen für unvergessliche Urlaubserinnerungen.",
      },
    ] as TiqetsNiche[],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten überall akzeptiert. Spanien hat kein Trinkgeldpflicht, aber 10 % ist üblich.",
      language: "Katalanisch & Spanisch. In Touristengebieten weit verbreitet: Englisch, Deutsch.",
      timezone: "UTC+1 / UTC+2 (Sommerzeit). Gleiche Zeitzone wie Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC/EHIC) wird akzeptiert. Sunscreen empfohlen. Leitungswasser trinkbar.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 15, tempLow: 8, rain: 40 },
      { month: "Feb", tempHigh: 16, tempLow: 8, rain: 35 },
      { month: "Mär", tempHigh: 18, tempLow: 10, rain: 40 },
      { month: "Apr", tempHigh: 20, tempLow: 12, rain: 45 },
      { month: "Mai", tempHigh: 24, tempLow: 16, rain: 30 },
      { month: "Jun", tempHigh: 28, tempLow: 20, rain: 15 },
      { month: "Jul", tempHigh: 31, tempLow: 23, rain: 5 },
      { month: "Aug", tempHigh: 31, tempLow: 23, rain: 10 },
      { month: "Sep", tempHigh: 28, tempLow: 20, rain: 40 },
      { month: "Okt", tempHigh: 23, tempLow: 16, rain: 70 },
      { month: "Nov", tempHigh: 18, tempLow: 12, rain: 60 },
      { month: "Dez", tempHigh: 15, tempLow: 9, rain: 50 },
    ] as ClimateMonth[],
    carLocationKey: "AS.ES.07.PMI.PMI",
    coordinates: { lat: 39.6953, lng: 3.0176 },
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    regionIds: [200, 201],
    country: "Spanien",
    heroImage: "/images/destinations/barcelona-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1600&q=80",
    cardImage: "/images/destinations/barcelona-card.jpg",
    description: "Barcelona – Gaudí, Tapas und Strand. Die katalanische Metropole begeistert mit Architektur, Kultur und Mittelmeer-Flair.",
    metaTitle: "Barcelona Urlaub – Städtereise buchen",
    metaDescription: "Günstige Barcelona Städtereisen ✓ Kurzurlaub ✓ Jetzt Angebote vergleichen und die katalanische Metropole entdecken.",
    iataCode: "BCN",
    ibeBpRegion: "eu",
    ibeRegionId: "100027",
    ibeCityId: "587",
    tiqetsCityId: "66342",
    tiqetsNiches: [
      {
        slug: "gaudi-architektur",
        label: "Gaudí & Architektur",
        keywords: "gaudí|gaudi|sagrada|güell|guell|batlló|batllo|pedrera|milà|mila|casa|palau",
        metaTitle: "Gaudí Sehenswürdigkeiten in Barcelona – Tickets günstig buchen",
        metaDescription: "Sagrada Família, Park Güell, Casa Batlló & mehr – Eintrittskarten für Gaudís Meisterwerke in Barcelona günstig buchen. ✓ Skip-the-Line ✓ Sofortbuchung.",
        h1: "Gaudí & Architektur in Barcelona",
        intro: "Kein Besuch Barcelonas ist vollständig ohne Antoni Gaudís architektonische Meisterwerke. Von der unvollendeten Sagrada Família über den bunten Park Güell bis zum atemberaubenden Casa Batlló – entdecke die Ikonen des katalanischen Modernismus.",
        tiqetsCategoryPath: "/sehenswuerdigkeiten-t435/",
      },
      {
        slug: "museen-kunst",
        label: "Museen & Kunst",
        keywords: "museum|moco|aquarium|zoo|kunst|galerie|fc barcelona|camp nou|picasso|historisches",
        metaTitle: "Museen & Kunst in Barcelona – Eintrittskarten günstig buchen",
        metaDescription: "Die besten Museen in Barcelona: Moco Museum, FC Barcelona Museum, Barcelona Aquarium & mehr günstig buchen. ✓ Gratis Storno ✓ Skip-the-Line Tickets.",
        h1: "Museen & Kunst in Barcelona",
        intro: "Barcelona ist eine Welthauptstadt der Kunst und Kultur. Das innovative Moco Museum, das legendäre Camp Nou, das faszinierende Barcelona Aquarium und unzählige weitere Museen machen die Stadt zu einem Paradies für Kulturliebhaber.",
      },
      {
        slug: "stadttouren",
        label: "Stadttouren",
        keywords: "hop-on|hop off|city tour|stadtführung|audioguide|audio guide|bus|sightseeing|guided|führung|rundfahrt",
        metaTitle: "Stadttouren Barcelona – Hop-on Hop-off & Geführte Touren buchen",
        metaDescription: "Barcelona Stadttouren günstig buchen: Hop-on Hop-off Bus, geführte Touren, Audioguides & mehr. ✓ Sofortbuchung ✓ Top-Bewertungen ✓ Gratis Storno.",
        h1: "Stadttouren in Barcelona",
        intro: "Entdecke Barcelona auf deine Art: Mit dem klassischen Hop-on Hop-off Bus hältst du an den schönsten Sehenswürdigkeiten, geführte Touren bringen dir die Geschichte der Stadt näher, und mit Audioguide-Apps erkundest du die Metropole in deinem eigenen Tempo.",
      },
      {
        slug: "sport-fc-barcelona",
        label: "Sport & FC Barcelona",
        keywords: "fc barcelona|camp nou|fútbol|fußball|sport|montjuïc|seilbahn|stadion|museum fc|barcelon",
        metaTitle: "FC Barcelona & Sport-Aktivitäten in Barcelona – Tickets buchen",
        metaDescription: "FC Barcelona Tickets, Camp Nou Tour, Montjuïc Seilbahn & Sportaktivitäten in Barcelona günstig buchen. ✓ Sofortbuchung ✓ Offizielle Tickets ✓ Top-Bewertungen.",
        h1: "Sport & FC Barcelona in Barcelona",
        intro: "Für Fußballfans ist eine Besichtigung des Camp Nou und des FC Barcelona Museums ein absolutes Muss. Darüber hinaus bietet Barcelona mit der Montjuïc-Seilbahn, Strand-Sports und vielen weiteren Aktivitäten Erlebnisse für jeden Sportbegeisterten.",
      },
      {
        slug: "barcelona-pass-citycard",
        label: "City Pässe & Kombi-Tickets",
        keywords: "pass|card|karte|kombi|bundle|essentials|hola|paket|kombiniert|transport|öpnv",
        metaTitle: "Barcelona City Pass & Kombi-Tickets – Günstig & Flexibel buchen",
        metaDescription: "Barcelona Pass, Hola Barcelona Card & Kombi-Tickets günstig buchen. Mit einem Pass Öffis + Attraktionen sparen. ✓ Sofortbuchung ✓ Gratis Storno ✓ Top-Angebote.",
        h1: "City Pässe & Kombi-Tickets für Barcelona",
        intro: "Mit einem Barcelona City Pass oder der Hola Barcelona Card sparst du doppelt: Du erhältst freien Eintritt oder Rabatte bei den beliebtesten Attraktionen und nutzt dabei bequem und kostenlos den öffentlichen Nahverkehr. Ideal für Kurzentschlossene und Vielseher.",
      },
    ] as TiqetsNiche[],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten überall akzeptiert. Restaurants: 10 % Trinkgeld ist üblich.",
      language: "Katalanisch & Spanisch. Englisch in der Tourismusbranche weit verbreitet.",
      timezone: "UTC+1 / UTC+2 (Sommerzeit). Gleiche Zeitzone wie Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Leitungswasser ist trinkbar.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 13, tempLow: 6, rain: 45 },
      { month: "Feb", tempHigh: 14, tempLow: 7, rain: 40 },
      { month: "Mär", tempHigh: 16, tempLow: 9, rain: 50 },
      { month: "Apr", tempHigh: 18, tempLow: 11, rain: 55 },
      { month: "Mai", tempHigh: 22, tempLow: 15, rain: 55 },
      { month: "Jun", tempHigh: 26, tempLow: 19, rain: 35 },
      { month: "Jul", tempHigh: 28, tempLow: 22, rain: 25 },
      { month: "Aug", tempHigh: 28, tempLow: 22, rain: 45 },
      { month: "Sep", tempHigh: 25, tempLow: 19, rain: 70 },
      { month: "Okt", tempHigh: 21, tempLow: 15, rain: 90 },
      { month: "Nov", tempHigh: 16, tempLow: 10, rain: 65 },
      { month: "Dez", tempHigh: 13, tempLow: 7, rain: 55 },
    ] as ClimateMonth[],
    carLocationKey: "AS.ES.06.BCN.BCN",
    coordinates: { lat: 41.3851, lng: 2.1734 },
  },
  {
    slug: "kreta",
    name: "Kreta",
    regionIds: [50, 51, 52],
    country: "Griechenland",
    heroImage: "/images/destinations/kreta-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1600&q=80",
    cardImage: "/images/destinations/kreta-card.jpg",
    description: "Kreta – die größte griechische Insel mit wilden Schluchten, goldenen Stränden und jahrtausendealter Geschichte.",
    metaTitle: "Kreta Urlaub – Pauschalreise buchen",
    metaDescription: "Günstige Kreta Pauschalreisen ✓ All-Inclusive ✓ Last-Minute ✓ Jetzt Angebote vergleichen und Griechenlands größte Insel erleben.",
    iataCode: "HER",
    ibeBpRegion: "eu",
    ibeRegionId: "46",
    tiqetsCityId: "38",
    tiqetsNiches: [
      {
        slug: "geschichte-archaeologie",
        label: "Geschichte & Archäologie",
        keywords: "knossos|minoisch|minoer|museum|archäolog|antik|byzantin|palast|festung|ruinen|minoan",
        metaTitle: "Geschichte & Archäologie auf Kreta – Tickets günstig buchen",
        metaDescription: "Kreta entdecken: Knossos, minoische Paläste, archäologische Museen & mehr günstig buchen. ✓ Sofortbuchung ✓ Gratis Storno ✓ Führungen auf Deutsch.",
        h1: "Geschichte & Archäologie auf Kreta",
        intro: "Kreta ist die Wiege der minoischen Zivilisation, einer der ältesten Hochkulturen Europas. Der Palast von Knossos, eindrucksvolle archäologische Museen und byzantinische Festungen machen die Insel zu einem Paradies für Geschichtsbegeisterte.",
      },
      {
        slug: "outdoor-natur",
        label: "Outdoor & Natur",
        keywords: "wandern|schlucht|gorge|strand|boot|segeln|kajak|natur|weinverkostung|wein|outdoor|tauchen|schnorcheln",
        metaTitle: "Outdoor & Natur auf Kreta – Aktivitäten günstig buchen",
        metaDescription: "Outdoor-Aktivitäten auf Kreta: Schluchten-Wanderungen, Segeln, Weinverkostungen & mehr günstig buchen. ✓ Unvergessliche Erlebnisse ✓ Sofortbuchung.",
        h1: "Outdoor & Natur auf Kreta",
        intro: "Kreta begeistert mit wilder Natur und vielfältigen Outdoor-Erlebnissen. Wandere durch die beeindruckende Samaria-Schlucht, erkunde die Küste per Boot oder genieße eine authentische kretische Weinverkostung inmitten atemberaubender Landschaft.",
      },
    ] as TiqetsNiche[],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten werden in Hotels und größeren Restaurants akzeptiert. Bargeld für kleine Tavernen empfohlen.",
      language: "Griechisch. In Touristengebieten wird Englisch und Deutsch häufig gesprochen.",
      timezone: "UTC+2 / UTC+3 (Sommerzeit). Kreta ist im Sommer 1 Stunde vor Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Sonnenschutz wichtig. Leitungswasser trinkbar in Städten.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 15, tempLow: 9, rain: 105 },
      { month: "Feb", tempHigh: 16, tempLow: 9, rain: 88 },
      { month: "Mär", tempHigh: 18, tempLow: 11, rain: 52 },
      { month: "Apr", tempHigh: 21, tempLow: 14, rain: 22 },
      { month: "Mai", tempHigh: 25, tempLow: 18, rain: 10 },
      { month: "Jun", tempHigh: 29, tempLow: 22, rain: 5 },
      { month: "Jul", tempHigh: 31, tempLow: 24, rain: 1 },
      { month: "Aug", tempHigh: 31, tempLow: 24, rain: 2 },
      { month: "Sep", tempHigh: 28, tempLow: 21, rain: 20 },
      { month: "Okt", tempHigh: 24, tempLow: 17, rain: 52 },
      { month: "Nov", tempHigh: 20, tempLow: 13, rain: 82 },
      { month: "Dez", tempHigh: 16, tempLow: 10, rain: 100 },
    ] as ClimateMonth[],
    carLocationKey: "AS.GR.07.HER.HER",
    coordinates: { lat: 35.3387, lng: 25.1442 },
  },
  {
    slug: "hurghada",
    name: "Hurghada",
    regionIds: [310, 311],
    country: "Ägypten",
    heroImage: "/images/destinations/hurghada-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80",
    cardImage: "/images/destinations/hurghada-card.jpg",
    description: "Hurghada – Ägyptens beliebteste Badestadt am Roten Meer mit traumhaften Korallenriffen und herrlichem Sonnenschein.",
    metaTitle: "Hurghada Urlaub – All Inclusive buchen",
    metaDescription: "Hurghada Urlaub günstig buchen: Pauschalreisen ✓ All Inclusive ✓ Last Minute Ägypten ✓ Traumstrand am Roten Meer – Angebote vergleichen & buchen!",
    iataCode: "HRG",
    ibeBpRegion: "africa",
    ibeRegionId: "310",
    tiqetsCityId: "19370",
    tiqetsNiches: [
      {
        slug: "wassersport-schnorcheln",
        label: "Wassersport & Schnorcheln",
        keywords: "schnorcheln|tauchen|diving|koralle|reef|riff|jet ski|jetski|parasail|kite|surf|boot|bootstour",
        metaTitle: "Wassersport & Schnorcheln in Hurghada – Tickets günstig buchen",
        metaDescription: "Schnorcheln, Tauchen & Wassersport in Hurghada günstig buchen. ✓ Korallenriff-Touren ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Wassersport & Schnorcheln in Hurghada",
        intro: "Das Rote Meer vor Hurghada gehört zu den schönsten Tauch- und Schnorchelrevieren der Welt. Farbenfrohe Korallenriffe, exotische Fische und glasklares Wasser machen jeden Ausflug zu einem unvergesslichen Erlebnis.",
      },
      {
        slug: "ausfluege-touren",
        label: "Ausflüge & Touren",
        keywords: "quad|buggy|jeep|safari|wüste|desert|luxor|kairo|gizeh|pyramide|ausflug|tour|kamel",
        metaTitle: "Ausflüge & Touren ab Hurghada – Wüste & Kultur buchen",
        metaDescription: "Wüstensafaris, Pyramiden-Touren & Ausflüge ab Hurghada günstig buchen. ✓ Luxor Tagesausflug ✓ Quad-Touren ✓ Sofortbuchung.",
        h1: "Ausflüge & Touren ab Hurghada",
        intro: "Hurghada ist der ideale Ausgangspunkt für spannende Ausflüge: Erlebe die Stille der ägyptischen Wüste auf einer Quad-Tour, besuche die Tempel von Luxor oder unternimm einen Tagesausflug zu den Pyramiden von Gizeh.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Hurghada?", answer: "Hurghada kann das ganze Jahr bereist werden. Die beste Zeit ist Oktober bis April mit angenehmen 25–30 °C. Juli und August können sehr heiß werden (bis 40 °C). Das Rote Meer hat ganzjährig angenehme Wassertemperaturen." },
      { question: "Brauche ich ein Visum für Ägypten?", answer: "Deutsche Staatsbürger benötigen ein Visum für Ägypten. Es kann als e-Visa online beantragt oder bei Ankunft am Flughafen (Visa on Arrival) für ca. 25 USD erworben werden. Ein gültiger Reisepass ist erforderlich." },
      { question: "Was kostet eine Pauschalreise nach Hurghada?", answer: "Pauschalreisen nach Hurghada gibt es bereits ab ca. 300 € pro Person (7 Nächte, Flug & Hotel). All-Inclusive-Angebote starten ab ca. 400 € p.P. Hurghada gilt als eines der günstigsten Reiseziele am Meer." },
      { question: "Welcher Flughafen liegt nah an Hurghada?", answer: "Der Flughafen Hurghada International (IATA: HRG) liegt direkt bei der Stadt. Von Deutschland gibt es Direktflüge ab Frankfurt, München, Düsseldorf und Berlin – Flugzeit ca. 4,5 Stunden." },
    ],
    entryInfo: {
      visa: "Visum erforderlich: e-Visa online oder Visa on Arrival (ca. 25 USD) am Flughafen Hurghada.",
      currency: "Ägyptisches Pfund (EGP). USD und EUR werden in vielen Hotels akzeptiert. Bargeld für Märkte und kleine Läden empfohlen.",
      language: "Arabisch. In Touristengebieten wird Englisch und Deutsch verbreitet gesprochen.",
      timezone: "UTC+2 (keine Sommerzeit). 1 Stunde vor Deutschland im Winter, gleiche Zeit im Sommer.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "Reisekrankenversicherung mit Auslandsschutz empfohlen. Sonnenschutz essenziell. Leitungswasser nicht trinken – nur Mineralwasser.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 22, tempLow: 12, rain: 3 },
      { month: "Feb", tempHigh: 24, tempLow: 13, rain: 2 },
      { month: "Mär", tempHigh: 27, tempLow: 16, rain: 2 },
      { month: "Apr", tempHigh: 31, tempLow: 19, rain: 1 },
      { month: "Mai", tempHigh: 35, tempLow: 23, rain: 0 },
      { month: "Jun", tempHigh: 38, tempLow: 26, rain: 0 },
      { month: "Jul", tempHigh: 39, tempLow: 27, rain: 0 },
      { month: "Aug", tempHigh: 39, tempLow: 27, rain: 0 },
      { month: "Sep", tempHigh: 36, tempLow: 25, rain: 0 },
      { month: "Okt", tempHigh: 32, tempLow: 21, rain: 1 },
      { month: "Nov", tempHigh: 27, tempLow: 17, rain: 2 },
      { month: "Dez", tempHigh: 23, tempLow: 13, rain: 3 },
    ] as ClimateMonth[],
    carLocationKey: "AS.EG.04.HRG.HRG",
    coordinates: { lat: 27.2579, lng: 33.8116 },
  },
  {
    slug: "teneriffa",
    name: "Teneriffa",
    regionIds: [400, 401],
    country: "Spanien",
    heroImage: "/images/destinations/teneriffa-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1600&q=80",
    cardImage: "/images/destinations/teneriffa-card.jpg",
    description: "Teneriffa – die größte Kanarische Insel mit dem Teide-Vulkan, traumhaften Stränden und ewigem Frühling.",
    metaTitle: "Teneriffa Urlaub – All Inclusive buchen",
    metaDescription: "Teneriffa Urlaub günstig buchen: Pauschalreisen ✓ All Inclusive ✓ Last Minute Kanaren ✓ Ganzjährig Sonne – Angebote vergleichen & buchen!",
    iataCode: "TFS",
    ibeBpRegion: "eu",
    ibeRegionId: "141",
    tiqetsCityId: "73432",
    tiqetsNiches: [
      {
        slug: "teide-natur",
        label: "Teide & Natur",
        keywords: "teide|vulkan|nationalpark|seilbahn|wandern|natur|stargazing|sterne|astronomie|lava",
        metaTitle: "Teide & Natur auf Teneriffa – Tickets günstig buchen",
        metaDescription: "Teide Seilbahn, Nationalpark-Touren & Natur-Erlebnisse auf Teneriffa günstig buchen. ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Teide & Natur auf Teneriffa",
        intro: "Der Teide ist Spaniens höchster Berg und einer der beeindruckendsten Vulkane der Welt. Fahre mit der Seilbahn auf 3.555 m, wandere durch den Nationalpark oder beobachte nachts den spektakulären Sternenhimmel.",
      },
      {
        slug: "wassersport-strand",
        label: "Wassersport & Strand",
        keywords: "surf|wellenreiten|jet ski|parasail|schnorcheln|tauchen|delfin|wal|whale|bootstour|strand|beach",
        metaTitle: "Wassersport & Strand auf Teneriffa – Aktivitäten buchen",
        metaDescription: "Surfen, Delfin-Touren & Wassersport auf Teneriffa günstig buchen. ✓ Wal- & Delfin-Watching ✓ Sofortbuchung ✓ Top-Bewertungen.",
        h1: "Wassersport & Strand auf Teneriffa",
        intro: "Teneriffas Atlantikküste bietet ideale Bedingungen für Wassersportler aller Levels. Surfe in Playa de las Américas, beobachte wilde Wale und Delfine auf einer Bootstour oder erforsche die Unterwasserwelt beim Schnorcheln.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Teneriffa?", answer: "Teneriffa ist ganzjährig ein top Reiseziel. Ewiger Frühling mit 20–28 °C das ganze Jahr. Sommer ist perfekt für Strand, Winter ideal zum Entfliehen der Kälte. Hauptsaison ist Oktober bis April." },
      { question: "Brauche ich ein Visum für Teneriffa?", answer: "Nein – Teneriffa gehört zu Spanien und ist EU-Mitglied. Deutsche Staatsbürger benötigen nur einen gültigen Personalausweis oder Reisepass." },
      { question: "Welcher Flughafen liegt nah an Teneriffa?", answer: "Teneriffa hat zwei Flughäfen: Teneriffa Süd (TFS) für Touristenregionen – Flugzeit ca. 4 Stunden ab Deutschland. Direktflüge ab Frankfurt, München, Düsseldorf, Berlin und Hamburg." },
      { question: "Was kostet eine Pauschalreise nach Teneriffa?", answer: "Pauschalreisen nach Teneriffa gibt es ab ca. 400 € pro Person (7 Nächte, Flug & Hotel). All-Inclusive-Angebote starten ab ca. 550 € p.P. Im Winter sind die Preise tendenziell etwas höher." },
    ],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten überall akzeptiert. Teneriffa ist günstiger als das spanische Festland.",
      language: "Spanisch. In Touristengebieten (Süd) wird Englisch und Deutsch häufig gesprochen.",
      timezone: "UTC+0 / UTC+1 (Sommerzeit). Teneriffa ist 1 Stunde hinter Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Sonnenschutz das ganze Jahr empfohlen.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 21, tempLow: 14, rain: 40 },
      { month: "Feb", tempHigh: 21, tempLow: 14, rain: 35 },
      { month: "Mär", tempHigh: 22, tempLow: 15, rain: 25 },
      { month: "Apr", tempHigh: 23, tempLow: 16, rain: 15 },
      { month: "Mai", tempHigh: 24, tempLow: 17, rain: 5 },
      { month: "Jun", tempHigh: 26, tempLow: 20, rain: 2 },
      { month: "Jul", tempHigh: 28, tempLow: 22, rain: 1 },
      { month: "Aug", tempHigh: 29, tempLow: 23, rain: 1 },
      { month: "Sep", tempHigh: 28, tempLow: 22, rain: 10 },
      { month: "Okt", tempHigh: 26, tempLow: 20, rain: 25 },
      { month: "Nov", tempHigh: 24, tempLow: 17, rain: 40 },
      { month: "Dez", tempHigh: 22, tempLow: 15, rain: 45 },
    ] as ClimateMonth[],
    carLocationKey: "AS.ES.10.TFS.TFS",
    coordinates: { lat: 28.2916, lng: -16.6291 },
  },
  {
    slug: "rhodos",
    name: "Rhodos",
    regionIds: [55, 56],
    country: "Griechenland",
    heroImage: "/images/destinations/rhodos-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1664118145742-f2ad1c09c10b?w=1600&q=80",
    cardImage: "/images/destinations/rhodos-card.jpg",
    description: "Rhodos – die Sonneninsel des Ägäischen Meeres mit mittelalterlicher Altstadt, türkisem Wasser und antikem Charme.",
    metaTitle: "Rhodos Urlaub – Pauschalreise buchen",
    metaDescription: "Rhodos Urlaub günstig buchen: Pauschalreisen ✓ All Inclusive ✓ Last Minute Griechenland ✓ Mittelalterliche Altstadt & traumhafte Strände – buchen!",
    iataCode: "RHO",
    ibeBpRegion: "eu",
    ibeRegionId: "55",
    tiqetsCityId: "25989",
    tiqetsNiches: [
      {
        slug: "altstadt-kultur",
        label: "Altstadt & Kultur",
        keywords: "altstadt|ritterburg|palace|palast|museum|mittelalter|stadtmauer|knights|lindos|akropolis|historisch",
        metaTitle: "Altstadt & Kultur auf Rhodos – Tickets günstig buchen",
        metaDescription: "Rhodos Altstadt, Ritterpalast & Lindos günstig buchen. ✓ UNESCO Weltkulturerbe ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Altstadt & Kultur auf Rhodos",
        intro: "Die mittelalterliche Altstadt von Rhodos ist UNESCO-Weltkulturerbe und eine der besterhaltenen mittelalterlichen Städte Europas. Der Palast der Großmeister, die Straße der Ritter und die Akropolis von Lindos sind absolute Highlights.",
      },
      {
        slug: "wassersport-strand",
        label: "Wassersport & Strand",
        keywords: "strand|beach|schnorcheln|tauchen|jet ski|parasail|bootstour|segeln|surfing|windsurf|prasonisi",
        metaTitle: "Wassersport & Strand auf Rhodos – Aktivitäten buchen",
        metaDescription: "Wassersport & Strand auf Rhodos günstig buchen. ✓ Schnorcheln ✓ Bootstouren ✓ Sofortbuchung.",
        h1: "Wassersport & Strand auf Rhodos",
        intro: "Rhodos besticht mit kristallklarem Wasser und traumhaften Stränden. Von den Familienstränden bei Faliraki bis zum Windsurf-Mekka Prasonisi – hier findet jeder seinen perfekten Platz am Meer.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Rhodos?", answer: "Mai bis Oktober ist die beste Reisezeit. Die Hochsaison Juli/August bringt bis zu 35 °C. Für angenehme Temperaturen empfehlen sich Mai/Juni oder September/Oktober – mit weniger Touristen und günstigeren Preisen." },
      { question: "Brauche ich ein Visum für Rhodos?", answer: "Nein – Rhodos gehört zu Griechenland und ist EU-Mitglied. Deutsche Staatsbürger benötigen nur einen gültigen Personalausweis oder Reisepass." },
      { question: "Welcher Flughafen liegt nah an Rhodos?", answer: "Der Flughafen Rhodos Diagoras (IATA: RHO) liegt ca. 14 km südwestlich der Stadt. Von Deutschland gibt es Direktflüge ab Frankfurt, München, Düsseldorf und Berlin – Flugzeit ca. 3,5 Stunden." },
      { question: "Was kostet eine Pauschalreise nach Rhodos?", answer: "Pauschalreisen nach Rhodos gibt es ab ca. 350 € pro Person (7 Nächte, Flug & Hotel). All-Inclusive-Angebote starten ab ca. 500 € p.P." },
    ],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten in Hotels und Restaurants akzeptiert. Bargeld für kleine Tavernen empfohlen.",
      language: "Griechisch. In Touristengebieten wird Englisch und Deutsch gesprochen.",
      timezone: "UTC+2 / UTC+3 (Sommerzeit). Im Sommer 1 Stunde vor Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Sonnenschutz wichtig.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 15, tempLow: 9, rain: 135 },
      { month: "Feb", tempHigh: 15, tempLow: 9, rain: 100 },
      { month: "Mär", tempHigh: 17, tempLow: 11, rain: 70 },
      { month: "Apr", tempHigh: 21, tempLow: 14, rain: 30 },
      { month: "Mai", tempHigh: 25, tempLow: 18, rain: 15 },
      { month: "Jun", tempHigh: 29, tempLow: 22, rain: 5 },
      { month: "Jul", tempHigh: 32, tempLow: 25, rain: 1 },
      { month: "Aug", tempHigh: 32, tempLow: 25, rain: 1 },
      { month: "Sep", tempHigh: 29, tempLow: 22, rain: 20 },
      { month: "Okt", tempHigh: 25, tempLow: 18, rain: 60 },
      { month: "Nov", tempHigh: 20, tempLow: 14, rain: 100 },
      { month: "Dez", tempHigh: 16, tempLow: 10, rain: 130 },
    ] as ClimateMonth[],
    carLocationKey: "AS.GR.05.RHO.RHO",
    coordinates: { lat: 36.4341, lng: 28.2176 },
  },
  {
    slug: "ibiza",
    name: "Ibiza",
    regionIds: [210, 211],
    country: "Spanien",
    heroImage: "/images/destinations/ibiza-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1689859870434-8248d5a113c1?w=1600&q=80",
    cardImage: "/images/destinations/ibiza-card.jpg",
    description: "Ibiza – die Partyinsel der Balearen mit atemberaubenden Sonnenuntergängen, türkisem Wasser und lebhafter Atmosphäre.",
    metaTitle: "Ibiza Urlaub – Pauschalreise buchen",
    metaDescription: "Ibiza Urlaub günstig buchen: Pauschalreisen ✓ Strandurlaub ✓ Last Minute Balearen ✓ Party & Entspannung – Angebote vergleichen & buchen!",
    iataCode: "IBZ",
    ibeBpRegion: "eu",
    ibeRegionId: "135",
    tiqetsCityId: "25988",
    tiqetsNiches: [
      {
        slug: "strand-boote",
        label: "Strand & Bootstouren",
        keywords: "strand|beach|bootstour|segeln|catamaran|katamaran|schnorcheln|tauchen|jet ski|paddleboard|sup",
        metaTitle: "Strand & Bootstouren auf Ibiza – günstig buchen",
        metaDescription: "Bootstouren, Katamaranfahrten & Strand-Aktivitäten auf Ibiza günstig buchen. ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Strand & Bootstouren auf Ibiza",
        intro: "Ibizas türkisblaues Wasser und versteckte Buchten lassen sich am besten per Boot erkunden. Katamarantouren, Schnorchel-Ausflüge und SUP-Kurse sind die perfekte Ergänzung zu Strandtagen an den schönsten Buchten der Insel.",
      },
      {
        slug: "altstadt-sonnenuntergang",
        label: "Altstadt & Sonnenuntergang",
        keywords: "dalt vila|altstadt|old town|sonnenuntergang|sunset|café del mar|san antonio|formentera|ausflug",
        metaTitle: "Ibiza Altstadt & Sonnenuntergang – Touren buchen",
        metaDescription: "Ibiza Altstadt Dalt Vila, Sonnenuntergang & Ausflüge günstig buchen. ✓ UNESCO-Erbe ✓ Sofortbuchung.",
        h1: "Altstadt & Sonnenuntergang auf Ibiza",
        intro: "Die UNESCO-geschützte Altstadt Dalt Vila thront majestätisch über der Bucht von Ibiza-Stadt. Genieße den legendären Sonnenuntergang am Café del Mar in San Antonio oder unternimm einen Tagesausflug zur benachbarten Insel Formentera.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Ibiza?", answer: "Mai bis Oktober ist ideal. Die Hochsaison Juni bis August bringt das meiste Leben mit Temperaturen um 30 °C. September und Oktober bieten noch warmes Wetter bei weniger Trubel und günstigeren Preisen." },
      { question: "Brauche ich ein Visum für Ibiza?", answer: "Nein – Ibiza gehört zu Spanien. EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass." },
      { question: "Welcher Flughafen liegt nah an Ibiza?", answer: "Der Flughafen Ibiza (IATA: IBZ) liegt ca. 7 km südwestlich der Stadt. Von Deutschland gibt es Direktflüge ab Frankfurt, München, Düsseldorf und Berlin – Flugzeit ca. 2,5 Stunden." },
      { question: "Was kostet eine Pauschalreise nach Ibiza?", answer: "Pauschalreisen nach Ibiza gibt es ab ca. 450 € pro Person (7 Nächte, Flug & Hotel). Die Insel zählt zu den teureren Balearen-Zielen, bietet aber alle Preisklassen." },
    ],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten überall akzeptiert.",
      language: "Spanisch & Katalanisch. Englisch in Touristenbereichen sehr verbreitet.",
      timezone: "UTC+1 / UTC+2 (Sommerzeit). Gleiche Zeitzone wie Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 14, tempLow: 8, rain: 45 },
      { month: "Feb", tempHigh: 15, tempLow: 8, rain: 40 },
      { month: "Mär", tempHigh: 17, tempLow: 10, rain: 40 },
      { month: "Apr", tempHigh: 19, tempLow: 12, rain: 40 },
      { month: "Mai", tempHigh: 23, tempLow: 16, rain: 30 },
      { month: "Jun", tempHigh: 27, tempLow: 20, rain: 15 },
      { month: "Jul", tempHigh: 30, tempLow: 23, rain: 5 },
      { month: "Aug", tempHigh: 30, tempLow: 23, rain: 10 },
      { month: "Sep", tempHigh: 27, tempLow: 20, rain: 35 },
      { month: "Okt", tempHigh: 23, tempLow: 16, rain: 65 },
      { month: "Nov", tempHigh: 18, tempLow: 12, rain: 55 },
      { month: "Dez", tempHigh: 15, tempLow: 9, rain: 50 },
    ] as ClimateMonth[],
    carLocationKey: "AS.ES.07.IBZ.IBZ",
    coordinates: { lat: 38.9067, lng: 1.4206 },
  },
  {
    slug: "dubai",
    name: "Dubai",
    regionIds: [500, 501],
    country: "VAE",
    heroImage: "/images/destinations/dubai-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600&q=80",
    cardImage: "/images/destinations/dubai-card.jpg",
    description: "Dubai – die Stadt der Superlative mit Burj Khalifa, luxuriösen Hotels, endlosen Stränden und pulsierendem Nachtleben.",
    metaTitle: "Dubai Urlaub – Pauschalreise buchen",
    metaDescription: "Dubai Urlaub günstig buchen: Pauschalreisen ✓ Luxushotels ✓ Last Minute VAE ✓ Burj Khalifa & Wüstensafari – Angebote vergleichen & buchen!",
    iataCode: "DXB",
    ibeBpRegion: "uae",
    ibeRegionId: "500",
    tiqetsCityId: "53199",
    tiqetsNiches: [
      {
        slug: "sehenswuerdigkeiten",
        label: "Sehenswürdigkeiten",
        keywords: "burj khalifa|burj arab|palm|frame|museum|aquarium|dubai mall|fountain|brunnen|aussicht|skydeck",
        metaTitle: "Dubai Sehenswürdigkeiten – Tickets günstig buchen",
        metaDescription: "Burj Khalifa, Dubai Frame & Sehenswürdigkeiten günstig buchen. ✓ Skip-the-Line ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Sehenswürdigkeiten in Dubai",
        intro: "Dubai ist eine Stadt der Superlative: Der Burj Khalifa ragt als höchstes Gebäude der Welt in den Himmel, das Dubai Frame bietet spektakuläre Stadtpanoramen, und das Dubai Aquarium fasziniert mit der größten acrylgläsernen Scheibe der Welt.",
      },
      {
        slug: "wueste-abenteuer",
        label: "Wüste & Abenteuer",
        keywords: "wüste|desert|safari|quad|dune|düne|buggy|camel|kamel|bedouin|beduinen|sandboard|hot air balloon",
        metaTitle: "Wüstensafari & Abenteuer in Dubai – günstig buchen",
        metaDescription: "Wüstensafaris, Quad-Touren & Abenteuer in Dubai günstig buchen. ✓ Abendessen in der Wüste ✓ Sofortbuchung.",
        h1: "Wüste & Abenteuer in Dubai",
        intro: "Die Arabische Wüste direkt vor Dubais Türen wartet mit unvergesslichen Erlebnissen: Fahre mit dem Quad über mächtige Dünen, erkunde die Wüste auf einem Kamel und genieße ein traditionelles Beduinen-Abendessen unter dem Sternenhimmel.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Dubai?", answer: "Die beste Reisezeit ist Oktober bis April mit angenehmen 20–30 °C. Sommer (Juni–September) ist extrem heiß (bis 45 °C) – Malls und Strände sind trotzdem gut besucht. November bis März gilt als Hochsaison." },
      { question: "Brauche ich ein Visum für Dubai?", answer: "Deutsche Staatsbürger erhalten bei Ankunft ein kostenloses Visum on Arrival für 30 Tage. Ein gültiger Reisepass (mind. 6 Monate gültig) ist erforderlich." },
      { question: "Welcher Flughafen liegt nah an Dubai?", answer: "Dubai International Airport (IATA: DXB) ist einer der größten Flughäfen weltweit. Von Deutschland gibt es Direktflüge ab Frankfurt, München, Düsseldorf, Berlin und Hamburg mit Emirates, Lufthansa & Co. – Flugzeit ca. 6 Stunden." },
      { question: "Was kostet eine Pauschalreise nach Dubai?", answer: "Pauschalreisen nach Dubai gibt es ab ca. 700 € pro Person (7 Nächte, Flug & Hotel). Luxushotels kosten mehr, aber es gibt auch gute Mittelklasse-Hotels zu fairen Preisen." },
    ],
    entryInfo: {
      visa: "Visum on Arrival kostenlos für 30 Tage. Reisepass mind. 6 Monate gültig.",
      currency: "Dirham (AED). Kreditkarten überall akzeptiert. 1 EUR ≈ 4 AED.",
      language: "Arabisch. Englisch ist Alltagssprache in Dubai – kein Problem ohne Arabischkenntnisse.",
      timezone: "UTC+4 (keine Sommerzeit). Dubai ist 3 Stunden vor Deutschland (Winter) bzw. 2 Stunden (Sommer).",
      voltage: "220 V, 50 Hz. Steckdosen Typ G (britisch) – Adapter empfohlen.",
      health: "Reisekrankenversicherung empfohlen. Leitungswasser trinkbar aber Mineralwasser bevorzugt. Sonnenschutz essenziell.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 24, tempLow: 14, rain: 10 },
      { month: "Feb", tempHigh: 26, tempLow: 15, rain: 15 },
      { month: "Mär", tempHigh: 30, tempLow: 18, rain: 10 },
      { month: "Apr", tempHigh: 35, tempLow: 22, rain: 5 },
      { month: "Mai", tempHigh: 40, tempLow: 27, rain: 1 },
      { month: "Jun", tempHigh: 42, tempLow: 30, rain: 0 },
      { month: "Jul", tempHigh: 43, tempLow: 31, rain: 0 },
      { month: "Aug", tempHigh: 43, tempLow: 31, rain: 0 },
      { month: "Sep", tempHigh: 40, tempLow: 28, rain: 0 },
      { month: "Okt", tempHigh: 36, tempLow: 24, rain: 1 },
      { month: "Nov", tempHigh: 31, tempLow: 20, rain: 5 },
      { month: "Dez", tempHigh: 26, tempLow: 16, rain: 10 },
    ] as ClimateMonth[],
    carLocationKey: "AS.AE.02.DXB.DXB",
    coordinates: { lat: 25.2048, lng: 55.2708 },
  },
  {
    slug: "phuket",
    name: "Phuket",
    regionIds: [600, 601],
    country: "Thailand",
    heroImage: "/images/destinations/phuket-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1704928517302-67b645c9b083?w=1600&q=80",
    cardImage: "/images/destinations/phuket-card.jpg",
    description: "Phuket – Thailands bekannteste Insel mit weißen Sandstränden, türkisem Wasser, Tempelkultur und leckerem Street Food.",
    metaTitle: "Phuket Urlaub – Pauschalreise buchen",
    metaDescription: "Phuket Urlaub günstig buchen: Pauschalreisen ✓ Strandurlaub Thailand ✓ Last Minute Asien ✓ Traumstrände & Tempel – Angebote vergleichen & buchen!",
    iataCode: "HKT",
    ibeBpRegion: "asia",
    ibeRegionId: "600",
    tiqetsCityId: "36095",
    tiqetsNiches: [
      {
        slug: "strand-inseln",
        label: "Strand & Inseln",
        keywords: "strand|beach|island|insel|phi phi|james bond|bootstour|schnorcheln|tauchen|kayak|kajak|lagune",
        metaTitle: "Strände & Inseln in Phuket – Touren günstig buchen",
        metaDescription: "Phi Phi Islands, James Bond Island & Strand-Touren in Phuket günstig buchen. ✓ Sofortbuchung ✓ Gratis Storno.",
        h1: "Strand & Inseln rund um Phuket",
        intro: "Phuket ist das Tor zu einigen der schönsten Inseln Südostasiens. Die Phi Phi Islands mit türkisklarem Wasser, James Bond Island in der Phang Nga Bay und unzählige versteckte Buchten warten auf dich – am besten per Schnellboot oder Katamaran erkundet.",
      },
      {
        slug: "kultur-tempel",
        label: "Kultur & Tempel",
        keywords: "tempel|wat|buddha|big buddha|old town|altstadt|patong|bangla|nachtmarkt|street food|massage|spa",
        metaTitle: "Kultur & Tempel in Phuket – Erlebnisse buchen",
        metaDescription: "Tempel, Phuket Old Town & Kulturerlebnisse günstig buchen. ✓ Big Buddha ✓ Sofortbuchung.",
        h1: "Kultur & Tempel in Phuket",
        intro: "Phuket hat mehr zu bieten als schöne Strände: Der goldene Big Buddha thront majestätisch über der Insel, die bunte Old Town begeistert mit Sino-Portuguese Architektur, und in den zahlreichen Tempeln taucht du in die spirituelle Welt Thailands ein.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Phuket?", answer: "November bis April ist die Trockenzeit und beste Reisezeit. Dezember bis Februar sind die angenehmsten Monate mit 28–32 °C und wenig Regen. Mai bis Oktober ist Regenzeit – günstigere Preise, aber tägliche Schauer möglich." },
      { question: "Brauche ich ein Visum für Thailand?", answer: "Deutsche Staatsbürger erhalten seit 2024 ein kostenloses Visum on Arrival für 60 Tage. Reisepass mind. 6 Monate gültig. Rückflugticket muss vorgelegt werden." },
      { question: "Welcher Flughafen liegt nah an Phuket?", answer: "Der Flughafen Phuket International (IATA: HKT) liegt im Norden der Insel. Direktflüge von Deutschland sind selten – meist Umstieg in Bangkok, Dubai oder Singapore. Flugzeit ca. 11–13 Stunden." },
      { question: "Was kostet eine Pauschalreise nach Phuket?", answer: "Pauschalreisen nach Phuket gibt es ab ca. 900 € pro Person (14 Nächte, Flug & Hotel). Günstiger als europäische Ziele bei gleicher Hotelqualität." },
    ],
    entryInfo: {
      visa: "Visum on Arrival kostenlos für 60 Tage. Reisepass mind. 6 Monate gültig, Rückflugticket erforderlich.",
      currency: "Baht (THB). Geldautomaten überall verfügbar. 1 EUR ≈ 38 THB. Bargeld für Märkte und Tuk-Tuks nötig.",
      language: "Thailändisch. In Touristenbereichen wird Englisch gesprochen. Deutsch selten.",
      timezone: "UTC+7 (keine Sommerzeit). Phuket ist 6 Stunden vor Deutschland (Winter) bzw. 5 Stunden (Sommer).",
      voltage: "220 V, 50 Hz. Steckdosen Typ A/B/C – universeller Adapter empfohlen.",
      health: "Reisekrankenversicherung empfohlen. Hepatitis A Impfung ratsam. Dengue-Mücken – Repellent verwenden.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 32, tempLow: 24, rain: 20 },
      { month: "Feb", tempHigh: 33, tempLow: 24, rain: 30 },
      { month: "Mär", tempHigh: 34, tempLow: 25, rain: 50 },
      { month: "Apr", tempHigh: 34, tempLow: 26, rain: 90 },
      { month: "Mai", tempHigh: 32, tempLow: 25, rain: 200 },
      { month: "Jun", tempHigh: 31, tempLow: 25, rain: 210 },
      { month: "Jul", tempHigh: 31, tempLow: 25, rain: 250 },
      { month: "Aug", tempHigh: 31, tempLow: 25, rain: 230 },
      { month: "Sep", tempHigh: 31, tempLow: 24, rain: 280 },
      { month: "Okt", tempHigh: 31, tempLow: 24, rain: 260 },
      { month: "Nov", tempHigh: 31, tempLow: 24, rain: 140 },
      { month: "Dez", tempHigh: 32, tempLow: 24, rain: 50 },
    ] as ClimateMonth[],
    carLocationKey: "AS.TH.01.HKT.HKT",
    coordinates: { lat: 7.8804, lng: 98.3923 },
  },
  {
    slug: "lissabon",
    name: "Lissabon",
    regionIds: [700, 701],
    country: "Portugal",
    heroImage: "/images/destinations/lissabon-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1600&q=80",
    cardImage: "/images/destinations/lissabon-card.jpg",
    description: "Lissabon – Europas westlichste Hauptstadt mit Fado, Pastéis de Nata, historischen Trams und Atlantikflair.",
    metaTitle: "Lissabon Urlaub – Städtereise buchen",
    metaDescription: "Lissabon Urlaub günstig buchen: Städtereisen ✓ Kurzurlaub Portugal ✓ Fado & Kultur ✓ Jetzt Angebote vergleichen & die atlantische Metropole entdecken!",
    iataCode: "LIS",
    ibeBpRegion: "eu",
    ibeRegionId: "700",
    tiqetsCityId: "36116",
    tiqetsNiches: [
      {
        slug: "stadttouren-sehenswuerdigkeiten",
        label: "Stadttouren & Sehenswürdigkeiten",
        keywords: "hop-on|hop off|tuk tuk|tram|belem|turm|monastério|jeronimos|sintra|stadtführung|panorama|aussicht",
        metaTitle: "Lissabon Stadttouren & Sehenswürdigkeiten – Tickets buchen",
        metaDescription: "Hop-on Hop-off, Tuk Tuk & Lissabon Stadttouren günstig buchen. ✓ Belém Tower ✓ Sintra ✓ Sofortbuchung.",
        h1: "Stadttouren & Sehenswürdigkeiten in Lissabon",
        intro: "Lissabon entfaltet seinen Charme am besten auf einer Tour durch die sieben Hügel der Stadt. Fahre mit der historischen Tram 28 durch Alfama, besuche den Turm von Belém und unternimm einen Tagesausflug ins märchenhafte Sintra.",
      },
      {
        slug: "fado-kulinarik",
        label: "Fado & Kulinarik",
        keywords: "fado|konzert|wein|wine|tasting|tour|food|kulinarisch|gourmet|markt|time out|lx factory",
        metaTitle: "Fado & Kulinarik in Lissabon – Erlebnisse buchen",
        metaDescription: "Fado-Konzerte, Weinverkostungen & kulinarische Touren in Lissabon buchen. ✓ Authentisches Portugal ✓ Sofortbuchung.",
        h1: "Fado & Kulinarik in Lissabon",
        intro: "Die Seele Lissabons klingt in den melancholischen Tönen des Fado. Erlebe ein authentisches Konzert in einer traditionellen Casa de Fado in Alfama, genieße portugiesischen Wein bei einer Verkostung oder lass dich auf einem kulinarischen Stadtspaziergang verführen.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Lissabon?", answer: "März bis Oktober ist ideal. Frühling (April/Mai) und Herbst (September/Oktober) bieten angenehme 20–25 °C ohne Sommertrubel. Sommer ist beliebt aber heiß (bis 35 °C). Winter ist mild mit ca. 15 °C." },
      { question: "Brauche ich ein Visum für Portugal?", answer: "Nein – Portugal ist EU-Mitglied. Deutsche Staatsbürger benötigen nur einen gültigen Personalausweis oder Reisepass." },
      { question: "Welcher Flughafen liegt nah an Lissabon?", answer: "Der Flughafen Lissabon Humberto Delgado (IATA: LIS) liegt nur 7 km vom Stadtzentrum entfernt. Von Deutschland gibt es Direktflüge ab Frankfurt, München, Düsseldorf, Berlin und Hamburg – Flugzeit ca. 2,5 Stunden." },
      { question: "Was kostet eine Städtereise nach Lissabon?", answer: "Kurztrips nach Lissabon (3–4 Nächte, Flug & Hotel) gibt es ab ca. 250 € pro Person. Lissabon gilt als eine der günstigsten westeuropäischen Hauptstädte." },
    ],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten überall akzeptiert. Lissabon ist günstiger als andere westeuropäische Hauptstädte.",
      language: "Portugiesisch. Englisch in der Tourismusbranche sehr verbreitet.",
      timezone: "UTC+0 / UTC+1 (Sommerzeit). Lissabon ist 1 Stunde hinter Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Leitungswasser trinkbar.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 15, tempLow: 8, rain: 90 },
      { month: "Feb", tempHigh: 16, tempLow: 9, rain: 75 },
      { month: "Mär", tempHigh: 18, tempLow: 11, rain: 65 },
      { month: "Apr", tempHigh: 20, tempLow: 12, rain: 55 },
      { month: "Mai", tempHigh: 22, tempLow: 14, rain: 40 },
      { month: "Jun", tempHigh: 26, tempLow: 17, rain: 15 },
      { month: "Jul", tempHigh: 29, tempLow: 19, rain: 5 },
      { month: "Aug", tempHigh: 29, tempLow: 20, rain: 5 },
      { month: "Sep", tempHigh: 27, tempLow: 18, rain: 25 },
      { month: "Okt", tempHigh: 22, tempLow: 15, rain: 65 },
      { month: "Nov", tempHigh: 18, tempLow: 11, rain: 90 },
      { month: "Dez", tempHigh: 15, tempLow: 9, rain: 95 },
    ] as ClimateMonth[],
    carLocationKey: "AS.PT.01.LIS.LIS",
    coordinates: { lat: 38.7223, lng: -9.1393 },
  },
  {
    slug: "sardinien",
    name: "Sardinien",
    regionIds: [800, 801],
    country: "Italien",
    heroImage: "/images/destinations/sardinien-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1600&q=80",
    cardImage: "/images/destinations/sardinien-card.jpg",
    description: "Sardinien – Italiens zweitgrößte Insel mit karibisch türkisem Wasser, unberührten Stränden und authentischer Kultur.",
    metaTitle: "Sardinien Urlaub – Pauschalreise buchen",
    metaDescription: "Sardinien Urlaub günstig buchen: Pauschalreisen ✓ Strandurlaub Italien ✓ Last Minute ✓ Traumstrände & Nuraghen – Angebote vergleichen & buchen!",
    iataCode: "CAG",
    ibeBpRegion: "eu",
    ibeRegionId: "800",
    tiqetsCityId: "38219",
    tiqetsNiches: [
      {
        slug: "strand-natur",
        label: "Strand & Natur",
        keywords: "strand|beach|bootstour|schnorcheln|tauchen|cala|grotte|höhle|wandern|natur|maddalena|emerald coast",
        metaTitle: "Strand & Natur auf Sardinien – Touren günstig buchen",
        metaDescription: "Strände, Bootstouren & Naturerlebnisse auf Sardinien günstig buchen. ✓ Costa Smeralda ✓ Sofortbuchung.",
        h1: "Strand & Natur auf Sardinien",
        intro: "Sardiniens Strände gehören zu den schönsten Europas: Die Costa Smeralda mit ihrem smaragdgrünen Wasser, die einsamen Buchten der Ostküste und der Archipel La Maddalena mit seinem Nationalpark – hier findet jeder sein Strandparadies.",
      },
      {
        slug: "kultur-nuraghen",
        label: "Kultur & Nuraghen",
        keywords: "nuraghe|nuraghisch|cagliari|altstadt|sassari|museum|archäolog|festung|historisch|wein|cannonau",
        metaTitle: "Kultur & Nuraghen auf Sardinien – Erlebnisse buchen",
        metaDescription: "Nuraghen, Cagliari Altstadt & Kulturerlebnisse auf Sardinien günstig buchen. ✓ UNESCO Kandidat ✓ Sofortbuchung.",
        h1: "Kultur & Nuraghen auf Sardinien",
        intro: "Sardinien trägt eine über 3.500 Jahre alte Geschichte: Die rätselhaften Nuraghen-Türme aus der Bronzezeit prägen das Innere der Insel, die Altstadt von Cagliari begeistert mit punischen und römischen Zeugnissen, und die sardinische Küche ist eine Entdeckung für sich.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Sardinien?", answer: "Mai bis Oktober ist die Badesaison. Hochsaison Juli/August: 30–35 °C, sehr belebt. Juni und September bieten top Wetter bei weniger Trubel. Frühling ist ideal zum Wandern." },
      { question: "Brauche ich ein Visum für Sardinien?", answer: "Nein – Sardinien gehört zu Italien. EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass." },
      { question: "Welcher Flughafen liegt nah an Sardinien?", answer: "Sardinien hat 3 Flughäfen: Cagliari (CAG) im Süden, Olbia (OLB) im Norden (Costa Smeralda), Alghero (AHO) im Nordwesten. Von Deutschland gibt es Direktflüge ab Frankfurt und München – Flugzeit ca. 2 Stunden." },
      { question: "Was kostet eine Pauschalreise nach Sardinien?", answer: "Pauschalreisen nach Sardinien gibt es ab ca. 450 € pro Person (7 Nächte, Flug & Hotel). Costa Smeralda ist teurer; Süden und Osten der Insel sind günstiger." },
    ],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten in Hotels und Restaurants akzeptiert. Bargeld für kleine Restaurants und Märkte empfohlen.",
      language: "Italienisch & Sardisch. Englisch in Touristenbereichen verbreitet.",
      timezone: "UTC+1 / UTC+2 (Sommerzeit). Gleiche Zeitzone wie Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F/L – Adapter Typ L empfohlen.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Leitungswasser trinkbar.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 14, tempLow: 6, rain: 55 },
      { month: "Feb", tempHigh: 14, tempLow: 6, rain: 50 },
      { month: "Mär", tempHigh: 16, tempLow: 8, rain: 45 },
      { month: "Apr", tempHigh: 19, tempLow: 11, rain: 40 },
      { month: "Mai", tempHigh: 24, tempLow: 15, rain: 25 },
      { month: "Jun", tempHigh: 28, tempLow: 19, rain: 10 },
      { month: "Jul", tempHigh: 32, tempLow: 22, rain: 3 },
      { month: "Aug", tempHigh: 32, tempLow: 23, rain: 5 },
      { month: "Sep", tempHigh: 28, tempLow: 20, rain: 25 },
      { month: "Okt", tempHigh: 23, tempLow: 15, rain: 55 },
      { month: "Nov", tempHigh: 18, tempLow: 11, rain: 65 },
      { month: "Dez", tempHigh: 15, tempLow: 7, rain: 60 },
    ] as ClimateMonth[],
    carLocationKey: "AS.IT.05.CAG.CAG",
    coordinates: { lat: 39.2238, lng: 9.1217 },
  },
  {
    slug: "santorini",
    name: "Santorini",
    regionIds: [57, 58],
    country: "Griechenland",
    heroImage: "/images/destinations/santorini-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1618478669118-1b3eb2b2bb95?w=1600&q=80",
    cardImage: "/images/destinations/santorini-card.jpg",
    description: "Santorini – die Vulkaninsel der Kykladen mit weißen Dörfern, blauen Kuppeln, blutrotem Sonnenuntergang und antikem Charme.",
    metaTitle: "Santorini Urlaub – Pauschalreise buchen",
    metaDescription: "Santorini Urlaub günstig buchen: Pauschalreisen ✓ Romantikurlaub ✓ Last Minute Griechenland ✓ Oia Sonnenuntergang & Vulkankrater – buchen!",
    iataCode: "JTR",
    ibeBpRegion: "eu",
    ibeRegionId: "57",
    tiqetsCityId: "37798",
    tiqetsNiches: [
      {
        slug: "sonnenuntergang-sehenswuerdigkeiten",
        label: "Sonnenuntergang & Sehenswürdigkeiten",
        keywords: "oia|sonnenuntergang|sunset|caldera|akrotiri|museum|fira|imerovigli|wandern|wein|weingut",
        metaTitle: "Santorini Sehenswürdigkeiten & Sonnenuntergang – Tickets buchen",
        metaDescription: "Oia Sonnenuntergang, Akrotiri & Santorini Touren günstig buchen. ✓ Caldera-Blick ✓ Sofortbuchung.",
        h1: "Sonnenuntergang & Sehenswürdigkeiten auf Santorini",
        intro: "Santorinis legendärer Sonnenuntergang über der Caldera in Oia gilt als einer der schönsten der Welt. Die antike Ausgrabungsstätte Akrotiri, Weinverkostungen in einzigartigen Weingütern und der atemberaubende Blick auf den Vulkankrater machen jeden Tag unvergesslich.",
      },
      {
        slug: "bootstouren-vulkan",
        label: "Bootstouren & Vulkan",
        keywords: "vulkan|volcano|hot spring|caldera|bootstour|katamaran|segel|sunset cruise|yacht|schnorcheln",
        metaTitle: "Bootstouren & Vulkan auf Santorini – günstig buchen",
        metaDescription: "Caldera-Bootstouren, Vulkan-Besuche & Katamaranfahrten auf Santorini günstig buchen. ✓ Sofortbuchung.",
        h1: "Bootstouren & Vulkan auf Santorini",
        intro: "Eine Caldera-Bootstour gehört zu den absoluten Highlights auf Santorini: Besuche den aktiven Vulkan, bade in heißen Quellen, schnorchle in kristallklarem Wasser und genieße den Sonnenuntergang vom Boot aus.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Santorini?", answer: "April bis November ist die Reisezeit. Hochsaison Juli/August: sehr heiß (35 °C) und überfüllt. Mai/Juni und September/Oktober bieten angenehmere Temperaturen, weniger Touristen und günstigere Preise." },
      { question: "Brauche ich ein Visum für Santorini?", answer: "Nein – Santorini gehört zu Griechenland. EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass." },
      { question: "Welcher Flughafen liegt nah an Santorini?", answer: "Der Flughafen Santorini Thira (IATA: JTR) liegt im Osten der Insel. Von Deutschland gibt es Direktflüge ab Frankfurt und München in der Saison – Flugzeit ca. 3 Stunden. Alternativ per Fähre von Athen (Piräus)." },
      { question: "Was kostet eine Pauschalreise nach Santorini?", answer: "Santorini ist eines der teureren griechischen Ziele. Pauschalreisen starten ab ca. 600 € pro Person (7 Nächte, Flug & Hotel). Höhlenhäuser und Infinity-Pool-Hotels kosten entsprechend mehr." },
    ],
    entryInfo: {
      visa: "Kein Visum – EU-Bürger benötigen nur einen gültigen Personalausweis oder Reisepass.",
      currency: "Euro (EUR). Kreditkarten akzeptiert. Bargeld für kleine Tavernen und Läden empfohlen.",
      language: "Griechisch. Englisch in der Touristensaison sehr verbreitet.",
      timezone: "UTC+2 / UTC+3 (Sommerzeit). Im Sommer 1 Stunde vor Deutschland.",
      voltage: "220 V, 50 Hz. Steckdosen Typ C/F – deutsche Stecker passen direkt.",
      health: "EU-Krankenversicherungskarte (EHIC) wird akzeptiert. Sonnenschutz unbedingt nötig.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 14, tempLow: 9, rain: 80 },
      { month: "Feb", tempHigh: 14, tempLow: 9, rain: 65 },
      { month: "Mär", tempHigh: 16, tempLow: 11, rain: 45 },
      { month: "Apr", tempHigh: 19, tempLow: 14, rain: 20 },
      { month: "Mai", tempHigh: 24, tempLow: 18, rain: 10 },
      { month: "Jun", tempHigh: 28, tempLow: 22, rain: 3 },
      { month: "Jul", tempHigh: 30, tempLow: 24, rain: 1 },
      { month: "Aug", tempHigh: 30, tempLow: 24, rain: 1 },
      { month: "Sep", tempHigh: 27, tempLow: 21, rain: 10 },
      { month: "Okt", tempHigh: 23, tempLow: 17, rain: 35 },
      { month: "Nov", tempHigh: 19, tempLow: 14, rain: 65 },
      { month: "Dez", tempHigh: 15, tempLow: 10, rain: 80 },
    ] as ClimateMonth[],
    carLocationKey: "AS.GR.08.JTR.JTR",
    coordinates: { lat: 36.3932, lng: 25.4615 },
  },
  {
    slug: "side",
    name: "Side",
    regionIds: [130, 131],
    country: "Türkei",
    heroImage: "/images/destinations/side-hero.jpg",
    heroImageFallback: "https://images.unsplash.com/photo-1561712815-883650f32f92?w=1600&q=80",
    cardImage: "/images/destinations/side-card.jpg",
    description: "Side – antike Stadt an der türkischen Riviera mit dem berühmten Apollon-Tempel, breiten Sandstränden und All-Inclusive-Resorts.",
    metaTitle: "Side Urlaub – All Inclusive buchen",
    metaDescription: "Side Urlaub günstig buchen: Pauschalreisen ✓ All Inclusive ✓ Last Minute Türkei ✓ Apollon-Tempel & Sandstrand – Angebote vergleichen & buchen!",
    iataCode: "AYT",
    ibeBpRegion: "turkey",
    ibeRegionId: "130",
    tiqetsCityId: "29054",
    tiqetsNiches: [
      {
        slug: "antike-kultur",
        label: "Antike & Kultur",
        keywords: "apollon|tempel|antik|ruinen|theater|museum|altstadt|archäolog|roman|side antik",
        metaTitle: "Antike & Kultur in Side – Tickets günstig buchen",
        metaDescription: "Apollon-Tempel, Antikes Theater & Kulturerlebnisse in Side günstig buchen. ✓ Archäologisches Museum ✓ Sofortbuchung.",
        h1: "Antike & Kultur in Side",
        intro: "Side ist eine der besterhaltenen antiken Städte der Türkei. Der Apollon-Tempel direkt am Meer, das 15.000 Zuschauer fassende antike Theater und das reiche archäologische Museum machen Side zu einem einzigartigen Ort, wo Geschichte und Strand zusammenkommen.",
      },
      {
        slug: "strand-wassersport",
        label: "Strand & Wassersport",
        keywords: "strand|beach|jet ski|parasail|boot|bootstour|schnorcheln|tauchen|kajak|banana boat|aquapark",
        metaTitle: "Strand & Wassersport in Side – Aktivitäten buchen",
        metaDescription: "Strand & Wassersport in Side günstig buchen. ✓ Breite Sandstrände ✓ Bootstouren ✓ Sofortbuchung.",
        h1: "Strand & Wassersport in Side",
        intro: "Side verfügt über zwei breite Sandstrände – den Oststand und Weststand – die das Städtchen einrahmen. Das türkisblaue Mittelmeer lädt zum Schwimmen, Schnorcheln und zu aufregenden Wassersport-Aktivitäten ein.",
      },
    ] as TiqetsNiche[],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Side?", answer: "Mai bis Oktober ist die Badesaison. Hochsaison Juli/August: bis 38 °C. Juni und September sind ideal – angenehme Temperaturen um 30 °C, weniger Trubel und günstigere Preise." },
      { question: "Brauche ich ein Visum für die Türkei?", answer: "Deutsche Staatsbürger benötigen für die Türkei ein e-Visum, das online über das offizielle Portal beantrag werden kann. Es kostet ca. 35 USD und ist für 90 Tage gültig. Reisepass mind. 6 Monate gültig." },
      { question: "Welcher Flughafen liegt nah an Side?", answer: "Der Flughafen Antalya (IATA: AYT) ist der nächste Flughafen, ca. 65 km entfernt. Transferzeit ca. 60–75 Minuten. Von Deutschland gibt es Direktflüge ab Frankfurt, München, Düsseldorf, Berlin und Hamburg." },
      { question: "Was kostet eine Pauschalreise nach Side?", answer: "Pauschalreisen nach Side gibt es ab ca. 350 € pro Person (7 Nächte, Flug & Hotel). All-Inclusive-Angebote starten ab ca. 500 € p.P. Side bietet ein sehr gutes Preis-Leistungs-Verhältnis." },
    ],
    entryInfo: {
      visa: "E-Visum erforderlich (ca. 35 USD, online unter evisa.gov.tr beantragen). Reisepass mind. 6 Monate gültig.",
      currency: "Türkische Lira (TRY). Kreditkarten werden in Hotels und Restaurants weitgehend akzeptiert. Wechselgeld in TRY empfohlen.",
      language: "Türkisch. In Touristengebieten wird häufig Englisch und Deutsch gesprochen.",
      timezone: "UTC+3 (keine Sommerzeit). Türkei ist 2 Stunden vor Deutschland (Winter) bzw. 1 Stunde vor (Sommer).",
      voltage: "220 V, 50 Hz. Steckdosen Typ F (Schuko) – deutsche Stecker passen direkt.",
      health: "Krankenversicherung mit Auslandsschutz empfohlen. Keine Pflichtimpfungen für EU-Bürger.",
    } as EntryInfo,
    climate: [
      { month: "Jan", tempHigh: 14, tempLow: 6, rain: 200 },
      { month: "Feb", tempHigh: 15, tempLow: 7, rain: 150 },
      { month: "Mär", tempHigh: 18, tempLow: 9, rain: 90 },
      { month: "Apr", tempHigh: 22, tempLow: 13, rain: 45 },
      { month: "Mai", tempHigh: 27, tempLow: 17, rain: 20 },
      { month: "Jun", tempHigh: 32, tempLow: 22, rain: 5 },
      { month: "Jul", tempHigh: 36, tempLow: 25, rain: 2 },
      { month: "Aug", tempHigh: 36, tempLow: 25, rain: 2 },
      { month: "Sep", tempHigh: 32, tempLow: 22, rain: 15 },
      { month: "Okt", tempHigh: 26, tempLow: 16, rain: 60 },
      { month: "Nov", tempHigh: 20, tempLow: 11, rain: 130 },
      { month: "Dez", tempHigh: 15, tempLow: 8, rain: 200 },
    ] as ClimateMonth[],
    carLocationKey: "AS.TR.07.AYT.AYT",
    coordinates: { lat: 36.7688, lng: 31.3894 },
  },
];

export function getDestinationBySlug(slug: string): DestinationConfig | undefined {
  return destinations.find((d) => d.slug === slug);
}

// Bild-Fallback: Unsplash bis eigene Bilder in /public/images/ vorhanden
export function destImg(dest: DestinationConfig, type: "hero" | "card" = "hero"): string {
  if (type === "card") return dest.heroImageFallback || dest.heroImage;
  return dest.heroImageFallback || dest.heroImage;
}
