export interface PauschalKombi {
  slug: string;          // URL-Slug
  country: string;       // Land
  flag: string;          // Emoji-Flagge
  board?: "AI";          // All Inclusive filter
  maxPrice?: string;     // max Preis pro Person
  minRecommrate?: string;
  category?: string;     // Hotelkategorie ("3", "4", "5")
  lastMinute?: boolean;  // last minute = from=0, to=35
  regionId?: string;     // IBE regionId
  cityId?: string;       // IBE cityId
  h1: string;            // H1 Headline
  seoTitle: string;
  seoDescription: string;
  heroImage: string;
  lead: string;          // Kurzer intro-Text
  longDescription: string; // SEO-Fließtext
  highlights: string[];
  faqs: { question: string; answer: string }[];
  // Verlinkungs-Slugs auf konkrete Ziele
  relatedDestinationSlugs: string[];
}

const YEAR = new Date().getFullYear();

export const PAUSCHAL_KOMBIS: PauschalKombi[] = [
  {
    slug: "tuerkei",
    country: "Türkei",
    flag: "🇹🇷",
    regionId: "724",
    minRecommrate: "65",
    category: "4",
    h1: `Pauschalreisen Türkei ${YEAR} günstig buchen`,
    seoTitle: `Pauschalreisen Türkei ${YEAR} – günstig buchen | Urlaubfinder365`,
    seoDescription: `Pauschalreisen Türkei ${YEAR} günstig buchen ✓ Antalya, Side, Alanya ✓ All Inclusive ab 350€ ✓ 50+ Veranstalter ✓ Täglich aktualisierte Angebote.`,
    heroImage: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&q=80&auto=format",
    lead: "Die Türkei zählt zu den Top-Destinationen für preisgünstige Pauschalreisen: Traumstrände, 4-Sterne-All-Inclusive-Resorts und garantierte Sonne von Mai bis Oktober.",
    longDescription: "Pauschalreisen in die Türkei sind seit Jahrzehnten der Klassiker für den sorgenfreien Badeurlaub. Die türkische Riviera rund um Antalya, Side, Belek und Alanya bietet ein unschlagbares Preis-Leistungs-Verhältnis: Schon ab 350 € pro Person gibt es All-Inclusive in 4-Sterne-Hotels direkt am Strand. Die Hauptsaison erstreckt sich von Mai bis Oktober, wobei Juli und August die heißesten Monate sind. Mai, Juni und September gelten als ideal – bei 25-30°C und günstigeren Preisen.",
    highlights: [
      "All-Inclusive Standard in den meisten Hotels",
      "Direkte Strandlage üblich",
      "Top-Resorts für Familien mit Kinderclub",
      "Kurze Flugzeit (3-3,5 Stunden)",
      "Sonnengarantie von Mai bis Oktober",
    ],
    faqs: [
      { question: "Wie viel kostet eine Pauschalreise in die Türkei?", answer: "Die günstigsten Pauschalreisen in die Türkei gibt es bereits ab 350 € pro Person für eine Woche All-Inclusive in einem 4-Sterne-Hotel. In der Hauptsaison (Juli/August) liegen die Preise bei 600-900 €. In der Nebensaison (Mai, September, Oktober) sparst du bis zu 40 %." },
      { question: "Ist die Türkei als Reiseziel sicher?", answer: "Die klassischen Urlaubsgebiete wie Antalya, Side, Belek und Alanya gelten als sicher. Das Auswärtige Amt hat für Touristengebiete keine Reisewarnung ausgesprochen. Wie überall solltest du auf deine Wertsachen achten und dich über die aktuelle Lage informieren." },
      { question: "Welche Flughäfen bedienen die türkische Riviera?", answer: "Der Hauptflughafen ist Antalya (AYT), der von nahezu allen deutschen Flughäfen angeflogen wird. Für Alanya und Side ist ebenfalls Antalya der nächste Flughafen (ca. 60-120 Minuten Transfer). Für Bodrum empfiehlt sich der Flughafen Bodrum-Milas (BJV)." },
      { question: "Wann ist die beste Zeit für einen Türkei-Urlaub?", answer: "Für Badeurlaub ist Mai bis Oktober ideal. Mai und September sind besonders empfehlenswert – weniger Hitze, weniger Touristen, niedrigere Preise. Juli und August sind Hauptsaison mit Temperaturen bis 35°C." },
    ],
    relatedDestinationSlugs: ["antalya", "side", "alanya", "bodrum"],
  },
  {
    slug: "tuerkei-all-inclusive",
    country: "Türkei",
    flag: "🇹🇷",
    board: "AI",
    regionId: "724",
    minRecommrate: "70",
    category: "4",
    h1: `All Inclusive Türkei ${YEAR} – Pauschalreisen mit Verpflegung`,
    seoTitle: `All Inclusive Türkei ${YEAR} günstig – Pauschalreisen | Urlaubfinder365`,
    seoDescription: `All Inclusive Türkei ${YEAR} günstig buchen ✓ Antalya, Side, Belek ✓ Ab 400€ pro Person ✓ 4-5 Sterne ✓ Täglich aktuelle Angebote.`,
    heroImage: "https://images.unsplash.com/photo-1596392927852-2a18c336fb78?w=800&q=80&auto=format",
    lead: "Alles inklusive – von Frühstück bis Cocktails an der Poolbar. Die Türkei ist das Land der All-Inclusive-Resorts mit unschlagbarem Preis-Leistungs-Verhältnis.",
    longDescription: "All-Inclusive-Pauschalreisen in die Türkei sind der Klassiker für sorgenfreien Urlaub. In den meisten 4- und 5-Sterne-Hotels ist das komplette Verpflegungskonzept inklusive: Frühstück, Mittagessen, Abendessen, Snacks, alkoholische und alkoholfreie Getränke. Viele Resorts bieten sogar 'Ultra All-Inclusive' mit Minibar, Premium-Alkoholika und à-la-carte-Restaurants ohne Aufpreis. Die Türkei ist damit ideal für Familien, die ohne Budget-Stress Urlaub machen wollen.",
    highlights: [
      "4-5 Sterne Resorts mit All-Inclusive-Konzept",
      "Frühstück, Mittagessen, Abendessen inklusive",
      "Snacks & Getränke ganztägig",
      "Viele Resorts mit à-la-carte-Restaurants",
      "Kinderbetreuung in Familienhotels",
    ],
    faqs: [
      { question: "Was ist bei All Inclusive in der Türkei enthalten?", answer: "Standard-All-Inclusive umfasst Frühstück, Mittagessen, Abendessen, Snacks sowie alkoholische und alkoholfreie Getränke aus lokalen Marken. 'Ultra All-Inclusive' erweitert dies um Premium-Getränke, Minibar-Auffüllung und kostenlosen Zugang zu à-la-carte-Restaurants." },
      { question: "Lohnt sich All Inclusive in der Türkei?", answer: "Ja, besonders für Familien und Paare, die die Urlaubskosten im Voraus kalkulieren wollen. In der Türkei ist All-Inclusive oft günstiger als Halbpension in anderen Ländern – bei besserer Qualität der Hotels." },
      { question: "Gibt es All Inclusive Türkei für unter 500€?", answer: "Ja, besonders in der Nebensaison (Mai, September, Oktober) gibt es regelmäßig All-Inclusive-Angebote in 4-Sterne-Hotels unter 500 € pro Person inklusive Flug. Frühbuchung oder Last-Minute-Deals zahlen sich besonders aus." },
    ],
    relatedDestinationSlugs: ["antalya", "side", "alanya", "bodrum"],
  },
  {
    slug: "aegypten",
    country: "Ägypten",
    flag: "🇪🇬",
    regionId: "651",
    minRecommrate: "65",
    category: "4",
    h1: `Pauschalreisen Ägypten ${YEAR} – Hurghada & Rotes Meer`,
    seoTitle: `Pauschalreisen Ägypten ${YEAR} günstig – Hurghada, Marsa Alam`,
    seoDescription: `Pauschalreisen Ägypten ${YEAR} günstig buchen ✓ Hurghada ✓ Rotes Meer ✓ All Inclusive ab 400€ ✓ Ganzjährig warm ✓ Top-Schnorchelgebiete.`,
    heroImage: "https://images.unsplash.com/photo-1601048902898-2f9a48c33b8e?w=800&q=80&auto=format",
    lead: "Ägypten bietet das ganze Jahr über warmes Badewetter, traumhafte Korallenriffe und unschlagbare All-Inclusive-Preise – ideal für Tauch-Fans und Sonnenanbeter.",
    longDescription: "Ägypten zählt zu den Ganzjahres-Zielen für Pauschalreisen: Das Rote Meer in Hurghada, Marsa Alam und Sharm el-Sheikh bietet selbst im europäischen Winter angenehme 22-25 °C und lädt zum Baden, Schnorcheln und Tauchen ein. Die Korallenriffe zählen zu den schönsten der Welt und sind direkt vor der Hoteltür erreichbar. All-Inclusive-Pauschalreisen starten bereits ab 400 € pro Person – auch in der Hauptsaison günstiger als viele europäische Ziele.",
    highlights: [
      "Ganzjährig warmes Wetter (22-30 °C)",
      "Top-Schnorchelgebiete direkt am Hotelstrand",
      "Günstige All-Inclusive-Preise",
      "Ausflüge nach Luxor & Kairo möglich",
      "Wellness & Spa in vielen Resorts",
    ],
    faqs: [
      { question: "Wann ist die beste Reisezeit für Ägypten?", answer: "Ägypten ist ganzjährig warm. Oktober bis April sind angenehm (22-28 °C), während Juli/August sehr heiß werden (35-40 °C). Für Badeurlaub ist fast jeder Monat geeignet – für Ausflüge nach Luxor oder Kairo sind die Wintermonate ideal." },
      { question: "Ist Ägypten sicher für Pauschalurlauber?", answer: "Die klassischen Touristengebiete in Hurghada, Marsa Alam und Sharm el-Sheikh gelten als sicher. Das Auswärtige Amt empfiehlt allerdings, größere Städte und bestimmte Wüstenregionen zu meiden. Informiere dich vor der Reise auf auswaertiges-amt.de." },
      { question: "Kann man in Ägypten mit Euro bezahlen?", answer: "In Touristenzonen werden Euro oft akzeptiert, aber zu schlechten Kursen. Besser: Bargeld vor Ort in Ägyptische Pfund tauschen oder per Kreditkarte zahlen. Kleine Beträge (Trinkgelder) solltest du in Ägyptischen Pfund parat haben." },
    ],
    relatedDestinationSlugs: ["hurghada", "marsa-alam", "sharm-el-sheikh"],
  },
  {
    slug: "mallorca",
    country: "Spanien",
    flag: "🇪🇸",
    regionId: "67",
    minRecommrate: "60",
    category: "3",
    h1: `Pauschalreisen Mallorca ${YEAR} – der Klassiker`,
    seoTitle: `Pauschalreisen Mallorca ${YEAR} günstig – Flug & Hotel`,
    seoDescription: `Pauschalreisen Mallorca ${YEAR} günstig buchen ✓ Palma, Alcudia, Cala Millor ✓ Ab 450€ ✓ Tägliche Flüge ✓ Top-Hotels & Ferienwohnungen.`,
    heroImage: "https://images.unsplash.com/photo-1580974852861-efd0cb71aa50?w=800&q=80&auto=format",
    lead: "Mallorca ist und bleibt die Lieblingsinsel der Deutschen – mit kurzen Flugzeiten, traumhaften Stränden und einer einzigartigen Mischung aus Erholung und Nachtleben.",
    longDescription: "Mallorca ist Deutschlands beliebtestes Pauschalreise-Ziel – und das aus gutem Grund. Die größte Baleareninsel bietet alles: traumhafte Sandstrände (Es Trenc, Playa de Muro), kristallklares Wasser, über 300 Sonnentage, kurze Flugzeiten von nur 2-2,5 Stunden und eine perfekte Infrastruktur. Ob Familie, Paar oder Party-Urlauber – jeder findet hier seinen Platz. Pauschalreisen starten ab 450 € pro Person inklusive Flug und Hotel.",
    highlights: [
      "Kurze Flugzeit (2-2,5 Stunden)",
      "300+ Sonnentage pro Jahr",
      "Über 200 Strände zur Auswahl",
      "Alle Hotelkategorien verfügbar",
      "Perfekt für Familien, Paare & Gruppen",
    ],
    faqs: [
      { question: "Wie teuer ist eine Pauschalreise nach Mallorca?", answer: "Pauschalreisen nach Mallorca starten in der Nebensaison bei etwa 350-450 € pro Person für eine Woche inklusive Flug und Hotel. In der Hauptsaison (Juli/August) liegen die Preise bei 700-1.200 €. All-Inclusive ist ab 550 € möglich." },
      { question: "Welche Region Mallorca ist am schönsten?", answer: "Das hängt von deinen Vorlieben ab: Playa de Palma & El Arenal für Partys und günstige Hotels, Alcudia und Cala Millor für Familien, Port de Soller und Deia für ruhigen Insel-Charme, Cala Rajada für Taucher. Für Kulturfans ist Palma de Mallorca Pflicht." },
      { question: "Wann ist Nebensaison auf Mallorca?", answer: "Nebensaison auf Mallorca ist von November bis April (außer Weihnachten/Ostern). Mai und Oktober zählen zur Vorsaison mit milderen Preisen, aber bereits badetauglichem Wetter. September ist ein Geheimtipp mit noch warmem Meer und günstigeren Preisen als im August." },
    ],
    relatedDestinationSlugs: ["mallorca", "palma-de-mallorca"],
  },
  {
    slug: "griechenland",
    country: "Griechenland",
    flag: "🇬🇷",
    regionId: "59",
    minRecommrate: "60",
    category: "3",
    h1: `Pauschalreisen Griechenland ${YEAR} – Inseln & Festland`,
    seoTitle: `Pauschalreisen Griechenland ${YEAR} günstig – Kreta, Rhodos, Kos`,
    seoDescription: `Pauschalreisen Griechenland ${YEAR} günstig buchen ✓ Kreta, Rhodos, Kos, Korfu ✓ Ab 400€ ✓ Mediterranes Flair & traumhafte Strände.`,
    heroImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80&auto=format",
    lead: "Sonne, Meer, antike Kultur und griechische Gastfreundschaft – Pauschalreisen nach Griechenland bieten pures mediterranes Lebensgefühl.",
    longDescription: "Griechenland ist mit seinen unzähligen Inseln ein Paradies für Pauschalreisende. Die größten Inseln Kreta, Rhodos, Kos und Korfu sind direkt mit Charterflügen erreichbar und bieten eine einzigartige Mischung aus Badeurlaub und Kulturerleben. Antike Stätten, malerische Fischerdörfer und traumhafte Buchten mit türkisblauem Wasser machen jeden Urlaub unvergesslich. All-Inclusive-Angebote starten ab 400 € pro Person.",
    highlights: [
      "Traumhafte Buchten und Sandstrände",
      "Antike Stätten und Kultur",
      "Griechische Küche & Gastfreundschaft",
      "Milde Temperaturen (Mai-Oktober)",
      "Vielfältige Inseln für jeden Geschmack",
    ],
    faqs: [
      { question: "Welche griechische Insel für Pauschalreise?", answer: "Kreta ist die größte und vielseitigste, ideal für alle. Rhodos bietet Sonne satt und tolle Strände. Kos eignet sich für Radfahrer und Familien. Korfu ist die grünste Insel mit venezianischem Flair. Santorin und Mykonos sind eher für Paare und Individualreisende (teurer)." },
      { question: "Wie teuer sind Pauschalreisen nach Griechenland?", answer: "In der Nebensaison (Mai, Oktober) gibt es Pauschalreisen ab 350-400 € pro Person für eine Woche. In der Hauptsaison liegen die Preise bei 600-900 €. All-Inclusive startet bei rund 450 €." },
      { question: "Ist Griechenland Pauschalreise kinderfreundlich?", answer: "Absolut. Die griechische Kultur ist sehr kinderfreundlich, viele Hotels haben spezielle Kids-Programme, Kinderpools und Familienzimmer. Kreta, Kos und Rhodos haben besonders viele familienorientierte Resorts." },
    ],
    relatedDestinationSlugs: ["kreta", "rhodos", "korfu", "kos"],
  },
  {
    slug: "kanaren",
    country: "Kanaren",
    flag: "🇪🇸",
    regionId: "851",
    minRecommrate: "65",
    category: "3",
    h1: `Pauschalreisen Kanaren ${YEAR} – Ganzjahres-Urlaub`,
    seoTitle: `Pauschalreisen Kanaren ${YEAR} günstig – Teneriffa, Gran Canaria`,
    seoDescription: `Pauschalreisen Kanaren ${YEAR} günstig buchen ✓ Teneriffa, Gran Canaria, Fuerteventura ✓ Ganzjahres-Sonne ✓ All Inclusive ab 450€.`,
    heroImage: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80&auto=format",
    lead: "Ewiger Frühling auf den Kanarischen Inseln: Das ideale Reiseziel für alle, die auch im Winter Sonne tanken wollen.",
    longDescription: "Die Kanarischen Inseln bieten ganzjährig mildes Klima mit 20-25 °C – der perfekte Ort, um dem deutschen Winter zu entfliehen. Teneriffa, Gran Canaria, Fuerteventura und Lanzarote sind jeweils mit Charterflügen direkt erreichbar und bieten ein breites Hotelangebot in allen Preisklassen. Vulkanlandschaften, kilometerlange Sandstrände und stabiles Klima machen die Kanaren zu einem Ganzjahres-Hit.",
    highlights: [
      "Ganzjährig 20-25 °C",
      "Über 300 Sonnentage",
      "Kilometerlange Sandstrände",
      "Ideales Wanderrevier (Teneriffa)",
      "Ungewöhnliche Vulkanlandschaften",
    ],
    faqs: [
      { question: "Welche kanarische Insel ist die beste?", answer: "Teneriffa ist die größte und vielfältigste mit Vulkanen, Wanderwegen und Stränden. Gran Canaria bietet die schönsten Sanddünen und Badeorte. Fuerteventura ist Traumziel für Wind- und Kitesurfer. Lanzarote hat einzigartige Vulkanlandschaften und ist ruhiger." },
      { question: "Sind die Kanaren ganzjährig warm?", answer: "Ja, die Temperaturen schwanken nur zwischen 18 °C im Januar und 25 °C im August. Die Wassertemperatur bleibt ganzjährig bei 19-22 °C. Es gibt selten Regen, dafür oft Sonne." },
      { question: "Wie lange dauert der Flug zu den Kanaren?", answer: "Von Deutschland sind es 4,5 bis 5 Stunden Flugzeit. Alle großen deutschen Flughäfen haben Charter- und Linienflüge zu Teneriffa, Gran Canaria, Fuerteventura und Lanzarote." },
    ],
    relatedDestinationSlugs: ["teneriffa", "gran-canaria", "fuerteventura", "lanzarote"],
  },
  {
    slug: "tuerkei-unter-500",
    country: "Türkei",
    flag: "🇹🇷",
    regionId: "724",
    maxPrice: "500",
    minRecommrate: "60",
    h1: `Türkei unter 500 € – günstige Pauschalreisen ${YEAR}`,
    seoTitle: `Türkei Pauschalreise unter 500€ ${YEAR} – All Inclusive Deals`,
    seoDescription: `Türkei Pauschalreisen unter 500€ ${YEAR} ✓ All Inclusive möglich ✓ Antalya, Side, Alanya ✓ Tägliche Deals ✓ Flug + Hotel + Transfer.`,
    heroImage: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&q=80&auto=format",
    lead: "Sonne, Strand und All-Inclusive für unter 500 € – in der Türkei machbar. Wir zeigen dir die besten Angebote.",
    longDescription: "Budget-Reisende können in der Türkei besonders viel Urlaub für ihr Geld bekommen. Pauschalreisen mit Flug, Hotel und Transfer gibt es regelmäßig unter 500 € pro Person – und das oft sogar mit All-Inclusive-Verpflegung. Die besten Schnäppchen findet man in der Nebensaison (Mai, September, Oktober) oder als Last-Minute-Deal 2-4 Wochen vor Abreise.",
    highlights: [
      "Pauschalreisen ab 350 €",
      "All-Inclusive oft unter 500 €",
      "Nebensaison besonders günstig",
      "Last-Minute-Schnäppchen verfügbar",
      "Standard 3-4 Sterne Hotels",
    ],
    faqs: [
      { question: "Gibt es wirklich Pauschalreisen Türkei unter 500€?", answer: "Ja, regelmäßig. Besonders in der Nebensaison (Mai, September, Oktober) und als Last-Minute-Deal gibt es All-Inclusive-Angebote unter 500 € pro Person. Frühbuchung kann auch für Hauptsaison lohnen." },
      { question: "Welche Hotels gibt es für unter 500€?", answer: "Hauptsächlich 3- und 4-Sterne-Hotels mit Halbpension oder All-Inclusive. Die Qualität ist in der Türkei meist sehr gut – viele '4-Sterne' Resorts sind internationalen 4,5-5 Sterne Hotels vergleichbar." },
    ],
    relatedDestinationSlugs: ["antalya", "side", "alanya"],
  },
  {
    slug: "aegypten-unter-1000",
    country: "Ägypten",
    flag: "🇪🇬",
    regionId: "651",
    maxPrice: "1000",
    minRecommrate: "70",
    category: "4",
    board: "AI",
    h1: `All Inclusive Ägypten unter 1000 € – Top-Deals ${YEAR}`,
    seoTitle: `All Inclusive Ägypten unter 1000€ ${YEAR} – Pauschalreisen Hurghada`,
    seoDescription: `All Inclusive Ägypten ${YEAR} unter 1000€ pro Person ✓ 4-5 Sterne Resorts ✓ Hurghada, Marsa Alam ✓ Täglich aktuelle Angebote.`,
    heroImage: "https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=800&q=80&auto=format",
    lead: "Ägypten All Inclusive unter 1000 € – wir zeigen dir, wie du in 4- oder 5-Sterne-Resorts am Roten Meer urlaubst, ohne das Budget zu sprengen.",
    longDescription: "Für unter 1000 € pro Person bekommst du in Ägypten bereits hochwertige 4- und 5-Sterne All-Inclusive-Pauschalreisen. Die Resorts am Roten Meer (Hurghada, Marsa Alam, Sharm el-Sheikh) bieten exzellentes Preis-Leistungs-Verhältnis: direkte Strandlage, Top-Schnorchelgebiete, mehrere Pools und abwechslungsreiche Verpflegung. Selbst in der Hauptsaison sind solche Deals realistisch – in der Nebensaison oft sogar unter 600 €.",
    highlights: [
      "4-5 Sterne Resorts unter 1000 €",
      "All-Inclusive inklusive Getränke",
      "Direkte Strandlage mit Hausriff",
      "Schnorchel- & Tauchmöglichkeiten",
      "Mehrere Pools und Wellness",
    ],
    faqs: [
      { question: "Ist All Inclusive Ägypten unter 1000€ möglich?", answer: "Definitiv. Auch in der Hauptsaison findet man 4- und 5-Sterne All-Inclusive-Resorts unter 1000 € pro Person. In der Nebensaison (März/April, Oktober/November) sind oft Preise unter 600 € realistisch." },
      { question: "Was kostet ein All-Inclusive-Urlaub Ägypten?", answer: "Günstige All-Inclusive Angebote starten bei etwa 400 € pro Person in der Nebensaison. In der Hauptsaison (Weihnachten, Ostern, Sommer) liegen die Preise zwischen 600-1200 €. 5-Sterne-Deluxe-Resorts kosten ab 800 €." },
    ],
    relatedDestinationSlugs: ["hurghada", "marsa-alam", "sharm-el-sheikh"],
  },
  {
    slug: "spanien",
    country: "Spanien",
    flag: "🇪🇸",
    regionId: "725",
    minRecommrate: "60",
    category: "3",
    h1: `Pauschalreisen Spanien ${YEAR} – Balearen, Kanaren & Festland`,
    seoTitle: `Pauschalreisen Spanien ${YEAR} – Mallorca, Kanaren, Costa del Sol`,
    seoDescription: `Pauschalreisen Spanien ${YEAR} günstig buchen ✓ Mallorca, Ibiza, Kanaren ✓ Costa del Sol ✓ Ab 350€ ✓ Täglich aktualisierte Angebote.`,
    heroImage: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&auto=format",
    lead: "Spanien ist das meistbesuchte Pauschalreise-Land der Deutschen – und das aus gutem Grund: abwechslungsreiche Regionen, fantastisches Essen und garantierte Sonne.",
    longDescription: "Kaum ein Land bietet so viel Vielfalt wie Spanien: Die Balearen (Mallorca, Ibiza, Menorca) locken mit Traumstränden und Partys, die Kanaren mit ganzjährigem Sommer, und das Festland (Costa Brava, Costa del Sol, Costa Dorada) mit historischen Städten und Kultur. Pauschalreisen in diese Regionen starten bei 350-450 € pro Person und sind mit kurzen Flugzeiten (2-5 Stunden) perfekt erreichbar.",
    highlights: [
      "Über 8.000 km Küste",
      "Inseln und Festland zur Wahl",
      "Exzellente Küche (Tapas, Paella)",
      "Ganzjährige Reisezeit (Kanaren)",
      "Kurze Flugzeiten",
    ],
    faqs: [
      { question: "Welche spanische Region für Pauschalreise?", answer: "Mallorca für Klassiker-Urlauber, Ibiza für Party-Fans, Kanaren für Ganzjahres-Sonne, Costa del Sol für Sonnensuchende am Festland, Costa Brava für Kulturfreunde nahe Barcelona." },
      { question: "Wann ist die beste Reisezeit für Spanien?", answer: "Festland-Spanien: Mai-Oktober. Balearen: Mai-Oktober. Kanaren: ganzjährig. Die beste Badezeit ist Juni-September, während September besonders empfehlenswert ist (warmes Meer, weniger Menschen, günstigere Preise)." },
    ],
    relatedDestinationSlugs: ["mallorca", "ibiza", "teneriffa", "gran-canaria", "barcelona"],
  },
  {
    slug: "italien",
    country: "Italien",
    flag: "🇮🇹",
    regionId: "718",
    minRecommrate: "60",
    category: "3",
    h1: `Pauschalreisen Italien ${YEAR} – La Dolce Vita`,
    seoTitle: `Pauschalreisen Italien ${YEAR} – Sardinien, Sizilien, Gardasee`,
    seoDescription: `Pauschalreisen Italien ${YEAR} günstig buchen ✓ Sardinien, Sizilien ✓ Gardasee ✓ Ab 450€ ✓ Täglich aktuelle Angebote & Flüge.`,
    heroImage: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80&auto=format",
    lead: "Italien vereint alles, was einen perfekten Urlaub ausmacht: traumhafte Küsten, exzellente Küche, antike Städte und mediterranes Lebensgefühl.",
    longDescription: "Pauschalreisen nach Italien bringen dich in die schönsten Küstenregionen des Stiefel-Landes. Sardinien besticht durch karibisch anmutende Strände und kristallklares Wasser. Sizilien bietet eine Mischung aus antiken Stätten, Vulkanen und griechisch-arabischer Geschichte. Für Familien ist der Gardasee ideal: milde Temperaturen, viele Aktivitäten und die Alpen als Kulisse. Flugzeiten betragen 1,5-2,5 Stunden.",
    highlights: [
      "Sardinien & Sizilien mit Traumstränden",
      "Gardasee für Familien",
      "Italienische Küche (Pizza, Pasta, Wein)",
      "Antike Stätten und Kultur",
      "Kurze Flugzeit",
    ],
    faqs: [
      { question: "Welche italienische Region für Badeurlaub?", answer: "Sardinien hat die schönsten Strände (Costa Smeralda, La Pelosa). Sizilien kombiniert Strand mit Kultur (Taormina, Cefalù). Kalabrien und Apulien sind günstiger und weniger touristisch. Die italienische Adria ist familienfreundlich mit flachem Wasser." },
      { question: "Sind Pauschalreisen Italien teuer?", answer: "Italien ist teurer als die Türkei oder Ägypten, aber günstiger als Frankreich. Pauschalreisen starten bei etwa 450-550 € pro Person. In der Hauptsaison liegen die Preise bei 800-1.200 €. Sardinien und Sizilien sind etwas teurer als das Festland." },
    ],
    relatedDestinationSlugs: ["sardinien", "sizilien", "rom"],
  },
  {
    slug: "thailand",
    country: "Thailand",
    flag: "🇹🇭",
    regionId: "100220",
    minRecommrate: "65",
    category: "4",
    h1: `Pauschalreisen Thailand ${YEAR} – Fernreise-Träume`,
    seoTitle: `Pauschalreisen Thailand ${YEAR} – Phuket, Khao Lak, Koh Samui`,
    seoDescription: `Pauschalreisen Thailand ${YEAR} ab 1100€ ✓ Phuket, Khao Lak, Koh Samui ✓ 4-5 Sterne ✓ Traumstrände ✓ Fernreise-Deals.`,
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80&auto=format",
    lead: "Weiße Strände, tropisches Klima und buddhistische Tempel – Thailand ist die perfekte Fernreise-Destination für Pauschalurlauber.",
    longDescription: "Thailand bietet auch im Pauschalreise-Segment unschlagbare Qualität: Luxuriöse 4- und 5-Sterne-Resorts an Traumstränden in Phuket, Khao Lak oder Koh Samui sind oft günstiger als vergleichbare Hotels in der Karibik. Die beste Reisezeit ist November bis März (Trockenzeit). Flugzeiten betragen 10-12 Stunden ab Deutschland. Pauschalreisen mit Flug und Hotel starten bei etwa 1100 € pro Person.",
    highlights: [
      "Traumstrände in Phuket & Khao Lak",
      "Luxuriöse Resorts zum fairen Preis",
      "Tropisches Klima (28-32 °C)",
      "Buddhistische Kultur & Tempel",
      "Exzellente thailändische Küche",
    ],
    faqs: [
      { question: "Wann ist beste Reisezeit Thailand?", answer: "Die Trockenzeit von November bis März bietet das beste Wetter: wenig Regen, angenehme Temperaturen (26-32 °C), stabile Bedingungen. April/Mai wird sehr heiß, Juni-Oktober ist Regenzeit (meist nur kurze, intensive Schauer)." },
      { question: "Ist Thailand sicher?", answer: "Thailand gilt als sehr sicheres Reiseland für Pauschalurlauber. Die üblichen Vorsichtsmaßnahmen gelten (Wertsachen, Leitungswasser). Die Thais sind extrem gastfreundlich." },
      { question: "Wie lang ist der Flug nach Thailand?", answer: "Direktflüge von Deutschland (Frankfurt, München) nach Bangkok dauern 10-11 Stunden. Nach Phuket sind es 11-12 Stunden (oft mit Zwischenstopp)." },
    ],
    relatedDestinationSlugs: ["phuket", "khao-lak", "koh-samui"],
  },
  {
    slug: "last-minute-tuerkei",
    country: "Türkei",
    flag: "🇹🇷",
    regionId: "724",
    minRecommrate: "65",
    category: "4",
    lastMinute: true,
    h1: `Last Minute Türkei ${YEAR} – spontan & günstig`,
    seoTitle: `Last Minute Türkei ${YEAR} – günstige Pauschalreisen kurzfristig`,
    seoDescription: `Last Minute Türkei ${YEAR} ✓ Pauschalreisen kurzfristig ✓ Antalya, Side, Alanya ✓ All Inclusive ✓ Ab 300€ ✓ Täglich neue Schnäppchen.`,
    heroImage: "https://images.unsplash.com/photo-1596392927852-2a18c336fb78?w=800&q=80&auto=format",
    lead: "Spontan in die Sonne: Last-Minute-Deals in die Türkei sind regelmäßig 30-50 % günstiger als Frühbucher-Angebote.",
    longDescription: "Wer spontan und flexibel ist, kann bei Last-Minute-Reisen in die Türkei ordentlich sparen. Die besten Schnäppchen gibt es 2-4 Wochen vor Abflug: All-Inclusive-Pauschalreisen in 4-Sterne-Hotels bereits ab 300 € pro Person. Die Veranstalter reduzieren kurz vor Abreise die Preise, um Restplätze zu füllen. Ideal für spontane Urlaubsentscheidungen oder Last-Minute-Stornos.",
    highlights: [
      "Ab 300 € pro Person möglich",
      "Abflug oft schon in wenigen Tagen",
      "4-Sterne All-Inclusive üblich",
      "Täglich neue Angebote",
      "Ideal für Spontane",
    ],
    faqs: [
      { question: "Wie kurzfristig kann ich Last Minute buchen?", answer: "Last-Minute-Reisen sind oft schon 2-3 Tage vor Abflug buchbar. Die besten Deals findet man meist 2-4 Wochen vor Abreise. Super-Last-Minute (24-48h) ist selten und meist mit eingeschränkter Hotel-Auswahl verbunden." },
      { question: "Sind Last-Minute-Reisen wirklich günstig?", answer: "Ja, oft 20-50 % günstiger als Frühbucher-Preise. Aber: Hotelauswahl ist eingeschränkt, Flüge zu unüblichen Zeiten und beliebte Resorts sind oft schon ausgebucht. Für Flexibilität belohnt mit ordentlichen Rabatten." },
    ],
    relatedDestinationSlugs: ["antalya", "side", "alanya"],
  },
];

export function getPauschalKombi(slug: string): PauschalKombi | undefined {
  return PAUSCHAL_KOMBIS.find((k) => k.slug === slug);
}
