export interface SeasonGuideDestination {
  slug: string;
  name: string;
  country: string;
  tempAir: string;
  tempWater?: string;
  priceHint: "günstig" | "mittel" | "teuer";
  reason: string;
}

export interface SeasonGuide {
  slug: string;                // URL-Slug (januar, februar ...)
  month: string;               // Anzeigename
  emoji: string;
  headline: string;
  lead: string;
  heroImage: string;
  seoTitle: string;
  seoDescription: string;
  weatherSummary: string;
  bookingTip: string;
  destinations: SeasonGuideDestination[];
  faqs: { question: string; answer: string }[];
}

const YEAR = new Date().getFullYear();

export const SEASON_GUIDES: SeasonGuide[] = [
  {
    slug: "januar",
    month: "Januar",
    emoji: "❄️",
    headline: "Beste Reiseziele im Januar",
    lead: "Dem Winter entfliehen: Ganzjahres-Sonnenziele, Ski-Hotspots und Fernreisen zum Schnäppchenpreis.",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im Januar ${YEAR} – Wintersonne & Fernreisen`,
    seoDescription: `Die schönsten Reiseziele im Januar ${YEAR} ✓ Wintersonne Kanaren ✓ Fernreisen günstig ✓ Ski-Urlaub Alpen ✓ Wetter, Preise & Tipps für deine Januar-Reise.`,
    weatherSummary: "Europa liegt im tiefen Winter. Für Sonnenhungrige sind die Kanaren (22 °C), Ägypten (21 °C) und Fernziele wie Thailand (31 °C), Kuba (28 °C) und Dubai (24 °C) perfekt. Die Alpen bieten beste Skibedingungen.",
    bookingTip: "Die erste Januar-Hälfte nach Silvester ist die günstigste Reisezeit im Jahr. Last-Minute-Angebote für Fernziele sind oft 30-50 % reduziert.",
    destinations: [
      { slug: "teneriffa",     name: "Teneriffa",    country: "Spanien",      tempAir: "21 °C", tempWater: "19 °C", priceHint: "mittel",  reason: "Ewiger Frühling auf den Kanaren – ideal zum Wandern und Strandbesuch." },
      { slug: "gran-canaria",  name: "Gran Canaria", country: "Spanien",      tempAir: "21 °C", tempWater: "20 °C", priceHint: "mittel",  reason: "Sandstrände bei mildem Klima, perfekt für Sonnensüchtige." },
      { slug: "fuerteventura", name: "Fuerteventura",country: "Spanien",      tempAir: "20 °C", tempWater: "19 °C", priceHint: "mittel",  reason: "Wind, Wellen & Wassersport bei dauerhaft warmen Temperaturen." },
      { slug: "lanzarote",     name: "Lanzarote",    country: "Spanien",      tempAir: "21 °C", tempWater: "19 °C", priceHint: "mittel",  reason: "Einzigartige Vulkanlandschaft – ideal für aktive Urlauber." },
      { slug: "hurghada",      name: "Hurghada",     country: "Ägypten",      tempAir: "22 °C", tempWater: "22 °C", priceHint: "günstig", reason: "Wärmste Option in Flugnähe – Schnorcheln & Tauchen im Roten Meer." },
      { slug: "dubai",         name: "Dubai",        country: "VAE",          tempAir: "24 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Luxus, Shopping & garantierte Sonne." },
      { slug: "bali",          name: "Bali",         country: "Indonesien",   tempAir: "31 °C", tempWater: "29 °C", priceHint: "teuer",   reason: "Regenzeit, aber trotzdem warm und authentisch." },
      { slug: "phuket",        name: "Phuket",       country: "Thailand",     tempAir: "31 °C", tempWater: "29 °C", priceHint: "teuer",   reason: "Trockenzeit – bestes Wetter für Strände und Inselhopping." },
      { slug: "malediven",     name: "Malediven",    country: "Malediven",    tempAir: "30 °C", tempWater: "28 °C", priceHint: "teuer",   reason: "Traumstrände abseits der Monsunzeit." },
      { slug: "kuba",          name: "Kuba",         country: "Kuba",         tempAir: "28 °C", tempWater: "26 °C", priceHint: "mittel",  reason: "Karibik-Feeling mit Rum, Rhythmus und Sonne satt." },
    ],
    faqs: [
      { question: "Wohin im Januar ohne lange Flugzeit?", answer: "Die Kanarischen Inseln (Teneriffa, Gran Canaria, Fuerteventura, Lanzarote) und Ägypten (Hurghada, Marsa Alam) sind in 4-5 Stunden Flug erreichbar und bieten 20-22 °C. Dort ist im Januar Badetemperatur und Sonnengarantie." },
      { question: "Wie teuer ist eine Januar-Reise?", answer: "Die erste Januar-Hälfte nach den Feiertagen zählt zur günstigsten Reisezeit im Jahr. Pauschalreisen auf die Kanaren sind oft ab 400 € pro Person zu haben, Fernreisen auf Sri Lanka oder nach Thailand ab 1.200 €." },
      { question: "Ist Skifahren im Januar sinnvoll?", answer: "Ja – der Januar bietet oft die beste Schneelage der Saison. Österreich (Ischgl, Sölden), Schweiz (Davos, Zermatt) und Südtirol sind Top-Ziele. Tipp: Die Januar-Woche nach den Heilig-Drei-Könige-Ferien ist meist am günstigsten." },
      { question: "Welche Fernreise lohnt im Januar besonders?", answer: "Thailand, Vietnam und Kambodscha liegen im Januar in der Trockenzeit – ideal für Rundreisen. Kuba und Dominikanische Republik bieten karibisches Wetter. Bali hat zwar Regenzeit, aber trotzdem 31 °C und ist außerhalb der Hochsaison günstiger." },
    ],
  },
  {
    slug: "februar",
    month: "Februar",
    emoji: "🏂",
    headline: "Beste Reiseziele im Februar",
    lead: "Ski-Hochsaison, Karneval in Rio & karibische Sonne – der Februar ist vielseitiger, als man denkt.",
    heroImage: "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im Februar ${YEAR} – Skiurlaub, Karneval & Karibik`,
    seoDescription: `Top-Reiseziele im Februar ${YEAR} ✓ Schneesichere Skigebiete ✓ Karibik-Sonne ✓ Karneval Rio & Venedig ✓ Wetter, Angebote & Tipps.`,
    weatherSummary: "Europa bleibt winterlich (Alpen: ideale Schneeverhältnisse). Karibik, Kanaren und Südostasien sind bei 25-30 °C ideal. In Brasilien und Venedig herrscht Karnevals-Hochsaison.",
    bookingTip: "Februar-Ferien sind in vielen Bundesländern aktiv – buche 3-4 Monate vorher, um teure Last-Minute-Preise zu umgehen.",
    destinations: [
      { slug: "teneriffa",    name: "Teneriffa",    country: "Spanien",     tempAir: "21 °C", tempWater: "18 °C", priceHint: "mittel", reason: "Karneval-Hochburg Santa Cruz – einer der größten Karnevale der Welt." },
      { slug: "gran-canaria", name: "Gran Canaria", country: "Spanien",     tempAir: "22 °C", tempWater: "19 °C", priceHint: "mittel", reason: "Garantierte Sonne und lange Sandstrände." },
      { slug: "fuerteventura",name: "Fuerteventura",country: "Spanien",     tempAir: "21 °C", tempWater: "18 °C", priceHint: "mittel", reason: "Windsportparadies mit Traumstränden." },
      { slug: "hurghada",     name: "Hurghada",     country: "Ägypten",     tempAir: "23 °C", tempWater: "22 °C", priceHint: "günstig", reason: "Preiswerte Wintersonne mit Schnorchel-Highlights." },
      { slug: "dubai",        name: "Dubai",        country: "VAE",         tempAir: "25 °C", tempWater: "22 °C", priceHint: "mittel", reason: "Angenehmste Reisezeit im Jahr – nicht zu heiß für Sightseeing." },
      { slug: "maldiven",     name: "Malediven",    country: "Malediven",   tempAir: "30 °C", tempWater: "28 °C", priceHint: "teuer",  reason: "Trockenste Jahreszeit – perfekt für Traumurlaub." },
      { slug: "thailand",     name: "Thailand",     country: "Thailand",    tempAir: "32 °C", tempWater: "29 °C", priceHint: "teuer",  reason: "Hauptsaison mit stabilem Wetter für Inselhopping." },
      { slug: "sri-lanka",    name: "Sri Lanka",    country: "Sri Lanka",   tempAir: "30 °C", tempWater: "28 °C", priceHint: "mittel", reason: "Südwestküste (Galle, Bentota) ist trocken und warm." },
    ],
    faqs: [
      { question: "Wohin mit Kindern im Februar?", answer: "Die Kanaren sind ideal: kurzer Flug, familienfreundliche Hotels, warmes Wetter. Für Aktivurlaub bieten sich Skigebiete in Österreich und Südtirol an – viele Hotels haben eigene Kinderbetreuung." },
      { question: "Ist Februar eine gute Zeit für die Karibik?", answer: "Ja, Februar zählt zur Trockenzeit in der Karibik. Kuba, Dominikanische Republik und Jamaika haben 26-28 °C, wenig Regen und angenehme Luftfeuchtigkeit. Allerdings ist es Hochsaison und entsprechend teuer." },
      { question: "Wo ist der beste Karneval 2026?", answer: "Der Karneval in Rio de Janeiro (Brasilien) ist der größte der Welt und findet meist in der zweiten Februarhälfte statt. In Europa sind Venedig (Italien), Santa Cruz de Tenerife und Köln die Top-Adressen." },
    ],
  },
  {
    slug: "maerz",
    month: "März",
    emoji: "🌸",
    headline: "Beste Reiseziele im März",
    lead: "Frühling am Mittelmeer, Kirschblüte in Japan & letzte Ski-Tage – März ist Übergangsmonat mit vielen Chancen.",
    heroImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im März ${YEAR} – Frühling, Kirschblüte & günstige Angebote`,
    seoDescription: `Top-Reiseziele im März ${YEAR} ✓ Mittelmeer im Frühling ✓ Kirschblüte Japan ✓ Städtereisen günstig ✓ Wetter & Buchungstipps.`,
    weatherSummary: "Mittelmeer-Ziele (Mallorca, Zypern, Kreta) erwachen langsam mit 17-21 °C. Kanaren und Ägypten sind badetauglich. In Japan beginnt die Kirschblüten-Saison.",
    bookingTip: "März ist traditionell günstig – vor den Osterferien besonders. Städtereisen und Mittelmeer-Ziele gibt es zum halben Preis der Hochsaison.",
    destinations: [
      { slug: "mallorca",     name: "Mallorca",    country: "Spanien",   tempAir: "17 °C", tempWater: "15 °C", priceHint: "günstig", reason: "Mandelblüte & Wanderwetter – Geheimtipp der Insel-Kenner." },
      { slug: "zypern",       name: "Zypern",      country: "Zypern",    tempAir: "19 °C", tempWater: "17 °C", priceHint: "günstig", reason: "Wärmstes EU-Ziel im März, perfekt für Sightseeing & leichte Wanderungen." },
      { slug: "marrakesch",   name: "Marrakesch",  country: "Marokko",   tempAir: "23 °C", tempWater: "—",     priceHint: "günstig", reason: "Angenehme Temperaturen für Medina-Bummel und Atlas-Ausflüge." },
      { slug: "dubai",        name: "Dubai",       country: "VAE",       tempAir: "26 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Letzte angenehme Reisezeit vor der Sommerhitze." },
      { slug: "teneriffa",    name: "Teneriffa",   country: "Spanien",   tempAir: "22 °C", tempWater: "19 °C", priceHint: "mittel",  reason: "Frühling im Sommerklima – Strand und Wandern möglich." },
      { slug: "hurghada",     name: "Hurghada",    country: "Ägypten",   tempAir: "25 °C", tempWater: "22 °C", priceHint: "günstig", reason: "Badetauglich bei Top-Preisen." },
      { slug: "barcelona",    name: "Barcelona",   country: "Spanien",   tempAir: "16 °C", tempWater: "—",     priceHint: "mittel",  reason: "Angenehme Städtereise ohne Sommerhitze." },
      { slug: "rom",          name: "Rom",         country: "Italien",   tempAir: "16 °C", tempWater: "—",     priceHint: "mittel",  reason: "Perfektes Sightseeing-Wetter ohne Touristenmassen." },
    ],
    faqs: [
      { question: "Ist Baden im März möglich?", answer: "Ja, aber nur außerhalb Europas oder auf den Kanaren. Die Kanaren, Ägypten (Rotes Meer), Zypern und Fernziele wie Thailand oder Dubai bieten Wassertemperaturen von 19-28 °C. Das Festland-Mittelmeer ist mit 14-15 °C noch zu kalt." },
      { question: "Wann beginnt die Kirschblüte in Japan 2026?", answer: "Die Kirschblüte (Sakura) beginnt normalerweise Ende März in Tokio und Kyoto und wandert Richtung Norden. Anfang April ist die Blütenpracht am schönsten – eine Reise Mitte März bis Anfang April lohnt sich besonders." },
      { question: "Sind Osterferien im März oder April?", answer: "2026 fällt Ostern auf den 5. April – die Osterferien liegen also hauptsächlich im April. Reisen in der zweiten Märzhälfte sind entsprechend günstiger als nach Ostern." },
    ],
  },
  {
    slug: "april",
    month: "April",
    emoji: "🌷",
    headline: "Beste Reiseziele im April",
    lead: "Oster-Highlights, Frühling am Mittelmeer und perfektes Wetter für Städtereisen und Rundreisen.",
    heroImage: "https://images.unsplash.com/photo-1528127269322-539801943592?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im April ${YEAR} – Ostern, Mittelmeer & Städtereisen`,
    seoDescription: `Die besten Reiseziele im April ${YEAR} ✓ Osterreisen ✓ Mittelmeer im Frühling ✓ Zypern & Mallorca ✓ Wetter, Preise & Geheimtipps.`,
    weatherSummary: "Das Mittelmeer erwärmt sich (Zypern 22 °C, Mallorca 20 °C), die Kanaren bleiben bei 22-23 °C. Südosteuropa wird attraktiv. Fernziele wie die Malediven sind im Übergang zur Regenzeit.",
    bookingTip: "Außerhalb der Osterferien sind April-Reisen stark reduziert. Lock-Angebote für Mallorca, Kreta und Antalya starten mit ab 300 €.",
    destinations: [
      { slug: "mallorca",    name: "Mallorca",    country: "Spanien",   tempAir: "20 °C", tempWater: "16 °C", priceHint: "günstig", reason: "Mandelblütenende, weniger Touristen, angenehmes Wanderwetter." },
      { slug: "zypern",      name: "Zypern",      country: "Zypern",    tempAir: "22 °C", tempWater: "19 °C", priceHint: "günstig", reason: "Bereits badetauglich und günstiger als in den Sommermonaten." },
      { slug: "antalya",     name: "Antalya",     country: "Türkei",    tempAir: "21 °C", tempWater: "19 °C", priceHint: "günstig", reason: "Pauschalreisen starten ab 350 € mit All-Inclusive." },
      { slug: "kreta",       name: "Kreta",       country: "Griechenland", tempAir: "21 °C", tempWater: "17 °C", priceHint: "günstig", reason: "Blütenpracht und leere Strände – Paradies für Wanderer." },
      { slug: "rhodos",      name: "Rhodos",      country: "Griechenland", tempAir: "20 °C", tempWater: "17 °C", priceHint: "günstig", reason: "Angenehmes Frühlingsklima für Kultur und Natur." },
      { slug: "teneriffa",   name: "Teneriffa",   country: "Spanien",   tempAir: "23 °C", tempWater: "20 °C", priceHint: "mittel",  reason: "Dauerhaft mildes Klima, gut für Familien." },
      { slug: "marrakesch",  name: "Marrakesch",  country: "Marokko",   tempAir: "25 °C", tempWater: "—",     priceHint: "günstig", reason: "Perfektes Klima für Atlas-Trekking und Wüstentouren." },
      { slug: "barcelona",   name: "Barcelona",   country: "Spanien",   tempAir: "18 °C", tempWater: "—",     priceHint: "mittel",  reason: "Ideales Wetter für Stadtspaziergänge und Tapas-Touren." },
      { slug: "lissabon",    name: "Lissabon",    country: "Portugal",  tempAir: "19 °C", tempWater: "—",     priceHint: "mittel",  reason: "Bezaubernde Stadt bei angenehmen Frühlingstemperaturen." },
    ],
    faqs: [
      { question: "Wohin an Ostern 2026?", answer: "Wenn du Sonnengarantie willst: Kanaren, Ägypten und die Türkei (Antalya, Side). Für Städtereisen lohnen Lissabon, Barcelona und Sevilla. Tipp: Wer abseits der Ferien reist, spart 30-50 %." },
      { question: "Kann man im April in Griechenland baden?", answer: "Nur eingeschränkt – das Wasser hat 16-17 °C, was für die meisten zu kalt ist. Die Luft ist aber bei 20-22 °C angenehm. Für Badeurlaub besser Zypern (19 °C Wassertemperatur) oder die Kanaren wählen." },
      { question: "Sind Frühbucher-Rabatte noch sinnvoll im April?", answer: "Ja, aber meist nur für Hauptsaison-Reisen. Für April selbst gibt es oft bessere Last-Minute-Deals als Frühbucher-Rabatte, da die Nachfrage außerhalb der Osterferien gering ist." },
    ],
  },
  {
    slug: "mai",
    month: "Mai",
    emoji: "🌺",
    headline: "Beste Reiseziele im Mai",
    lead: "Der wohl schönste Reisemonat – Mittelmeer in Bestform, noch keine Massen, faire Preise.",
    heroImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im Mai ${YEAR} – Mittelmeer, Griechenland & Türkei`,
    seoDescription: `Die besten Reiseziele im Mai ${YEAR} ✓ Mallorca, Kreta, Zypern ✓ Badewetter ✓ Pfingsten ✓ Günstige Preise vor der Hochsaison.`,
    weatherSummary: "Ideale Temperaturen von 22-28 °C in Griechenland, Türkei und auf den Balearen. Wassertemperaturen erreichen 19-22 °C. Das Wetter ist stabil, nicht zu heiß.",
    bookingTip: "Mai ist die perfekte Vorsaison: Wetter wie im Sommer, Preise der Nebensaison. Frühbucher-Angebote enden meist Ende April – jetzt buchen lohnt sich.",
    destinations: [
      { slug: "mallorca",     name: "Mallorca",     country: "Spanien",      tempAir: "23 °C", tempWater: "19 °C", priceHint: "mittel",  reason: "Perfekte Strand- & Wandertemperaturen, noch entspannt." },
      { slug: "kreta",        name: "Kreta",        country: "Griechenland", tempAir: "24 °C", tempWater: "20 °C", priceHint: "mittel",  reason: "Badeurlaub startet – Blütenpracht in voller Pracht." },
      { slug: "rhodos",       name: "Rhodos",       country: "Griechenland", tempAir: "24 °C", tempWater: "20 °C", priceHint: "mittel",  reason: "Top-Ziel für Familien & Sonnenhungrige vor der Hitze." },
      { slug: "zypern",       name: "Zypern",       country: "Zypern",       tempAir: "26 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Sommerwetter ohne Mengenansturm." },
      { slug: "antalya",      name: "Antalya",      country: "Türkei",       tempAir: "25 °C", tempWater: "21 °C", priceHint: "günstig", reason: "Bestes Wetter bei All-Inclusive-Preisen unter Hochsaison." },
      { slug: "side",         name: "Side",        country: "Türkei",       tempAir: "26 °C", tempWater: "21 °C", priceHint: "günstig", reason: "Antike Ruinen ohne Hitze, Badewasser schon warm." },
      { slug: "korfu",        name: "Korfu",       country: "Griechenland", tempAir: "22 °C", tempWater: "19 °C", priceHint: "mittel",  reason: "Grüne Insel im schönsten Frühlingskleid." },
      { slug: "madeira",      name: "Madeira",     country: "Portugal",     tempAir: "21 °C", tempWater: "19 °C", priceHint: "mittel",  reason: "Wanderparadies mit Blüten und mildem Klima." },
    ],
    faqs: [
      { question: "Wann sind die Pfingstferien 2026?", answer: "Pfingsten fällt 2026 auf den 24.-25. Mai. Die Pfingstferien variieren je nach Bundesland – meistens eine Woche davor oder danach. Reisen außerhalb der Ferien sparen bis zu 40 %." },
      { question: "Wo gibt's im Mai Badeurlaub in Europa?", answer: "Zypern (22 °C Wasser), Türkei (21 °C), Rhodos & Kreta (20 °C) und Balearen (19 °C) sind bereits badetauglich. Italienische Adria und Kroatien sind noch zu kühl (15-17 °C)." },
      { question: "Ist Mai günstiger als Juni?", answer: "Ja, deutlich. Mai zählt zur Vorsaison und ist 20-40 % günstiger als Juni/Juli. Besonders bei Pauschalreisen auf die Türkei, Ägypten und Griechenland sind die Preise im Mai am besten." },
    ],
  },
  {
    slug: "juni",
    month: "Juni",
    emoji: "☀️",
    headline: "Beste Reiseziele im Juni",
    lead: "Der Sommer beginnt – perfekte Bedingungen fürs Mittelmeer, lange Tage und maritime Stimmung.",
    heroImage: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im Juni ${YEAR} – Mittelmeer, Balearen & Badeurlaub`,
    seoDescription: `Die besten Reiseziele im Juni ${YEAR} ✓ Mallorca, Kreta & Türkei ✓ Sommerhitze ✓ Badewetter garantiert ✓ Tipps & Preise.`,
    weatherSummary: "Europa erreicht Badeklima: Mittelmeer (25-30 °C Luft, 21-24 °C Wasser), Adria (24 °C Luft) und Kanaren (25 °C). Skandinavien wird sehr attraktiv für Naturfreunde.",
    bookingTip: "Der Juni-Anfang ist noch günstig, zum Schulferienstart steigen die Preise rasant. Wer flexibel ist, sollte in den ersten drei Juniwochen reisen.",
    destinations: [
      { slug: "mallorca",    name: "Mallorca",    country: "Spanien",      tempAir: "26 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Wetterhoch, volle Strandtauglichkeit, Partys starten." },
      { slug: "ibiza",       name: "Ibiza",       country: "Spanien",      tempAir: "27 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Party-Saison beginnt, Strände noch leerer." },
      { slug: "kreta",       name: "Kreta",       country: "Griechenland", tempAir: "27 °C", tempWater: "23 °C", priceHint: "mittel",  reason: "Stabiles Sommerwetter, wenig Regen." },
      { slug: "rhodos",      name: "Rhodos",      country: "Griechenland", tempAir: "27 °C", tempWater: "23 °C", priceHint: "mittel",  reason: "Beste Strände voll badetauglich." },
      { slug: "antalya",     name: "Antalya",     country: "Türkei",       tempAir: "30 °C", tempWater: "24 °C", priceHint: "mittel",  reason: "Hitze startet – All-Inclusive-Hotels ideal." },
      { slug: "bodrum",      name: "Bodrum",      country: "Türkei",       tempAir: "29 °C", tempWater: "23 °C", priceHint: "mittel",  reason: "Türkische Ägäis im besten Licht." },
      { slug: "zypern",      name: "Zypern",      country: "Zypern",       tempAir: "29 °C", tempWater: "24 °C", priceHint: "mittel",  reason: "Garantierte Sonne und warmes Meer." },
      { slug: "fuerteventura",name: "Fuerteventura",country: "Spanien",    tempAir: "24 °C", tempWater: "20 °C", priceHint: "mittel",  reason: "Mild dank Atlantik, perfekt für Familien." },
    ],
    faqs: [
      { question: "Wie voll ist es im Juni am Mittelmeer?", answer: "In den ersten zwei Juni-Wochen ist es noch entspannt, da die Schulferien in Deutschland erst Ende Juni starten. Ab Mitte Juni füllen sich Hotels und Strände merklich." },
      { question: "Sind Juni-Reisen günstig oder teuer?", answer: "Juni ist Mittelpreis-Saison. Anfang Juni ist 25-30 % günstiger als Juli/August, in den letzten Tagen vor Schulferien ziehen die Preise aber stark an. Frühbuchung empfohlen." },
      { question: "Wohin mit kleinen Kindern im Juni?", answer: "Familien sollten eher die kühleren Mittelmeer-Ziele wählen: Kroatien, Italien, Menorca oder Madeira. Die Türkei ist im Juni schon sehr heiß (30+ °C) – für Kleinkinder oft zu viel." },
    ],
  },
  {
    slug: "juli",
    month: "Juli",
    emoji: "🌞",
    headline: "Beste Reiseziele im Juli",
    lead: "Sommer-Hochsaison am Mittelmeer – plus Geheimtipps abseits der Massen.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im Juli ${YEAR} – Sommer am Mittelmeer & mehr`,
    seoDescription: `Top-Reiseziele im Juli ${YEAR} ✓ Mallorca, Kreta, Türkei ✓ Schulferien ✓ Badewetter ✓ Geheimtipps gegen Massen & Hitze.`,
    weatherSummary: "Absolute Hochsaison: Mittelmeer 28-32 °C, Wasser 23-26 °C. Skandinavien perfekt (20-25 °C). Fernziele wie Südostasien meist Regenzeit.",
    bookingTip: "Juli ist am teuersten – wer jetzt bucht, sollte Frühbucher nutzen oder abgelegene Ziele wie die Azoren, Skandinavien oder Albanien wählen.",
    destinations: [
      { slug: "mallorca",    name: "Mallorca",    country: "Spanien",      tempAir: "30 °C", tempWater: "24 °C", priceHint: "teuer",  reason: "Hochsommer auf der Lieblingsinsel der Deutschen." },
      { slug: "ibiza",       name: "Ibiza",       country: "Spanien",      tempAir: "30 °C", tempWater: "24 °C", priceHint: "teuer",  reason: "Party-Hochsaison, alle Clubs haben geöffnet." },
      { slug: "kreta",       name: "Kreta",       country: "Griechenland", tempAir: "30 °C", tempWater: "25 °C", priceHint: "teuer",  reason: "Perfektes Mittelmeer-Klima ohne Hitzeextrem." },
      { slug: "rhodos",      name: "Rhodos",      country: "Griechenland", tempAir: "30 °C", tempWater: "25 °C", priceHint: "teuer",  reason: "Sommer-Klassiker mit allen Strandaktivitäten." },
      { slug: "korfu",       name: "Korfu",       country: "Griechenland", tempAir: "30 °C", tempWater: "25 °C", priceHint: "teuer",  reason: "Grün, waldreich, mediterrane Atmosphäre." },
      { slug: "antalya",     name: "Antalya",     country: "Türkei",       tempAir: "34 °C", tempWater: "26 °C", priceHint: "teuer",  reason: "Türkische Riviera im Sommermodus – All-Inclusive dominiert." },
      { slug: "side",        name: "Side",        country: "Türkei",       tempAir: "33 °C", tempWater: "26 °C", priceHint: "teuer",  reason: "Strand + Kultur – römische Ruinen inklusive." },
      { slug: "island",      name: "Island",      country: "Island",       tempAir: "15 °C", tempWater: "—",     priceHint: "teuer",  reason: "Mitternachtssonne, Vulkane und Wasserfälle – ideal gegen Sommerhitze." },
    ],
    faqs: [
      { question: "Wohin in den Sommerferien ohne Hitzeschock?", answer: "Skandinavien (Norwegen, Schweden), die Azoren, Island, Kanada und die Ostsee sind ideal für Familien, die extreme Hitze meiden wollen. Temperaturen liegen bei 18-25 °C." },
      { question: "Wie teuer sind Pauschalreisen im Juli?", answer: "Juli zählt zur Hochsaison – Pauschalreisen sind 40-80 % teurer als im Mai oder Oktober. Für eine Woche Mallorca All-Inclusive sollte man mit 800-1.400 € pro Person rechnen." },
      { question: "Lohnt sich Fernreise im Juli?", answer: "Die meisten Fernziele haben im Juli Regenzeit (Thailand, Bali, Malediven) oder Hurrikan-Risiko (Karibik). Ausnahmen: Mauritius und Sansibar sind trocken, Kuba und Mexiko mild. Japan und China sind heiß-schwül." },
    ],
  },
  {
    slug: "august",
    month: "August",
    emoji: "🏖️",
    headline: "Beste Reiseziele im August",
    lead: "Mittelmeer im Vollbetrieb – plus Alternativen für Familien und Hitze-Meider.",
    heroImage: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im August ${YEAR} – Sommerferien, Balearen & Türkei`,
    seoDescription: `Die besten Reiseziele im August ${YEAR} ✓ Sommerferien ✓ Mittelmeer ✓ Geheimtipps ✓ Wetter, Preise & Familien-Empfehlungen.`,
    weatherSummary: "Heißester Monat am Mittelmeer: 30-35 °C (tagsüber auch 40 °C möglich). Wasser 24-27 °C. Ideal für Skandinavien, Ostsee und Alpen-Regionen.",
    bookingTip: "Teuerster Monat des Jahres. Wer sparen will, nutzt die letzte August-Woche (Schulstart in einigen Bundesländern) oder bucht 9-12 Monate vorher.",
    destinations: [
      { slug: "mallorca",    name: "Mallorca",    country: "Spanien",      tempAir: "31 °C", tempWater: "26 °C", priceHint: "teuer", reason: "Sommerhöhepunkt – frühzeitige Buchung Pflicht." },
      { slug: "kreta",       name: "Kreta",       country: "Griechenland", tempAir: "30 °C", tempWater: "26 °C", priceHint: "teuer", reason: "Trockenstes, stabiles Mittelmeer-Klima." },
      { slug: "rhodos",      name: "Rhodos",      country: "Griechenland", tempAir: "30 °C", tempWater: "26 °C", priceHint: "teuer", reason: "Meltemi-Winde kühlen angenehm ab." },
      { slug: "kos",         name: "Kos",         country: "Griechenland", tempAir: "30 °C", tempWater: "25 °C", priceHint: "teuer", reason: "Inselflair mit Radwegen für Familien." },
      { slug: "korfu",       name: "Korfu",       country: "Griechenland", tempAir: "31 °C", tempWater: "26 °C", priceHint: "teuer", reason: "Grünste griechische Insel – etwas kühler." },
      { slug: "antalya",     name: "Antalya",     country: "Türkei",       tempAir: "35 °C", tempWater: "28 °C", priceHint: "teuer", reason: "Türkei bleibt Familien-Favorit trotz Hitze." },
      { slug: "costa-brava", name: "Costa Brava", country: "Spanien",      tempAir: "29 °C", tempWater: "24 °C", priceHint: "teuer", reason: "Badestrände mit Kulturanschluss nach Barcelona." },
    ],
    faqs: [
      { question: "Wo kühlt es im August am Mittelmeer ab?", answer: "Die nordgriechischen Inseln (Korfu, Thassos, Skiathos) sind etwas milder als die Südägäis. Rhodos profitiert von den Meltemi-Winden. In der Türkei sind Bodrum und Marmaris kühler als Antalya." },
      { question: "Sind Sommerferien teurer als Pfingsten?", answer: "Ja, deutlich. August ist 20-40 % teurer als Pfingsten (Ende Mai). Familien mit schulpflichtigen Kindern haben kaum eine Wahl – wer flexibel ist, sollte die erste oder letzte Ferienwoche wählen." },
      { question: "Wo ist es im August NICHT zu heiß?", answer: "Skandinavien (18-22 °C), Ostsee, Alpen, Schottland, Kanada und Neuseeland (dort ist Winter). In Deutschland sind die Nordsee, Ostsee und die Mittelgebirge angenehm bei 22-25 °C." },
    ],
  },
  {
    slug: "september",
    month: "September",
    emoji: "🍂",
    headline: "Beste Reiseziele im September",
    lead: "Der Geheimtipp-Monat: warmes Meer, weniger Menschen, deutlich niedrigere Preise.",
    heroImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im September ${YEAR} – Nachsaison am Mittelmeer`,
    seoDescription: `Die besten September-Reiseziele ${YEAR} ✓ Mallorca, Kreta, Türkei in der Nachsaison ✓ Warmes Meer ✓ Günstige Preise ✓ Geheimtipps.`,
    weatherSummary: "Ideale Temperaturen: Mittelmeer 26-30 °C, Wasser 24-25 °C. Weniger Regen als im August, angenehmere Nächte. Fernziele wie Thailand nähern sich dem Ende der Regenzeit.",
    bookingTip: "September ist der beste Monat zum Sparen ohne Einbußen. Nach den Schulferien fallen die Preise um 30-50 % – perfekt für Paare und Paare ohne Kinder.",
    destinations: [
      { slug: "mallorca",    name: "Mallorca",    country: "Spanien",      tempAir: "28 °C", tempWater: "25 °C", priceHint: "mittel", reason: "Noch Sommer – aber zu Frühsommer-Preisen." },
      { slug: "kreta",       name: "Kreta",       country: "Griechenland", tempAir: "28 °C", tempWater: "25 °C", priceHint: "mittel", reason: "Warmes Meer, leere Strände, angenehme Nächte." },
      { slug: "rhodos",      name: "Rhodos",      country: "Griechenland", tempAir: "28 °C", tempWater: "25 °C", priceHint: "mittel", reason: "Entspannte Atmosphäre ohne Sommerhektik." },
      { slug: "antalya",     name: "Antalya",     country: "Türkei",       tempAir: "32 °C", tempWater: "26 °C", priceHint: "mittel", reason: "Türkei bleibt warm – Preise fallen stark." },
      { slug: "sardinien",   name: "Sardinien",   country: "Italien",      tempAir: "27 °C", tempWater: "24 °C", priceHint: "mittel", reason: "Klarstes Mittelmeer-Wasser, jetzt erschwinglich." },
      { slug: "madeira",     name: "Madeira",     country: "Portugal",     tempAir: "24 °C", tempWater: "22 °C", priceHint: "mittel", reason: "Wanderparadies bei idealen Temperaturen." },
      { slug: "barcelona",   name: "Barcelona",   country: "Spanien",      tempAir: "25 °C", tempWater: "24 °C", priceHint: "mittel", reason: "Perfekte Städtereise ohne Hochsommerhitze." },
    ],
    faqs: [
      { question: "Warum ist der September so beliebt bei Paaren?", answer: "Nach den Sommerferien fallen die Preise stark, die Strände werden leer und das Wetter bleibt sommerlich. Paare und Paare ohne schulpflichtige Kinder profitieren besonders – teils 50 % Ersparnis gegenüber August." },
      { question: "Kann man im September noch baden?", answer: "Absolut. Wassertemperaturen im September liegen oft höher als im Juni: Kreta und Rhodos 25 °C, Mallorca 24 °C, Türkei 26 °C. Das Meer ist vom Sommer 'aufgeheizt' und auf dem Temperatur-Höhepunkt." },
      { question: "Welche Fernreise ist im September top?", answer: "Die Südsee, Mauritius und Sansibar sind ideal (Trockenzeit). Karibik ist Hurrikan-Saison – Vorsicht. Japan und Südkorea sind perfekt (22-26 °C). Thailand und Vietnam gehen Ende September aus der Regenzeit." },
    ],
  },
  {
    slug: "oktober",
    month: "Oktober",
    emoji: "🌅",
    headline: "Beste Reiseziele im Oktober",
    lead: "Goldener Herbst in Südeuropa, warmes Meer in der Türkei und die perfekte Zeit für Fernreisen.",
    heroImage: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im Oktober ${YEAR} – Herbstferien & Nachsaison`,
    seoDescription: `Die besten Oktober-Reiseziele ${YEAR} ✓ Herbstferien ✓ Kanaren, Ägypten & Türkei ✓ Fernreisen starten ✓ Wetter & Preise.`,
    weatherSummary: "Mittelmeer-Ende: Kreta, Zypern und Türkei noch bei 23-27 °C. Kanaren konstant bei 25 °C. Fernreiseziele (Thailand, Bali, Mexiko) starten in die beste Saison.",
    bookingTip: "Herbstferien (meist Mitte Oktober) treiben die Preise kurzzeitig hoch. Wer davor oder danach reist, spart bis zu 40 %.",
    destinations: [
      { slug: "zypern",      name: "Zypern",      country: "Zypern",       tempAir: "27 °C", tempWater: "25 °C", priceHint: "mittel", reason: "Wärmstes EU-Ziel im Oktober – Badeurlaub garantiert." },
      { slug: "teneriffa",   name: "Teneriffa",   country: "Spanien",      tempAir: "26 °C", tempWater: "23 °C", priceHint: "mittel", reason: "Kanaren in Bestform, weniger Menschen." },
      { slug: "gran-canaria",name: "Gran Canaria",country: "Spanien",      tempAir: "26 °C", tempWater: "23 °C", priceHint: "mittel", reason: "Stabiles Sommerklima ganzjährig." },
      { slug: "kreta",       name: "Kreta",       country: "Griechenland", tempAir: "25 °C", tempWater: "24 °C", priceHint: "günstig", reason: "Letzter Bademonat mit sehr günstigen Preisen." },
      { slug: "rhodos",      name: "Rhodos",      country: "Griechenland", tempAir: "25 °C", tempWater: "24 °C", priceHint: "günstig", reason: "Sonne satt zu Last-Minute-Preisen." },
      { slug: "antalya",     name: "Antalya",     country: "Türkei",       tempAir: "27 °C", tempWater: "24 °C", priceHint: "günstig", reason: "Nachsaison – All-Inclusive oft unter 400 €." },
      { slug: "hurghada",    name: "Hurghada",    country: "Ägypten",      tempAir: "28 °C", tempWater: "26 °C", priceHint: "günstig", reason: "Rotes Meer bleibt ganzjährig badetauglich." },
      { slug: "marrakesch",  name: "Marrakesch",  country: "Marokko",      tempAir: "27 °C", tempWater: "—",     priceHint: "günstig", reason: "Beste Reisezeit für Kultur und Atlas-Trekking." },
    ],
    faqs: [
      { question: "Wann sind die Herbstferien 2026?", answer: "Die Herbstferien fallen 2026 meist zwischen 12. und 30. Oktober, je nach Bundesland. Die Preise während der Ferien steigen um 30-50 % – wer davor oder danach reist, spart erheblich." },
      { question: "Welches Fernziel ist im Oktober ideal?", answer: "Thailand, Vietnam und Kambodscha starten in die Trockenzeit. Bali hat noch gemischtes Wetter. Mexiko und Kuba sind optimal (28 °C, kaum Regen). Die Malediven beginnen ihre Top-Saison." },
      { question: "Lohnt sich die Türkei im Oktober?", answer: "Unbedingt. Antalya und Side bieten im Oktober noch 24 °C Wasser und 27 °C Luft – bei Preisen, die 40-60 % unter der Juli-Hochsaison liegen. Ideal für preisbewusste Urlauber." },
    ],
  },
  {
    slug: "november",
    month: "November",
    emoji: "🍁",
    headline: "Beste Reiseziele im November",
    lead: "Wintersonne zum Schnäppchenpreis – Kanaren, Ägypten und Fernreisen starten in ihre Hauptsaison.",
    heroImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im November ${YEAR} – Wintersonne & Fernreisen`,
    seoDescription: `Die besten November-Reiseziele ${YEAR} ✓ Kanaren & Ägypten ✓ Karibik & Thailand ✓ Dubai ✓ Wintersonne zum Bestpreis.`,
    weatherSummary: "Europa wird kalt und regnerisch, nur Kanaren und Ägypten bieten badetaugliches Wetter (22-25 °C). Fernziele wie Thailand, Karibik, Malediven und Dubai sind in der Top-Saison.",
    bookingTip: "November ist für Fernreisen der günstigste Monat vor der Weihnachts-Hochsaison. Last-Minute-Deals auf die Kanaren sind besonders attraktiv.",
    destinations: [
      { slug: "teneriffa",   name: "Teneriffa",   country: "Spanien",    tempAir: "24 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Ewiger Frühling – Wanderwetter und Strandflair." },
      { slug: "gran-canaria",name: "Gran Canaria",country: "Spanien",    tempAir: "24 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Dauersonne mit 7 Stunden pro Tag." },
      { slug: "fuerteventura",name: "Fuerteventura",country: "Spanien",  tempAir: "23 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Windparadies mit ganzjährig stabilem Klima." },
      { slug: "lanzarote",   name: "Lanzarote",   country: "Spanien",    tempAir: "23 °C", tempWater: "22 °C", priceHint: "mittel",  reason: "Vulkanlandschaft bei angenehmen Temperaturen." },
      { slug: "hurghada",    name: "Hurghada",    country: "Ägypten",    tempAir: "25 °C", tempWater: "24 °C", priceHint: "günstig", reason: "Rotes Meer im Wohlfühlklima, günstige Preise." },
      { slug: "dubai",       name: "Dubai",       country: "VAE",        tempAir: "27 °C", tempWater: "25 °C", priceHint: "mittel",  reason: "Beste Reisezeit in den Emiraten." },
      { slug: "thailand",    name: "Thailand",    country: "Thailand",   tempAir: "31 °C", tempWater: "29 °C", priceHint: "teuer",   reason: "Trockenzeit startet – Inselhopping top." },
      { slug: "malediven",   name: "Malediven",   country: "Malediven",  tempAir: "30 °C", tempWater: "28 °C", priceHint: "teuer",   reason: "Top-Saison beginnt – Luxusurlaub pur." },
    ],
    faqs: [
      { question: "Wo ist es im November in Flugnähe warm?", answer: "Die Kanarischen Inseln (Teneriffa, Gran Canaria, Fuerteventura, Lanzarote), Madeira und Ägypten (Hurghada, Marsa Alam) sind in 4-5 Flugstunden erreichbar und bieten 22-25 °C bei Sonnenschein." },
      { question: "Lohnt sich eine Karibik-Reise im November?", answer: "Ja, November zählt zu den besten Monaten. Die Hurrikan-Saison endet Ende November, die Preise sind noch moderat (steigen erst zu Weihnachten), und das Wetter ist zuverlässig gut." },
      { question: "Sind November-Reisen günstig?", answer: "Für die Kanaren, Ägypten und Europa-Städtereisen ja – oft 30-50 % unter Sommerpreisen. Fernreisen nach Thailand, Malediven oder in die Karibik sind ab Mitte November wegen Top-Saison aber teurer." },
    ],
  },
  {
    slug: "dezember",
    month: "Dezember",
    emoji: "🎄",
    headline: "Beste Reiseziele im Dezember",
    lead: "Weihnachten am Strand, Silvester in der Metropole oder Ski-Woche in den Alpen – der Dezember bietet alles.",
    heroImage: "https://images.unsplash.com/photo-1482685945432-29a7abf2f466?w=1200&q=75&auto=format",
    seoTitle: `Beste Reiseziele im Dezember ${YEAR} – Weihnachten, Silvester & Wintersonne`,
    seoDescription: `Die besten Dezember-Reiseziele ${YEAR} ✓ Weihnachten & Silvester ✓ Ski & Wintersonne ✓ Karibik & Asien ✓ Tipps & Preise.`,
    weatherSummary: "Zwei Gesichter: Europa tief winterlich (Alpen-Ski ideal), Fernziele in bester Form. Kanaren (22 °C), Karibik (27 °C), Thailand (30 °C), Dubai (24 °C) sind top.",
    bookingTip: "Die erste Dezember-Hälfte ist günstig, um Weihnachten & Silvester sind die Preise dreistellig höher. Wer Anfang Dezember reist, spart massiv.",
    destinations: [
      { slug: "teneriffa",   name: "Teneriffa",   country: "Spanien",    tempAir: "22 °C", tempWater: "20 °C", priceHint: "mittel", reason: "Stabiles Klima – ideal für Weihnachten in der Sonne." },
      { slug: "gran-canaria",name: "Gran Canaria",country: "Spanien",    tempAir: "22 °C", tempWater: "20 °C", priceHint: "mittel", reason: "Sonnengarantie zur dunkelsten Zeit des Jahres." },
      { slug: "hurghada",    name: "Hurghada",    country: "Ägypten",    tempAir: "22 °C", tempWater: "22 °C", priceHint: "mittel", reason: "Rotes Meer bei Winter-Temperaturen wie Sommer in Deutschland." },
      { slug: "dubai",       name: "Dubai",       country: "VAE",        tempAir: "24 °C", tempWater: "23 °C", priceHint: "mittel", reason: "Beste Reisezeit – angenehme Temperaturen, Shopping & Festivals." },
      { slug: "thailand",    name: "Thailand",    country: "Thailand",   tempAir: "30 °C", tempWater: "28 °C", priceHint: "teuer",  reason: "Peak Season – Trockenzeit und bestes Reisewetter." },
      { slug: "bali",        name: "Bali",        country: "Indonesien", tempAir: "30 °C", tempWater: "28 °C", priceHint: "teuer",  reason: "Tropisches Klima, Weihnachten exotisch erleben." },
      { slug: "malediven",   name: "Malediven",   country: "Malediven",  tempAir: "30 °C", tempWater: "28 °C", priceHint: "teuer",  reason: "Luxus-Robinsonade zur schönsten Jahreszeit." },
      { slug: "wien",        name: "Wien",        country: "Österreich", tempAir: "3 °C",  tempWater: "—",     priceHint: "mittel", reason: "Weihnachtsmärkte & Silvester in Kaiserlicher Atmosphäre." },
    ],
    faqs: [
      { question: "Wo verbringt man Weihnachten am Strand?", answer: "Die beliebtesten Strand-Weihnachts-Ziele sind Kanaren (Teneriffa, Gran Canaria), Ägypten (Hurghada), Malediven, Thailand (Phuket, Krabi), Bali, Dubai und die Karibik. Alle bieten 22-30 °C und sichere Weihnachtssonne." },
      { question: "Wie teuer ist eine Silvesterreise?", answer: "Silvester ist nach den Sommerferien die teuerste Reisezeit. Pauschalreisen sind 50-100 % teurer als im normalen Dezember. Wer flexibel ist, reist Anfang Dezember (sehr günstig) oder erst ab dem 2. Januar." },
      { question: "Wohin zum Skifahren im Dezember?", answer: "Die besten Schneebedingungen bieten hochgelegene Gebiete: Ischgl, Obergurgl, Sölden (Österreich), Zermatt, Saas-Fee (Schweiz) und Val Thorens (Frankreich). Vor Weihnachten oft noch mäßig besucht und günstiger." },
    ],
  },
];

export function getSeasonGuide(slug: string): SeasonGuide | undefined {
  return SEASON_GUIDES.find((g) => g.slug === slug);
}
